/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s29 CASADI_PREFIX(s29)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = 
  {1, 4, 0, 1, 2, 3, 4, 0,
  0, 0, 0};
static const casadi_int casadi_s1[23] = 
  {4, 4, 0, 4, 8, 12, 16, 0,
  1, 2, 3, 0, 1, 2, 3, 0,
  1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s4[9] = 
  {1, 3, 0, 1, 2, 3, 0, 0,
  0};
static const casadi_int casadi_s5[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s6[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s7[11] = 
  {0, 1, 2, 3, 4, 5, 6, 10,
  11, 12, 13};
static const casadi_int casadi_s8[11] = 
  {0, 1, 2, 3, 16, 17, 18, 25,
  26, 27, 28};
static const casadi_int casadi_s9[11] = 
  {0, 4, 8, 12, 16, 19, 22, 25,
  29, 33, 37};
static const casadi_int casadi_s10[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s11[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s12[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s13[11] = 
  {4, 5, 6, 7, 19, 20, 21, 29,
  30, 31, 32};
static const casadi_int casadi_s14[11] = 
  {1, 5, 9, 13, 17, 20, 23, 26,
  30, 34, 38};
static const casadi_int casadi_s15[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s16[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s17[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s18[11] = 
  {8, 9, 10, 11, 22, 23, 24, 33,
  34, 35, 36};
static const casadi_int casadi_s19[11] = 
  {2, 6, 10, 14, 18, 21, 24, 27,
  31, 35, 39};
static const casadi_int casadi_s20[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s21[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s22[61] = 
  {17, 17, 0, 4, 8, 12, 16, 19,
  22, 25, 25, 25, 25, 29, 33, 37,
  41, 41, 41, 41, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 4, 5, 6, 4,
  5, 6, 4, 5, 6, 10, 11, 12,
  13, 10, 11, 12, 13, 10, 11, 12,
  13, 10, 11, 12, 13};
static const casadi_int casadi_s23[3] = {13, 1, 1};
static const casadi_int casadi_s24[3] = {4, 1, 1};
static const casadi_int casadi_s25[3] = {0, 1, 1};
static const casadi_int casadi_s26[3] = {17, 1, 1};
static const casadi_int casadi_s27[3] = {1, 1, 1};
static const casadi_int casadi_s28[3] = {0, 0, 1};
static const casadi_int casadi_s29[3] = {0, 17, 1};

static const casadi_real casadi_c0[9] = 
  {25., 0., 0., 0., 25., 0., 0., 0.,
  30.};
static const casadi_real casadi_c1[16] = 
  {1., 0., 0., 0., 0., 800., 0., 0.,
  0., 0., 800., 0., 0., 0., 0., 800.};
static const casadi_real casadi_c2[9] = 
  {12., 0., 0., 0., 12., 0., 0., 0.,
  12.};

/* Drone_ode_complete_cost_ext_cost_0_fun_jac_hess:(i0[13],i1[4],i2[0],i3[17])->(o0,o1[17],o2[17x17,41nz],o3[],o4[0x17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *tt, w00, *w01=w+2, w02, w03, w04, w05, w06, w07, w08, w09;
  casadi_real w10, w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+22, *w20=w+39, *w21=w+42;
  casadi_real *w22=w+55, *w24=w+67, *w25=w+70, *w26=w+74, *w27=w+78, *w29=w+98, *w30=w+102, *w31=w+106, *w32=w+110, *w33=w+114, *w34=w+117, *w35=w+120;
  casadi_real *w37=w+132, *w38=w+135, *w39=w+151, *w40=w+160, *w41=w+163, *w42=w+166, w43, w44, w45, w46, w47, w48;
  casadi_real *w49=w+175, *w50=w+188, w51, w52, w53, w54, w55, w56, *w57=w+203, *w58=w+244, *w60=w+253, *w61=w+257;
  casadi_real w62, w63, *w64=w+263, *w65=w+267, *w66=w+270, *w67=w+273, w68, w69, w70, w71, *w72=w+280, w73;
  casadi_real w74, w75, w76, w77, w78, w79, *w80=w+291, *w81=w+302, *w82=w+305, *w83=w+307, *w84=w+315;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct, *wr23, *wr28, *wr36;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[3][0] */
  w02 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w03 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w04 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w05 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w06 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w07 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w08 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w09 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = input[3][16] */
  w18 = arg[3] ? arg[3][16] : 0;
  /* #19: @19 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #20: @20 = @19[:3] */
  for (rr=w20, cs=w19+0; cs!=w19+3; cs+=1) *rr++ = *cs;
  /* #21: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #22: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #23: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #24: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #25: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #26: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #27: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #28: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #29: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #30: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #31: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #32: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #33: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #34: @21 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w21;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #35: @22 = @21[:3] */
  for (rr=w22, cs=w21+0; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #36: @20 = (@20-@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #37: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #38: @23 = 
  [[25, 0, 0], 
   [0, 25, 0], 
   [0, 0, 30]] */
  wr23 = casadi_c0;
  /* #39: @24 = mac(@22,@23,@1) */
  casadi_copy(w01, 3, w24);
  for (i=0, rr=w24; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=wr23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #40: @2 = mac(@24,@20,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w24+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #41: @25 = zeros(1x4) */
  casadi_clear(w25, 4);
  /* #42: @3 = input[1][0] */
  w03 = arg[1] ? arg[1][0] : 0;
  /* #43: @4 = input[1][1] */
  w04 = arg[1] ? arg[1][1] : 0;
  /* #44: @5 = input[1][2] */
  w05 = arg[1] ? arg[1][2] : 0;
  /* #45: @6 = input[1][3] */
  w06 = arg[1] ? arg[1][3] : 0;
  /* #46: @26 = vertcat(@3, @4, @5, @6) */
  rr=w26;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  /* #47: @27 = @26' */
  casadi_copy(w26, 4, w27);
  /* #48: @28 = 
  [[1, 0, 0, 0], 
   [0, 800, 0, 0], 
   [0, 0, 800, 0], 
   [0, 0, 0, 800]] */
  wr28 = casadi_c1;
  /* #49: @29 = mac(@27,@28,@25) */
  casadi_copy(w25, 4, w29);
  for (i=0, rr=w29; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w27+j, ct=wr28+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #50: @3 = mac(@29,@26,@0) */
  casadi_copy((&w00), 1, (&w03));
  for (i=0, rr=(&w03); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w26+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #51: @2 = (@2+@3) */
  w02 += w03;
  /* #52: @9 = (-@9) */
  w09 = (- w09 );
  /* #53: @10 = (-@10) */
  w10 = (- w10 );
  /* #54: @11 = (-@11) */
  w11 = (- w11 );
  /* #55: @26 = vertcat(@8, @9, @10, @11) */
  rr=w26;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  /* #56: @30 = @21[6:10] */
  for (rr=w30, cs=w21+6; cs!=w21+10; cs+=1) *rr++ = *cs;
  /* #57: @8 = ||@30||_F */
  w08 = casadi_norm_2(4, w30);
  /* #58: @26 = (@26/@8) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) /= w08;
  /* #59: {@9, @10, @11, @3} = vertsplit(@26) */
  w09 = w26[0];
  w10 = w26[1];
  w11 = w26[2];
  w03 = w26[3];
  /* #60: @31 = @19[6:10] */
  for (rr=w31, cs=w19+6; cs!=w19+10; cs+=1) *rr++ = *cs;
  /* #61: {@4, @5, @6, @7} = vertsplit(@31) */
  w04 = w31[0];
  w05 = w31[1];
  w06 = w31[2];
  w07 = w31[3];
  /* #62: @12 = (@9*@4) */
  w12  = (w09*w04);
  /* #63: @13 = (@10*@5) */
  w13  = (w10*w05);
  /* #64: @12 = (@12-@13) */
  w12 -= w13;
  /* #65: @13 = (@11*@6) */
  w13  = (w11*w06);
  /* #66: @12 = (@12-@13) */
  w12 -= w13;
  /* #67: @13 = (@3*@7) */
  w13  = (w03*w07);
  /* #68: @12 = (@12-@13) */
  w12 -= w13;
  /* #69: @13 = (@12<@0) */
  w13  = (w12<w00);
  /* #70: @14 = (@9*@5) */
  w14  = (w09*w05);
  /* #71: @15 = (@10*@4) */
  w15  = (w10*w04);
  /* #72: @14 = (@14+@15) */
  w14 += w15;
  /* #73: @15 = (@11*@7) */
  w15  = (w11*w07);
  /* #74: @14 = (@14+@15) */
  w14 += w15;
  /* #75: @15 = (@3*@6) */
  w15  = (w03*w06);
  /* #76: @14 = (@14-@15) */
  w14 -= w15;
  /* #77: @15 = (@9*@6) */
  w15  = (w09*w06);
  /* #78: @16 = (@10*@7) */
  w16  = (w10*w07);
  /* #79: @15 = (@15-@16) */
  w15 -= w16;
  /* #80: @16 = (@11*@4) */
  w16  = (w11*w04);
  /* #81: @15 = (@15+@16) */
  w15 += w16;
  /* #82: @16 = (@3*@5) */
  w16  = (w03*w05);
  /* #83: @15 = (@15+@16) */
  w15 += w16;
  /* #84: @9 = (@9*@7) */
  w09 *= w07;
  /* #85: @10 = (@10*@6) */
  w10 *= w06;
  /* #86: @9 = (@9+@10) */
  w09 += w10;
  /* #87: @11 = (@11*@5) */
  w11 *= w05;
  /* #88: @9 = (@9-@11) */
  w09 -= w11;
  /* #89: @3 = (@3*@4) */
  w03 *= w04;
  /* #90: @9 = (@9+@3) */
  w09 += w03;
  /* #91: @31 = vertcat(@12, @14, @15, @9) */
  rr=w31;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w09;
  /* #92: @32 = (-@31) */
  for (i=0, rr=w32, cs=w31; i<4; ++i) *rr++ = (- *cs++ );
  /* #93: @32 = (@13?@32:0) */
  for (i=0, rr=w32, cs=w32; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #94: @12 = (!@13) */
  w12 = (! w13 );
  /* #95: @31 = (@12?@31:0) */
  for (i=0, rr=w31, cs=w31; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #96: @32 = (@32+@31) */
  for (i=0, rr=w32, cs=w31; i<4; ++i) (*rr++) += (*cs++);
  /* #97: @20 = @32[1:4] */
  for (rr=w20, cs=w32+1; cs!=w32+4; cs+=1) *rr++ = *cs;
  /* #98: @33 = (2.*@20) */
  for (i=0, rr=w33, cs=w20; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #99: @14 = ||@20||_F */
  w14 = casadi_norm_2(3, w20);
  /* #100: @15 = @32[0] */
  for (rr=(&w15), cs=w32+0; cs!=w32+1; cs+=1) *rr++ = *cs;
  /* #101: @9 = atan2(@14,@15) */
  w09  = atan2(w14,w15);
  /* #102: @34 = (@33*@9) */
  for (i=0, rr=w34, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)*w09);
  /* #103: @3 = 1e-09 */
  w03 = 1.0000000000000001e-09;
  /* #104: @3 = (@3+@14) */
  w03 += w14;
  /* #105: @34 = (@34/@3) */
  for (i=0, rr=w34; i<3; ++i) (*rr++) /= w03;
  /* #106: @35 = @34' */
  casadi_copy(w34, 3, w35);
  /* #107: @36 = 
  [[12, 0, 0], 
   [0, 12, 0], 
   [0, 0, 12]] */
  wr36 = casadi_c2;
  /* #108: @37 = mac(@35,@36,@1) */
  casadi_copy(w01, 3, w37);
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=wr36+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #109: @0 = mac(@37,@34,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w37+j, ct=w34+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #110: @2 = (@2+@0) */
  w02 += w00;
  /* #111: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #112: @29 = @29' */
  /* #113: @38 = @28' */
  for (i=0, rr=w38, cs=wr28; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #114: @32 = mac(@27,@38,@25) */
  casadi_copy(w25, 4, w32);
  for (i=0, rr=w32; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w27+j, ct=w38+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #115: @32 = @32' */
  /* #116: @29 = (@29+@32) */
  for (i=0, rr=w29, cs=w32; i<4; ++i) (*rr++) += (*cs++);
  /* #117: {@2, @0, @11, @10} = vertsplit(@29) */
  w02 = w29[0];
  w00 = w29[1];
  w11 = w29[2];
  w10 = w29[3];
  /* #118: output[1][0] = @2 */
  if (res[1]) res[1][0] = w02;
  /* #119: output[1][1] = @0 */
  if (res[1]) res[1][1] = w00;
  /* #120: output[1][2] = @11 */
  if (res[1]) res[1][2] = w11;
  /* #121: output[1][3] = @10 */
  if (res[1]) res[1][3] = w10;
  /* #122: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #123: @26 = (@26/@8) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) /= w08;
  /* #124: @29 = (-@26) */
  for (i=0, rr=w29, cs=w26; i<4; ++i) *rr++ = (- *cs++ );
  /* #125: @32 = zeros(4x1) */
  casadi_clear(w32, 4);
  /* #126: @10 = sq(@14) */
  w10 = casadi_sq( w14 );
  /* #127: @11 = sq(@15) */
  w11 = casadi_sq( w15 );
  /* #128: @10 = (@10+@11) */
  w10 += w11;
  /* #129: @11 = (@14/@10) */
  w11  = (w14/w10);
  /* #130: @37 = @37' */
  /* #131: @39 = @36' */
  for (i=0, rr=w39, cs=wr36; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #132: @40 = mac(@35,@39,@1) */
  casadi_copy(w01, 3, w40);
  for (i=0, rr=w40; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #133: @40 = @40' */
  /* #134: @37 = (@37+@40) */
  for (i=0, rr=w37, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #135: @40 = (@37/@3) */
  for (i=0, rr=w40, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #136: @0 = dot(@33, @40) */
  w00 = casadi_dot(3, w33, w40);
  /* #137: @2 = (@11*@0) */
  w02  = (w11*w00);
  /* #138: @2 = (-@2) */
  w02 = (- w02 );
  /* #139: @27 = @32; (@27[0] += @2) */
  casadi_copy(w32, 4, w27);
  for (rr=w27+0, cs=(&w02); rr!=w27+1; rr+=1) *rr += *cs++;
  /* #140: @34 = (@34/@3) */
  for (i=0, rr=w34; i<3; ++i) (*rr++) /= w03;
  /* #141: @35 = (-@34) */
  for (i=0, rr=w35, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #142: @2 = dot(@35, @37) */
  w02 = casadi_dot(3, w35, w37);
  /* #143: @16 = (@15/@10) */
  w16  = (w15/w10);
  /* #144: @17 = (@16*@0) */
  w17  = (w16*w00);
  /* #145: @2 = (@2+@17) */
  w02 += w17;
  /* #146: @2 = (@2/@14) */
  w02 /= w14;
  /* #147: @41 = (@2*@20) */
  for (i=0, rr=w41, cs=w20; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #148: @42 = (@9*@40) */
  for (i=0, rr=w42, cs=w40; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #149: @42 = (2.*@42) */
  for (i=0, rr=w42, cs=w42; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #150: @41 = (@41+@42) */
  for (i=0, rr=w41, cs=w42; i<3; ++i) (*rr++) += (*cs++);
  /* #151: (@27[1:4] += @41) */
  for (rr=w27+1, cs=w41; rr!=w27+4; rr+=1) *rr += *cs++;
  /* #152: @31 = (@12?@27:0) */
  for (i=0, rr=w31, cs=w27; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #153: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<4; ++i) *rr++ = (- *cs++ );
  /* #154: @27 = (@13?@27:0) */
  for (i=0, rr=w27, cs=w27; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #155: @31 = (@31+@27) */
  for (i=0, rr=w31, cs=w27; i<4; ++i) (*rr++) += (*cs++);
  /* #156: {@17, @18, @43, @44} = vertsplit(@31) */
  w17 = w31[0];
  w18 = w31[1];
  w43 = w31[2];
  w44 = w31[3];
  /* #157: @45 = (@7*@44) */
  w45  = (w07*w44);
  /* #158: @46 = (@6*@43) */
  w46  = (w06*w43);
  /* #159: @45 = (@45+@46) */
  w45 += w46;
  /* #160: @46 = (@5*@18) */
  w46  = (w05*w18);
  /* #161: @45 = (@45+@46) */
  w45 += w46;
  /* #162: @46 = (@4*@17) */
  w46  = (w04*w17);
  /* #163: @45 = (@45+@46) */
  w45 += w46;
  /* #164: @46 = (@6*@44) */
  w46  = (w06*w44);
  /* #165: @47 = (@7*@43) */
  w47  = (w07*w43);
  /* #166: @46 = (@46-@47) */
  w46 -= w47;
  /* #167: @47 = (@4*@18) */
  w47  = (w04*w18);
  /* #168: @46 = (@46+@47) */
  w46 += w47;
  /* #169: @47 = (@5*@17) */
  w47  = (w05*w17);
  /* #170: @46 = (@46-@47) */
  w46 -= w47;
  /* #171: @47 = (@4*@43) */
  w47  = (w04*w43);
  /* #172: @48 = (@5*@44) */
  w48  = (w05*w44);
  /* #173: @47 = (@47-@48) */
  w47 -= w48;
  /* #174: @48 = (@7*@18) */
  w48  = (w07*w18);
  /* #175: @47 = (@47+@48) */
  w47 += w48;
  /* #176: @48 = (@6*@17) */
  w48  = (w06*w17);
  /* #177: @47 = (@47-@48) */
  w47 -= w48;
  /* #178: @44 = (@4*@44) */
  w44  = (w04*w44);
  /* #179: @43 = (@5*@43) */
  w43  = (w05*w43);
  /* #180: @44 = (@44+@43) */
  w44 += w43;
  /* #181: @18 = (@6*@18) */
  w18  = (w06*w18);
  /* #182: @44 = (@44-@18) */
  w44 -= w18;
  /* #183: @17 = (@7*@17) */
  w17  = (w07*w17);
  /* #184: @44 = (@44-@17) */
  w44 -= w17;
  /* #185: @31 = vertcat(@45, @46, @47, @44) */
  rr=w31;
  *rr++ = w45;
  *rr++ = w46;
  *rr++ = w47;
  *rr++ = w44;
  /* #186: @45 = dot(@29, @31) */
  w45 = casadi_dot(4, w29, w31);
  /* #187: @45 = (@45/@8) */
  w45 /= w08;
  /* #188: @27 = (@45*@30) */
  for (i=0, rr=w27, cs=w30; i<4; ++i) (*rr++)  = (w45*(*cs++));
  /* #189: @49 = @21; (@49[6:10] += @27) */
  casadi_copy(w21, 13, w49);
  for (rr=w49+6, cs=w27; rr!=w49+10; rr+=1) *rr += *cs++;
  /* #190: @24 = @24' */
  /* #191: @50 = @23' */
  for (i=0, rr=w50, cs=wr23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #192: @41 = mac(@22,@50,@1) */
  casadi_copy(w01, 3, w41);
  for (i=0, rr=w41; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w50+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #193: @41 = @41' */
  /* #194: @24 = (@24+@41) */
  for (i=0, rr=w24, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #195: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) *rr++ = (- *cs++ );
  /* #196: (@49[:3] += @24) */
  for (rr=w49+0, cs=w24; rr!=w49+3; rr+=1) *rr += *cs++;
  /* #197: {@46, @47, @44, @17, @18, @43, @48, @51, @52, @53, @54, @55, @56} = vertsplit(@49) */
  w46 = w49[0];
  w47 = w49[1];
  w44 = w49[2];
  w17 = w49[3];
  w18 = w49[4];
  w43 = w49[5];
  w48 = w49[6];
  w51 = w49[7];
  w52 = w49[8];
  w53 = w49[9];
  w54 = w49[10];
  w55 = w49[11];
  w56 = w49[12];
  /* #198: output[1][4] = @46 */
  if (res[1]) res[1][4] = w46;
  /* #199: output[1][5] = @47 */
  if (res[1]) res[1][5] = w47;
  /* #200: output[1][6] = @44 */
  if (res[1]) res[1][6] = w44;
  /* #201: output[1][7] = @17 */
  if (res[1]) res[1][7] = w17;
  /* #202: output[1][8] = @18 */
  if (res[1]) res[1][8] = w18;
  /* #203: output[1][9] = @43 */
  if (res[1]) res[1][9] = w43;
  /* #204: @27 = (@31/@8) */
  for (i=0, rr=w27, cr=w31; i<4; ++i) (*rr++)  = ((*cr++)/w08);
  /* #205: {@43, @18, @17, @44} = vertsplit(@27) */
  w43 = w27[0];
  w18 = w27[1];
  w17 = w27[2];
  w44 = w27[3];
  /* #206: @43 = (@43+@48) */
  w43 += w48;
  /* #207: output[1][10] = @43 */
  if (res[1]) res[1][10] = w43;
  /* #208: @51 = (@51-@18) */
  w51 -= w18;
  /* #209: output[1][11] = @51 */
  if (res[1]) res[1][11] = w51;
  /* #210: @52 = (@52-@17) */
  w52 -= w17;
  /* #211: output[1][12] = @52 */
  if (res[1]) res[1][12] = w52;
  /* #212: @53 = (@53-@44) */
  w53 -= w44;
  /* #213: output[1][13] = @53 */
  if (res[1]) res[1][13] = w53;
  /* #214: output[1][14] = @54 */
  if (res[1]) res[1][14] = w54;
  /* #215: output[1][15] = @55 */
  if (res[1]) res[1][15] = w55;
  /* #216: output[1][16] = @56 */
  if (res[1]) res[1][16] = w56;
  /* #217: @57 = zeros(17x17,41nz) */
  casadi_clear(w57, 41);
  /* #218: @58 = ones(17x1,9nz) */
  casadi_fill(w58, 9, 1.);
  /* #219: {@56, NULL, NULL, NULL, @55, NULL, NULL, NULL, NULL, NULL, @54, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@58) */
  w56 = w58[0];
  w55 = w58[1];
  w54 = w58[5];
  /* #220: @59 = 00 */
  /* #221: @53 = vertcat(@56, @59, @59, @59) */
  rr=(&w53);
  *rr++ = w56;
  /* #222: @53 = @53' */
  /* #223: @60 = mac(@53,@28,@25) */
  casadi_copy(w25, 4, w60);
  casadi_mtimes((&w53), casadi_s2, wr28, casadi_s1, w60, casadi_s0, w, 0);
  /* #224: @60 = @60' */
  /* #225: @61 = mac(@53,@38,@25) */
  casadi_copy(w25, 4, w61);
  casadi_mtimes((&w53), casadi_s2, w38, casadi_s1, w61, casadi_s0, w, 0);
  /* #226: @61 = @61' */
  /* #227: @60 = (@60+@61) */
  for (i=0, rr=w60, cs=w61; i<4; ++i) (*rr++) += (*cs++);
  /* #228: {@53, @56, @44, @52} = vertsplit(@60) */
  w53 = w60[0];
  w56 = w60[1];
  w44 = w60[2];
  w52 = w60[3];
  /* #229: @17 = vertcat(@54, @59, @59, @59) */
  rr=(&w17);
  *rr++ = w54;
  /* #230: @17 = (@17/@8) */
  w17 /= w08;
  /* #231: @60 = dense(@17) */
  casadi_densify((&w17), casadi_s3, w60, 0);
  /* #232: @17 = project(@30) */
  casadi_sparsify(w30, (&w17), casadi_s3, 0);
  /* #233: @54 = sparsity_cast(@54) */
  /* #234: @51 = dot(@17, @54) */
  w51 = casadi_dot(1, (&w17), (&w54));
  /* #235: @51 = (@51/@8) */
  w51 /= w08;
  /* #236: @61 = (@26*@51) */
  for (i=0, rr=w61, cr=w26; i<4; ++i) (*rr++)  = ((*cr++)*w51);
  /* #237: @60 = (@60-@61) */
  for (i=0, rr=w60, cs=w61; i<4; ++i) (*rr++) -= (*cs++);
  /* #238: {@17, @18, @43, @48} = vertsplit(@60) */
  w17 = w60[0];
  w18 = w60[1];
  w43 = w60[2];
  w48 = w60[3];
  /* #239: @47 = (@4*@17) */
  w47  = (w04*w17);
  /* #240: @46 = (@5*@18) */
  w46  = (w05*w18);
  /* #241: @47 = (@47-@46) */
  w47 -= w46;
  /* #242: @46 = (@6*@43) */
  w46  = (w06*w43);
  /* #243: @47 = (@47-@46) */
  w47 -= w46;
  /* #244: @46 = (@7*@48) */
  w46  = (w07*w48);
  /* #245: @47 = (@47-@46) */
  w47 -= w46;
  /* #246: @46 = (@5*@17) */
  w46  = (w05*w17);
  /* #247: @62 = (@4*@18) */
  w62  = (w04*w18);
  /* #248: @46 = (@46+@62) */
  w46 += w62;
  /* #249: @62 = (@7*@43) */
  w62  = (w07*w43);
  /* #250: @46 = (@46+@62) */
  w46 += w62;
  /* #251: @62 = (@6*@48) */
  w62  = (w06*w48);
  /* #252: @46 = (@46-@62) */
  w46 -= w62;
  /* #253: @62 = (@6*@17) */
  w62  = (w06*w17);
  /* #254: @63 = (@7*@18) */
  w63  = (w07*w18);
  /* #255: @62 = (@62-@63) */
  w62 -= w63;
  /* #256: @63 = (@4*@43) */
  w63  = (w04*w43);
  /* #257: @62 = (@62+@63) */
  w62 += w63;
  /* #258: @63 = (@5*@48) */
  w63  = (w05*w48);
  /* #259: @62 = (@62+@63) */
  w62 += w63;
  /* #260: @17 = (@7*@17) */
  w17  = (w07*w17);
  /* #261: @18 = (@6*@18) */
  w18  = (w06*w18);
  /* #262: @17 = (@17+@18) */
  w17 += w18;
  /* #263: @43 = (@5*@43) */
  w43  = (w05*w43);
  /* #264: @17 = (@17-@43) */
  w17 -= w43;
  /* #265: @48 = (@4*@48) */
  w48  = (w04*w48);
  /* #266: @17 = (@17+@48) */
  w17 += w48;
  /* #267: @61 = vertcat(@47, @46, @62, @17) */
  rr=w61;
  *rr++ = w47;
  *rr++ = w46;
  *rr++ = w62;
  *rr++ = w17;
  /* #268: @64 = (-@61) */
  for (i=0, rr=w64, cs=w61; i<4; ++i) *rr++ = (- *cs++ );
  /* #269: @64 = (@13?@64:0) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #270: @61 = (@12?@61:0) */
  for (i=0, rr=w61, cs=w61; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #271: @64 = (@64+@61) */
  for (i=0, rr=w64, cs=w61; i<4; ++i) (*rr++) += (*cs++);
  /* #272: @24 = @64[1:4] */
  for (rr=w24, cs=w64+1; cs!=w64+4; cs+=1) *rr++ = *cs;
  /* #273: @47 = dot(@20, @24) */
  w47 = casadi_dot(3, w20, w24);
  /* #274: @47 = (@47/@14) */
  w47 /= w14;
  /* #275: @46 = (@47/@10) */
  w46  = (w47/w10);
  /* #276: @62 = (@11/@10) */
  w62  = (w11/w10);
  /* #277: @17 = (2.*@14) */
  w17 = (2.* w14 );
  /* #278: @48 = (@17*@47) */
  w48  = (w17*w47);
  /* #279: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #280: @43 = @64[0] */
  for (rr=(&w43), cs=w64+0; cs!=w64+1; cs+=1) *rr++ = *cs;
  /* #281: @18 = (@15*@43) */
  w18  = (w15*w43);
  /* #282: @48 = (@48+@18) */
  w48 += w18;
  /* #283: @18 = (@62*@48) */
  w18  = (w62*w48);
  /* #284: @46 = (@46-@18) */
  w46 -= w18;
  /* #285: @46 = (@0*@46) */
  w46  = (w00*w46);
  /* #286: @41 = (2.*@24) */
  for (i=0, rr=w41, cs=w24; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #287: @22 = (@9*@41) */
  for (i=0, rr=w22, cs=w41; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #288: @18 = (@16*@47) */
  w18  = (w16*w47);
  /* #289: @63 = (@11*@43) */
  w63  = (w11*w43);
  /* #290: @18 = (@18-@63) */
  w18 -= w63;
  /* #291: @42 = (@33*@18) */
  for (i=0, rr=w42, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)*w18);
  /* #292: @22 = (@22+@42) */
  for (i=0, rr=w22, cs=w42; i<3; ++i) (*rr++) += (*cs++);
  /* #293: @22 = (@22/@3) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) /= w03;
  /* #294: @42 = (@34*@47) */
  for (i=0, rr=w42, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #295: @22 = (@22-@42) */
  for (i=0, rr=w22, cs=w42; i<3; ++i) (*rr++) -= (*cs++);
  /* #296: @42 = @22' */
  casadi_copy(w22, 3, w42);
  /* #297: @65 = mac(@42,@36,@1) */
  casadi_copy(w01, 3, w65);
  for (i=0, rr=w65; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w42+j, ct=wr36+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #298: @65 = @65' */
  /* #299: @66 = mac(@42,@39,@1) */
  casadi_copy(w01, 3, w66);
  for (i=0, rr=w66; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w42+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #300: @66 = @66' */
  /* #301: @65 = (@65+@66) */
  for (i=0, rr=w65, cs=w66; i<3; ++i) (*rr++) += (*cs++);
  /* #302: @66 = (@65/@3) */
  for (i=0, rr=w66, cr=w65; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #303: @42 = (@40/@3) */
  for (i=0, rr=w42, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #304: @67 = (@42*@47) */
  for (i=0, rr=w67, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #305: @66 = (@66-@67) */
  for (i=0, rr=w66, cs=w67; i<3; ++i) (*rr++) -= (*cs++);
  /* #306: @63 = dot(@33, @66) */
  w63 = casadi_dot(3, w33, w66);
  /* #307: @68 = dot(@41, @40) */
  w68 = casadi_dot(3, w41, w40);
  /* #308: @63 = (@63+@68) */
  w63 += w68;
  /* #309: @68 = (@11*@63) */
  w68  = (w11*w63);
  /* #310: @46 = (@46+@68) */
  w46 += w68;
  /* #311: @46 = (-@46) */
  w46 = (- w46 );
  /* #312: @64 = @32; (@64[0] += @46) */
  casadi_copy(w32, 4, w64);
  for (rr=w64+0, cs=(&w46); rr!=w64+1; rr+=1) *rr += *cs++;
  /* #313: @46 = dot(@35, @65) */
  w46 = casadi_dot(3, w35, w65);
  /* #314: @22 = (@22/@3) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) /= w03;
  /* #315: @65 = (@34/@3) */
  for (i=0, rr=w65, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #316: @41 = (@65*@47) */
  for (i=0, rr=w41, cr=w65; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #317: @22 = (@22-@41) */
  for (i=0, rr=w22, cs=w41; i<3; ++i) (*rr++) -= (*cs++);
  /* #318: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #319: @68 = dot(@22, @37) */
  w68 = casadi_dot(3, w22, w37);
  /* #320: @46 = (@46+@68) */
  w46 += w68;
  /* #321: @43 = (@43/@10) */
  w43 /= w10;
  /* #322: @68 = (@16/@10) */
  w68  = (w16/w10);
  /* #323: @48 = (@68*@48) */
  w48  = (w68*w48);
  /* #324: @43 = (@43-@48) */
  w43 -= w48;
  /* #325: @43 = (@0*@43) */
  w43  = (w00*w43);
  /* #326: @63 = (@16*@63) */
  w63  = (w16*w63);
  /* #327: @43 = (@43+@63) */
  w43 += w63;
  /* #328: @46 = (@46+@43) */
  w46 += w43;
  /* #329: @46 = (@46/@14) */
  w46 /= w14;
  /* #330: @43 = (@2/@14) */
  w43  = (w02/w14);
  /* #331: @47 = (@43*@47) */
  w47  = (w43*w47);
  /* #332: @46 = (@46-@47) */
  w46 -= w47;
  /* #333: @22 = (@20*@46) */
  for (i=0, rr=w22, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w46);
  /* #334: @24 = (@2*@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #335: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #336: @24 = (@40*@18) */
  for (i=0, rr=w24, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w18);
  /* #337: @66 = (@9*@66) */
  for (i=0, rr=w66, cs=w66; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #338: @24 = (@24+@66) */
  for (i=0, rr=w24, cs=w66; i<3; ++i) (*rr++) += (*cs++);
  /* #339: @24 = (2.*@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #340: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #341: (@64[1:4] += @22) */
  for (rr=w64+1, cs=w22; rr!=w64+4; rr+=1) *rr += *cs++;
  /* #342: @61 = (@12?@64:0) */
  for (i=0, rr=w61, cs=w64; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #343: @64 = (-@64) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) *rr++ = (- *cs++ );
  /* #344: @64 = (@13?@64:0) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #345: @61 = (@61+@64) */
  for (i=0, rr=w61, cs=w64; i<4; ++i) (*rr++) += (*cs++);
  /* #346: {@18, @46, @47, @63} = vertsplit(@61) */
  w18 = w61[0];
  w46 = w61[1];
  w47 = w61[2];
  w63 = w61[3];
  /* #347: @48 = (@7*@63) */
  w48  = (w07*w63);
  /* #348: @69 = (@6*@47) */
  w69  = (w06*w47);
  /* #349: @48 = (@48+@69) */
  w48 += w69;
  /* #350: @69 = (@5*@46) */
  w69  = (w05*w46);
  /* #351: @48 = (@48+@69) */
  w48 += w69;
  /* #352: @69 = (@4*@18) */
  w69  = (w04*w18);
  /* #353: @48 = (@48+@69) */
  w48 += w69;
  /* #354: @69 = (@6*@63) */
  w69  = (w06*w63);
  /* #355: @70 = (@7*@47) */
  w70  = (w07*w47);
  /* #356: @69 = (@69-@70) */
  w69 -= w70;
  /* #357: @70 = (@4*@46) */
  w70  = (w04*w46);
  /* #358: @69 = (@69+@70) */
  w69 += w70;
  /* #359: @70 = (@5*@18) */
  w70  = (w05*w18);
  /* #360: @69 = (@69-@70) */
  w69 -= w70;
  /* #361: @70 = (@4*@47) */
  w70  = (w04*w47);
  /* #362: @71 = (@5*@63) */
  w71  = (w05*w63);
  /* #363: @70 = (@70-@71) */
  w70 -= w71;
  /* #364: @71 = (@7*@46) */
  w71  = (w07*w46);
  /* #365: @70 = (@70+@71) */
  w70 += w71;
  /* #366: @71 = (@6*@18) */
  w71  = (w06*w18);
  /* #367: @70 = (@70-@71) */
  w70 -= w71;
  /* #368: @63 = (@4*@63) */
  w63  = (w04*w63);
  /* #369: @47 = (@5*@47) */
  w47  = (w05*w47);
  /* #370: @63 = (@63+@47) */
  w63 += w47;
  /* #371: @46 = (@6*@46) */
  w46  = (w06*w46);
  /* #372: @63 = (@63-@46) */
  w63 -= w46;
  /* #373: @18 = (@7*@18) */
  w18  = (w07*w18);
  /* #374: @63 = (@63-@18) */
  w63 -= w18;
  /* #375: @61 = vertcat(@48, @69, @70, @63) */
  rr=w61;
  *rr++ = w48;
  *rr++ = w69;
  *rr++ = w70;
  *rr++ = w63;
  /* #376: @48 = dot(@29, @61) */
  w48 = casadi_dot(4, w29, w61);
  /* #377: @60 = (@60/@8) */
  for (i=0, rr=w60; i<4; ++i) (*rr++) /= w08;
  /* #378: @64 = (@26/@8) */
  for (i=0, rr=w64, cr=w26; i<4; ++i) (*rr++)  = ((*cr++)/w08);
  /* #379: @72 = (@64*@51) */
  for (i=0, rr=w72, cr=w64; i<4; ++i) (*rr++)  = ((*cr++)*w51);
  /* #380: @60 = (@60-@72) */
  for (i=0, rr=w60, cs=w72; i<4; ++i) (*rr++) -= (*cs++);
  /* #381: @60 = (-@60) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) *rr++ = (- *cs++ );
  /* #382: @69 = dot(@60, @31) */
  w69 = casadi_dot(4, w60, w31);
  /* #383: @48 = (@48+@69) */
  w48 += w69;
  /* #384: @48 = (@48/@8) */
  w48 /= w08;
  /* #385: @69 = (@45/@8) */
  w69  = (w45/w08);
  /* #386: @70 = (@69*@51) */
  w70  = (w69*w51);
  /* #387: @48 = (@48-@70) */
  w48 -= w70;
  /* #388: @60 = (@30*@48) */
  for (i=0, rr=w60, cr=w30; i<4; ++i) (*rr++)  = ((*cr++)*w48);
  /* #389: @54 = (@45*@54) */
  w54  = (w45*w54);
  /* #390: @72 = dense(@54) */
  casadi_densify((&w54), casadi_s3, w72, 0);
  /* #391: @60 = (@60+@72) */
  for (i=0, rr=w60, cs=w72; i<4; ++i) (*rr++) += (*cs++);
  /* #392: @49 = @21; (@49[6:10] += @60) */
  casadi_copy(w21, 13, w49);
  for (rr=w49+6, cs=w60; rr!=w49+10; rr+=1) *rr += *cs++;
  /* #393: @55 = sparsity_cast(@55) */
  /* #394: @55 = (-@55) */
  w55 = (- w55 );
  /* #395: @55 = @55' */
  /* #396: @22 = mac(@55,@23,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w55), casadi_s6, wr23, casadi_s5, w22, casadi_s4, w, 0);
  /* #397: @22 = @22' */
  /* #398: @24 = mac(@55,@50,@1) */
  casadi_copy(w01, 3, w24);
  casadi_mtimes((&w55), casadi_s6, w50, casadi_s5, w24, casadi_s4, w, 0);
  /* #399: @24 = @24' */
  /* #400: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #401: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #402: (@49[:3] += @22) */
  for (rr=w49+0, cs=w22; rr!=w49+3; rr+=1) *rr += *cs++;
  /* #403: {@55, @54, @48, @70, @63, @18, @46, @47, @71, @73, @74, @75, @76} = vertsplit(@49) */
  w55 = w49[0];
  w54 = w49[1];
  w48 = w49[2];
  w70 = w49[3];
  w63 = w49[4];
  w18 = w49[5];
  w46 = w49[6];
  w47 = w49[7];
  w71 = w49[8];
  w73 = w49[9];
  w74 = w49[10];
  w75 = w49[11];
  w76 = w49[12];
  /* #404: @61 = (@61/@8) */
  for (i=0, rr=w61; i<4; ++i) (*rr++) /= w08;
  /* #405: @27 = (@27/@8) */
  for (i=0, rr=w27; i<4; ++i) (*rr++) /= w08;
  /* #406: @60 = (@27*@51) */
  for (i=0, rr=w60, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)*w51);
  /* #407: @61 = (@61-@60) */
  for (i=0, rr=w61, cs=w60; i<4; ++i) (*rr++) -= (*cs++);
  /* #408: {@51, @77, @78, @79} = vertsplit(@61) */
  w51 = w61[0];
  w77 = w61[1];
  w78 = w61[2];
  w79 = w61[3];
  /* #409: @51 = (@51+@46) */
  w51 += w46;
  /* #410: @47 = (@47-@77) */
  w47 -= w77;
  /* #411: @71 = (@71-@78) */
  w71 -= w78;
  /* #412: @73 = (@73-@79) */
  w73 -= w79;
  /* #413: @19 = vertcat(@53, @56, @44, @52, @55, @54, @48, @70, @63, @18, @51, @47, @71, @73, @74, @75, @76) */
  rr=w19;
  *rr++ = w53;
  *rr++ = w56;
  *rr++ = w44;
  *rr++ = w52;
  *rr++ = w55;
  *rr++ = w54;
  *rr++ = w48;
  *rr++ = w70;
  *rr++ = w63;
  *rr++ = w18;
  *rr++ = w51;
  *rr++ = w47;
  *rr++ = w71;
  *rr++ = w73;
  *rr++ = w74;
  *rr++ = w75;
  *rr++ = w76;
  /* #414: @80 = @19[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s7, rr=w80, cs=w19; cii!=casadi_s7+11; ++cii) *rr++ = cs[*cii];
  /* #415: (@57[0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 28] = @80) */
  for (cii=casadi_s8, rr=w57, cs=w80; cii!=casadi_s8+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #416: (@57[0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37] = @80) */
  for (cii=casadi_s9, rr=w57, cs=w80; cii!=casadi_s9+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #417: @22 = ones(17x1,3nz) */
  casadi_fill(w22, 3, 1.);
  /* #418: {NULL, @53, NULL, NULL, NULL, @56, NULL, NULL, NULL, NULL, NULL, @44, NULL, NULL, NULL, NULL, NULL} = vertsplit(@22) */
  w53 = w22[0];
  w56 = w22[1];
  w44 = w22[2];
  /* #419: @52 = vertcat(@59, @53, @59, @59) */
  rr=(&w52);
  *rr++ = w53;
  /* #420: @52 = @52' */
  /* #421: @61 = mac(@52,@28,@25) */
  casadi_copy(w25, 4, w61);
  casadi_mtimes((&w52), casadi_s10, wr28, casadi_s1, w61, casadi_s0, w, 0);
  /* #422: @61 = @61' */
  /* #423: @60 = mac(@52,@38,@25) */
  casadi_copy(w25, 4, w60);
  casadi_mtimes((&w52), casadi_s10, w38, casadi_s1, w60, casadi_s0, w, 0);
  /* #424: @60 = @60' */
  /* #425: @61 = (@61+@60) */
  for (i=0, rr=w61, cs=w60; i<4; ++i) (*rr++) += (*cs++);
  /* #426: {@52, @53, @55, @54} = vertsplit(@61) */
  w52 = w61[0];
  w53 = w61[1];
  w55 = w61[2];
  w54 = w61[3];
  /* #427: @48 = (-@44) */
  w48 = (- w44 );
  /* #428: @70 = vertcat(@59, @48, @59, @59) */
  rr=(&w70);
  *rr++ = w48;
  /* #429: @70 = (@70/@8) */
  w70 /= w08;
  /* #430: @61 = dense(@70) */
  casadi_densify((&w70), casadi_s11, w61, 0);
  /* #431: @70 = project(@30) */
  casadi_sparsify(w30, (&w70), casadi_s11, 0);
  /* #432: @44 = sparsity_cast(@44) */
  /* #433: @48 = dot(@70, @44) */
  w48 = casadi_dot(1, (&w70), (&w44));
  /* #434: @48 = (@48/@8) */
  w48 /= w08;
  /* #435: @60 = (@26*@48) */
  for (i=0, rr=w60, cr=w26; i<4; ++i) (*rr++)  = ((*cr++)*w48);
  /* #436: @61 = (@61-@60) */
  for (i=0, rr=w61, cs=w60; i<4; ++i) (*rr++) -= (*cs++);
  /* #437: {@70, @63, @18, @51} = vertsplit(@61) */
  w70 = w61[0];
  w63 = w61[1];
  w18 = w61[2];
  w51 = w61[3];
  /* #438: @47 = (@4*@70) */
  w47  = (w04*w70);
  /* #439: @71 = (@5*@63) */
  w71  = (w05*w63);
  /* #440: @47 = (@47-@71) */
  w47 -= w71;
  /* #441: @71 = (@6*@18) */
  w71  = (w06*w18);
  /* #442: @47 = (@47-@71) */
  w47 -= w71;
  /* #443: @71 = (@7*@51) */
  w71  = (w07*w51);
  /* #444: @47 = (@47-@71) */
  w47 -= w71;
  /* #445: @71 = (@5*@70) */
  w71  = (w05*w70);
  /* #446: @73 = (@4*@63) */
  w73  = (w04*w63);
  /* #447: @71 = (@71+@73) */
  w71 += w73;
  /* #448: @73 = (@7*@18) */
  w73  = (w07*w18);
  /* #449: @71 = (@71+@73) */
  w71 += w73;
  /* #450: @73 = (@6*@51) */
  w73  = (w06*w51);
  /* #451: @71 = (@71-@73) */
  w71 -= w73;
  /* #452: @73 = (@6*@70) */
  w73  = (w06*w70);
  /* #453: @74 = (@7*@63) */
  w74  = (w07*w63);
  /* #454: @73 = (@73-@74) */
  w73 -= w74;
  /* #455: @74 = (@4*@18) */
  w74  = (w04*w18);
  /* #456: @73 = (@73+@74) */
  w73 += w74;
  /* #457: @74 = (@5*@51) */
  w74  = (w05*w51);
  /* #458: @73 = (@73+@74) */
  w73 += w74;
  /* #459: @70 = (@7*@70) */
  w70  = (w07*w70);
  /* #460: @63 = (@6*@63) */
  w63  = (w06*w63);
  /* #461: @70 = (@70+@63) */
  w70 += w63;
  /* #462: @18 = (@5*@18) */
  w18  = (w05*w18);
  /* #463: @70 = (@70-@18) */
  w70 -= w18;
  /* #464: @51 = (@4*@51) */
  w51  = (w04*w51);
  /* #465: @70 = (@70+@51) */
  w70 += w51;
  /* #466: @60 = vertcat(@47, @71, @73, @70) */
  rr=w60;
  *rr++ = w47;
  *rr++ = w71;
  *rr++ = w73;
  *rr++ = w70;
  /* #467: @72 = (-@60) */
  for (i=0, rr=w72, cs=w60; i<4; ++i) *rr++ = (- *cs++ );
  /* #468: @72 = (@13?@72:0) */
  for (i=0, rr=w72, cs=w72; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #469: @60 = (@12?@60:0) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #470: @72 = (@72+@60) */
  for (i=0, rr=w72, cs=w60; i<4; ++i) (*rr++) += (*cs++);
  /* #471: @22 = @72[1:4] */
  for (rr=w22, cs=w72+1; cs!=w72+4; cs+=1) *rr++ = *cs;
  /* #472: @47 = dot(@20, @22) */
  w47 = casadi_dot(3, w20, w22);
  /* #473: @47 = (@47/@14) */
  w47 /= w14;
  /* #474: @71 = (@47/@10) */
  w71  = (w47/w10);
  /* #475: @73 = (@17*@47) */
  w73  = (w17*w47);
  /* #476: @70 = @72[0] */
  for (rr=(&w70), cs=w72+0; cs!=w72+1; cs+=1) *rr++ = *cs;
  /* #477: @51 = (@15*@70) */
  w51  = (w15*w70);
  /* #478: @73 = (@73+@51) */
  w73 += w51;
  /* #479: @51 = (@62*@73) */
  w51  = (w62*w73);
  /* #480: @71 = (@71-@51) */
  w71 -= w51;
  /* #481: @71 = (@0*@71) */
  w71  = (w00*w71);
  /* #482: @24 = (2.*@22) */
  for (i=0, rr=w24, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #483: @66 = (@9*@24) */
  for (i=0, rr=w66, cs=w24; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #484: @51 = (@16*@47) */
  w51  = (w16*w47);
  /* #485: @18 = (@11*@70) */
  w18  = (w11*w70);
  /* #486: @51 = (@51-@18) */
  w51 -= w18;
  /* #487: @41 = (@33*@51) */
  for (i=0, rr=w41, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)*w51);
  /* #488: @66 = (@66+@41) */
  for (i=0, rr=w66, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #489: @66 = (@66/@3) */
  for (i=0, rr=w66; i<3; ++i) (*rr++) /= w03;
  /* #490: @41 = (@34*@47) */
  for (i=0, rr=w41, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #491: @66 = (@66-@41) */
  for (i=0, rr=w66, cs=w41; i<3; ++i) (*rr++) -= (*cs++);
  /* #492: @41 = @66' */
  casadi_copy(w66, 3, w41);
  /* #493: @67 = mac(@41,@36,@1) */
  casadi_copy(w01, 3, w67);
  for (i=0, rr=w67; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w41+j, ct=wr36+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #494: @67 = @67' */
  /* #495: @81 = mac(@41,@39,@1) */
  casadi_copy(w01, 3, w81);
  for (i=0, rr=w81; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w41+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #496: @81 = @81' */
  /* #497: @67 = (@67+@81) */
  for (i=0, rr=w67, cs=w81; i<3; ++i) (*rr++) += (*cs++);
  /* #498: @81 = (@67/@3) */
  for (i=0, rr=w81, cr=w67; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #499: @41 = (@42*@47) */
  for (i=0, rr=w41, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #500: @81 = (@81-@41) */
  for (i=0, rr=w81, cs=w41; i<3; ++i) (*rr++) -= (*cs++);
  /* #501: @18 = dot(@33, @81) */
  w18 = casadi_dot(3, w33, w81);
  /* #502: @63 = dot(@24, @40) */
  w63 = casadi_dot(3, w24, w40);
  /* #503: @18 = (@18+@63) */
  w18 += w63;
  /* #504: @63 = (@11*@18) */
  w63  = (w11*w18);
  /* #505: @71 = (@71+@63) */
  w71 += w63;
  /* #506: @71 = (-@71) */
  w71 = (- w71 );
  /* #507: @72 = @32; (@72[0] += @71) */
  casadi_copy(w32, 4, w72);
  for (rr=w72+0, cs=(&w71); rr!=w72+1; rr+=1) *rr += *cs++;
  /* #508: @71 = dot(@35, @67) */
  w71 = casadi_dot(3, w35, w67);
  /* #509: @66 = (@66/@3) */
  for (i=0, rr=w66; i<3; ++i) (*rr++) /= w03;
  /* #510: @67 = (@65*@47) */
  for (i=0, rr=w67, cr=w65; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #511: @66 = (@66-@67) */
  for (i=0, rr=w66, cs=w67; i<3; ++i) (*rr++) -= (*cs++);
  /* #512: @66 = (-@66) */
  for (i=0, rr=w66, cs=w66; i<3; ++i) *rr++ = (- *cs++ );
  /* #513: @63 = dot(@66, @37) */
  w63 = casadi_dot(3, w66, w37);
  /* #514: @71 = (@71+@63) */
  w71 += w63;
  /* #515: @70 = (@70/@10) */
  w70 /= w10;
  /* #516: @73 = (@68*@73) */
  w73  = (w68*w73);
  /* #517: @70 = (@70-@73) */
  w70 -= w73;
  /* #518: @70 = (@0*@70) */
  w70  = (w00*w70);
  /* #519: @18 = (@16*@18) */
  w18  = (w16*w18);
  /* #520: @70 = (@70+@18) */
  w70 += w18;
  /* #521: @71 = (@71+@70) */
  w71 += w70;
  /* #522: @71 = (@71/@14) */
  w71 /= w14;
  /* #523: @47 = (@43*@47) */
  w47  = (w43*w47);
  /* #524: @71 = (@71-@47) */
  w71 -= w47;
  /* #525: @66 = (@20*@71) */
  for (i=0, rr=w66, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w71);
  /* #526: @22 = (@2*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #527: @66 = (@66+@22) */
  for (i=0, rr=w66, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #528: @22 = (@40*@51) */
  for (i=0, rr=w22, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w51);
  /* #529: @81 = (@9*@81) */
  for (i=0, rr=w81, cs=w81; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #530: @22 = (@22+@81) */
  for (i=0, rr=w22, cs=w81; i<3; ++i) (*rr++) += (*cs++);
  /* #531: @22 = (2.*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #532: @66 = (@66+@22) */
  for (i=0, rr=w66, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #533: (@72[1:4] += @66) */
  for (rr=w72+1, cs=w66; rr!=w72+4; rr+=1) *rr += *cs++;
  /* #534: @60 = (@12?@72:0) */
  for (i=0, rr=w60, cs=w72; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #535: @72 = (-@72) */
  for (i=0, rr=w72, cs=w72; i<4; ++i) *rr++ = (- *cs++ );
  /* #536: @72 = (@13?@72:0) */
  for (i=0, rr=w72, cs=w72; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #537: @60 = (@60+@72) */
  for (i=0, rr=w60, cs=w72; i<4; ++i) (*rr++) += (*cs++);
  /* #538: {@51, @71, @47, @70} = vertsplit(@60) */
  w51 = w60[0];
  w71 = w60[1];
  w47 = w60[2];
  w70 = w60[3];
  /* #539: @18 = (@7*@70) */
  w18  = (w07*w70);
  /* #540: @73 = (@6*@47) */
  w73  = (w06*w47);
  /* #541: @18 = (@18+@73) */
  w18 += w73;
  /* #542: @73 = (@5*@71) */
  w73  = (w05*w71);
  /* #543: @18 = (@18+@73) */
  w18 += w73;
  /* #544: @73 = (@4*@51) */
  w73  = (w04*w51);
  /* #545: @18 = (@18+@73) */
  w18 += w73;
  /* #546: @73 = (@6*@70) */
  w73  = (w06*w70);
  /* #547: @63 = (@7*@47) */
  w63  = (w07*w47);
  /* #548: @73 = (@73-@63) */
  w73 -= w63;
  /* #549: @63 = (@4*@71) */
  w63  = (w04*w71);
  /* #550: @73 = (@73+@63) */
  w73 += w63;
  /* #551: @63 = (@5*@51) */
  w63  = (w05*w51);
  /* #552: @73 = (@73-@63) */
  w73 -= w63;
  /* #553: @63 = (@4*@47) */
  w63  = (w04*w47);
  /* #554: @74 = (@5*@70) */
  w74  = (w05*w70);
  /* #555: @63 = (@63-@74) */
  w63 -= w74;
  /* #556: @74 = (@7*@71) */
  w74  = (w07*w71);
  /* #557: @63 = (@63+@74) */
  w63 += w74;
  /* #558: @74 = (@6*@51) */
  w74  = (w06*w51);
  /* #559: @63 = (@63-@74) */
  w63 -= w74;
  /* #560: @70 = (@4*@70) */
  w70  = (w04*w70);
  /* #561: @47 = (@5*@47) */
  w47  = (w05*w47);
  /* #562: @70 = (@70+@47) */
  w70 += w47;
  /* #563: @71 = (@6*@71) */
  w71  = (w06*w71);
  /* #564: @70 = (@70-@71) */
  w70 -= w71;
  /* #565: @51 = (@7*@51) */
  w51  = (w07*w51);
  /* #566: @70 = (@70-@51) */
  w70 -= w51;
  /* #567: @60 = vertcat(@18, @73, @63, @70) */
  rr=w60;
  *rr++ = w18;
  *rr++ = w73;
  *rr++ = w63;
  *rr++ = w70;
  /* #568: @18 = dot(@29, @60) */
  w18 = casadi_dot(4, w29, w60);
  /* #569: @61 = (@61/@8) */
  for (i=0, rr=w61; i<4; ++i) (*rr++) /= w08;
  /* #570: @72 = (@64*@48) */
  for (i=0, rr=w72, cr=w64; i<4; ++i) (*rr++)  = ((*cr++)*w48);
  /* #571: @61 = (@61-@72) */
  for (i=0, rr=w61, cs=w72; i<4; ++i) (*rr++) -= (*cs++);
  /* #572: @61 = (-@61) */
  for (i=0, rr=w61, cs=w61; i<4; ++i) *rr++ = (- *cs++ );
  /* #573: @73 = dot(@61, @31) */
  w73 = casadi_dot(4, w61, w31);
  /* #574: @18 = (@18+@73) */
  w18 += w73;
  /* #575: @18 = (@18/@8) */
  w18 /= w08;
  /* #576: @73 = (@69*@48) */
  w73  = (w69*w48);
  /* #577: @18 = (@18-@73) */
  w18 -= w73;
  /* #578: @61 = (@30*@18) */
  for (i=0, rr=w61, cr=w30; i<4; ++i) (*rr++)  = ((*cr++)*w18);
  /* #579: @44 = (@45*@44) */
  w44  = (w45*w44);
  /* #580: @72 = dense(@44) */
  casadi_densify((&w44), casadi_s11, w72, 0);
  /* #581: @61 = (@61+@72) */
  for (i=0, rr=w61, cs=w72; i<4; ++i) (*rr++) += (*cs++);
  /* #582: @49 = @21; (@49[6:10] += @61) */
  casadi_copy(w21, 13, w49);
  for (rr=w49+6, cs=w61; rr!=w49+10; rr+=1) *rr += *cs++;
  /* #583: @56 = sparsity_cast(@56) */
  /* #584: @56 = (-@56) */
  w56 = (- w56 );
  /* #585: @56 = @56' */
  /* #586: @66 = mac(@56,@23,@1) */
  casadi_copy(w01, 3, w66);
  casadi_mtimes((&w56), casadi_s12, wr23, casadi_s5, w66, casadi_s4, w, 0);
  /* #587: @66 = @66' */
  /* #588: @22 = mac(@56,@50,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w56), casadi_s12, w50, casadi_s5, w22, casadi_s4, w, 0);
  /* #589: @22 = @22' */
  /* #590: @66 = (@66+@22) */
  for (i=0, rr=w66, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #591: @66 = (-@66) */
  for (i=0, rr=w66, cs=w66; i<3; ++i) *rr++ = (- *cs++ );
  /* #592: (@49[:3] += @66) */
  for (rr=w49+0, cs=w66; rr!=w49+3; rr+=1) *rr += *cs++;
  /* #593: {@56, @44, @18, @73, @63, @70, @51, @71, @47, @74, @75, @76, @79} = vertsplit(@49) */
  w56 = w49[0];
  w44 = w49[1];
  w18 = w49[2];
  w73 = w49[3];
  w63 = w49[4];
  w70 = w49[5];
  w51 = w49[6];
  w71 = w49[7];
  w47 = w49[8];
  w74 = w49[9];
  w75 = w49[10];
  w76 = w49[11];
  w79 = w49[12];
  /* #594: @60 = (@60/@8) */
  for (i=0, rr=w60; i<4; ++i) (*rr++) /= w08;
  /* #595: @61 = (@27*@48) */
  for (i=0, rr=w61, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)*w48);
  /* #596: @60 = (@60-@61) */
  for (i=0, rr=w60, cs=w61; i<4; ++i) (*rr++) -= (*cs++);
  /* #597: {@48, @78, @77, @46} = vertsplit(@60) */
  w48 = w60[0];
  w78 = w60[1];
  w77 = w60[2];
  w46 = w60[3];
  /* #598: @48 = (@48+@51) */
  w48 += w51;
  /* #599: @71 = (@71-@78) */
  w71 -= w78;
  /* #600: @47 = (@47-@77) */
  w47 -= w77;
  /* #601: @74 = (@74-@46) */
  w74 -= w46;
  /* #602: @19 = vertcat(@52, @53, @55, @54, @56, @44, @18, @73, @63, @70, @48, @71, @47, @74, @75, @76, @79) */
  rr=w19;
  *rr++ = w52;
  *rr++ = w53;
  *rr++ = w55;
  *rr++ = w54;
  *rr++ = w56;
  *rr++ = w44;
  *rr++ = w18;
  *rr++ = w73;
  *rr++ = w63;
  *rr++ = w70;
  *rr++ = w48;
  *rr++ = w71;
  *rr++ = w47;
  *rr++ = w74;
  *rr++ = w75;
  *rr++ = w76;
  *rr++ = w79;
  /* #603: @80 = @19[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s7, rr=w80, cs=w19; cii!=casadi_s7+11; ++cii) *rr++ = cs[*cii];
  /* #604: (@57[4, 5, 6, 7, 19, 20, 21, 29, 30, 31, 32] = @80) */
  for (cii=casadi_s13, rr=w57, cs=w80; cii!=casadi_s13+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #605: (@57[1, 5, 9, 13, 17, 20, 23, 26, 30, 34, 38] = @80) */
  for (cii=casadi_s14, rr=w57, cs=w80; cii!=casadi_s14+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #606: @66 = ones(17x1,3nz) */
  casadi_fill(w66, 3, 1.);
  /* #607: {NULL, NULL, @52, NULL, NULL, NULL, @53, NULL, NULL, NULL, NULL, NULL, @55, NULL, NULL, NULL, NULL} = vertsplit(@66) */
  w52 = w66[0];
  w53 = w66[1];
  w55 = w66[2];
  /* #608: @54 = vertcat(@59, @59, @52, @59) */
  rr=(&w54);
  *rr++ = w52;
  /* #609: @54 = @54' */
  /* #610: @60 = mac(@54,@28,@25) */
  casadi_copy(w25, 4, w60);
  casadi_mtimes((&w54), casadi_s15, wr28, casadi_s1, w60, casadi_s0, w, 0);
  /* #611: @60 = @60' */
  /* #612: @61 = mac(@54,@38,@25) */
  casadi_copy(w25, 4, w61);
  casadi_mtimes((&w54), casadi_s15, w38, casadi_s1, w61, casadi_s0, w, 0);
  /* #613: @61 = @61' */
  /* #614: @60 = (@60+@61) */
  for (i=0, rr=w60, cs=w61; i<4; ++i) (*rr++) += (*cs++);
  /* #615: {@54, @52, @56, @44} = vertsplit(@60) */
  w54 = w60[0];
  w52 = w60[1];
  w56 = w60[2];
  w44 = w60[3];
  /* #616: @18 = (-@55) */
  w18 = (- w55 );
  /* #617: @73 = vertcat(@59, @59, @18, @59) */
  rr=(&w73);
  *rr++ = w18;
  /* #618: @73 = (@73/@8) */
  w73 /= w08;
  /* #619: @60 = dense(@73) */
  casadi_densify((&w73), casadi_s16, w60, 0);
  /* #620: @73 = project(@30) */
  casadi_sparsify(w30, (&w73), casadi_s16, 0);
  /* #621: @55 = sparsity_cast(@55) */
  /* #622: @18 = dot(@73, @55) */
  w18 = casadi_dot(1, (&w73), (&w55));
  /* #623: @18 = (@18/@8) */
  w18 /= w08;
  /* #624: @61 = (@26*@18) */
  for (i=0, rr=w61, cr=w26; i<4; ++i) (*rr++)  = ((*cr++)*w18);
  /* #625: @60 = (@60-@61) */
  for (i=0, rr=w60, cs=w61; i<4; ++i) (*rr++) -= (*cs++);
  /* #626: {@73, @63, @70, @48} = vertsplit(@60) */
  w73 = w60[0];
  w63 = w60[1];
  w70 = w60[2];
  w48 = w60[3];
  /* #627: @71 = (@4*@73) */
  w71  = (w04*w73);
  /* #628: @47 = (@5*@63) */
  w47  = (w05*w63);
  /* #629: @71 = (@71-@47) */
  w71 -= w47;
  /* #630: @47 = (@6*@70) */
  w47  = (w06*w70);
  /* #631: @71 = (@71-@47) */
  w71 -= w47;
  /* #632: @47 = (@7*@48) */
  w47  = (w07*w48);
  /* #633: @71 = (@71-@47) */
  w71 -= w47;
  /* #634: @47 = (@5*@73) */
  w47  = (w05*w73);
  /* #635: @74 = (@4*@63) */
  w74  = (w04*w63);
  /* #636: @47 = (@47+@74) */
  w47 += w74;
  /* #637: @74 = (@7*@70) */
  w74  = (w07*w70);
  /* #638: @47 = (@47+@74) */
  w47 += w74;
  /* #639: @74 = (@6*@48) */
  w74  = (w06*w48);
  /* #640: @47 = (@47-@74) */
  w47 -= w74;
  /* #641: @74 = (@6*@73) */
  w74  = (w06*w73);
  /* #642: @75 = (@7*@63) */
  w75  = (w07*w63);
  /* #643: @74 = (@74-@75) */
  w74 -= w75;
  /* #644: @75 = (@4*@70) */
  w75  = (w04*w70);
  /* #645: @74 = (@74+@75) */
  w74 += w75;
  /* #646: @75 = (@5*@48) */
  w75  = (w05*w48);
  /* #647: @74 = (@74+@75) */
  w74 += w75;
  /* #648: @73 = (@7*@73) */
  w73  = (w07*w73);
  /* #649: @63 = (@6*@63) */
  w63  = (w06*w63);
  /* #650: @73 = (@73+@63) */
  w73 += w63;
  /* #651: @70 = (@5*@70) */
  w70  = (w05*w70);
  /* #652: @73 = (@73-@70) */
  w73 -= w70;
  /* #653: @48 = (@4*@48) */
  w48  = (w04*w48);
  /* #654: @73 = (@73+@48) */
  w73 += w48;
  /* #655: @61 = vertcat(@71, @47, @74, @73) */
  rr=w61;
  *rr++ = w71;
  *rr++ = w47;
  *rr++ = w74;
  *rr++ = w73;
  /* #656: @72 = (-@61) */
  for (i=0, rr=w72, cs=w61; i<4; ++i) *rr++ = (- *cs++ );
  /* #657: @72 = (@13?@72:0) */
  for (i=0, rr=w72, cs=w72; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #658: @61 = (@12?@61:0) */
  for (i=0, rr=w61, cs=w61; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #659: @72 = (@72+@61) */
  for (i=0, rr=w72, cs=w61; i<4; ++i) (*rr++) += (*cs++);
  /* #660: @66 = @72[1:4] */
  for (rr=w66, cs=w72+1; cs!=w72+4; cs+=1) *rr++ = *cs;
  /* #661: @71 = dot(@20, @66) */
  w71 = casadi_dot(3, w20, w66);
  /* #662: @71 = (@71/@14) */
  w71 /= w14;
  /* #663: @47 = (@71/@10) */
  w47  = (w71/w10);
  /* #664: @74 = (@17*@71) */
  w74  = (w17*w71);
  /* #665: @73 = @72[0] */
  for (rr=(&w73), cs=w72+0; cs!=w72+1; cs+=1) *rr++ = *cs;
  /* #666: @48 = (@15*@73) */
  w48  = (w15*w73);
  /* #667: @74 = (@74+@48) */
  w74 += w48;
  /* #668: @48 = (@62*@74) */
  w48  = (w62*w74);
  /* #669: @47 = (@47-@48) */
  w47 -= w48;
  /* #670: @47 = (@0*@47) */
  w47  = (w00*w47);
  /* #671: @22 = (2.*@66) */
  for (i=0, rr=w22, cs=w66; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #672: @81 = (@9*@22) */
  for (i=0, rr=w81, cs=w22; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #673: @48 = (@16*@71) */
  w48  = (w16*w71);
  /* #674: @70 = (@11*@73) */
  w70  = (w11*w73);
  /* #675: @48 = (@48-@70) */
  w48 -= w70;
  /* #676: @67 = (@33*@48) */
  for (i=0, rr=w67, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)*w48);
  /* #677: @81 = (@81+@67) */
  for (i=0, rr=w81, cs=w67; i<3; ++i) (*rr++) += (*cs++);
  /* #678: @81 = (@81/@3) */
  for (i=0, rr=w81; i<3; ++i) (*rr++) /= w03;
  /* #679: @67 = (@34*@71) */
  for (i=0, rr=w67, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w71);
  /* #680: @81 = (@81-@67) */
  for (i=0, rr=w81, cs=w67; i<3; ++i) (*rr++) -= (*cs++);
  /* #681: @67 = @81' */
  casadi_copy(w81, 3, w67);
  /* #682: @24 = mac(@67,@36,@1) */
  casadi_copy(w01, 3, w24);
  for (i=0, rr=w24; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w67+j, ct=wr36+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #683: @24 = @24' */
  /* #684: @41 = mac(@67,@39,@1) */
  casadi_copy(w01, 3, w41);
  for (i=0, rr=w41; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w67+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #685: @41 = @41' */
  /* #686: @24 = (@24+@41) */
  for (i=0, rr=w24, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #687: @41 = (@24/@3) */
  for (i=0, rr=w41, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #688: @67 = (@42*@71) */
  for (i=0, rr=w67, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w71);
  /* #689: @41 = (@41-@67) */
  for (i=0, rr=w41, cs=w67; i<3; ++i) (*rr++) -= (*cs++);
  /* #690: @70 = dot(@33, @41) */
  w70 = casadi_dot(3, w33, w41);
  /* #691: @63 = dot(@22, @40) */
  w63 = casadi_dot(3, w22, w40);
  /* #692: @70 = (@70+@63) */
  w70 += w63;
  /* #693: @63 = (@11*@70) */
  w63  = (w11*w70);
  /* #694: @47 = (@47+@63) */
  w47 += w63;
  /* #695: @47 = (-@47) */
  w47 = (- w47 );
  /* #696: @72 = @32; (@72[0] += @47) */
  casadi_copy(w32, 4, w72);
  for (rr=w72+0, cs=(&w47); rr!=w72+1; rr+=1) *rr += *cs++;
  /* #697: @47 = dot(@35, @24) */
  w47 = casadi_dot(3, w35, w24);
  /* #698: @81 = (@81/@3) */
  for (i=0, rr=w81; i<3; ++i) (*rr++) /= w03;
  /* #699: @24 = (@65*@71) */
  for (i=0, rr=w24, cr=w65; i<3; ++i) (*rr++)  = ((*cr++)*w71);
  /* #700: @81 = (@81-@24) */
  for (i=0, rr=w81, cs=w24; i<3; ++i) (*rr++) -= (*cs++);
  /* #701: @81 = (-@81) */
  for (i=0, rr=w81, cs=w81; i<3; ++i) *rr++ = (- *cs++ );
  /* #702: @63 = dot(@81, @37) */
  w63 = casadi_dot(3, w81, w37);
  /* #703: @47 = (@47+@63) */
  w47 += w63;
  /* #704: @73 = (@73/@10) */
  w73 /= w10;
  /* #705: @74 = (@68*@74) */
  w74  = (w68*w74);
  /* #706: @73 = (@73-@74) */
  w73 -= w74;
  /* #707: @73 = (@0*@73) */
  w73  = (w00*w73);
  /* #708: @70 = (@16*@70) */
  w70  = (w16*w70);
  /* #709: @73 = (@73+@70) */
  w73 += w70;
  /* #710: @47 = (@47+@73) */
  w47 += w73;
  /* #711: @47 = (@47/@14) */
  w47 /= w14;
  /* #712: @71 = (@43*@71) */
  w71  = (w43*w71);
  /* #713: @47 = (@47-@71) */
  w47 -= w71;
  /* #714: @81 = (@20*@47) */
  for (i=0, rr=w81, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #715: @66 = (@2*@66) */
  for (i=0, rr=w66, cs=w66; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #716: @81 = (@81+@66) */
  for (i=0, rr=w81, cs=w66; i<3; ++i) (*rr++) += (*cs++);
  /* #717: @66 = (@40*@48) */
  for (i=0, rr=w66, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w48);
  /* #718: @41 = (@9*@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #719: @66 = (@66+@41) */
  for (i=0, rr=w66, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #720: @66 = (2.*@66) */
  for (i=0, rr=w66, cs=w66; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #721: @81 = (@81+@66) */
  for (i=0, rr=w81, cs=w66; i<3; ++i) (*rr++) += (*cs++);
  /* #722: (@72[1:4] += @81) */
  for (rr=w72+1, cs=w81; rr!=w72+4; rr+=1) *rr += *cs++;
  /* #723: @61 = (@12?@72:0) */
  for (i=0, rr=w61, cs=w72; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #724: @72 = (-@72) */
  for (i=0, rr=w72, cs=w72; i<4; ++i) *rr++ = (- *cs++ );
  /* #725: @72 = (@13?@72:0) */
  for (i=0, rr=w72, cs=w72; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #726: @61 = (@61+@72) */
  for (i=0, rr=w61, cs=w72; i<4; ++i) (*rr++) += (*cs++);
  /* #727: {@48, @47, @71, @73} = vertsplit(@61) */
  w48 = w61[0];
  w47 = w61[1];
  w71 = w61[2];
  w73 = w61[3];
  /* #728: @70 = (@7*@73) */
  w70  = (w07*w73);
  /* #729: @74 = (@6*@71) */
  w74  = (w06*w71);
  /* #730: @70 = (@70+@74) */
  w70 += w74;
  /* #731: @74 = (@5*@47) */
  w74  = (w05*w47);
  /* #732: @70 = (@70+@74) */
  w70 += w74;
  /* #733: @74 = (@4*@48) */
  w74  = (w04*w48);
  /* #734: @70 = (@70+@74) */
  w70 += w74;
  /* #735: @74 = (@6*@73) */
  w74  = (w06*w73);
  /* #736: @63 = (@7*@71) */
  w63  = (w07*w71);
  /* #737: @74 = (@74-@63) */
  w74 -= w63;
  /* #738: @63 = (@4*@47) */
  w63  = (w04*w47);
  /* #739: @74 = (@74+@63) */
  w74 += w63;
  /* #740: @63 = (@5*@48) */
  w63  = (w05*w48);
  /* #741: @74 = (@74-@63) */
  w74 -= w63;
  /* #742: @63 = (@4*@71) */
  w63  = (w04*w71);
  /* #743: @75 = (@5*@73) */
  w75  = (w05*w73);
  /* #744: @63 = (@63-@75) */
  w63 -= w75;
  /* #745: @75 = (@7*@47) */
  w75  = (w07*w47);
  /* #746: @63 = (@63+@75) */
  w63 += w75;
  /* #747: @75 = (@6*@48) */
  w75  = (w06*w48);
  /* #748: @63 = (@63-@75) */
  w63 -= w75;
  /* #749: @73 = (@4*@73) */
  w73  = (w04*w73);
  /* #750: @71 = (@5*@71) */
  w71  = (w05*w71);
  /* #751: @73 = (@73+@71) */
  w73 += w71;
  /* #752: @47 = (@6*@47) */
  w47  = (w06*w47);
  /* #753: @73 = (@73-@47) */
  w73 -= w47;
  /* #754: @48 = (@7*@48) */
  w48  = (w07*w48);
  /* #755: @73 = (@73-@48) */
  w73 -= w48;
  /* #756: @61 = vertcat(@70, @74, @63, @73) */
  rr=w61;
  *rr++ = w70;
  *rr++ = w74;
  *rr++ = w63;
  *rr++ = w73;
  /* #757: @70 = dot(@29, @61) */
  w70 = casadi_dot(4, w29, w61);
  /* #758: @60 = (@60/@8) */
  for (i=0, rr=w60; i<4; ++i) (*rr++) /= w08;
  /* #759: @72 = (@64*@18) */
  for (i=0, rr=w72, cr=w64; i<4; ++i) (*rr++)  = ((*cr++)*w18);
  /* #760: @60 = (@60-@72) */
  for (i=0, rr=w60, cs=w72; i<4; ++i) (*rr++) -= (*cs++);
  /* #761: @60 = (-@60) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) *rr++ = (- *cs++ );
  /* #762: @74 = dot(@60, @31) */
  w74 = casadi_dot(4, w60, w31);
  /* #763: @70 = (@70+@74) */
  w70 += w74;
  /* #764: @70 = (@70/@8) */
  w70 /= w08;
  /* #765: @74 = (@69*@18) */
  w74  = (w69*w18);
  /* #766: @70 = (@70-@74) */
  w70 -= w74;
  /* #767: @60 = (@30*@70) */
  for (i=0, rr=w60, cr=w30; i<4; ++i) (*rr++)  = ((*cr++)*w70);
  /* #768: @55 = (@45*@55) */
  w55  = (w45*w55);
  /* #769: @72 = dense(@55) */
  casadi_densify((&w55), casadi_s16, w72, 0);
  /* #770: @60 = (@60+@72) */
  for (i=0, rr=w60, cs=w72; i<4; ++i) (*rr++) += (*cs++);
  /* #771: @49 = @21; (@49[6:10] += @60) */
  casadi_copy(w21, 13, w49);
  for (rr=w49+6, cs=w60; rr!=w49+10; rr+=1) *rr += *cs++;
  /* #772: @53 = sparsity_cast(@53) */
  /* #773: @53 = (-@53) */
  w53 = (- w53 );
  /* #774: @53 = @53' */
  /* #775: @81 = mac(@53,@23,@1) */
  casadi_copy(w01, 3, w81);
  casadi_mtimes((&w53), casadi_s17, wr23, casadi_s5, w81, casadi_s4, w, 0);
  /* #776: @81 = @81' */
  /* #777: @66 = mac(@53,@50,@1) */
  casadi_copy(w01, 3, w66);
  casadi_mtimes((&w53), casadi_s17, w50, casadi_s5, w66, casadi_s4, w, 0);
  /* #778: @66 = @66' */
  /* #779: @81 = (@81+@66) */
  for (i=0, rr=w81, cs=w66; i<3; ++i) (*rr++) += (*cs++);
  /* #780: @81 = (-@81) */
  for (i=0, rr=w81, cs=w81; i<3; ++i) *rr++ = (- *cs++ );
  /* #781: (@49[:3] += @81) */
  for (rr=w49+0, cs=w81; rr!=w49+3; rr+=1) *rr += *cs++;
  /* #782: {@53, @55, @70, @74, @63, @73, @48, @47, @71, @75, @76, @79, @46} = vertsplit(@49) */
  w53 = w49[0];
  w55 = w49[1];
  w70 = w49[2];
  w74 = w49[3];
  w63 = w49[4];
  w73 = w49[5];
  w48 = w49[6];
  w47 = w49[7];
  w71 = w49[8];
  w75 = w49[9];
  w76 = w49[10];
  w79 = w49[11];
  w46 = w49[12];
  /* #783: @61 = (@61/@8) */
  for (i=0, rr=w61; i<4; ++i) (*rr++) /= w08;
  /* #784: @60 = (@27*@18) */
  for (i=0, rr=w60, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)*w18);
  /* #785: @61 = (@61-@60) */
  for (i=0, rr=w61, cs=w60; i<4; ++i) (*rr++) -= (*cs++);
  /* #786: {@18, @77, @78, @51} = vertsplit(@61) */
  w18 = w61[0];
  w77 = w61[1];
  w78 = w61[2];
  w51 = w61[3];
  /* #787: @18 = (@18+@48) */
  w18 += w48;
  /* #788: @47 = (@47-@77) */
  w47 -= w77;
  /* #789: @71 = (@71-@78) */
  w71 -= w78;
  /* #790: @75 = (@75-@51) */
  w75 -= w51;
  /* #791: @19 = vertcat(@54, @52, @56, @44, @53, @55, @70, @74, @63, @73, @18, @47, @71, @75, @76, @79, @46) */
  rr=w19;
  *rr++ = w54;
  *rr++ = w52;
  *rr++ = w56;
  *rr++ = w44;
  *rr++ = w53;
  *rr++ = w55;
  *rr++ = w70;
  *rr++ = w74;
  *rr++ = w63;
  *rr++ = w73;
  *rr++ = w18;
  *rr++ = w47;
  *rr++ = w71;
  *rr++ = w75;
  *rr++ = w76;
  *rr++ = w79;
  *rr++ = w46;
  /* #792: @80 = @19[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s7, rr=w80, cs=w19; cii!=casadi_s7+11; ++cii) *rr++ = cs[*cii];
  /* #793: (@57[8, 9, 10, 11, 22, 23, 24, 33, 34, 35, 36] = @80) */
  for (cii=casadi_s18, rr=w57, cs=w80; cii!=casadi_s18+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #794: (@57[2, 6, 10, 14, 18, 21, 24, 27, 31, 35, 39] = @80) */
  for (cii=casadi_s19, rr=w57, cs=w80; cii!=casadi_s19+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #795: @82 = ones(17x1,2nz) */
  casadi_fill(w82, 2, 1.);
  /* #796: {NULL, NULL, NULL, @54, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @52, NULL, NULL, NULL} = vertsplit(@82) */
  w54 = w82[0];
  w52 = w82[1];
  /* #797: @56 = vertcat(@59, @59, @59, @54) */
  rr=(&w56);
  *rr++ = w54;
  /* #798: @56 = @56' */
  /* #799: @61 = mac(@56,@28,@25) */
  casadi_copy(w25, 4, w61);
  casadi_mtimes((&w56), casadi_s20, wr28, casadi_s1, w61, casadi_s0, w, 0);
  /* #800: @61 = @61' */
  /* #801: @25 = mac(@56,@38,@25) */
  casadi_mtimes((&w56), casadi_s20, w38, casadi_s1, w25, casadi_s0, w, 0);
  /* #802: @25 = @25' */
  /* #803: @61 = (@61+@25) */
  for (i=0, rr=w61, cs=w25; i<4; ++i) (*rr++) += (*cs++);
  /* #804: {@56, @54, @44, @53} = vertsplit(@61) */
  w56 = w61[0];
  w54 = w61[1];
  w44 = w61[2];
  w53 = w61[3];
  /* #805: @55 = (-@52) */
  w55 = (- w52 );
  /* #806: @70 = vertcat(@59, @59, @59, @55) */
  rr=(&w70);
  *rr++ = w55;
  /* #807: @70 = (@70/@8) */
  w70 /= w08;
  /* #808: @61 = dense(@70) */
  casadi_densify((&w70), casadi_s21, w61, 0);
  /* #809: @70 = project(@30) */
  casadi_sparsify(w30, (&w70), casadi_s21, 0);
  /* #810: @52 = sparsity_cast(@52) */
  /* #811: @55 = dot(@70, @52) */
  w55 = casadi_dot(1, (&w70), (&w52));
  /* #812: @55 = (@55/@8) */
  w55 /= w08;
  /* #813: @26 = (@26*@55) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) *= w55;
  /* #814: @61 = (@61-@26) */
  for (i=0, rr=w61, cs=w26; i<4; ++i) (*rr++) -= (*cs++);
  /* #815: {@70, @74, @63, @73} = vertsplit(@61) */
  w70 = w61[0];
  w74 = w61[1];
  w63 = w61[2];
  w73 = w61[3];
  /* #816: @18 = (@4*@70) */
  w18  = (w04*w70);
  /* #817: @47 = (@5*@74) */
  w47  = (w05*w74);
  /* #818: @18 = (@18-@47) */
  w18 -= w47;
  /* #819: @47 = (@6*@63) */
  w47  = (w06*w63);
  /* #820: @18 = (@18-@47) */
  w18 -= w47;
  /* #821: @47 = (@7*@73) */
  w47  = (w07*w73);
  /* #822: @18 = (@18-@47) */
  w18 -= w47;
  /* #823: @47 = (@5*@70) */
  w47  = (w05*w70);
  /* #824: @71 = (@4*@74) */
  w71  = (w04*w74);
  /* #825: @47 = (@47+@71) */
  w47 += w71;
  /* #826: @71 = (@7*@63) */
  w71  = (w07*w63);
  /* #827: @47 = (@47+@71) */
  w47 += w71;
  /* #828: @71 = (@6*@73) */
  w71  = (w06*w73);
  /* #829: @47 = (@47-@71) */
  w47 -= w71;
  /* #830: @71 = (@6*@70) */
  w71  = (w06*w70);
  /* #831: @75 = (@7*@74) */
  w75  = (w07*w74);
  /* #832: @71 = (@71-@75) */
  w71 -= w75;
  /* #833: @75 = (@4*@63) */
  w75  = (w04*w63);
  /* #834: @71 = (@71+@75) */
  w71 += w75;
  /* #835: @75 = (@5*@73) */
  w75  = (w05*w73);
  /* #836: @71 = (@71+@75) */
  w71 += w75;
  /* #837: @70 = (@7*@70) */
  w70  = (w07*w70);
  /* #838: @74 = (@6*@74) */
  w74  = (w06*w74);
  /* #839: @70 = (@70+@74) */
  w70 += w74;
  /* #840: @63 = (@5*@63) */
  w63  = (w05*w63);
  /* #841: @70 = (@70-@63) */
  w70 -= w63;
  /* #842: @73 = (@4*@73) */
  w73  = (w04*w73);
  /* #843: @70 = (@70+@73) */
  w70 += w73;
  /* #844: @26 = vertcat(@18, @47, @71, @70) */
  rr=w26;
  *rr++ = w18;
  *rr++ = w47;
  *rr++ = w71;
  *rr++ = w70;
  /* #845: @25 = (-@26) */
  for (i=0, rr=w25, cs=w26; i<4; ++i) *rr++ = (- *cs++ );
  /* #846: @25 = (@13?@25:0) */
  for (i=0, rr=w25, cs=w25; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #847: @26 = (@12?@26:0) */
  for (i=0, rr=w26, cs=w26; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #848: @25 = (@25+@26) */
  for (i=0, rr=w25, cs=w26; i<4; ++i) (*rr++) += (*cs++);
  /* #849: @81 = @25[1:4] */
  for (rr=w81, cs=w25+1; cs!=w25+4; cs+=1) *rr++ = *cs;
  /* #850: @18 = dot(@20, @81) */
  w18 = casadi_dot(3, w20, w81);
  /* #851: @18 = (@18/@14) */
  w18 /= w14;
  /* #852: @47 = (@18/@10) */
  w47  = (w18/w10);
  /* #853: @17 = (@17*@18) */
  w17 *= w18;
  /* #854: @71 = @25[0] */
  for (rr=(&w71), cs=w25+0; cs!=w25+1; cs+=1) *rr++ = *cs;
  /* #855: @15 = (@15*@71) */
  w15 *= w71;
  /* #856: @17 = (@17+@15) */
  w17 += w15;
  /* #857: @62 = (@62*@17) */
  w62 *= w17;
  /* #858: @47 = (@47-@62) */
  w47 -= w62;
  /* #859: @47 = (@0*@47) */
  w47  = (w00*w47);
  /* #860: @66 = (2.*@81) */
  for (i=0, rr=w66, cs=w81; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #861: @41 = (@9*@66) */
  for (i=0, rr=w41, cs=w66; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #862: @62 = (@16*@18) */
  w62  = (w16*w18);
  /* #863: @15 = (@11*@71) */
  w15  = (w11*w71);
  /* #864: @62 = (@62-@15) */
  w62 -= w15;
  /* #865: @24 = (@33*@62) */
  for (i=0, rr=w24, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)*w62);
  /* #866: @41 = (@41+@24) */
  for (i=0, rr=w41, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #867: @41 = (@41/@3) */
  for (i=0, rr=w41; i<3; ++i) (*rr++) /= w03;
  /* #868: @34 = (@34*@18) */
  for (i=0, rr=w34; i<3; ++i) (*rr++) *= w18;
  /* #869: @41 = (@41-@34) */
  for (i=0, rr=w41, cs=w34; i<3; ++i) (*rr++) -= (*cs++);
  /* #870: @34 = @41' */
  casadi_copy(w41, 3, w34);
  /* #871: @24 = mac(@34,@36,@1) */
  casadi_copy(w01, 3, w24);
  for (i=0, rr=w24; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=wr36+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #872: @24 = @24' */
  /* #873: @1 = mac(@34,@39,@1) */
  for (i=0, rr=w01; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #874: @1 = @1' */
  /* #875: @24 = (@24+@1) */
  for (i=0, rr=w24, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #876: @1 = (@24/@3) */
  for (i=0, rr=w01, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #877: @42 = (@42*@18) */
  for (i=0, rr=w42; i<3; ++i) (*rr++) *= w18;
  /* #878: @1 = (@1-@42) */
  for (i=0, rr=w01, cs=w42; i<3; ++i) (*rr++) -= (*cs++);
  /* #879: @15 = dot(@33, @1) */
  w15 = casadi_dot(3, w33, w01);
  /* #880: @70 = dot(@66, @40) */
  w70 = casadi_dot(3, w66, w40);
  /* #881: @15 = (@15+@70) */
  w15 += w70;
  /* #882: @11 = (@11*@15) */
  w11 *= w15;
  /* #883: @47 = (@47+@11) */
  w47 += w11;
  /* #884: @47 = (-@47) */
  w47 = (- w47 );
  /* #885: (@32[0] += @47) */
  for (rr=w32+0, cs=(&w47); rr!=w32+1; rr+=1) *rr += *cs++;
  /* #886: @47 = dot(@35, @24) */
  w47 = casadi_dot(3, w35, w24);
  /* #887: @41 = (@41/@3) */
  for (i=0, rr=w41; i<3; ++i) (*rr++) /= w03;
  /* #888: @65 = (@65*@18) */
  for (i=0, rr=w65; i<3; ++i) (*rr++) *= w18;
  /* #889: @41 = (@41-@65) */
  for (i=0, rr=w41, cs=w65; i<3; ++i) (*rr++) -= (*cs++);
  /* #890: @41 = (-@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) *rr++ = (- *cs++ );
  /* #891: @3 = dot(@41, @37) */
  w03 = casadi_dot(3, w41, w37);
  /* #892: @47 = (@47+@3) */
  w47 += w03;
  /* #893: @71 = (@71/@10) */
  w71 /= w10;
  /* #894: @68 = (@68*@17) */
  w68 *= w17;
  /* #895: @71 = (@71-@68) */
  w71 -= w68;
  /* #896: @0 = (@0*@71) */
  w00 *= w71;
  /* #897: @16 = (@16*@15) */
  w16 *= w15;
  /* #898: @0 = (@0+@16) */
  w00 += w16;
  /* #899: @47 = (@47+@0) */
  w47 += w00;
  /* #900: @47 = (@47/@14) */
  w47 /= w14;
  /* #901: @43 = (@43*@18) */
  w43 *= w18;
  /* #902: @47 = (@47-@43) */
  w47 -= w43;
  /* #903: @20 = (@20*@47) */
  for (i=0, rr=w20; i<3; ++i) (*rr++) *= w47;
  /* #904: @81 = (@2*@81) */
  for (i=0, rr=w81, cs=w81; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #905: @20 = (@20+@81) */
  for (i=0, rr=w20, cs=w81; i<3; ++i) (*rr++) += (*cs++);
  /* #906: @40 = (@40*@62) */
  for (i=0, rr=w40; i<3; ++i) (*rr++) *= w62;
  /* #907: @1 = (@9*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #908: @40 = (@40+@1) */
  for (i=0, rr=w40, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #909: @40 = (2.*@40) */
  for (i=0, rr=w40, cs=w40; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #910: @20 = (@20+@40) */
  for (i=0, rr=w20, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #911: (@32[1:4] += @20) */
  for (rr=w32+1, cs=w20; rr!=w32+4; rr+=1) *rr += *cs++;
  /* #912: @25 = (@12?@32:0) */
  for (i=0, rr=w25, cs=w32; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #913: @32 = (-@32) */
  for (i=0, rr=w32, cs=w32; i<4; ++i) *rr++ = (- *cs++ );
  /* #914: @32 = (@13?@32:0) */
  for (i=0, rr=w32, cs=w32; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #915: @25 = (@25+@32) */
  for (i=0, rr=w25, cs=w32; i<4; ++i) (*rr++) += (*cs++);
  /* #916: {@13, @12, @9, @62} = vertsplit(@25) */
  w13 = w25[0];
  w12 = w25[1];
  w09 = w25[2];
  w62 = w25[3];
  /* #917: @2 = (@7*@62) */
  w02  = (w07*w62);
  /* #918: @47 = (@6*@9) */
  w47  = (w06*w09);
  /* #919: @2 = (@2+@47) */
  w02 += w47;
  /* #920: @47 = (@5*@12) */
  w47  = (w05*w12);
  /* #921: @2 = (@2+@47) */
  w02 += w47;
  /* #922: @47 = (@4*@13) */
  w47  = (w04*w13);
  /* #923: @2 = (@2+@47) */
  w02 += w47;
  /* #924: @47 = (@6*@62) */
  w47  = (w06*w62);
  /* #925: @43 = (@7*@9) */
  w43  = (w07*w09);
  /* #926: @47 = (@47-@43) */
  w47 -= w43;
  /* #927: @43 = (@4*@12) */
  w43  = (w04*w12);
  /* #928: @47 = (@47+@43) */
  w47 += w43;
  /* #929: @43 = (@5*@13) */
  w43  = (w05*w13);
  /* #930: @47 = (@47-@43) */
  w47 -= w43;
  /* #931: @43 = (@4*@9) */
  w43  = (w04*w09);
  /* #932: @18 = (@5*@62) */
  w18  = (w05*w62);
  /* #933: @43 = (@43-@18) */
  w43 -= w18;
  /* #934: @18 = (@7*@12) */
  w18  = (w07*w12);
  /* #935: @43 = (@43+@18) */
  w43 += w18;
  /* #936: @18 = (@6*@13) */
  w18  = (w06*w13);
  /* #937: @43 = (@43-@18) */
  w43 -= w18;
  /* #938: @4 = (@4*@62) */
  w04 *= w62;
  /* #939: @5 = (@5*@9) */
  w05 *= w09;
  /* #940: @4 = (@4+@5) */
  w04 += w05;
  /* #941: @6 = (@6*@12) */
  w06 *= w12;
  /* #942: @4 = (@4-@6) */
  w04 -= w06;
  /* #943: @7 = (@7*@13) */
  w07 *= w13;
  /* #944: @4 = (@4-@7) */
  w04 -= w07;
  /* #945: @25 = vertcat(@2, @47, @43, @4) */
  rr=w25;
  *rr++ = w02;
  *rr++ = w47;
  *rr++ = w43;
  *rr++ = w04;
  /* #946: @2 = dot(@29, @25) */
  w02 = casadi_dot(4, w29, w25);
  /* #947: @61 = (@61/@8) */
  for (i=0, rr=w61; i<4; ++i) (*rr++) /= w08;
  /* #948: @64 = (@64*@55) */
  for (i=0, rr=w64; i<4; ++i) (*rr++) *= w55;
  /* #949: @61 = (@61-@64) */
  for (i=0, rr=w61, cs=w64; i<4; ++i) (*rr++) -= (*cs++);
  /* #950: @61 = (-@61) */
  for (i=0, rr=w61, cs=w61; i<4; ++i) *rr++ = (- *cs++ );
  /* #951: @47 = dot(@61, @31) */
  w47 = casadi_dot(4, w61, w31);
  /* #952: @2 = (@2+@47) */
  w02 += w47;
  /* #953: @2 = (@2/@8) */
  w02 /= w08;
  /* #954: @69 = (@69*@55) */
  w69 *= w55;
  /* #955: @2 = (@2-@69) */
  w02 -= w69;
  /* #956: @30 = (@30*@2) */
  for (i=0, rr=w30; i<4; ++i) (*rr++) *= w02;
  /* #957: @45 = (@45*@52) */
  w45 *= w52;
  /* #958: @61 = dense(@45) */
  casadi_densify((&w45), casadi_s21, w61, 0);
  /* #959: @30 = (@30+@61) */
  for (i=0, rr=w30, cs=w61; i<4; ++i) (*rr++) += (*cs++);
  /* #960: (@21[6:10] += @30) */
  for (rr=w21+6, cs=w30; rr!=w21+10; rr+=1) *rr += *cs++;
  /* #961: {@45, @52, @2, @69, @47, @43, @4, @7, @13, @6, @12, @5, @9} = vertsplit(@21) */
  w45 = w21[0];
  w52 = w21[1];
  w02 = w21[2];
  w69 = w21[3];
  w47 = w21[4];
  w43 = w21[5];
  w04 = w21[6];
  w07 = w21[7];
  w13 = w21[8];
  w06 = w21[9];
  w12 = w21[10];
  w05 = w21[11];
  w09 = w21[12];
  /* #962: @25 = (@25/@8) */
  for (i=0, rr=w25; i<4; ++i) (*rr++) /= w08;
  /* #963: @27 = (@27*@55) */
  for (i=0, rr=w27; i<4; ++i) (*rr++) *= w55;
  /* #964: @25 = (@25-@27) */
  for (i=0, rr=w25, cs=w27; i<4; ++i) (*rr++) -= (*cs++);
  /* #965: {@55, @8, @62, @18} = vertsplit(@25) */
  w55 = w25[0];
  w08 = w25[1];
  w62 = w25[2];
  w18 = w25[3];
  /* #966: @55 = (@55+@4) */
  w55 += w04;
  /* #967: @7 = (@7-@8) */
  w07 -= w08;
  /* #968: @13 = (@13-@62) */
  w13 -= w62;
  /* #969: @6 = (@6-@18) */
  w06 -= w18;
  /* #970: @19 = vertcat(@56, @54, @44, @53, @45, @52, @2, @69, @47, @43, @55, @7, @13, @6, @12, @5, @9) */
  rr=w19;
  *rr++ = w56;
  *rr++ = w54;
  *rr++ = w44;
  *rr++ = w53;
  *rr++ = w45;
  *rr++ = w52;
  *rr++ = w02;
  *rr++ = w69;
  *rr++ = w47;
  *rr++ = w43;
  *rr++ = w55;
  *rr++ = w07;
  *rr++ = w13;
  *rr++ = w06;
  *rr++ = w12;
  *rr++ = w05;
  *rr++ = w09;
  /* #971: @83 = @19[:20:10;:4] */
  for (rr=w83, cs=w19+0; cs!=w19+20; cs+=10) for (ct=cs+0; ct!=cs+4; ct+=1) *rr++ = *ct;
  /* #972: (@57[:50:25;12:16] = @83) */
  for (rr=w57+0, cs=w83; rr!=w57+50; rr+=25) for (tt=rr+12; tt!=rr+16; tt+=1) *tt = *cs++;
  /* #973: (@57[:50:25;3:19:4] = @83) */
  for (rr=w57+0, cs=w83; rr!=w57+50; rr+=25) for (tt=rr+3; tt!=rr+19; tt+=4) *tt = *cs++;
  /* #974: @84 = @57' */
  casadi_trans(w57,casadi_s22, w84, casadi_s22, iw);
  /* #975: output[2][0] = @84 */
  casadi_copy(w84, 41, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s23;
    case 1: return casadi_s24;
    case 2: return casadi_s25;
    case 3: return casadi_s26;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s27;
    case 1: return casadi_s26;
    case 2: return casadi_s22;
    case 3: return casadi_s28;
    case 4: return casadi_s29;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 22;
  if (sz_iw) *sz_iw = 18;
  if (sz_w) *sz_w = 356;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 22*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 18*sizeof(casadi_int);
  if (sz_w) *sz_w = 356*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
