/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_gate_tracker_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = 
  {1, 4, 0, 1, 2, 3, 4, 0,
  0, 0, 0};
static const casadi_int casadi_s1[23] = 
  {4, 4, 0, 4, 8, 12, 16, 0,
  1, 2, 3, 0, 1, 2, 3, 0,
  1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[9] = 
  {1, 3, 0, 1, 2, 3, 0, 0,
  0};
static const casadi_int casadi_s4[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s5[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s6[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s7[17] = 
  {0, 1, 2, 3, 16, 17, 18, 25,
  26, 27, 34, 35, 36, 37, 50, 51,
  52};
static const casadi_int casadi_s8[17] = 
  {0, 4, 8, 12, 16, 19, 22, 25,
  28, 31, 34, 38, 42, 46, 50, 53,
  56};
static const casadi_int casadi_s9[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s10[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s11[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s12[17] = 
  {4, 5, 6, 7, 19, 20, 21, 28,
  29, 30, 38, 39, 40, 41, 53, 54,
  55};
static const casadi_int casadi_s13[17] = 
  {1, 5, 9, 13, 17, 20, 23, 26,
  29, 32, 35, 39, 43, 47, 51, 54,
  57};
static const casadi_int casadi_s14[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s15[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s16[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s17[17] = 
  {8, 9, 10, 11, 22, 23, 24, 31,
  32, 33, 42, 43, 44, 45, 56, 57,
  58};
static const casadi_int casadi_s18[17] = 
  {2, 6, 10, 14, 18, 21, 24, 27,
  30, 33, 36, 40, 44, 48, 52, 55,
  58};
static const casadi_int casadi_s19[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s20[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s21[79] = 
  {17, 17, 0, 4, 8, 12, 16, 19,
  22, 25, 28, 31, 34, 38, 42, 46,
  50, 53, 56, 59, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 4, 5, 6, 4,
  5, 6, 4, 5, 6, 7, 8, 9,
  7, 8, 9, 7, 8, 9, 10, 11,
  12, 13, 10, 11, 12, 13, 10, 11,
  12, 13, 10, 11, 12, 13, 14, 15,
  16, 14, 15, 16, 14, 15, 16};
static const casadi_int casadi_s22[3] = {13, 1, 1};
static const casadi_int casadi_s23[3] = {4, 1, 1};
static const casadi_int casadi_s24[3] = {0, 1, 1};
static const casadi_int casadi_s25[3] = {17, 1, 1};
static const casadi_int casadi_s26[3] = {1, 1, 1};
static const casadi_int casadi_s27[3] = {0, 0, 1};
static const casadi_int casadi_s28[3] = {0, 17, 1};

static const casadi_real casadi_c0[9] = 
  {35., 0., 0., 0., 35., 0., 0., 0.,
  40.};
static const casadi_real casadi_c1[9] = 
  {6., 0., 0., 0., 6., 0., 0., 0.,
  6.};
static const casadi_real casadi_c2[9] = 
  {15., 0., 0., 0., 15., 0., 0., 0.,
  15.};
static const casadi_real casadi_c3[9] = 
  {5.0000000000000000e-01, 0., 0., 0., 5.0000000000000000e-01, 0., 0., 0.,
  5.0000000000000000e-01};
static const casadi_real casadi_c4[16] = 
  {2.9999999999999999e-01, 0., 0., 0., 0., 1., 0., 0.,
  0., 0., 1., 0., 0., 0., 0., 1.};

/* Drone_gate_tracker_cost_ext_cost_fun_jac_hess:(i0[13],i1[4],i2[0],i3[17])->(o0,o1[17],o2[17x17,59nz],o3[],o4[0x17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *tt, w00, *w01=w+2, w02, w03, w04, w05, w06, w07, w08, w09;
  casadi_real w10, w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+22, *w20=w+39, *w21=w+42;
  casadi_real *w22=w+55, *w24=w+67, *w25=w+70, *w27=w+82, *w28=w+85, *w29=w+89, *w30=w+93, *w31=w+97, *w32=w+101, *w33=w+104, *w34=w+107, *w36=w+119;
  casadi_real *w37=w+122, *w38=w+125, *w40=w+137, *w41=w+140, *w43=w+160, *w44=w+164, *w45=w+180, *w46=w+189, *w47=w+202, *w48=w+211, w49, w50;
  casadi_real w51, w52, w53, w54, *w55=w+221, *w56=w+230, w57, w58, w59, w60, w61, w62;
  casadi_real *w63=w+245, *w64=w+304, *w66=w+309, *w67=w+313, w68, w69, w70, *w71=w+320, *w72=w+324, w73, w74, w75;
  casadi_real w76, *w77=w+331, w78, w79, w80, w81, w82, w83, *w84=w+341, *w85=w+344, *w86=w+346, *w87=w+354;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct, *wr23, *wr26, *wr35, *wr39, *wr42;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[3][0] */
  w02 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w03 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w04 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w05 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w06 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w07 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w08 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w09 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = input[3][16] */
  w18 = arg[3] ? arg[3][16] : 0;
  /* #19: @19 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #20: @20 = @19[:3] */
  for (rr=w20, cs=w19+0; cs!=w19+3; cs+=1) *rr++ = *cs;
  /* #21: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #22: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #23: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #24: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #25: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #26: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #27: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #28: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #29: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #30: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #31: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #32: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #33: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #34: @21 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w21;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #35: @22 = @21[:3] */
  for (rr=w22, cs=w21+0; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #36: @20 = (@20-@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #37: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #38: @23 = 
  [[35, 0, 0], 
   [0, 35, 0], 
   [0, 0, 40]] */
  wr23 = casadi_c0;
  /* #39: @24 = mac(@22,@23,@1) */
  casadi_copy(w01, 3, w24);
  for (i=0, rr=w24; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=wr23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #40: @2 = mac(@24,@20,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w24+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #41: @20 = @19[3:6] */
  for (rr=w20, cs=w19+3; cs!=w19+6; cs+=1) *rr++ = *cs;
  /* #42: @25 = @21[3:6] */
  for (rr=w25, cs=w21+3; cs!=w21+6; cs+=1) *rr++ = *cs;
  /* #43: @20 = (@20-@25) */
  for (i=0, rr=w20, cs=w25; i<3; ++i) (*rr++) -= (*cs++);
  /* #44: @25 = @20' */
  casadi_copy(w20, 3, w25);
  /* #45: @26 = 
  [[6, 0, 0], 
   [0, 6, 0], 
   [0, 0, 6]] */
  wr26 = casadi_c1;
  /* #46: @27 = mac(@25,@26,@1) */
  casadi_copy(w01, 3, w27);
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=wr26+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #47: @3 = mac(@27,@20,@0) */
  casadi_copy((&w00), 1, (&w03));
  for (i=0, rr=(&w03); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w27+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #48: @2 = (@2+@3) */
  w02 += w03;
  /* #49: @9 = (-@9) */
  w09 = (- w09 );
  /* #50: @10 = (-@10) */
  w10 = (- w10 );
  /* #51: @11 = (-@11) */
  w11 = (- w11 );
  /* #52: @28 = vertcat(@8, @9, @10, @11) */
  rr=w28;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  /* #53: @29 = @21[6:10] */
  for (rr=w29, cs=w21+6; cs!=w21+10; cs+=1) *rr++ = *cs;
  /* #54: @8 = ||@29||_F */
  w08 = casadi_norm_2(4, w29);
  /* #55: @28 = (@28/@8) */
  for (i=0, rr=w28; i<4; ++i) (*rr++) /= w08;
  /* #56: {@9, @10, @11, @3} = vertsplit(@28) */
  w09 = w28[0];
  w10 = w28[1];
  w11 = w28[2];
  w03 = w28[3];
  /* #57: @30 = @19[6:10] */
  for (rr=w30, cs=w19+6; cs!=w19+10; cs+=1) *rr++ = *cs;
  /* #58: {@4, @5, @6, @7} = vertsplit(@30) */
  w04 = w30[0];
  w05 = w30[1];
  w06 = w30[2];
  w07 = w30[3];
  /* #59: @12 = (@9*@4) */
  w12  = (w09*w04);
  /* #60: @13 = (@10*@5) */
  w13  = (w10*w05);
  /* #61: @12 = (@12-@13) */
  w12 -= w13;
  /* #62: @13 = (@11*@6) */
  w13  = (w11*w06);
  /* #63: @12 = (@12-@13) */
  w12 -= w13;
  /* #64: @13 = (@3*@7) */
  w13  = (w03*w07);
  /* #65: @12 = (@12-@13) */
  w12 -= w13;
  /* #66: @13 = (@12<@0) */
  w13  = (w12<w00);
  /* #67: @14 = (@9*@5) */
  w14  = (w09*w05);
  /* #68: @15 = (@10*@4) */
  w15  = (w10*w04);
  /* #69: @14 = (@14+@15) */
  w14 += w15;
  /* #70: @15 = (@11*@7) */
  w15  = (w11*w07);
  /* #71: @14 = (@14+@15) */
  w14 += w15;
  /* #72: @15 = (@3*@6) */
  w15  = (w03*w06);
  /* #73: @14 = (@14-@15) */
  w14 -= w15;
  /* #74: @15 = (@9*@6) */
  w15  = (w09*w06);
  /* #75: @16 = (@10*@7) */
  w16  = (w10*w07);
  /* #76: @15 = (@15-@16) */
  w15 -= w16;
  /* #77: @16 = (@11*@4) */
  w16  = (w11*w04);
  /* #78: @15 = (@15+@16) */
  w15 += w16;
  /* #79: @16 = (@3*@5) */
  w16  = (w03*w05);
  /* #80: @15 = (@15+@16) */
  w15 += w16;
  /* #81: @9 = (@9*@7) */
  w09 *= w07;
  /* #82: @10 = (@10*@6) */
  w10 *= w06;
  /* #83: @9 = (@9+@10) */
  w09 += w10;
  /* #84: @11 = (@11*@5) */
  w11 *= w05;
  /* #85: @9 = (@9-@11) */
  w09 -= w11;
  /* #86: @3 = (@3*@4) */
  w03 *= w04;
  /* #87: @9 = (@9+@3) */
  w09 += w03;
  /* #88: @30 = vertcat(@12, @14, @15, @9) */
  rr=w30;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w09;
  /* #89: @31 = (-@30) */
  for (i=0, rr=w31, cs=w30; i<4; ++i) *rr++ = (- *cs++ );
  /* #90: @31 = (@13?@31:0) */
  for (i=0, rr=w31, cs=w31; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #91: @12 = (!@13) */
  w12 = (! w13 );
  /* #92: @30 = (@12?@30:0) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #93: @31 = (@31+@30) */
  for (i=0, rr=w31, cs=w30; i<4; ++i) (*rr++) += (*cs++);
  /* #94: @20 = @31[1:4] */
  for (rr=w20, cs=w31+1; cs!=w31+4; cs+=1) *rr++ = *cs;
  /* #95: @32 = (2.*@20) */
  for (i=0, rr=w32, cs=w20; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #96: @14 = ||@20||_F */
  w14 = casadi_norm_2(3, w20);
  /* #97: @15 = @31[0] */
  for (rr=(&w15), cs=w31+0; cs!=w31+1; cs+=1) *rr++ = *cs;
  /* #98: @9 = atan2(@14,@15) */
  w09  = atan2(w14,w15);
  /* #99: @33 = (@32*@9) */
  for (i=0, rr=w33, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w09);
  /* #100: @3 = 1e-09 */
  w03 = 1.0000000000000001e-09;
  /* #101: @3 = (@3+@14) */
  w03 += w14;
  /* #102: @33 = (@33/@3) */
  for (i=0, rr=w33; i<3; ++i) (*rr++) /= w03;
  /* #103: @34 = @33' */
  casadi_copy(w33, 3, w34);
  /* #104: @35 = 
  [[15, 0, 0], 
   [0, 15, 0], 
   [0, 0, 15]] */
  wr35 = casadi_c2;
  /* #105: @36 = mac(@34,@35,@1) */
  casadi_copy(w01, 3, w36);
  for (i=0, rr=w36; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=wr35+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #106: @11 = mac(@36,@33,@0) */
  casadi_copy((&w00), 1, (&w11));
  for (i=0, rr=(&w11); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w36+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #107: @2 = (@2+@11) */
  w02 += w11;
  /* #108: @37 = @19[10:13] */
  for (rr=w37, cs=w19+10; cs!=w19+13; cs+=1) *rr++ = *cs;
  /* #109: @38 = @21[10:13] */
  for (rr=w38, cs=w21+10; cs!=w21+13; cs+=1) *rr++ = *cs;
  /* #110: @37 = (@37-@38) */
  for (i=0, rr=w37, cs=w38; i<3; ++i) (*rr++) -= (*cs++);
  /* #111: @38 = @37' */
  casadi_copy(w37, 3, w38);
  /* #112: @39 = 
  [[0.5, 0, 0], 
   [0, 0.5, 0], 
   [0, 0, 0.5]] */
  wr39 = casadi_c3;
  /* #113: @40 = mac(@38,@39,@1) */
  casadi_copy(w01, 3, w40);
  for (i=0, rr=w40; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=wr39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #114: @11 = mac(@40,@37,@0) */
  casadi_copy((&w00), 1, (&w11));
  for (i=0, rr=(&w11); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w40+j, ct=w37+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #115: @2 = (@2+@11) */
  w02 += w11;
  /* #116: @31 = zeros(1x4) */
  casadi_clear(w31, 4);
  /* #117: @11 = input[1][0] */
  w11 = arg[1] ? arg[1][0] : 0;
  /* #118: @10 = input[1][1] */
  w10 = arg[1] ? arg[1][1] : 0;
  /* #119: @16 = input[1][2] */
  w16 = arg[1] ? arg[1][2] : 0;
  /* #120: @17 = input[1][3] */
  w17 = arg[1] ? arg[1][3] : 0;
  /* #121: @30 = vertcat(@11, @10, @16, @17) */
  rr=w30;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w16;
  *rr++ = w17;
  /* #122: @41 = @19[13:17] */
  for (rr=w41, cs=w19+13; cs!=w19+17; cs+=1) *rr++ = *cs;
  /* #123: @30 = (@30-@41) */
  for (i=0, rr=w30, cs=w41; i<4; ++i) (*rr++) -= (*cs++);
  /* #124: @41 = @30' */
  casadi_copy(w30, 4, w41);
  /* #125: @42 = 
  [[0.3, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  wr42 = casadi_c4;
  /* #126: @43 = mac(@41,@42,@31) */
  casadi_copy(w31, 4, w43);
  for (i=0, rr=w43; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w41+j, ct=wr42+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #127: @0 = mac(@43,@30,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w43+j, ct=w30+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #128: @2 = (@2+@0) */
  w02 += w00;
  /* #129: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #130: @43 = @43' */
  /* #131: @44 = @42' */
  for (i=0, rr=w44, cs=wr42; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #132: @30 = mac(@41,@44,@31) */
  casadi_copy(w31, 4, w30);
  for (i=0, rr=w30; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w41+j, ct=w44+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #133: @30 = @30' */
  /* #134: @43 = (@43+@30) */
  for (i=0, rr=w43, cs=w30; i<4; ++i) (*rr++) += (*cs++);
  /* #135: {@2, @0, @11, @10} = vertsplit(@43) */
  w02 = w43[0];
  w00 = w43[1];
  w11 = w43[2];
  w10 = w43[3];
  /* #136: output[1][0] = @2 */
  if (res[1]) res[1][0] = w02;
  /* #137: output[1][1] = @0 */
  if (res[1]) res[1][1] = w00;
  /* #138: output[1][2] = @11 */
  if (res[1]) res[1][2] = w11;
  /* #139: output[1][3] = @10 */
  if (res[1]) res[1][3] = w10;
  /* #140: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #141: @40 = @40' */
  /* #142: @45 = @39' */
  for (i=0, rr=w45, cs=wr39; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #143: @37 = mac(@38,@45,@1) */
  casadi_copy(w01, 3, w37);
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w45+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #144: @37 = @37' */
  /* #145: @40 = (@40+@37) */
  for (i=0, rr=w40, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #146: @40 = (-@40) */
  for (i=0, rr=w40, cs=w40; i<3; ++i) *rr++ = (- *cs++ );
  /* #147: @46 = @21; (@46[10:13] += @40) */
  casadi_copy(w21, 13, w46);
  for (rr=w46+10, cs=w40; rr!=w46+13; rr+=1) *rr += *cs++;
  /* #148: @28 = (@28/@8) */
  for (i=0, rr=w28; i<4; ++i) (*rr++) /= w08;
  /* #149: @43 = (-@28) */
  for (i=0, rr=w43, cs=w28; i<4; ++i) *rr++ = (- *cs++ );
  /* #150: @30 = zeros(4x1) */
  casadi_clear(w30, 4);
  /* #151: @10 = sq(@14) */
  w10 = casadi_sq( w14 );
  /* #152: @11 = sq(@15) */
  w11 = casadi_sq( w15 );
  /* #153: @10 = (@10+@11) */
  w10 += w11;
  /* #154: @11 = (@14/@10) */
  w11  = (w14/w10);
  /* #155: @36 = @36' */
  /* #156: @47 = @35' */
  for (i=0, rr=w47, cs=wr35; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #157: @40 = mac(@34,@47,@1) */
  casadi_copy(w01, 3, w40);
  for (i=0, rr=w40; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=w47+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #158: @40 = @40' */
  /* #159: @36 = (@36+@40) */
  for (i=0, rr=w36, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #160: @40 = (@36/@3) */
  for (i=0, rr=w40, cr=w36; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #161: @0 = dot(@32, @40) */
  w00 = casadi_dot(3, w32, w40);
  /* #162: @2 = (@11*@0) */
  w02  = (w11*w00);
  /* #163: @2 = (-@2) */
  w02 = (- w02 );
  /* #164: @41 = @30; (@41[0] += @2) */
  casadi_copy(w30, 4, w41);
  for (rr=w41+0, cs=(&w02); rr!=w41+1; rr+=1) *rr += *cs++;
  /* #165: @33 = (@33/@3) */
  for (i=0, rr=w33; i<3; ++i) (*rr++) /= w03;
  /* #166: @34 = (-@33) */
  for (i=0, rr=w34, cs=w33; i<3; ++i) *rr++ = (- *cs++ );
  /* #167: @2 = dot(@34, @36) */
  w02 = casadi_dot(3, w34, w36);
  /* #168: @16 = (@15/@10) */
  w16  = (w15/w10);
  /* #169: @17 = (@16*@0) */
  w17  = (w16*w00);
  /* #170: @2 = (@2+@17) */
  w02 += w17;
  /* #171: @2 = (@2/@14) */
  w02 /= w14;
  /* #172: @37 = (@2*@20) */
  for (i=0, rr=w37, cs=w20; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #173: @38 = (@9*@40) */
  for (i=0, rr=w38, cs=w40; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #174: @38 = (2.*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #175: @37 = (@37+@38) */
  for (i=0, rr=w37, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #176: (@41[1:4] += @37) */
  for (rr=w41+1, cs=w37; rr!=w41+4; rr+=1) *rr += *cs++;
  /* #177: @48 = (@12?@41:0) */
  for (i=0, rr=w48, cs=w41; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #178: @41 = (-@41) */
  for (i=0, rr=w41, cs=w41; i<4; ++i) *rr++ = (- *cs++ );
  /* #179: @41 = (@13?@41:0) */
  for (i=0, rr=w41, cs=w41; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #180: @48 = (@48+@41) */
  for (i=0, rr=w48, cs=w41; i<4; ++i) (*rr++) += (*cs++);
  /* #181: {@17, @18, @49, @50} = vertsplit(@48) */
  w17 = w48[0];
  w18 = w48[1];
  w49 = w48[2];
  w50 = w48[3];
  /* #182: @51 = (@7*@50) */
  w51  = (w07*w50);
  /* #183: @52 = (@6*@49) */
  w52  = (w06*w49);
  /* #184: @51 = (@51+@52) */
  w51 += w52;
  /* #185: @52 = (@5*@18) */
  w52  = (w05*w18);
  /* #186: @51 = (@51+@52) */
  w51 += w52;
  /* #187: @52 = (@4*@17) */
  w52  = (w04*w17);
  /* #188: @51 = (@51+@52) */
  w51 += w52;
  /* #189: @52 = (@6*@50) */
  w52  = (w06*w50);
  /* #190: @53 = (@7*@49) */
  w53  = (w07*w49);
  /* #191: @52 = (@52-@53) */
  w52 -= w53;
  /* #192: @53 = (@4*@18) */
  w53  = (w04*w18);
  /* #193: @52 = (@52+@53) */
  w52 += w53;
  /* #194: @53 = (@5*@17) */
  w53  = (w05*w17);
  /* #195: @52 = (@52-@53) */
  w52 -= w53;
  /* #196: @53 = (@4*@49) */
  w53  = (w04*w49);
  /* #197: @54 = (@5*@50) */
  w54  = (w05*w50);
  /* #198: @53 = (@53-@54) */
  w53 -= w54;
  /* #199: @54 = (@7*@18) */
  w54  = (w07*w18);
  /* #200: @53 = (@53+@54) */
  w53 += w54;
  /* #201: @54 = (@6*@17) */
  w54  = (w06*w17);
  /* #202: @53 = (@53-@54) */
  w53 -= w54;
  /* #203: @50 = (@4*@50) */
  w50  = (w04*w50);
  /* #204: @49 = (@5*@49) */
  w49  = (w05*w49);
  /* #205: @50 = (@50+@49) */
  w50 += w49;
  /* #206: @18 = (@6*@18) */
  w18  = (w06*w18);
  /* #207: @50 = (@50-@18) */
  w50 -= w18;
  /* #208: @17 = (@7*@17) */
  w17  = (w07*w17);
  /* #209: @50 = (@50-@17) */
  w50 -= w17;
  /* #210: @48 = vertcat(@51, @52, @53, @50) */
  rr=w48;
  *rr++ = w51;
  *rr++ = w52;
  *rr++ = w53;
  *rr++ = w50;
  /* #211: @51 = dot(@43, @48) */
  w51 = casadi_dot(4, w43, w48);
  /* #212: @51 = (@51/@8) */
  w51 /= w08;
  /* #213: @41 = (@51*@29) */
  for (i=0, rr=w41, cs=w29; i<4; ++i) (*rr++)  = (w51*(*cs++));
  /* #214: (@46[6:10] += @41) */
  for (rr=w46+6, cs=w41; rr!=w46+10; rr+=1) *rr += *cs++;
  /* #215: @27 = @27' */
  /* #216: @55 = @26' */
  for (i=0, rr=w55, cs=wr26; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #217: @37 = mac(@25,@55,@1) */
  casadi_copy(w01, 3, w37);
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=w55+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #218: @37 = @37' */
  /* #219: @27 = (@27+@37) */
  for (i=0, rr=w27, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #220: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) *rr++ = (- *cs++ );
  /* #221: (@46[3:6] += @27) */
  for (rr=w46+3, cs=w27; rr!=w46+6; rr+=1) *rr += *cs++;
  /* #222: @24 = @24' */
  /* #223: @56 = @23' */
  for (i=0, rr=w56, cs=wr23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #224: @27 = mac(@22,@56,@1) */
  casadi_copy(w01, 3, w27);
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w56+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #225: @27 = @27' */
  /* #226: @24 = (@24+@27) */
  for (i=0, rr=w24, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #227: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) *rr++ = (- *cs++ );
  /* #228: (@46[:3] += @24) */
  for (rr=w46+0, cs=w24; rr!=w46+3; rr+=1) *rr += *cs++;
  /* #229: {@52, @53, @50, @17, @18, @49, @54, @57, @58, @59, @60, @61, @62} = vertsplit(@46) */
  w52 = w46[0];
  w53 = w46[1];
  w50 = w46[2];
  w17 = w46[3];
  w18 = w46[4];
  w49 = w46[5];
  w54 = w46[6];
  w57 = w46[7];
  w58 = w46[8];
  w59 = w46[9];
  w60 = w46[10];
  w61 = w46[11];
  w62 = w46[12];
  /* #230: output[1][4] = @52 */
  if (res[1]) res[1][4] = w52;
  /* #231: output[1][5] = @53 */
  if (res[1]) res[1][5] = w53;
  /* #232: output[1][6] = @50 */
  if (res[1]) res[1][6] = w50;
  /* #233: output[1][7] = @17 */
  if (res[1]) res[1][7] = w17;
  /* #234: output[1][8] = @18 */
  if (res[1]) res[1][8] = w18;
  /* #235: output[1][9] = @49 */
  if (res[1]) res[1][9] = w49;
  /* #236: @41 = (@48/@8) */
  for (i=0, rr=w41, cr=w48; i<4; ++i) (*rr++)  = ((*cr++)/w08);
  /* #237: {@49, @18, @17, @50} = vertsplit(@41) */
  w49 = w41[0];
  w18 = w41[1];
  w17 = w41[2];
  w50 = w41[3];
  /* #238: @49 = (@49+@54) */
  w49 += w54;
  /* #239: output[1][10] = @49 */
  if (res[1]) res[1][10] = w49;
  /* #240: @57 = (@57-@18) */
  w57 -= w18;
  /* #241: output[1][11] = @57 */
  if (res[1]) res[1][11] = w57;
  /* #242: @58 = (@58-@17) */
  w58 -= w17;
  /* #243: output[1][12] = @58 */
  if (res[1]) res[1][12] = w58;
  /* #244: @59 = (@59-@50) */
  w59 -= w50;
  /* #245: output[1][13] = @59 */
  if (res[1]) res[1][13] = w59;
  /* #246: output[1][14] = @60 */
  if (res[1]) res[1][14] = w60;
  /* #247: output[1][15] = @61 */
  if (res[1]) res[1][15] = w61;
  /* #248: output[1][16] = @62 */
  if (res[1]) res[1][16] = w62;
  /* #249: @63 = zeros(17x17,59nz) */
  casadi_clear(w63, 59);
  /* #250: @64 = ones(17x1,5nz) */
  casadi_fill(w64, 5, 1.);
  /* #251: {@62, NULL, NULL, NULL, @61, NULL, NULL, @60, NULL, NULL, @59, NULL, NULL, NULL, @50, NULL, NULL} = vertsplit(@64) */
  w62 = w64[0];
  w61 = w64[1];
  w60 = w64[2];
  w59 = w64[3];
  w50 = w64[4];
  /* #252: @65 = 00 */
  /* #253: @58 = vertcat(@62, @65, @65, @65) */
  rr=(&w58);
  *rr++ = w62;
  /* #254: @58 = @58' */
  /* #255: @66 = mac(@58,@42,@31) */
  casadi_copy(w31, 4, w66);
  casadi_mtimes((&w58), casadi_s2, wr42, casadi_s1, w66, casadi_s0, w, 0);
  /* #256: @66 = @66' */
  /* #257: @67 = mac(@58,@44,@31) */
  casadi_copy(w31, 4, w67);
  casadi_mtimes((&w58), casadi_s2, w44, casadi_s1, w67, casadi_s0, w, 0);
  /* #258: @67 = @67' */
  /* #259: @66 = (@66+@67) */
  for (i=0, rr=w66, cs=w67; i<4; ++i) (*rr++) += (*cs++);
  /* #260: {@58, @62, @17, @57} = vertsplit(@66) */
  w58 = w66[0];
  w62 = w66[1];
  w17 = w66[2];
  w57 = w66[3];
  /* #261: @50 = sparsity_cast(@50) */
  /* #262: @50 = (-@50) */
  w50 = (- w50 );
  /* #263: @50 = @50' */
  /* #264: @24 = mac(@50,@39,@1) */
  casadi_copy(w01, 3, w24);
  casadi_mtimes((&w50), casadi_s5, wr39, casadi_s4, w24, casadi_s3, w, 0);
  /* #265: @24 = @24' */
  /* #266: @27 = mac(@50,@45,@1) */
  casadi_copy(w01, 3, w27);
  casadi_mtimes((&w50), casadi_s5, w45, casadi_s4, w27, casadi_s3, w, 0);
  /* #267: @27 = @27' */
  /* #268: @24 = (@24+@27) */
  for (i=0, rr=w24, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #269: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) *rr++ = (- *cs++ );
  /* #270: @46 = @21; (@46[10:13] += @24) */
  casadi_copy(w21, 13, w46);
  for (rr=w46+10, cs=w24; rr!=w46+13; rr+=1) *rr += *cs++;
  /* #271: @50 = vertcat(@59, @65, @65, @65) */
  rr=(&w50);
  *rr++ = w59;
  /* #272: @50 = (@50/@8) */
  w50 /= w08;
  /* #273: @66 = dense(@50) */
  casadi_densify((&w50), casadi_s6, w66, 0);
  /* #274: @50 = project(@29) */
  casadi_sparsify(w29, (&w50), casadi_s6, 0);
  /* #275: @59 = sparsity_cast(@59) */
  /* #276: @18 = dot(@50, @59) */
  w18 = casadi_dot(1, (&w50), (&w59));
  /* #277: @18 = (@18/@8) */
  w18 /= w08;
  /* #278: @67 = (@28*@18) */
  for (i=0, rr=w67, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)*w18);
  /* #279: @66 = (@66-@67) */
  for (i=0, rr=w66, cs=w67; i<4; ++i) (*rr++) -= (*cs++);
  /* #280: {@50, @49, @54, @53} = vertsplit(@66) */
  w50 = w66[0];
  w49 = w66[1];
  w54 = w66[2];
  w53 = w66[3];
  /* #281: @52 = (@4*@50) */
  w52  = (w04*w50);
  /* #282: @68 = (@5*@49) */
  w68  = (w05*w49);
  /* #283: @52 = (@52-@68) */
  w52 -= w68;
  /* #284: @68 = (@6*@54) */
  w68  = (w06*w54);
  /* #285: @52 = (@52-@68) */
  w52 -= w68;
  /* #286: @68 = (@7*@53) */
  w68  = (w07*w53);
  /* #287: @52 = (@52-@68) */
  w52 -= w68;
  /* #288: @68 = (@5*@50) */
  w68  = (w05*w50);
  /* #289: @69 = (@4*@49) */
  w69  = (w04*w49);
  /* #290: @68 = (@68+@69) */
  w68 += w69;
  /* #291: @69 = (@7*@54) */
  w69  = (w07*w54);
  /* #292: @68 = (@68+@69) */
  w68 += w69;
  /* #293: @69 = (@6*@53) */
  w69  = (w06*w53);
  /* #294: @68 = (@68-@69) */
  w68 -= w69;
  /* #295: @69 = (@6*@50) */
  w69  = (w06*w50);
  /* #296: @70 = (@7*@49) */
  w70  = (w07*w49);
  /* #297: @69 = (@69-@70) */
  w69 -= w70;
  /* #298: @70 = (@4*@54) */
  w70  = (w04*w54);
  /* #299: @69 = (@69+@70) */
  w69 += w70;
  /* #300: @70 = (@5*@53) */
  w70  = (w05*w53);
  /* #301: @69 = (@69+@70) */
  w69 += w70;
  /* #302: @50 = (@7*@50) */
  w50  = (w07*w50);
  /* #303: @49 = (@6*@49) */
  w49  = (w06*w49);
  /* #304: @50 = (@50+@49) */
  w50 += w49;
  /* #305: @54 = (@5*@54) */
  w54  = (w05*w54);
  /* #306: @50 = (@50-@54) */
  w50 -= w54;
  /* #307: @53 = (@4*@53) */
  w53  = (w04*w53);
  /* #308: @50 = (@50+@53) */
  w50 += w53;
  /* #309: @67 = vertcat(@52, @68, @69, @50) */
  rr=w67;
  *rr++ = w52;
  *rr++ = w68;
  *rr++ = w69;
  *rr++ = w50;
  /* #310: @71 = (-@67) */
  for (i=0, rr=w71, cs=w67; i<4; ++i) *rr++ = (- *cs++ );
  /* #311: @71 = (@13?@71:0) */
  for (i=0, rr=w71, cs=w71; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #312: @67 = (@12?@67:0) */
  for (i=0, rr=w67, cs=w67; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #313: @71 = (@71+@67) */
  for (i=0, rr=w71, cs=w67; i<4; ++i) (*rr++) += (*cs++);
  /* #314: @24 = @71[1:4] */
  for (rr=w24, cs=w71+1; cs!=w71+4; cs+=1) *rr++ = *cs;
  /* #315: @52 = dot(@20, @24) */
  w52 = casadi_dot(3, w20, w24);
  /* #316: @52 = (@52/@14) */
  w52 /= w14;
  /* #317: @68 = (@52/@10) */
  w68  = (w52/w10);
  /* #318: @69 = (@11/@10) */
  w69  = (w11/w10);
  /* #319: @50 = (2.*@14) */
  w50 = (2.* w14 );
  /* #320: @53 = (@50*@52) */
  w53  = (w50*w52);
  /* #321: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #322: @54 = @71[0] */
  for (rr=(&w54), cs=w71+0; cs!=w71+1; cs+=1) *rr++ = *cs;
  /* #323: @49 = (@15*@54) */
  w49  = (w15*w54);
  /* #324: @53 = (@53+@49) */
  w53 += w49;
  /* #325: @49 = (@69*@53) */
  w49  = (w69*w53);
  /* #326: @68 = (@68-@49) */
  w68 -= w49;
  /* #327: @68 = (@0*@68) */
  w68  = (w00*w68);
  /* #328: @27 = (2.*@24) */
  for (i=0, rr=w27, cs=w24; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #329: @22 = (@9*@27) */
  for (i=0, rr=w22, cs=w27; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #330: @49 = (@16*@52) */
  w49  = (w16*w52);
  /* #331: @70 = (@11*@54) */
  w70  = (w11*w54);
  /* #332: @49 = (@49-@70) */
  w49 -= w70;
  /* #333: @37 = (@32*@49) */
  for (i=0, rr=w37, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w49);
  /* #334: @22 = (@22+@37) */
  for (i=0, rr=w22, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #335: @22 = (@22/@3) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) /= w03;
  /* #336: @37 = (@33*@52) */
  for (i=0, rr=w37, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #337: @22 = (@22-@37) */
  for (i=0, rr=w22, cs=w37; i<3; ++i) (*rr++) -= (*cs++);
  /* #338: @37 = @22' */
  casadi_copy(w22, 3, w37);
  /* #339: @25 = mac(@37,@35,@1) */
  casadi_copy(w01, 3, w25);
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w37+j, ct=wr35+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #340: @25 = @25' */
  /* #341: @38 = mac(@37,@47,@1) */
  casadi_copy(w01, 3, w38);
  for (i=0, rr=w38; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w37+j, ct=w47+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #342: @38 = @38' */
  /* #343: @25 = (@25+@38) */
  for (i=0, rr=w25, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #344: @38 = (@25/@3) */
  for (i=0, rr=w38, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #345: @37 = (@40/@3) */
  for (i=0, rr=w37, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #346: @72 = (@37*@52) */
  for (i=0, rr=w72, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #347: @38 = (@38-@72) */
  for (i=0, rr=w38, cs=w72; i<3; ++i) (*rr++) -= (*cs++);
  /* #348: @70 = dot(@32, @38) */
  w70 = casadi_dot(3, w32, w38);
  /* #349: @73 = dot(@27, @40) */
  w73 = casadi_dot(3, w27, w40);
  /* #350: @70 = (@70+@73) */
  w70 += w73;
  /* #351: @73 = (@11*@70) */
  w73  = (w11*w70);
  /* #352: @68 = (@68+@73) */
  w68 += w73;
  /* #353: @68 = (-@68) */
  w68 = (- w68 );
  /* #354: @71 = @30; (@71[0] += @68) */
  casadi_copy(w30, 4, w71);
  for (rr=w71+0, cs=(&w68); rr!=w71+1; rr+=1) *rr += *cs++;
  /* #355: @68 = dot(@34, @25) */
  w68 = casadi_dot(3, w34, w25);
  /* #356: @22 = (@22/@3) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) /= w03;
  /* #357: @25 = (@33/@3) */
  for (i=0, rr=w25, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #358: @27 = (@25*@52) */
  for (i=0, rr=w27, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #359: @22 = (@22-@27) */
  for (i=0, rr=w22, cs=w27; i<3; ++i) (*rr++) -= (*cs++);
  /* #360: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #361: @73 = dot(@22, @36) */
  w73 = casadi_dot(3, w22, w36);
  /* #362: @68 = (@68+@73) */
  w68 += w73;
  /* #363: @54 = (@54/@10) */
  w54 /= w10;
  /* #364: @73 = (@16/@10) */
  w73  = (w16/w10);
  /* #365: @53 = (@73*@53) */
  w53  = (w73*w53);
  /* #366: @54 = (@54-@53) */
  w54 -= w53;
  /* #367: @54 = (@0*@54) */
  w54  = (w00*w54);
  /* #368: @70 = (@16*@70) */
  w70  = (w16*w70);
  /* #369: @54 = (@54+@70) */
  w54 += w70;
  /* #370: @68 = (@68+@54) */
  w68 += w54;
  /* #371: @68 = (@68/@14) */
  w68 /= w14;
  /* #372: @54 = (@2/@14) */
  w54  = (w02/w14);
  /* #373: @52 = (@54*@52) */
  w52  = (w54*w52);
  /* #374: @68 = (@68-@52) */
  w68 -= w52;
  /* #375: @22 = (@20*@68) */
  for (i=0, rr=w22, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w68);
  /* #376: @24 = (@2*@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #377: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #378: @24 = (@40*@49) */
  for (i=0, rr=w24, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w49);
  /* #379: @38 = (@9*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #380: @24 = (@24+@38) */
  for (i=0, rr=w24, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #381: @24 = (2.*@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #382: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #383: (@71[1:4] += @22) */
  for (rr=w71+1, cs=w22; rr!=w71+4; rr+=1) *rr += *cs++;
  /* #384: @67 = (@12?@71:0) */
  for (i=0, rr=w67, cs=w71; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #385: @71 = (-@71) */
  for (i=0, rr=w71, cs=w71; i<4; ++i) *rr++ = (- *cs++ );
  /* #386: @71 = (@13?@71:0) */
  for (i=0, rr=w71, cs=w71; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #387: @67 = (@67+@71) */
  for (i=0, rr=w67, cs=w71; i<4; ++i) (*rr++) += (*cs++);
  /* #388: {@49, @68, @52, @70} = vertsplit(@67) */
  w49 = w67[0];
  w68 = w67[1];
  w52 = w67[2];
  w70 = w67[3];
  /* #389: @53 = (@7*@70) */
  w53  = (w07*w70);
  /* #390: @74 = (@6*@52) */
  w74  = (w06*w52);
  /* #391: @53 = (@53+@74) */
  w53 += w74;
  /* #392: @74 = (@5*@68) */
  w74  = (w05*w68);
  /* #393: @53 = (@53+@74) */
  w53 += w74;
  /* #394: @74 = (@4*@49) */
  w74  = (w04*w49);
  /* #395: @53 = (@53+@74) */
  w53 += w74;
  /* #396: @74 = (@6*@70) */
  w74  = (w06*w70);
  /* #397: @75 = (@7*@52) */
  w75  = (w07*w52);
  /* #398: @74 = (@74-@75) */
  w74 -= w75;
  /* #399: @75 = (@4*@68) */
  w75  = (w04*w68);
  /* #400: @74 = (@74+@75) */
  w74 += w75;
  /* #401: @75 = (@5*@49) */
  w75  = (w05*w49);
  /* #402: @74 = (@74-@75) */
  w74 -= w75;
  /* #403: @75 = (@4*@52) */
  w75  = (w04*w52);
  /* #404: @76 = (@5*@70) */
  w76  = (w05*w70);
  /* #405: @75 = (@75-@76) */
  w75 -= w76;
  /* #406: @76 = (@7*@68) */
  w76  = (w07*w68);
  /* #407: @75 = (@75+@76) */
  w75 += w76;
  /* #408: @76 = (@6*@49) */
  w76  = (w06*w49);
  /* #409: @75 = (@75-@76) */
  w75 -= w76;
  /* #410: @70 = (@4*@70) */
  w70  = (w04*w70);
  /* #411: @52 = (@5*@52) */
  w52  = (w05*w52);
  /* #412: @70 = (@70+@52) */
  w70 += w52;
  /* #413: @68 = (@6*@68) */
  w68  = (w06*w68);
  /* #414: @70 = (@70-@68) */
  w70 -= w68;
  /* #415: @49 = (@7*@49) */
  w49  = (w07*w49);
  /* #416: @70 = (@70-@49) */
  w70 -= w49;
  /* #417: @67 = vertcat(@53, @74, @75, @70) */
  rr=w67;
  *rr++ = w53;
  *rr++ = w74;
  *rr++ = w75;
  *rr++ = w70;
  /* #418: @53 = dot(@43, @67) */
  w53 = casadi_dot(4, w43, w67);
  /* #419: @66 = (@66/@8) */
  for (i=0, rr=w66; i<4; ++i) (*rr++) /= w08;
  /* #420: @71 = (@28/@8) */
  for (i=0, rr=w71, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)/w08);
  /* #421: @77 = (@71*@18) */
  for (i=0, rr=w77, cr=w71; i<4; ++i) (*rr++)  = ((*cr++)*w18);
  /* #422: @66 = (@66-@77) */
  for (i=0, rr=w66, cs=w77; i<4; ++i) (*rr++) -= (*cs++);
  /* #423: @66 = (-@66) */
  for (i=0, rr=w66, cs=w66; i<4; ++i) *rr++ = (- *cs++ );
  /* #424: @74 = dot(@66, @48) */
  w74 = casadi_dot(4, w66, w48);
  /* #425: @53 = (@53+@74) */
  w53 += w74;
  /* #426: @53 = (@53/@8) */
  w53 /= w08;
  /* #427: @74 = (@51/@8) */
  w74  = (w51/w08);
  /* #428: @75 = (@74*@18) */
  w75  = (w74*w18);
  /* #429: @53 = (@53-@75) */
  w53 -= w75;
  /* #430: @66 = (@29*@53) */
  for (i=0, rr=w66, cr=w29; i<4; ++i) (*rr++)  = ((*cr++)*w53);
  /* #431: @59 = (@51*@59) */
  w59  = (w51*w59);
  /* #432: @77 = dense(@59) */
  casadi_densify((&w59), casadi_s6, w77, 0);
  /* #433: @66 = (@66+@77) */
  for (i=0, rr=w66, cs=w77; i<4; ++i) (*rr++) += (*cs++);
  /* #434: (@46[6:10] += @66) */
  for (rr=w46+6, cs=w66; rr!=w46+10; rr+=1) *rr += *cs++;
  /* #435: @60 = sparsity_cast(@60) */
  /* #436: @60 = (-@60) */
  w60 = (- w60 );
  /* #437: @60 = @60' */
  /* #438: @22 = mac(@60,@26,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w60), casadi_s5, wr26, casadi_s4, w22, casadi_s3, w, 0);
  /* #439: @22 = @22' */
  /* #440: @24 = mac(@60,@55,@1) */
  casadi_copy(w01, 3, w24);
  casadi_mtimes((&w60), casadi_s5, w55, casadi_s4, w24, casadi_s3, w, 0);
  /* #441: @24 = @24' */
  /* #442: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #443: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #444: (@46[3:6] += @22) */
  for (rr=w46+3, cs=w22; rr!=w46+6; rr+=1) *rr += *cs++;
  /* #445: @61 = sparsity_cast(@61) */
  /* #446: @61 = (-@61) */
  w61 = (- w61 );
  /* #447: @61 = @61' */
  /* #448: @22 = mac(@61,@23,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w61), casadi_s5, wr23, casadi_s4, w22, casadi_s3, w, 0);
  /* #449: @22 = @22' */
  /* #450: @24 = mac(@61,@56,@1) */
  casadi_copy(w01, 3, w24);
  casadi_mtimes((&w61), casadi_s5, w56, casadi_s4, w24, casadi_s3, w, 0);
  /* #451: @24 = @24' */
  /* #452: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #453: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #454: (@46[:3] += @22) */
  for (rr=w46+0, cs=w22; rr!=w46+3; rr+=1) *rr += *cs++;
  /* #455: {@61, @60, @59, @53, @75, @70, @49, @68, @52, @76, @78, @79, @80} = vertsplit(@46) */
  w61 = w46[0];
  w60 = w46[1];
  w59 = w46[2];
  w53 = w46[3];
  w75 = w46[4];
  w70 = w46[5];
  w49 = w46[6];
  w68 = w46[7];
  w52 = w46[8];
  w76 = w46[9];
  w78 = w46[10];
  w79 = w46[11];
  w80 = w46[12];
  /* #456: @67 = (@67/@8) */
  for (i=0, rr=w67; i<4; ++i) (*rr++) /= w08;
  /* #457: @41 = (@41/@8) */
  for (i=0, rr=w41; i<4; ++i) (*rr++) /= w08;
  /* #458: @66 = (@41*@18) */
  for (i=0, rr=w66, cr=w41; i<4; ++i) (*rr++)  = ((*cr++)*w18);
  /* #459: @67 = (@67-@66) */
  for (i=0, rr=w67, cs=w66; i<4; ++i) (*rr++) -= (*cs++);
  /* #460: {@18, @81, @82, @83} = vertsplit(@67) */
  w18 = w67[0];
  w81 = w67[1];
  w82 = w67[2];
  w83 = w67[3];
  /* #461: @18 = (@18+@49) */
  w18 += w49;
  /* #462: @68 = (@68-@81) */
  w68 -= w81;
  /* #463: @52 = (@52-@82) */
  w52 -= w82;
  /* #464: @76 = (@76-@83) */
  w76 -= w83;
  /* #465: @19 = vertcat(@58, @62, @17, @57, @61, @60, @59, @53, @75, @70, @18, @68, @52, @76, @78, @79, @80) */
  rr=w19;
  *rr++ = w58;
  *rr++ = w62;
  *rr++ = w17;
  *rr++ = w57;
  *rr++ = w61;
  *rr++ = w60;
  *rr++ = w59;
  *rr++ = w53;
  *rr++ = w75;
  *rr++ = w70;
  *rr++ = w18;
  *rr++ = w68;
  *rr++ = w52;
  *rr++ = w76;
  *rr++ = w78;
  *rr++ = w79;
  *rr++ = w80;
  /* #466: (@63[0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 34, 35, 36, 37, 50, 51, 52] = @19) */
  for (cii=casadi_s7, rr=w63, cs=w19; cii!=casadi_s7+17; ++cii, ++cs) rr[*cii] = *cs;
  /* #467: (@63[0, 4, 8, 12, 16, 19, 22, 25, 28, 31, 34, 38, 42, 46, 50, 53, 56] = @19) */
  for (cii=casadi_s8, rr=w63, cs=w19; cii!=casadi_s8+17; ++cii, ++cs) rr[*cii] = *cs;
  /* #468: @64 = ones(17x1,5nz) */
  casadi_fill(w64, 5, 1.);
  /* #469: {NULL, @58, NULL, NULL, NULL, @62, NULL, NULL, @17, NULL, NULL, @57, NULL, NULL, NULL, @61, NULL} = vertsplit(@64) */
  w58 = w64[0];
  w62 = w64[1];
  w17 = w64[2];
  w57 = w64[3];
  w61 = w64[4];
  /* #470: @60 = vertcat(@65, @58, @65, @65) */
  rr=(&w60);
  *rr++ = w58;
  /* #471: @60 = @60' */
  /* #472: @67 = mac(@60,@42,@31) */
  casadi_copy(w31, 4, w67);
  casadi_mtimes((&w60), casadi_s9, wr42, casadi_s1, w67, casadi_s0, w, 0);
  /* #473: @67 = @67' */
  /* #474: @66 = mac(@60,@44,@31) */
  casadi_copy(w31, 4, w66);
  casadi_mtimes((&w60), casadi_s9, w44, casadi_s1, w66, casadi_s0, w, 0);
  /* #475: @66 = @66' */
  /* #476: @67 = (@67+@66) */
  for (i=0, rr=w67, cs=w66; i<4; ++i) (*rr++) += (*cs++);
  /* #477: {@60, @58, @59, @53} = vertsplit(@67) */
  w60 = w67[0];
  w58 = w67[1];
  w59 = w67[2];
  w53 = w67[3];
  /* #478: @61 = sparsity_cast(@61) */
  /* #479: @61 = (-@61) */
  w61 = (- w61 );
  /* #480: @61 = @61' */
  /* #481: @22 = mac(@61,@39,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w61), casadi_s10, wr39, casadi_s4, w22, casadi_s3, w, 0);
  /* #482: @22 = @22' */
  /* #483: @24 = mac(@61,@45,@1) */
  casadi_copy(w01, 3, w24);
  casadi_mtimes((&w61), casadi_s10, w45, casadi_s4, w24, casadi_s3, w, 0);
  /* #484: @24 = @24' */
  /* #485: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #486: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #487: @46 = @21; (@46[10:13] += @22) */
  casadi_copy(w21, 13, w46);
  for (rr=w46+10, cs=w22; rr!=w46+13; rr+=1) *rr += *cs++;
  /* #488: @61 = (-@57) */
  w61 = (- w57 );
  /* #489: @75 = vertcat(@65, @61, @65, @65) */
  rr=(&w75);
  *rr++ = w61;
  /* #490: @75 = (@75/@8) */
  w75 /= w08;
  /* #491: @67 = dense(@75) */
  casadi_densify((&w75), casadi_s11, w67, 0);
  /* #492: @75 = project(@29) */
  casadi_sparsify(w29, (&w75), casadi_s11, 0);
  /* #493: @57 = sparsity_cast(@57) */
  /* #494: @61 = dot(@75, @57) */
  w61 = casadi_dot(1, (&w75), (&w57));
  /* #495: @61 = (@61/@8) */
  w61 /= w08;
  /* #496: @66 = (@28*@61) */
  for (i=0, rr=w66, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)*w61);
  /* #497: @67 = (@67-@66) */
  for (i=0, rr=w67, cs=w66; i<4; ++i) (*rr++) -= (*cs++);
  /* #498: {@75, @70, @18, @68} = vertsplit(@67) */
  w75 = w67[0];
  w70 = w67[1];
  w18 = w67[2];
  w68 = w67[3];
  /* #499: @52 = (@4*@75) */
  w52  = (w04*w75);
  /* #500: @76 = (@5*@70) */
  w76  = (w05*w70);
  /* #501: @52 = (@52-@76) */
  w52 -= w76;
  /* #502: @76 = (@6*@18) */
  w76  = (w06*w18);
  /* #503: @52 = (@52-@76) */
  w52 -= w76;
  /* #504: @76 = (@7*@68) */
  w76  = (w07*w68);
  /* #505: @52 = (@52-@76) */
  w52 -= w76;
  /* #506: @76 = (@5*@75) */
  w76  = (w05*w75);
  /* #507: @78 = (@4*@70) */
  w78  = (w04*w70);
  /* #508: @76 = (@76+@78) */
  w76 += w78;
  /* #509: @78 = (@7*@18) */
  w78  = (w07*w18);
  /* #510: @76 = (@76+@78) */
  w76 += w78;
  /* #511: @78 = (@6*@68) */
  w78  = (w06*w68);
  /* #512: @76 = (@76-@78) */
  w76 -= w78;
  /* #513: @78 = (@6*@75) */
  w78  = (w06*w75);
  /* #514: @79 = (@7*@70) */
  w79  = (w07*w70);
  /* #515: @78 = (@78-@79) */
  w78 -= w79;
  /* #516: @79 = (@4*@18) */
  w79  = (w04*w18);
  /* #517: @78 = (@78+@79) */
  w78 += w79;
  /* #518: @79 = (@5*@68) */
  w79  = (w05*w68);
  /* #519: @78 = (@78+@79) */
  w78 += w79;
  /* #520: @75 = (@7*@75) */
  w75  = (w07*w75);
  /* #521: @70 = (@6*@70) */
  w70  = (w06*w70);
  /* #522: @75 = (@75+@70) */
  w75 += w70;
  /* #523: @18 = (@5*@18) */
  w18  = (w05*w18);
  /* #524: @75 = (@75-@18) */
  w75 -= w18;
  /* #525: @68 = (@4*@68) */
  w68  = (w04*w68);
  /* #526: @75 = (@75+@68) */
  w75 += w68;
  /* #527: @66 = vertcat(@52, @76, @78, @75) */
  rr=w66;
  *rr++ = w52;
  *rr++ = w76;
  *rr++ = w78;
  *rr++ = w75;
  /* #528: @77 = (-@66) */
  for (i=0, rr=w77, cs=w66; i<4; ++i) *rr++ = (- *cs++ );
  /* #529: @77 = (@13?@77:0) */
  for (i=0, rr=w77, cs=w77; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #530: @66 = (@12?@66:0) */
  for (i=0, rr=w66, cs=w66; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #531: @77 = (@77+@66) */
  for (i=0, rr=w77, cs=w66; i<4; ++i) (*rr++) += (*cs++);
  /* #532: @22 = @77[1:4] */
  for (rr=w22, cs=w77+1; cs!=w77+4; cs+=1) *rr++ = *cs;
  /* #533: @52 = dot(@20, @22) */
  w52 = casadi_dot(3, w20, w22);
  /* #534: @52 = (@52/@14) */
  w52 /= w14;
  /* #535: @76 = (@52/@10) */
  w76  = (w52/w10);
  /* #536: @78 = (@50*@52) */
  w78  = (w50*w52);
  /* #537: @75 = @77[0] */
  for (rr=(&w75), cs=w77+0; cs!=w77+1; cs+=1) *rr++ = *cs;
  /* #538: @68 = (@15*@75) */
  w68  = (w15*w75);
  /* #539: @78 = (@78+@68) */
  w78 += w68;
  /* #540: @68 = (@69*@78) */
  w68  = (w69*w78);
  /* #541: @76 = (@76-@68) */
  w76 -= w68;
  /* #542: @76 = (@0*@76) */
  w76  = (w00*w76);
  /* #543: @24 = (2.*@22) */
  for (i=0, rr=w24, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #544: @38 = (@9*@24) */
  for (i=0, rr=w38, cs=w24; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #545: @68 = (@16*@52) */
  w68  = (w16*w52);
  /* #546: @18 = (@11*@75) */
  w18  = (w11*w75);
  /* #547: @68 = (@68-@18) */
  w68 -= w18;
  /* #548: @27 = (@32*@68) */
  for (i=0, rr=w27, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w68);
  /* #549: @38 = (@38+@27) */
  for (i=0, rr=w38, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #550: @38 = (@38/@3) */
  for (i=0, rr=w38; i<3; ++i) (*rr++) /= w03;
  /* #551: @27 = (@33*@52) */
  for (i=0, rr=w27, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #552: @38 = (@38-@27) */
  for (i=0, rr=w38, cs=w27; i<3; ++i) (*rr++) -= (*cs++);
  /* #553: @27 = @38' */
  casadi_copy(w38, 3, w27);
  /* #554: @72 = mac(@27,@35,@1) */
  casadi_copy(w01, 3, w72);
  for (i=0, rr=w72; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w27+j, ct=wr35+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #555: @72 = @72' */
  /* #556: @84 = mac(@27,@47,@1) */
  casadi_copy(w01, 3, w84);
  for (i=0, rr=w84; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w27+j, ct=w47+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #557: @84 = @84' */
  /* #558: @72 = (@72+@84) */
  for (i=0, rr=w72, cs=w84; i<3; ++i) (*rr++) += (*cs++);
  /* #559: @84 = (@72/@3) */
  for (i=0, rr=w84, cr=w72; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #560: @27 = (@37*@52) */
  for (i=0, rr=w27, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #561: @84 = (@84-@27) */
  for (i=0, rr=w84, cs=w27; i<3; ++i) (*rr++) -= (*cs++);
  /* #562: @18 = dot(@32, @84) */
  w18 = casadi_dot(3, w32, w84);
  /* #563: @70 = dot(@24, @40) */
  w70 = casadi_dot(3, w24, w40);
  /* #564: @18 = (@18+@70) */
  w18 += w70;
  /* #565: @70 = (@11*@18) */
  w70  = (w11*w18);
  /* #566: @76 = (@76+@70) */
  w76 += w70;
  /* #567: @76 = (-@76) */
  w76 = (- w76 );
  /* #568: @77 = @30; (@77[0] += @76) */
  casadi_copy(w30, 4, w77);
  for (rr=w77+0, cs=(&w76); rr!=w77+1; rr+=1) *rr += *cs++;
  /* #569: @76 = dot(@34, @72) */
  w76 = casadi_dot(3, w34, w72);
  /* #570: @38 = (@38/@3) */
  for (i=0, rr=w38; i<3; ++i) (*rr++) /= w03;
  /* #571: @72 = (@25*@52) */
  for (i=0, rr=w72, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #572: @38 = (@38-@72) */
  for (i=0, rr=w38, cs=w72; i<3; ++i) (*rr++) -= (*cs++);
  /* #573: @38 = (-@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (- *cs++ );
  /* #574: @70 = dot(@38, @36) */
  w70 = casadi_dot(3, w38, w36);
  /* #575: @76 = (@76+@70) */
  w76 += w70;
  /* #576: @75 = (@75/@10) */
  w75 /= w10;
  /* #577: @78 = (@73*@78) */
  w78  = (w73*w78);
  /* #578: @75 = (@75-@78) */
  w75 -= w78;
  /* #579: @75 = (@0*@75) */
  w75  = (w00*w75);
  /* #580: @18 = (@16*@18) */
  w18  = (w16*w18);
  /* #581: @75 = (@75+@18) */
  w75 += w18;
  /* #582: @76 = (@76+@75) */
  w76 += w75;
  /* #583: @76 = (@76/@14) */
  w76 /= w14;
  /* #584: @52 = (@54*@52) */
  w52  = (w54*w52);
  /* #585: @76 = (@76-@52) */
  w76 -= w52;
  /* #586: @38 = (@20*@76) */
  for (i=0, rr=w38, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w76);
  /* #587: @22 = (@2*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #588: @38 = (@38+@22) */
  for (i=0, rr=w38, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #589: @22 = (@40*@68) */
  for (i=0, rr=w22, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w68);
  /* #590: @84 = (@9*@84) */
  for (i=0, rr=w84, cs=w84; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #591: @22 = (@22+@84) */
  for (i=0, rr=w22, cs=w84; i<3; ++i) (*rr++) += (*cs++);
  /* #592: @22 = (2.*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #593: @38 = (@38+@22) */
  for (i=0, rr=w38, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #594: (@77[1:4] += @38) */
  for (rr=w77+1, cs=w38; rr!=w77+4; rr+=1) *rr += *cs++;
  /* #595: @66 = (@12?@77:0) */
  for (i=0, rr=w66, cs=w77; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #596: @77 = (-@77) */
  for (i=0, rr=w77, cs=w77; i<4; ++i) *rr++ = (- *cs++ );
  /* #597: @77 = (@13?@77:0) */
  for (i=0, rr=w77, cs=w77; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #598: @66 = (@66+@77) */
  for (i=0, rr=w66, cs=w77; i<4; ++i) (*rr++) += (*cs++);
  /* #599: {@68, @76, @52, @75} = vertsplit(@66) */
  w68 = w66[0];
  w76 = w66[1];
  w52 = w66[2];
  w75 = w66[3];
  /* #600: @18 = (@7*@75) */
  w18  = (w07*w75);
  /* #601: @78 = (@6*@52) */
  w78  = (w06*w52);
  /* #602: @18 = (@18+@78) */
  w18 += w78;
  /* #603: @78 = (@5*@76) */
  w78  = (w05*w76);
  /* #604: @18 = (@18+@78) */
  w18 += w78;
  /* #605: @78 = (@4*@68) */
  w78  = (w04*w68);
  /* #606: @18 = (@18+@78) */
  w18 += w78;
  /* #607: @78 = (@6*@75) */
  w78  = (w06*w75);
  /* #608: @70 = (@7*@52) */
  w70  = (w07*w52);
  /* #609: @78 = (@78-@70) */
  w78 -= w70;
  /* #610: @70 = (@4*@76) */
  w70  = (w04*w76);
  /* #611: @78 = (@78+@70) */
  w78 += w70;
  /* #612: @70 = (@5*@68) */
  w70  = (w05*w68);
  /* #613: @78 = (@78-@70) */
  w78 -= w70;
  /* #614: @70 = (@4*@52) */
  w70  = (w04*w52);
  /* #615: @79 = (@5*@75) */
  w79  = (w05*w75);
  /* #616: @70 = (@70-@79) */
  w70 -= w79;
  /* #617: @79 = (@7*@76) */
  w79  = (w07*w76);
  /* #618: @70 = (@70+@79) */
  w70 += w79;
  /* #619: @79 = (@6*@68) */
  w79  = (w06*w68);
  /* #620: @70 = (@70-@79) */
  w70 -= w79;
  /* #621: @75 = (@4*@75) */
  w75  = (w04*w75);
  /* #622: @52 = (@5*@52) */
  w52  = (w05*w52);
  /* #623: @75 = (@75+@52) */
  w75 += w52;
  /* #624: @76 = (@6*@76) */
  w76  = (w06*w76);
  /* #625: @75 = (@75-@76) */
  w75 -= w76;
  /* #626: @68 = (@7*@68) */
  w68  = (w07*w68);
  /* #627: @75 = (@75-@68) */
  w75 -= w68;
  /* #628: @66 = vertcat(@18, @78, @70, @75) */
  rr=w66;
  *rr++ = w18;
  *rr++ = w78;
  *rr++ = w70;
  *rr++ = w75;
  /* #629: @18 = dot(@43, @66) */
  w18 = casadi_dot(4, w43, w66);
  /* #630: @67 = (@67/@8) */
  for (i=0, rr=w67; i<4; ++i) (*rr++) /= w08;
  /* #631: @77 = (@71*@61) */
  for (i=0, rr=w77, cr=w71; i<4; ++i) (*rr++)  = ((*cr++)*w61);
  /* #632: @67 = (@67-@77) */
  for (i=0, rr=w67, cs=w77; i<4; ++i) (*rr++) -= (*cs++);
  /* #633: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<4; ++i) *rr++ = (- *cs++ );
  /* #634: @78 = dot(@67, @48) */
  w78 = casadi_dot(4, w67, w48);
  /* #635: @18 = (@18+@78) */
  w18 += w78;
  /* #636: @18 = (@18/@8) */
  w18 /= w08;
  /* #637: @78 = (@74*@61) */
  w78  = (w74*w61);
  /* #638: @18 = (@18-@78) */
  w18 -= w78;
  /* #639: @67 = (@29*@18) */
  for (i=0, rr=w67, cr=w29; i<4; ++i) (*rr++)  = ((*cr++)*w18);
  /* #640: @57 = (@51*@57) */
  w57  = (w51*w57);
  /* #641: @77 = dense(@57) */
  casadi_densify((&w57), casadi_s11, w77, 0);
  /* #642: @67 = (@67+@77) */
  for (i=0, rr=w67, cs=w77; i<4; ++i) (*rr++) += (*cs++);
  /* #643: (@46[6:10] += @67) */
  for (rr=w46+6, cs=w67; rr!=w46+10; rr+=1) *rr += *cs++;
  /* #644: @17 = sparsity_cast(@17) */
  /* #645: @17 = (-@17) */
  w17 = (- w17 );
  /* #646: @17 = @17' */
  /* #647: @38 = mac(@17,@26,@1) */
  casadi_copy(w01, 3, w38);
  casadi_mtimes((&w17), casadi_s10, wr26, casadi_s4, w38, casadi_s3, w, 0);
  /* #648: @38 = @38' */
  /* #649: @22 = mac(@17,@55,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w17), casadi_s10, w55, casadi_s4, w22, casadi_s3, w, 0);
  /* #650: @22 = @22' */
  /* #651: @38 = (@38+@22) */
  for (i=0, rr=w38, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #652: @38 = (-@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (- *cs++ );
  /* #653: (@46[3:6] += @38) */
  for (rr=w46+3, cs=w38; rr!=w46+6; rr+=1) *rr += *cs++;
  /* #654: @62 = sparsity_cast(@62) */
  /* #655: @62 = (-@62) */
  w62 = (- w62 );
  /* #656: @62 = @62' */
  /* #657: @38 = mac(@62,@23,@1) */
  casadi_copy(w01, 3, w38);
  casadi_mtimes((&w62), casadi_s10, wr23, casadi_s4, w38, casadi_s3, w, 0);
  /* #658: @38 = @38' */
  /* #659: @22 = mac(@62,@56,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w62), casadi_s10, w56, casadi_s4, w22, casadi_s3, w, 0);
  /* #660: @22 = @22' */
  /* #661: @38 = (@38+@22) */
  for (i=0, rr=w38, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #662: @38 = (-@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (- *cs++ );
  /* #663: (@46[:3] += @38) */
  for (rr=w46+0, cs=w38; rr!=w46+3; rr+=1) *rr += *cs++;
  /* #664: {@62, @17, @57, @18, @78, @70, @75, @68, @76, @52, @79, @80, @83} = vertsplit(@46) */
  w62 = w46[0];
  w17 = w46[1];
  w57 = w46[2];
  w18 = w46[3];
  w78 = w46[4];
  w70 = w46[5];
  w75 = w46[6];
  w68 = w46[7];
  w76 = w46[8];
  w52 = w46[9];
  w79 = w46[10];
  w80 = w46[11];
  w83 = w46[12];
  /* #665: @66 = (@66/@8) */
  for (i=0, rr=w66; i<4; ++i) (*rr++) /= w08;
  /* #666: @67 = (@41*@61) */
  for (i=0, rr=w67, cr=w41; i<4; ++i) (*rr++)  = ((*cr++)*w61);
  /* #667: @66 = (@66-@67) */
  for (i=0, rr=w66, cs=w67; i<4; ++i) (*rr++) -= (*cs++);
  /* #668: {@61, @82, @81, @49} = vertsplit(@66) */
  w61 = w66[0];
  w82 = w66[1];
  w81 = w66[2];
  w49 = w66[3];
  /* #669: @61 = (@61+@75) */
  w61 += w75;
  /* #670: @68 = (@68-@82) */
  w68 -= w82;
  /* #671: @76 = (@76-@81) */
  w76 -= w81;
  /* #672: @52 = (@52-@49) */
  w52 -= w49;
  /* #673: @19 = vertcat(@60, @58, @59, @53, @62, @17, @57, @18, @78, @70, @61, @68, @76, @52, @79, @80, @83) */
  rr=w19;
  *rr++ = w60;
  *rr++ = w58;
  *rr++ = w59;
  *rr++ = w53;
  *rr++ = w62;
  *rr++ = w17;
  *rr++ = w57;
  *rr++ = w18;
  *rr++ = w78;
  *rr++ = w70;
  *rr++ = w61;
  *rr++ = w68;
  *rr++ = w76;
  *rr++ = w52;
  *rr++ = w79;
  *rr++ = w80;
  *rr++ = w83;
  /* #674: (@63[4, 5, 6, 7, 19, 20, 21, 28, 29, 30, 38, 39, 40, 41, 53, 54, 55] = @19) */
  for (cii=casadi_s12, rr=w63, cs=w19; cii!=casadi_s12+17; ++cii, ++cs) rr[*cii] = *cs;
  /* #675: (@63[1, 5, 9, 13, 17, 20, 23, 26, 29, 32, 35, 39, 43, 47, 51, 54, 57] = @19) */
  for (cii=casadi_s13, rr=w63, cs=w19; cii!=casadi_s13+17; ++cii, ++cs) rr[*cii] = *cs;
  /* #676: @64 = ones(17x1,5nz) */
  casadi_fill(w64, 5, 1.);
  /* #677: {NULL, NULL, @60, NULL, NULL, NULL, @58, NULL, NULL, @59, NULL, NULL, @53, NULL, NULL, NULL, @62} = vertsplit(@64) */
  w60 = w64[0];
  w58 = w64[1];
  w59 = w64[2];
  w53 = w64[3];
  w62 = w64[4];
  /* #678: @17 = vertcat(@65, @65, @60, @65) */
  rr=(&w17);
  *rr++ = w60;
  /* #679: @17 = @17' */
  /* #680: @66 = mac(@17,@42,@31) */
  casadi_copy(w31, 4, w66);
  casadi_mtimes((&w17), casadi_s14, wr42, casadi_s1, w66, casadi_s0, w, 0);
  /* #681: @66 = @66' */
  /* #682: @67 = mac(@17,@44,@31) */
  casadi_copy(w31, 4, w67);
  casadi_mtimes((&w17), casadi_s14, w44, casadi_s1, w67, casadi_s0, w, 0);
  /* #683: @67 = @67' */
  /* #684: @66 = (@66+@67) */
  for (i=0, rr=w66, cs=w67; i<4; ++i) (*rr++) += (*cs++);
  /* #685: {@17, @60, @57, @18} = vertsplit(@66) */
  w17 = w66[0];
  w60 = w66[1];
  w57 = w66[2];
  w18 = w66[3];
  /* #686: @62 = sparsity_cast(@62) */
  /* #687: @62 = (-@62) */
  w62 = (- w62 );
  /* #688: @62 = @62' */
  /* #689: @38 = mac(@62,@39,@1) */
  casadi_copy(w01, 3, w38);
  casadi_mtimes((&w62), casadi_s15, wr39, casadi_s4, w38, casadi_s3, w, 0);
  /* #690: @38 = @38' */
  /* #691: @22 = mac(@62,@45,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w62), casadi_s15, w45, casadi_s4, w22, casadi_s3, w, 0);
  /* #692: @22 = @22' */
  /* #693: @38 = (@38+@22) */
  for (i=0, rr=w38, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #694: @38 = (-@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (- *cs++ );
  /* #695: @46 = @21; (@46[10:13] += @38) */
  casadi_copy(w21, 13, w46);
  for (rr=w46+10, cs=w38; rr!=w46+13; rr+=1) *rr += *cs++;
  /* #696: @62 = (-@53) */
  w62 = (- w53 );
  /* #697: @78 = vertcat(@65, @65, @62, @65) */
  rr=(&w78);
  *rr++ = w62;
  /* #698: @78 = (@78/@8) */
  w78 /= w08;
  /* #699: @66 = dense(@78) */
  casadi_densify((&w78), casadi_s16, w66, 0);
  /* #700: @78 = project(@29) */
  casadi_sparsify(w29, (&w78), casadi_s16, 0);
  /* #701: @53 = sparsity_cast(@53) */
  /* #702: @62 = dot(@78, @53) */
  w62 = casadi_dot(1, (&w78), (&w53));
  /* #703: @62 = (@62/@8) */
  w62 /= w08;
  /* #704: @67 = (@28*@62) */
  for (i=0, rr=w67, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)*w62);
  /* #705: @66 = (@66-@67) */
  for (i=0, rr=w66, cs=w67; i<4; ++i) (*rr++) -= (*cs++);
  /* #706: {@78, @70, @61, @68} = vertsplit(@66) */
  w78 = w66[0];
  w70 = w66[1];
  w61 = w66[2];
  w68 = w66[3];
  /* #707: @76 = (@4*@78) */
  w76  = (w04*w78);
  /* #708: @52 = (@5*@70) */
  w52  = (w05*w70);
  /* #709: @76 = (@76-@52) */
  w76 -= w52;
  /* #710: @52 = (@6*@61) */
  w52  = (w06*w61);
  /* #711: @76 = (@76-@52) */
  w76 -= w52;
  /* #712: @52 = (@7*@68) */
  w52  = (w07*w68);
  /* #713: @76 = (@76-@52) */
  w76 -= w52;
  /* #714: @52 = (@5*@78) */
  w52  = (w05*w78);
  /* #715: @79 = (@4*@70) */
  w79  = (w04*w70);
  /* #716: @52 = (@52+@79) */
  w52 += w79;
  /* #717: @79 = (@7*@61) */
  w79  = (w07*w61);
  /* #718: @52 = (@52+@79) */
  w52 += w79;
  /* #719: @79 = (@6*@68) */
  w79  = (w06*w68);
  /* #720: @52 = (@52-@79) */
  w52 -= w79;
  /* #721: @79 = (@6*@78) */
  w79  = (w06*w78);
  /* #722: @80 = (@7*@70) */
  w80  = (w07*w70);
  /* #723: @79 = (@79-@80) */
  w79 -= w80;
  /* #724: @80 = (@4*@61) */
  w80  = (w04*w61);
  /* #725: @79 = (@79+@80) */
  w79 += w80;
  /* #726: @80 = (@5*@68) */
  w80  = (w05*w68);
  /* #727: @79 = (@79+@80) */
  w79 += w80;
  /* #728: @78 = (@7*@78) */
  w78  = (w07*w78);
  /* #729: @70 = (@6*@70) */
  w70  = (w06*w70);
  /* #730: @78 = (@78+@70) */
  w78 += w70;
  /* #731: @61 = (@5*@61) */
  w61  = (w05*w61);
  /* #732: @78 = (@78-@61) */
  w78 -= w61;
  /* #733: @68 = (@4*@68) */
  w68  = (w04*w68);
  /* #734: @78 = (@78+@68) */
  w78 += w68;
  /* #735: @67 = vertcat(@76, @52, @79, @78) */
  rr=w67;
  *rr++ = w76;
  *rr++ = w52;
  *rr++ = w79;
  *rr++ = w78;
  /* #736: @77 = (-@67) */
  for (i=0, rr=w77, cs=w67; i<4; ++i) *rr++ = (- *cs++ );
  /* #737: @77 = (@13?@77:0) */
  for (i=0, rr=w77, cs=w77; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #738: @67 = (@12?@67:0) */
  for (i=0, rr=w67, cs=w67; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #739: @77 = (@77+@67) */
  for (i=0, rr=w77, cs=w67; i<4; ++i) (*rr++) += (*cs++);
  /* #740: @38 = @77[1:4] */
  for (rr=w38, cs=w77+1; cs!=w77+4; cs+=1) *rr++ = *cs;
  /* #741: @76 = dot(@20, @38) */
  w76 = casadi_dot(3, w20, w38);
  /* #742: @76 = (@76/@14) */
  w76 /= w14;
  /* #743: @52 = (@76/@10) */
  w52  = (w76/w10);
  /* #744: @79 = (@50*@76) */
  w79  = (w50*w76);
  /* #745: @78 = @77[0] */
  for (rr=(&w78), cs=w77+0; cs!=w77+1; cs+=1) *rr++ = *cs;
  /* #746: @68 = (@15*@78) */
  w68  = (w15*w78);
  /* #747: @79 = (@79+@68) */
  w79 += w68;
  /* #748: @68 = (@69*@79) */
  w68  = (w69*w79);
  /* #749: @52 = (@52-@68) */
  w52 -= w68;
  /* #750: @52 = (@0*@52) */
  w52  = (w00*w52);
  /* #751: @22 = (2.*@38) */
  for (i=0, rr=w22, cs=w38; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #752: @84 = (@9*@22) */
  for (i=0, rr=w84, cs=w22; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #753: @68 = (@16*@76) */
  w68  = (w16*w76);
  /* #754: @61 = (@11*@78) */
  w61  = (w11*w78);
  /* #755: @68 = (@68-@61) */
  w68 -= w61;
  /* #756: @72 = (@32*@68) */
  for (i=0, rr=w72, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w68);
  /* #757: @84 = (@84+@72) */
  for (i=0, rr=w84, cs=w72; i<3; ++i) (*rr++) += (*cs++);
  /* #758: @84 = (@84/@3) */
  for (i=0, rr=w84; i<3; ++i) (*rr++) /= w03;
  /* #759: @72 = (@33*@76) */
  for (i=0, rr=w72, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)*w76);
  /* #760: @84 = (@84-@72) */
  for (i=0, rr=w84, cs=w72; i<3; ++i) (*rr++) -= (*cs++);
  /* #761: @72 = @84' */
  casadi_copy(w84, 3, w72);
  /* #762: @24 = mac(@72,@35,@1) */
  casadi_copy(w01, 3, w24);
  for (i=0, rr=w24; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w72+j, ct=wr35+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #763: @24 = @24' */
  /* #764: @27 = mac(@72,@47,@1) */
  casadi_copy(w01, 3, w27);
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w72+j, ct=w47+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #765: @27 = @27' */
  /* #766: @24 = (@24+@27) */
  for (i=0, rr=w24, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #767: @27 = (@24/@3) */
  for (i=0, rr=w27, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #768: @72 = (@37*@76) */
  for (i=0, rr=w72, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w76);
  /* #769: @27 = (@27-@72) */
  for (i=0, rr=w27, cs=w72; i<3; ++i) (*rr++) -= (*cs++);
  /* #770: @61 = dot(@32, @27) */
  w61 = casadi_dot(3, w32, w27);
  /* #771: @70 = dot(@22, @40) */
  w70 = casadi_dot(3, w22, w40);
  /* #772: @61 = (@61+@70) */
  w61 += w70;
  /* #773: @70 = (@11*@61) */
  w70  = (w11*w61);
  /* #774: @52 = (@52+@70) */
  w52 += w70;
  /* #775: @52 = (-@52) */
  w52 = (- w52 );
  /* #776: @77 = @30; (@77[0] += @52) */
  casadi_copy(w30, 4, w77);
  for (rr=w77+0, cs=(&w52); rr!=w77+1; rr+=1) *rr += *cs++;
  /* #777: @52 = dot(@34, @24) */
  w52 = casadi_dot(3, w34, w24);
  /* #778: @84 = (@84/@3) */
  for (i=0, rr=w84; i<3; ++i) (*rr++) /= w03;
  /* #779: @24 = (@25*@76) */
  for (i=0, rr=w24, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)*w76);
  /* #780: @84 = (@84-@24) */
  for (i=0, rr=w84, cs=w24; i<3; ++i) (*rr++) -= (*cs++);
  /* #781: @84 = (-@84) */
  for (i=0, rr=w84, cs=w84; i<3; ++i) *rr++ = (- *cs++ );
  /* #782: @70 = dot(@84, @36) */
  w70 = casadi_dot(3, w84, w36);
  /* #783: @52 = (@52+@70) */
  w52 += w70;
  /* #784: @78 = (@78/@10) */
  w78 /= w10;
  /* #785: @79 = (@73*@79) */
  w79  = (w73*w79);
  /* #786: @78 = (@78-@79) */
  w78 -= w79;
  /* #787: @78 = (@0*@78) */
  w78  = (w00*w78);
  /* #788: @61 = (@16*@61) */
  w61  = (w16*w61);
  /* #789: @78 = (@78+@61) */
  w78 += w61;
  /* #790: @52 = (@52+@78) */
  w52 += w78;
  /* #791: @52 = (@52/@14) */
  w52 /= w14;
  /* #792: @76 = (@54*@76) */
  w76  = (w54*w76);
  /* #793: @52 = (@52-@76) */
  w52 -= w76;
  /* #794: @84 = (@20*@52) */
  for (i=0, rr=w84, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #795: @38 = (@2*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #796: @84 = (@84+@38) */
  for (i=0, rr=w84, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #797: @38 = (@40*@68) */
  for (i=0, rr=w38, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w68);
  /* #798: @27 = (@9*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #799: @38 = (@38+@27) */
  for (i=0, rr=w38, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #800: @38 = (2.*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #801: @84 = (@84+@38) */
  for (i=0, rr=w84, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #802: (@77[1:4] += @84) */
  for (rr=w77+1, cs=w84; rr!=w77+4; rr+=1) *rr += *cs++;
  /* #803: @67 = (@12?@77:0) */
  for (i=0, rr=w67, cs=w77; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #804: @77 = (-@77) */
  for (i=0, rr=w77, cs=w77; i<4; ++i) *rr++ = (- *cs++ );
  /* #805: @77 = (@13?@77:0) */
  for (i=0, rr=w77, cs=w77; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #806: @67 = (@67+@77) */
  for (i=0, rr=w67, cs=w77; i<4; ++i) (*rr++) += (*cs++);
  /* #807: {@68, @52, @76, @78} = vertsplit(@67) */
  w68 = w67[0];
  w52 = w67[1];
  w76 = w67[2];
  w78 = w67[3];
  /* #808: @61 = (@7*@78) */
  w61  = (w07*w78);
  /* #809: @79 = (@6*@76) */
  w79  = (w06*w76);
  /* #810: @61 = (@61+@79) */
  w61 += w79;
  /* #811: @79 = (@5*@52) */
  w79  = (w05*w52);
  /* #812: @61 = (@61+@79) */
  w61 += w79;
  /* #813: @79 = (@4*@68) */
  w79  = (w04*w68);
  /* #814: @61 = (@61+@79) */
  w61 += w79;
  /* #815: @79 = (@6*@78) */
  w79  = (w06*w78);
  /* #816: @70 = (@7*@76) */
  w70  = (w07*w76);
  /* #817: @79 = (@79-@70) */
  w79 -= w70;
  /* #818: @70 = (@4*@52) */
  w70  = (w04*w52);
  /* #819: @79 = (@79+@70) */
  w79 += w70;
  /* #820: @70 = (@5*@68) */
  w70  = (w05*w68);
  /* #821: @79 = (@79-@70) */
  w79 -= w70;
  /* #822: @70 = (@4*@76) */
  w70  = (w04*w76);
  /* #823: @80 = (@5*@78) */
  w80  = (w05*w78);
  /* #824: @70 = (@70-@80) */
  w70 -= w80;
  /* #825: @80 = (@7*@52) */
  w80  = (w07*w52);
  /* #826: @70 = (@70+@80) */
  w70 += w80;
  /* #827: @80 = (@6*@68) */
  w80  = (w06*w68);
  /* #828: @70 = (@70-@80) */
  w70 -= w80;
  /* #829: @78 = (@4*@78) */
  w78  = (w04*w78);
  /* #830: @76 = (@5*@76) */
  w76  = (w05*w76);
  /* #831: @78 = (@78+@76) */
  w78 += w76;
  /* #832: @52 = (@6*@52) */
  w52  = (w06*w52);
  /* #833: @78 = (@78-@52) */
  w78 -= w52;
  /* #834: @68 = (@7*@68) */
  w68  = (w07*w68);
  /* #835: @78 = (@78-@68) */
  w78 -= w68;
  /* #836: @67 = vertcat(@61, @79, @70, @78) */
  rr=w67;
  *rr++ = w61;
  *rr++ = w79;
  *rr++ = w70;
  *rr++ = w78;
  /* #837: @61 = dot(@43, @67) */
  w61 = casadi_dot(4, w43, w67);
  /* #838: @66 = (@66/@8) */
  for (i=0, rr=w66; i<4; ++i) (*rr++) /= w08;
  /* #839: @77 = (@71*@62) */
  for (i=0, rr=w77, cr=w71; i<4; ++i) (*rr++)  = ((*cr++)*w62);
  /* #840: @66 = (@66-@77) */
  for (i=0, rr=w66, cs=w77; i<4; ++i) (*rr++) -= (*cs++);
  /* #841: @66 = (-@66) */
  for (i=0, rr=w66, cs=w66; i<4; ++i) *rr++ = (- *cs++ );
  /* #842: @79 = dot(@66, @48) */
  w79 = casadi_dot(4, w66, w48);
  /* #843: @61 = (@61+@79) */
  w61 += w79;
  /* #844: @61 = (@61/@8) */
  w61 /= w08;
  /* #845: @79 = (@74*@62) */
  w79  = (w74*w62);
  /* #846: @61 = (@61-@79) */
  w61 -= w79;
  /* #847: @66 = (@29*@61) */
  for (i=0, rr=w66, cr=w29; i<4; ++i) (*rr++)  = ((*cr++)*w61);
  /* #848: @53 = (@51*@53) */
  w53  = (w51*w53);
  /* #849: @77 = dense(@53) */
  casadi_densify((&w53), casadi_s16, w77, 0);
  /* #850: @66 = (@66+@77) */
  for (i=0, rr=w66, cs=w77; i<4; ++i) (*rr++) += (*cs++);
  /* #851: (@46[6:10] += @66) */
  for (rr=w46+6, cs=w66; rr!=w46+10; rr+=1) *rr += *cs++;
  /* #852: @59 = sparsity_cast(@59) */
  /* #853: @59 = (-@59) */
  w59 = (- w59 );
  /* #854: @59 = @59' */
  /* #855: @84 = mac(@59,@26,@1) */
  casadi_copy(w01, 3, w84);
  casadi_mtimes((&w59), casadi_s15, wr26, casadi_s4, w84, casadi_s3, w, 0);
  /* #856: @84 = @84' */
  /* #857: @38 = mac(@59,@55,@1) */
  casadi_copy(w01, 3, w38);
  casadi_mtimes((&w59), casadi_s15, w55, casadi_s4, w38, casadi_s3, w, 0);
  /* #858: @38 = @38' */
  /* #859: @84 = (@84+@38) */
  for (i=0, rr=w84, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #860: @84 = (-@84) */
  for (i=0, rr=w84, cs=w84; i<3; ++i) *rr++ = (- *cs++ );
  /* #861: (@46[3:6] += @84) */
  for (rr=w46+3, cs=w84; rr!=w46+6; rr+=1) *rr += *cs++;
  /* #862: @58 = sparsity_cast(@58) */
  /* #863: @58 = (-@58) */
  w58 = (- w58 );
  /* #864: @58 = @58' */
  /* #865: @84 = mac(@58,@23,@1) */
  casadi_copy(w01, 3, w84);
  casadi_mtimes((&w58), casadi_s15, wr23, casadi_s4, w84, casadi_s3, w, 0);
  /* #866: @84 = @84' */
  /* #867: @38 = mac(@58,@56,@1) */
  casadi_copy(w01, 3, w38);
  casadi_mtimes((&w58), casadi_s15, w56, casadi_s4, w38, casadi_s3, w, 0);
  /* #868: @38 = @38' */
  /* #869: @84 = (@84+@38) */
  for (i=0, rr=w84, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #870: @84 = (-@84) */
  for (i=0, rr=w84, cs=w84; i<3; ++i) *rr++ = (- *cs++ );
  /* #871: (@46[:3] += @84) */
  for (rr=w46+0, cs=w84; rr!=w46+3; rr+=1) *rr += *cs++;
  /* #872: {@58, @59, @53, @61, @79, @70, @78, @68, @52, @76, @80, @83, @49} = vertsplit(@46) */
  w58 = w46[0];
  w59 = w46[1];
  w53 = w46[2];
  w61 = w46[3];
  w79 = w46[4];
  w70 = w46[5];
  w78 = w46[6];
  w68 = w46[7];
  w52 = w46[8];
  w76 = w46[9];
  w80 = w46[10];
  w83 = w46[11];
  w49 = w46[12];
  /* #873: @67 = (@67/@8) */
  for (i=0, rr=w67; i<4; ++i) (*rr++) /= w08;
  /* #874: @66 = (@41*@62) */
  for (i=0, rr=w66, cr=w41; i<4; ++i) (*rr++)  = ((*cr++)*w62);
  /* #875: @67 = (@67-@66) */
  for (i=0, rr=w67, cs=w66; i<4; ++i) (*rr++) -= (*cs++);
  /* #876: {@62, @81, @82, @75} = vertsplit(@67) */
  w62 = w67[0];
  w81 = w67[1];
  w82 = w67[2];
  w75 = w67[3];
  /* #877: @62 = (@62+@78) */
  w62 += w78;
  /* #878: @68 = (@68-@81) */
  w68 -= w81;
  /* #879: @52 = (@52-@82) */
  w52 -= w82;
  /* #880: @76 = (@76-@75) */
  w76 -= w75;
  /* #881: @19 = vertcat(@17, @60, @57, @18, @58, @59, @53, @61, @79, @70, @62, @68, @52, @76, @80, @83, @49) */
  rr=w19;
  *rr++ = w17;
  *rr++ = w60;
  *rr++ = w57;
  *rr++ = w18;
  *rr++ = w58;
  *rr++ = w59;
  *rr++ = w53;
  *rr++ = w61;
  *rr++ = w79;
  *rr++ = w70;
  *rr++ = w62;
  *rr++ = w68;
  *rr++ = w52;
  *rr++ = w76;
  *rr++ = w80;
  *rr++ = w83;
  *rr++ = w49;
  /* #882: (@63[8, 9, 10, 11, 22, 23, 24, 31, 32, 33, 42, 43, 44, 45, 56, 57, 58] = @19) */
  for (cii=casadi_s17, rr=w63, cs=w19; cii!=casadi_s17+17; ++cii, ++cs) rr[*cii] = *cs;
  /* #883: (@63[2, 6, 10, 14, 18, 21, 24, 27, 30, 33, 36, 40, 44, 48, 52, 55, 58] = @19) */
  for (cii=casadi_s18, rr=w63, cs=w19; cii!=casadi_s18+17; ++cii, ++cs) rr[*cii] = *cs;
  /* #884: @85 = ones(17x1,2nz) */
  casadi_fill(w85, 2, 1.);
  /* #885: {NULL, NULL, NULL, @17, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @60, NULL, NULL, NULL} = vertsplit(@85) */
  w17 = w85[0];
  w60 = w85[1];
  /* #886: @57 = vertcat(@65, @65, @65, @17) */
  rr=(&w57);
  *rr++ = w17;
  /* #887: @57 = @57' */
  /* #888: @67 = mac(@57,@42,@31) */
  casadi_copy(w31, 4, w67);
  casadi_mtimes((&w57), casadi_s19, wr42, casadi_s1, w67, casadi_s0, w, 0);
  /* #889: @67 = @67' */
  /* #890: @31 = mac(@57,@44,@31) */
  casadi_mtimes((&w57), casadi_s19, w44, casadi_s1, w31, casadi_s0, w, 0);
  /* #891: @31 = @31' */
  /* #892: @67 = (@67+@31) */
  for (i=0, rr=w67, cs=w31; i<4; ++i) (*rr++) += (*cs++);
  /* #893: {@57, @17, @18, @58} = vertsplit(@67) */
  w57 = w67[0];
  w17 = w67[1];
  w18 = w67[2];
  w58 = w67[3];
  /* #894: @59 = (-@60) */
  w59 = (- w60 );
  /* #895: @53 = vertcat(@65, @65, @65, @59) */
  rr=(&w53);
  *rr++ = w59;
  /* #896: @53 = (@53/@8) */
  w53 /= w08;
  /* #897: @67 = dense(@53) */
  casadi_densify((&w53), casadi_s20, w67, 0);
  /* #898: @53 = project(@29) */
  casadi_sparsify(w29, (&w53), casadi_s20, 0);
  /* #899: @60 = sparsity_cast(@60) */
  /* #900: @59 = dot(@53, @60) */
  w59 = casadi_dot(1, (&w53), (&w60));
  /* #901: @59 = (@59/@8) */
  w59 /= w08;
  /* #902: @28 = (@28*@59) */
  for (i=0, rr=w28; i<4; ++i) (*rr++) *= w59;
  /* #903: @67 = (@67-@28) */
  for (i=0, rr=w67, cs=w28; i<4; ++i) (*rr++) -= (*cs++);
  /* #904: {@53, @61, @79, @70} = vertsplit(@67) */
  w53 = w67[0];
  w61 = w67[1];
  w79 = w67[2];
  w70 = w67[3];
  /* #905: @62 = (@4*@53) */
  w62  = (w04*w53);
  /* #906: @68 = (@5*@61) */
  w68  = (w05*w61);
  /* #907: @62 = (@62-@68) */
  w62 -= w68;
  /* #908: @68 = (@6*@79) */
  w68  = (w06*w79);
  /* #909: @62 = (@62-@68) */
  w62 -= w68;
  /* #910: @68 = (@7*@70) */
  w68  = (w07*w70);
  /* #911: @62 = (@62-@68) */
  w62 -= w68;
  /* #912: @68 = (@5*@53) */
  w68  = (w05*w53);
  /* #913: @52 = (@4*@61) */
  w52  = (w04*w61);
  /* #914: @68 = (@68+@52) */
  w68 += w52;
  /* #915: @52 = (@7*@79) */
  w52  = (w07*w79);
  /* #916: @68 = (@68+@52) */
  w68 += w52;
  /* #917: @52 = (@6*@70) */
  w52  = (w06*w70);
  /* #918: @68 = (@68-@52) */
  w68 -= w52;
  /* #919: @52 = (@6*@53) */
  w52  = (w06*w53);
  /* #920: @76 = (@7*@61) */
  w76  = (w07*w61);
  /* #921: @52 = (@52-@76) */
  w52 -= w76;
  /* #922: @76 = (@4*@79) */
  w76  = (w04*w79);
  /* #923: @52 = (@52+@76) */
  w52 += w76;
  /* #924: @76 = (@5*@70) */
  w76  = (w05*w70);
  /* #925: @52 = (@52+@76) */
  w52 += w76;
  /* #926: @53 = (@7*@53) */
  w53  = (w07*w53);
  /* #927: @61 = (@6*@61) */
  w61  = (w06*w61);
  /* #928: @53 = (@53+@61) */
  w53 += w61;
  /* #929: @79 = (@5*@79) */
  w79  = (w05*w79);
  /* #930: @53 = (@53-@79) */
  w53 -= w79;
  /* #931: @70 = (@4*@70) */
  w70  = (w04*w70);
  /* #932: @53 = (@53+@70) */
  w53 += w70;
  /* #933: @28 = vertcat(@62, @68, @52, @53) */
  rr=w28;
  *rr++ = w62;
  *rr++ = w68;
  *rr++ = w52;
  *rr++ = w53;
  /* #934: @31 = (-@28) */
  for (i=0, rr=w31, cs=w28; i<4; ++i) *rr++ = (- *cs++ );
  /* #935: @31 = (@13?@31:0) */
  for (i=0, rr=w31, cs=w31; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #936: @28 = (@12?@28:0) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #937: @31 = (@31+@28) */
  for (i=0, rr=w31, cs=w28; i<4; ++i) (*rr++) += (*cs++);
  /* #938: @84 = @31[1:4] */
  for (rr=w84, cs=w31+1; cs!=w31+4; cs+=1) *rr++ = *cs;
  /* #939: @62 = dot(@20, @84) */
  w62 = casadi_dot(3, w20, w84);
  /* #940: @62 = (@62/@14) */
  w62 /= w14;
  /* #941: @68 = (@62/@10) */
  w68  = (w62/w10);
  /* #942: @50 = (@50*@62) */
  w50 *= w62;
  /* #943: @52 = @31[0] */
  for (rr=(&w52), cs=w31+0; cs!=w31+1; cs+=1) *rr++ = *cs;
  /* #944: @15 = (@15*@52) */
  w15 *= w52;
  /* #945: @50 = (@50+@15) */
  w50 += w15;
  /* #946: @69 = (@69*@50) */
  w69 *= w50;
  /* #947: @68 = (@68-@69) */
  w68 -= w69;
  /* #948: @68 = (@0*@68) */
  w68  = (w00*w68);
  /* #949: @38 = (2.*@84) */
  for (i=0, rr=w38, cs=w84; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #950: @27 = (@9*@38) */
  for (i=0, rr=w27, cs=w38; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #951: @69 = (@16*@62) */
  w69  = (w16*w62);
  /* #952: @15 = (@11*@52) */
  w15  = (w11*w52);
  /* #953: @69 = (@69-@15) */
  w69 -= w15;
  /* #954: @24 = (@32*@69) */
  for (i=0, rr=w24, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w69);
  /* #955: @27 = (@27+@24) */
  for (i=0, rr=w27, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #956: @27 = (@27/@3) */
  for (i=0, rr=w27; i<3; ++i) (*rr++) /= w03;
  /* #957: @33 = (@33*@62) */
  for (i=0, rr=w33; i<3; ++i) (*rr++) *= w62;
  /* #958: @27 = (@27-@33) */
  for (i=0, rr=w27, cs=w33; i<3; ++i) (*rr++) -= (*cs++);
  /* #959: @33 = @27' */
  casadi_copy(w27, 3, w33);
  /* #960: @24 = mac(@33,@35,@1) */
  casadi_copy(w01, 3, w24);
  for (i=0, rr=w24; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w33+j, ct=wr35+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #961: @24 = @24' */
  /* #962: @1 = mac(@33,@47,@1) */
  for (i=0, rr=w01; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w33+j, ct=w47+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #963: @1 = @1' */
  /* #964: @24 = (@24+@1) */
  for (i=0, rr=w24, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #965: @1 = (@24/@3) */
  for (i=0, rr=w01, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #966: @37 = (@37*@62) */
  for (i=0, rr=w37; i<3; ++i) (*rr++) *= w62;
  /* #967: @1 = (@1-@37) */
  for (i=0, rr=w01, cs=w37; i<3; ++i) (*rr++) -= (*cs++);
  /* #968: @15 = dot(@32, @1) */
  w15 = casadi_dot(3, w32, w01);
  /* #969: @53 = dot(@38, @40) */
  w53 = casadi_dot(3, w38, w40);
  /* #970: @15 = (@15+@53) */
  w15 += w53;
  /* #971: @11 = (@11*@15) */
  w11 *= w15;
  /* #972: @68 = (@68+@11) */
  w68 += w11;
  /* #973: @68 = (-@68) */
  w68 = (- w68 );
  /* #974: (@30[0] += @68) */
  for (rr=w30+0, cs=(&w68); rr!=w30+1; rr+=1) *rr += *cs++;
  /* #975: @68 = dot(@34, @24) */
  w68 = casadi_dot(3, w34, w24);
  /* #976: @27 = (@27/@3) */
  for (i=0, rr=w27; i<3; ++i) (*rr++) /= w03;
  /* #977: @25 = (@25*@62) */
  for (i=0, rr=w25; i<3; ++i) (*rr++) *= w62;
  /* #978: @27 = (@27-@25) */
  for (i=0, rr=w27, cs=w25; i<3; ++i) (*rr++) -= (*cs++);
  /* #979: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) *rr++ = (- *cs++ );
  /* #980: @3 = dot(@27, @36) */
  w03 = casadi_dot(3, w27, w36);
  /* #981: @68 = (@68+@3) */
  w68 += w03;
  /* #982: @52 = (@52/@10) */
  w52 /= w10;
  /* #983: @73 = (@73*@50) */
  w73 *= w50;
  /* #984: @52 = (@52-@73) */
  w52 -= w73;
  /* #985: @0 = (@0*@52) */
  w00 *= w52;
  /* #986: @16 = (@16*@15) */
  w16 *= w15;
  /* #987: @0 = (@0+@16) */
  w00 += w16;
  /* #988: @68 = (@68+@0) */
  w68 += w00;
  /* #989: @68 = (@68/@14) */
  w68 /= w14;
  /* #990: @54 = (@54*@62) */
  w54 *= w62;
  /* #991: @68 = (@68-@54) */
  w68 -= w54;
  /* #992: @20 = (@20*@68) */
  for (i=0, rr=w20; i<3; ++i) (*rr++) *= w68;
  /* #993: @84 = (@2*@84) */
  for (i=0, rr=w84, cs=w84; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #994: @20 = (@20+@84) */
  for (i=0, rr=w20, cs=w84; i<3; ++i) (*rr++) += (*cs++);
  /* #995: @40 = (@40*@69) */
  for (i=0, rr=w40; i<3; ++i) (*rr++) *= w69;
  /* #996: @1 = (@9*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #997: @40 = (@40+@1) */
  for (i=0, rr=w40, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #998: @40 = (2.*@40) */
  for (i=0, rr=w40, cs=w40; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #999: @20 = (@20+@40) */
  for (i=0, rr=w20, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #1000: (@30[1:4] += @20) */
  for (rr=w30+1, cs=w20; rr!=w30+4; rr+=1) *rr += *cs++;
  /* #1001: @31 = (@12?@30:0) */
  for (i=0, rr=w31, cs=w30; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #1002: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) *rr++ = (- *cs++ );
  /* #1003: @30 = (@13?@30:0) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #1004: @31 = (@31+@30) */
  for (i=0, rr=w31, cs=w30; i<4; ++i) (*rr++) += (*cs++);
  /* #1005: {@13, @12, @9, @69} = vertsplit(@31) */
  w13 = w31[0];
  w12 = w31[1];
  w09 = w31[2];
  w69 = w31[3];
  /* #1006: @2 = (@7*@69) */
  w02  = (w07*w69);
  /* #1007: @68 = (@6*@9) */
  w68  = (w06*w09);
  /* #1008: @2 = (@2+@68) */
  w02 += w68;
  /* #1009: @68 = (@5*@12) */
  w68  = (w05*w12);
  /* #1010: @2 = (@2+@68) */
  w02 += w68;
  /* #1011: @68 = (@4*@13) */
  w68  = (w04*w13);
  /* #1012: @2 = (@2+@68) */
  w02 += w68;
  /* #1013: @68 = (@6*@69) */
  w68  = (w06*w69);
  /* #1014: @54 = (@7*@9) */
  w54  = (w07*w09);
  /* #1015: @68 = (@68-@54) */
  w68 -= w54;
  /* #1016: @54 = (@4*@12) */
  w54  = (w04*w12);
  /* #1017: @68 = (@68+@54) */
  w68 += w54;
  /* #1018: @54 = (@5*@13) */
  w54  = (w05*w13);
  /* #1019: @68 = (@68-@54) */
  w68 -= w54;
  /* #1020: @54 = (@4*@9) */
  w54  = (w04*w09);
  /* #1021: @62 = (@5*@69) */
  w62  = (w05*w69);
  /* #1022: @54 = (@54-@62) */
  w54 -= w62;
  /* #1023: @62 = (@7*@12) */
  w62  = (w07*w12);
  /* #1024: @54 = (@54+@62) */
  w54 += w62;
  /* #1025: @62 = (@6*@13) */
  w62  = (w06*w13);
  /* #1026: @54 = (@54-@62) */
  w54 -= w62;
  /* #1027: @4 = (@4*@69) */
  w04 *= w69;
  /* #1028: @5 = (@5*@9) */
  w05 *= w09;
  /* #1029: @4 = (@4+@5) */
  w04 += w05;
  /* #1030: @6 = (@6*@12) */
  w06 *= w12;
  /* #1031: @4 = (@4-@6) */
  w04 -= w06;
  /* #1032: @7 = (@7*@13) */
  w07 *= w13;
  /* #1033: @4 = (@4-@7) */
  w04 -= w07;
  /* #1034: @31 = vertcat(@2, @68, @54, @4) */
  rr=w31;
  *rr++ = w02;
  *rr++ = w68;
  *rr++ = w54;
  *rr++ = w04;
  /* #1035: @2 = dot(@43, @31) */
  w02 = casadi_dot(4, w43, w31);
  /* #1036: @67 = (@67/@8) */
  for (i=0, rr=w67; i<4; ++i) (*rr++) /= w08;
  /* #1037: @71 = (@71*@59) */
  for (i=0, rr=w71; i<4; ++i) (*rr++) *= w59;
  /* #1038: @67 = (@67-@71) */
  for (i=0, rr=w67, cs=w71; i<4; ++i) (*rr++) -= (*cs++);
  /* #1039: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<4; ++i) *rr++ = (- *cs++ );
  /* #1040: @68 = dot(@67, @48) */
  w68 = casadi_dot(4, w67, w48);
  /* #1041: @2 = (@2+@68) */
  w02 += w68;
  /* #1042: @2 = (@2/@8) */
  w02 /= w08;
  /* #1043: @74 = (@74*@59) */
  w74 *= w59;
  /* #1044: @2 = (@2-@74) */
  w02 -= w74;
  /* #1045: @29 = (@29*@2) */
  for (i=0, rr=w29; i<4; ++i) (*rr++) *= w02;
  /* #1046: @51 = (@51*@60) */
  w51 *= w60;
  /* #1047: @67 = dense(@51) */
  casadi_densify((&w51), casadi_s20, w67, 0);
  /* #1048: @29 = (@29+@67) */
  for (i=0, rr=w29, cs=w67; i<4; ++i) (*rr++) += (*cs++);
  /* #1049: (@21[6:10] += @29) */
  for (rr=w21+6, cs=w29; rr!=w21+10; rr+=1) *rr += *cs++;
  /* #1050: {@51, @60, @2, @74, @68, @54, @4, @7, @13, @6, @12, @5, @9} = vertsplit(@21) */
  w51 = w21[0];
  w60 = w21[1];
  w02 = w21[2];
  w74 = w21[3];
  w68 = w21[4];
  w54 = w21[5];
  w04 = w21[6];
  w07 = w21[7];
  w13 = w21[8];
  w06 = w21[9];
  w12 = w21[10];
  w05 = w21[11];
  w09 = w21[12];
  /* #1051: @31 = (@31/@8) */
  for (i=0, rr=w31; i<4; ++i) (*rr++) /= w08;
  /* #1052: @41 = (@41*@59) */
  for (i=0, rr=w41; i<4; ++i) (*rr++) *= w59;
  /* #1053: @31 = (@31-@41) */
  for (i=0, rr=w31, cs=w41; i<4; ++i) (*rr++) -= (*cs++);
  /* #1054: {@59, @8, @69, @62} = vertsplit(@31) */
  w59 = w31[0];
  w08 = w31[1];
  w69 = w31[2];
  w62 = w31[3];
  /* #1055: @59 = (@59+@4) */
  w59 += w04;
  /* #1056: @7 = (@7-@8) */
  w07 -= w08;
  /* #1057: @13 = (@13-@69) */
  w13 -= w69;
  /* #1058: @6 = (@6-@62) */
  w06 -= w62;
  /* #1059: @19 = vertcat(@57, @17, @18, @58, @51, @60, @2, @74, @68, @54, @59, @7, @13, @6, @12, @5, @9) */
  rr=w19;
  *rr++ = w57;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w58;
  *rr++ = w51;
  *rr++ = w60;
  *rr++ = w02;
  *rr++ = w74;
  *rr++ = w68;
  *rr++ = w54;
  *rr++ = w59;
  *rr++ = w07;
  *rr++ = w13;
  *rr++ = w06;
  *rr++ = w12;
  *rr++ = w05;
  *rr++ = w09;
  /* #1060: @86 = @19[:20:10;:4] */
  for (rr=w86, cs=w19+0; cs!=w19+20; cs+=10) for (ct=cs+0; ct!=cs+4; ct+=1) *rr++ = *ct;
  /* #1061: (@63[:68:34;12:16] = @86) */
  for (rr=w63+0, cs=w86; rr!=w63+68; rr+=34) for (tt=rr+12; tt!=rr+16; tt+=1) *tt = *cs++;
  /* #1062: (@63[:68:34;3:19:4] = @86) */
  for (rr=w63+0, cs=w86; rr!=w63+68; rr+=34) for (tt=rr+3; tt!=rr+19; tt+=4) *tt = *cs++;
  /* #1063: @87 = @63' */
  casadi_trans(w63,casadi_s21, w87, casadi_s21, iw);
  /* #1064: output[2][0] = @87 */
  casadi_copy(w87, 59, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_gate_tracker_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_gate_tracker_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_gate_tracker_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_gate_tracker_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_gate_tracker_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_gate_tracker_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_gate_tracker_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_gate_tracker_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_gate_tracker_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_gate_tracker_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_gate_tracker_cost_ext_cost_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_gate_tracker_cost_ext_cost_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_gate_tracker_cost_ext_cost_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_gate_tracker_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s22;
    case 1: return casadi_s23;
    case 2: return casadi_s24;
    case 3: return casadi_s25;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_gate_tracker_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s26;
    case 1: return casadi_s25;
    case 2: return casadi_s21;
    case 3: return casadi_s27;
    case 4: return casadi_s28;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_gate_tracker_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 22;
  if (sz_iw) *sz_iw = 18;
  if (sz_w) *sz_w = 413;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_gate_tracker_cost_ext_cost_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 22*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 18*sizeof(casadi_int);
  if (sz_w) *sz_w = 413*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
