/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_gate_tracker_cost_ext_cost_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {17, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

static const casadi_real casadi_c0[9] = 
  {35., 0., 0., 0., 35., 0., 0., 0.,
  40.};
static const casadi_real casadi_c1[9] = 
  {6., 0., 0., 0., 6., 0., 0., 0.,
  6.};
static const casadi_real casadi_c2[9] = 
  {15., 0., 0., 0., 15., 0., 0., 0.,
  15.};
static const casadi_real casadi_c3[9] = 
  {5.0000000000000000e-01, 0., 0., 0., 5.0000000000000000e-01, 0., 0., 0.,
  5.0000000000000000e-01};

/* Drone_gate_tracker_cost_ext_cost_e_fun:(i0[13],i1[0],i2[0],i3[17])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+22, *w20=w+39, *w21=w+42, *w22=w+55;
  casadi_real *w24=w+67, *w25=w+70, *w26=w+74;
  const casadi_real *cs, *ct, *wr23;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[3][0] */
  w02 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w03 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w04 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w05 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w06 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w07 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w08 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w09 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = input[3][16] */
  w18 = arg[3] ? arg[3][16] : 0;
  /* #19: @19 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #20: @20 = @19[:3] */
  for (rr=w20, cs=w19+0; cs!=w19+3; cs+=1) *rr++ = *cs;
  /* #21: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #22: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #23: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #24: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #25: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #26: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #27: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #28: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #29: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #30: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #31: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #32: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #33: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #34: @21 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w21;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #35: @22 = @21[:3] */
  for (rr=w22, cs=w21+0; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #36: @20 = (@20-@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #37: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #38: @23 = 
  [[35, 0, 0], 
   [0, 35, 0], 
   [0, 0, 40]] */
  wr23 = casadi_c0;
  /* #39: @24 = mac(@22,@23,@1) */
  casadi_copy(w01, 3, w24);
  for (i=0, rr=w24; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=wr23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #40: @2 = mac(@24,@20,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w24+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #41: @24 = @19[3:6] */
  for (rr=w24, cs=w19+3; cs!=w19+6; cs+=1) *rr++ = *cs;
  /* #42: @20 = @21[3:6] */
  for (rr=w20, cs=w21+3; cs!=w21+6; cs+=1) *rr++ = *cs;
  /* #43: @24 = (@24-@20) */
  for (i=0, rr=w24, cs=w20; i<3; ++i) (*rr++) -= (*cs++);
  /* #44: @20 = @24' */
  casadi_copy(w24, 3, w20);
  /* #45: @23 = 
  [[6, 0, 0], 
   [0, 6, 0], 
   [0, 0, 6]] */
  wr23 = casadi_c1;
  /* #46: @22 = mac(@20,@23,@1) */
  casadi_copy(w01, 3, w22);
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w20+j, ct=wr23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #47: @3 = mac(@22,@24,@0) */
  casadi_copy((&w00), 1, (&w03));
  for (i=0, rr=(&w03); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w24+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #48: @2 = (@2+@3) */
  w02 += w03;
  /* #49: @9 = (-@9) */
  w09 = (- w09 );
  /* #50: @10 = (-@10) */
  w10 = (- w10 );
  /* #51: @11 = (-@11) */
  w11 = (- w11 );
  /* #52: @25 = vertcat(@8, @9, @10, @11) */
  rr=w25;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  /* #53: @26 = @21[6:10] */
  for (rr=w26, cs=w21+6; cs!=w21+10; cs+=1) *rr++ = *cs;
  /* #54: @8 = ||@26||_F */
  w08 = casadi_norm_2(4, w26);
  /* #55: @25 = (@25/@8) */
  for (i=0, rr=w25; i<4; ++i) (*rr++) /= w08;
  /* #56: {@8, @9, @10, @11} = vertsplit(@25) */
  w08 = w25[0];
  w09 = w25[1];
  w10 = w25[2];
  w11 = w25[3];
  /* #57: @25 = @19[6:10] */
  for (rr=w25, cs=w19+6; cs!=w19+10; cs+=1) *rr++ = *cs;
  /* #58: {@3, @4, @5, @6} = vertsplit(@25) */
  w03 = w25[0];
  w04 = w25[1];
  w05 = w25[2];
  w06 = w25[3];
  /* #59: @7 = (@8*@3) */
  w07  = (w08*w03);
  /* #60: @12 = (@9*@4) */
  w12  = (w09*w04);
  /* #61: @7 = (@7-@12) */
  w07 -= w12;
  /* #62: @12 = (@10*@5) */
  w12  = (w10*w05);
  /* #63: @7 = (@7-@12) */
  w07 -= w12;
  /* #64: @12 = (@11*@6) */
  w12  = (w11*w06);
  /* #65: @7 = (@7-@12) */
  w07 -= w12;
  /* #66: @12 = (@7<@0) */
  w12  = (w07<w00);
  /* #67: @13 = (@8*@4) */
  w13  = (w08*w04);
  /* #68: @14 = (@9*@3) */
  w14  = (w09*w03);
  /* #69: @13 = (@13+@14) */
  w13 += w14;
  /* #70: @14 = (@10*@6) */
  w14  = (w10*w06);
  /* #71: @13 = (@13+@14) */
  w13 += w14;
  /* #72: @14 = (@11*@5) */
  w14  = (w11*w05);
  /* #73: @13 = (@13-@14) */
  w13 -= w14;
  /* #74: @14 = (@8*@5) */
  w14  = (w08*w05);
  /* #75: @15 = (@9*@6) */
  w15  = (w09*w06);
  /* #76: @14 = (@14-@15) */
  w14 -= w15;
  /* #77: @15 = (@10*@3) */
  w15  = (w10*w03);
  /* #78: @14 = (@14+@15) */
  w14 += w15;
  /* #79: @15 = (@11*@4) */
  w15  = (w11*w04);
  /* #80: @14 = (@14+@15) */
  w14 += w15;
  /* #81: @8 = (@8*@6) */
  w08 *= w06;
  /* #82: @9 = (@9*@5) */
  w09 *= w05;
  /* #83: @8 = (@8+@9) */
  w08 += w09;
  /* #84: @10 = (@10*@4) */
  w10 *= w04;
  /* #85: @8 = (@8-@10) */
  w08 -= w10;
  /* #86: @11 = (@11*@3) */
  w11 *= w03;
  /* #87: @8 = (@8+@11) */
  w08 += w11;
  /* #88: @25 = vertcat(@7, @13, @14, @8) */
  rr=w25;
  *rr++ = w07;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w08;
  /* #89: @26 = (-@25) */
  for (i=0, rr=w26, cs=w25; i<4; ++i) *rr++ = (- *cs++ );
  /* #90: @26 = (@12?@26:0) */
  for (i=0, rr=w26, cs=w26; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #91: @12 = (!@12) */
  w12 = (! w12 );
  /* #92: @25 = (@12?@25:0) */
  for (i=0, rr=w25, cs=w25; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #93: @26 = (@26+@25) */
  for (i=0, rr=w26, cs=w25; i<4; ++i) (*rr++) += (*cs++);
  /* #94: @22 = @26[1:4] */
  for (rr=w22, cs=w26+1; cs!=w26+4; cs+=1) *rr++ = *cs;
  /* #95: @24 = (2.*@22) */
  for (i=0, rr=w24, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #96: @12 = ||@22||_F */
  w12 = casadi_norm_2(3, w22);
  /* #97: @7 = @26[0] */
  for (rr=(&w07), cs=w26+0; cs!=w26+1; cs+=1) *rr++ = *cs;
  /* #98: @7 = atan2(@12,@7) */
  w07  = atan2(w12,w07);
  /* #99: @24 = (@24*@7) */
  for (i=0, rr=w24; i<3; ++i) (*rr++) *= w07;
  /* #100: @7 = 1e-09 */
  w07 = 1.0000000000000001e-09;
  /* #101: @7 = (@7+@12) */
  w07 += w12;
  /* #102: @24 = (@24/@7) */
  for (i=0, rr=w24; i<3; ++i) (*rr++) /= w07;
  /* #103: @22 = @24' */
  casadi_copy(w24, 3, w22);
  /* #104: @23 = 
  [[15, 0, 0], 
   [0, 15, 0], 
   [0, 0, 15]] */
  wr23 = casadi_c2;
  /* #105: @20 = mac(@22,@23,@1) */
  casadi_copy(w01, 3, w20);
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=wr23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #106: @7 = mac(@20,@24,@0) */
  casadi_copy((&w00), 1, (&w07));
  for (i=0, rr=(&w07); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w20+j, ct=w24+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #107: @2 = (@2+@7) */
  w02 += w07;
  /* #108: @20 = @19[10:13] */
  for (rr=w20, cs=w19+10; cs!=w19+13; cs+=1) *rr++ = *cs;
  /* #109: @24 = @21[10:13] */
  for (rr=w24, cs=w21+10; cs!=w21+13; cs+=1) *rr++ = *cs;
  /* #110: @20 = (@20-@24) */
  for (i=0, rr=w20, cs=w24; i<3; ++i) (*rr++) -= (*cs++);
  /* #111: @24 = @20' */
  casadi_copy(w20, 3, w24);
  /* #112: @23 = 
  [[0.5, 0, 0], 
   [0, 0.5, 0], 
   [0, 0, 0.5]] */
  wr23 = casadi_c3;
  /* #113: @1 = mac(@24,@23,@1) */
  for (i=0, rr=w01; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w24+j, ct=wr23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #114: @0 = mac(@1,@20,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w01+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #115: @2 = (@2+@0) */
  w02 += w00;
  /* #116: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_gate_tracker_cost_ext_cost_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_gate_tracker_cost_ext_cost_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_gate_tracker_cost_ext_cost_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_gate_tracker_cost_ext_cost_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_gate_tracker_cost_ext_cost_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_gate_tracker_cost_ext_cost_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_gate_tracker_cost_ext_cost_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_gate_tracker_cost_ext_cost_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_gate_tracker_cost_ext_cost_e_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_gate_tracker_cost_ext_cost_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_gate_tracker_cost_ext_cost_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_gate_tracker_cost_ext_cost_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_gate_tracker_cost_ext_cost_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_gate_tracker_cost_ext_cost_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_gate_tracker_cost_ext_cost_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_gate_tracker_cost_ext_cost_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 78;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_gate_tracker_cost_ext_cost_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 78*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
