/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_wargame_evader_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[14] = 
  {23, 1, 0, 10, 0, 1, 2, 3,
  4, 5, 6, 17, 18, 19};
static const casadi_int casadi_s1[3] = {19, 1, 1};
static const casadi_int casadi_s2[3] = {4, 1, 1};
static const casadi_int casadi_s3[3] = {0, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {23, 1, 1};

static const casadi_real casadi_c0[16] = 
  {5.0000000000000000e-01, 0., 0., 0., 0., 5.0000000000000000e-01, 0., 0.,
  0., 0., 5.0000000000000000e-01, 0., 0., 0., 0., 5.0000000000000000e-01};

/* Drone_wargame_evader_cost_ext_cost_fun_jac:(i0[19],i1[4],i2[0],i3[0])->(o0,o1[23]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, w02, w03, w04, *w05=w+6, *w06=w+9, *w07=w+12, w08, w09, *w10=w+18;
  casadi_real *w11=w+22, *w13=w+42, *w14=w+46, w16, w17, w18, *w19=w+65, *w20=w+75;
  const casadi_real *cs, *ct, *wr12;
  /* #0: @0 = -20 */
  w00 = -20.;
  /* #1: @1 = 0 */
  w01 = 0.;
  /* #2: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #4: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #5: @5 = vertcat(@2, @3, @4) */
  rr=w05;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  /* #6: @2 = input[0][13] */
  w02 = arg[0] ? arg[0][13] : 0;
  /* #7: @3 = input[0][14] */
  w03 = arg[0] ? arg[0][14] : 0;
  /* #8: @4 = input[0][15] */
  w04 = arg[0] ? arg[0][15] : 0;
  /* #9: @6 = vertcat(@2, @3, @4) */
  rr=w06;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  /* #10: @5 = (@5-@6) */
  for (i=0, rr=w05, cs=w06; i<3; ++i) (*rr++) -= (*cs++);
  /* #11: @6 = @5' */
  casadi_copy(w05, 3, w06);
  /* #12: @2 = mac(@6,@5,@1) */
  casadi_copy((&w01), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w06+j, ct=w05+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #13: @3 = 0.25 */
  w03 = 2.5000000000000000e-01;
  /* #14: @2 = (@2-@3) */
  w02 -= w03;
  /* #15: @2 = (@0*@2) */
  w02  = (w00*w02);
  /* #16: @7 = zeros(1x4) */
  casadi_clear(w07, 4);
  /* #17: @3 = input[1][0] */
  w03 = arg[1] ? arg[1][0] : 0;
  /* #18: @4 = input[1][1] */
  w04 = arg[1] ? arg[1][1] : 0;
  /* #19: @8 = input[1][2] */
  w08 = arg[1] ? arg[1][2] : 0;
  /* #20: @9 = input[1][3] */
  w09 = arg[1] ? arg[1][3] : 0;
  /* #21: @10 = vertcat(@3, @4, @8, @9) */
  rr=w10;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w08;
  *rr++ = w09;
  /* #22: @11 = @10' */
  casadi_copy(w10, 4, w11);
  /* #23: @12 = 
  [[0.5, 0, 0, 0], 
   [0, 0.5, 0, 0], 
   [0, 0, 0.5, 0], 
   [0, 0, 0, 0.5]] */
  wr12 = casadi_c0;
  /* #24: @13 = mac(@11,@12,@7) */
  casadi_copy(w07, 4, w13);
  for (i=0, rr=w13; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w11+j, ct=wr12+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #25: @1 = mac(@13,@10,@1) */
  for (i=0, rr=(&w01); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w13+j, ct=w10+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #26: @2 = (@2+@1) */
  w02 += w01;
  /* #27: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #28: @13 = @13' */
  /* #29: @14 = @12' */
  for (i=0, rr=w14, cs=wr12; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #30: @7 = mac(@11,@14,@7) */
  for (i=0, rr=w07; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w11+j, ct=w14+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #31: @7 = @7' */
  /* #32: @13 = (@13+@7) */
  for (i=0, rr=w13, cs=w07; i<4; ++i) (*rr++) += (*cs++);
  /* #33: {@2, @1, @3, @4} = vertsplit(@13) */
  w02 = w13[0];
  w01 = w13[1];
  w03 = w13[2];
  w04 = w13[3];
  /* #34: @5 = (@0*@5) */
  for (i=0, rr=w05, cs=w05; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #35: @6 = (@0*@6) */
  for (i=0, rr=w06, cs=w06; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #36: @6 = @6' */
  /* #37: @5 = (@5+@6) */
  for (i=0, rr=w05, cs=w06; i<3; ++i) (*rr++) += (*cs++);
  /* #38: {@0, @8, @9} = vertsplit(@5) */
  w00 = w05[0];
  w08 = w05[1];
  w09 = w05[2];
  /* #39: @15 = 00 */
  /* #40: @5 = (-@5) */
  for (i=0, rr=w05, cs=w05; i<3; ++i) *rr++ = (- *cs++ );
  /* #41: {@16, @17, @18} = vertsplit(@5) */
  w16 = w05[0];
  w17 = w05[1];
  w18 = w05[2];
  /* #42: @19 = vertcat(@2, @1, @3, @4, @0, @8, @9, @15, @15, @15, @15, @15, @15, @15, @15, @15, @15, @16, @17, @18, @15, @15, @15) */
  rr=w19;
  *rr++ = w02;
  *rr++ = w01;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w00;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #43: @20 = dense(@19) */
  casadi_densify(w19, casadi_s0, w20, 0);
  /* #44: output[1][0] = @20 */
  casadi_copy(w20, 23, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_wargame_evader_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_wargame_evader_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_wargame_evader_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_wargame_evader_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_wargame_evader_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_wargame_evader_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_wargame_evader_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_wargame_evader_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_wargame_evader_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_wargame_evader_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Drone_wargame_evader_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_wargame_evader_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_wargame_evader_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_wargame_evader_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_wargame_evader_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_wargame_evader_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 27;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 98;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_wargame_evader_cost_ext_cost_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 27*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 6*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 98*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
