/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_wargame_evader_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[14] = 
  {23, 1, 0, 10, 0, 1, 2, 3,
  4, 5, 6, 17, 18, 19};
static const casadi_int casadi_s1[11] = 
  {1, 4, 0, 1, 2, 3, 4, 0,
  0, 0, 0};
static const casadi_int casadi_s2[23] = 
  {4, 4, 0, 4, 8, 12, 16, 0,
  1, 2, 3, 0, 1, 2, 3, 0,
  1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s3[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s4[10] = 
  {0, 1, 2, 3, 16, 18, 20, 17,
  19, 21};
static const casadi_int casadi_s5[10] = 
  {0, 4, 8, 12, 16, 18, 20, 22,
  24, 26};
static const casadi_int casadi_s6[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s7[10] = 
  {4, 5, 6, 7, 22, 24, 26, 23,
  25, 27};
static const casadi_int casadi_s8[10] = 
  {1, 5, 9, 13, 17, 19, 21, 23,
  25, 27};
static const casadi_int casadi_s9[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s10[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s11[54] = 
  {23, 23, 0, 4, 8, 12, 16, 18,
  20, 22, 22, 22, 22, 22, 22, 22,
  22, 22, 22, 22, 24, 26, 28, 28,
  28, 28, 0, 1, 2, 3, 0, 1,
  2, 3, 0, 1, 2, 3, 0, 1,
  2, 3, 4, 17, 5, 18, 6, 19,
  4, 17, 5, 18, 6, 19};
static const casadi_int casadi_s12[3] = {19, 1, 1};
static const casadi_int casadi_s13[3] = {4, 1, 1};
static const casadi_int casadi_s14[3] = {0, 1, 1};
static const casadi_int casadi_s15[3] = {1, 1, 1};
static const casadi_int casadi_s16[3] = {23, 1, 1};
static const casadi_int casadi_s17[3] = {0, 0, 1};
static const casadi_int casadi_s18[3] = {0, 23, 1};

static const casadi_real casadi_c0[16] = 
  {5.0000000000000000e-01, 0., 0., 0., 0., 5.0000000000000000e-01, 0., 0.,
  0., 0., 5.0000000000000000e-01, 0., 0., 0., 0., 5.0000000000000000e-01};

/* Drone_wargame_evader_cost_ext_cost_fun_jac_hess:(i0[19],i1[4],i2[0],i3[0])->(o0,o1[23],o2[23x23,28nz],o3[],o4[0x23]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, w02, w03, w04, *w05=w+6, *w06=w+9, *w07=w+12, w08, w09, *w10=w+18;
  casadi_real *w11=w+22, *w13=w+42, *w14=w+46, w15, w17, w18, w19, *w20=w+66, *w21=w+76, *w22=w+99, *w23=w+127, *w24=w+144;
  casadi_real *w25=w+154;
  const casadi_int *cii;
  const casadi_real *cs, *ct, *wr12;
  /* #0: @0 = -20 */
  w00 = -20.;
  /* #1: @1 = 0 */
  w01 = 0.;
  /* #2: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #4: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #5: @5 = vertcat(@2, @3, @4) */
  rr=w05;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  /* #6: @2 = input[0][13] */
  w02 = arg[0] ? arg[0][13] : 0;
  /* #7: @3 = input[0][14] */
  w03 = arg[0] ? arg[0][14] : 0;
  /* #8: @4 = input[0][15] */
  w04 = arg[0] ? arg[0][15] : 0;
  /* #9: @6 = vertcat(@2, @3, @4) */
  rr=w06;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  /* #10: @5 = (@5-@6) */
  for (i=0, rr=w05, cs=w06; i<3; ++i) (*rr++) -= (*cs++);
  /* #11: @6 = @5' */
  casadi_copy(w05, 3, w06);
  /* #12: @2 = mac(@6,@5,@1) */
  casadi_copy((&w01), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w06+j, ct=w05+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #13: @3 = 0.25 */
  w03 = 2.5000000000000000e-01;
  /* #14: @2 = (@2-@3) */
  w02 -= w03;
  /* #15: @2 = (@0*@2) */
  w02  = (w00*w02);
  /* #16: @7 = zeros(1x4) */
  casadi_clear(w07, 4);
  /* #17: @3 = input[1][0] */
  w03 = arg[1] ? arg[1][0] : 0;
  /* #18: @4 = input[1][1] */
  w04 = arg[1] ? arg[1][1] : 0;
  /* #19: @8 = input[1][2] */
  w08 = arg[1] ? arg[1][2] : 0;
  /* #20: @9 = input[1][3] */
  w09 = arg[1] ? arg[1][3] : 0;
  /* #21: @10 = vertcat(@3, @4, @8, @9) */
  rr=w10;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w08;
  *rr++ = w09;
  /* #22: @11 = @10' */
  casadi_copy(w10, 4, w11);
  /* #23: @12 = 
  [[0.5, 0, 0, 0], 
   [0, 0.5, 0, 0], 
   [0, 0, 0.5, 0], 
   [0, 0, 0, 0.5]] */
  wr12 = casadi_c0;
  /* #24: @13 = mac(@11,@12,@7) */
  casadi_copy(w07, 4, w13);
  for (i=0, rr=w13; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w11+j, ct=wr12+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #25: @1 = mac(@13,@10,@1) */
  for (i=0, rr=(&w01); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w13+j, ct=w10+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #26: @2 = (@2+@1) */
  w02 += w01;
  /* #27: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #28: @13 = @13' */
  /* #29: @14 = @12' */
  for (i=0, rr=w14, cs=wr12; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #30: @10 = mac(@11,@14,@7) */
  casadi_copy(w07, 4, w10);
  for (i=0, rr=w10; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w11+j, ct=w14+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #31: @10 = @10' */
  /* #32: @13 = (@13+@10) */
  for (i=0, rr=w13, cs=w10; i<4; ++i) (*rr++) += (*cs++);
  /* #33: {@2, @1, @3, @4} = vertsplit(@13) */
  w02 = w13[0];
  w01 = w13[1];
  w03 = w13[2];
  w04 = w13[3];
  /* #34: @5 = (@0*@5) */
  for (i=0, rr=w05, cs=w05; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #35: @6 = (@0*@6) */
  for (i=0, rr=w06, cs=w06; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #36: @6 = @6' */
  /* #37: @5 = (@5+@6) */
  for (i=0, rr=w05, cs=w06; i<3; ++i) (*rr++) += (*cs++);
  /* #38: {@8, @9, @15} = vertsplit(@5) */
  w08 = w05[0];
  w09 = w05[1];
  w15 = w05[2];
  /* #39: @16 = 00 */
  /* #40: @5 = (-@5) */
  for (i=0, rr=w05, cs=w05; i<3; ++i) *rr++ = (- *cs++ );
  /* #41: {@17, @18, @19} = vertsplit(@5) */
  w17 = w05[0];
  w18 = w05[1];
  w19 = w05[2];
  /* #42: @20 = vertcat(@2, @1, @3, @4, @8, @9, @15, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16, @17, @18, @19, @16, @16, @16) */
  rr=w20;
  *rr++ = w02;
  *rr++ = w01;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w15;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  /* #43: @21 = dense(@20) */
  casadi_densify(w20, casadi_s0, w21, 0);
  /* #44: output[1][0] = @21 */
  casadi_copy(w21, 23, res[1]);
  /* #45: @22 = zeros(23x23,28nz) */
  casadi_clear(w22, 28);
  /* #46: @23 = ones(23x1,17nz) */
  casadi_fill(w23, 17, 1.);
  /* #47: {@2, NULL, NULL, NULL, @1, @3, @4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@23) */
  w02 = w23[0];
  w01 = w23[1];
  w03 = w23[2];
  w04 = w23[3];
  /* #48: @8 = vertcat(@2, @16, @16, @16) */
  rr=(&w08);
  *rr++ = w02;
  /* #49: @8 = @8' */
  /* #50: @13 = mac(@8,@12,@7) */
  casadi_copy(w07, 4, w13);
  casadi_mtimes((&w08), casadi_s3, wr12, casadi_s2, w13, casadi_s1, w, 0);
  /* #51: @13 = @13' */
  /* #52: @10 = mac(@8,@14,@7) */
  casadi_copy(w07, 4, w10);
  casadi_mtimes((&w08), casadi_s3, w14, casadi_s2, w10, casadi_s1, w, 0);
  /* #53: @10 = @10' */
  /* #54: @13 = (@13+@10) */
  for (i=0, rr=w13, cs=w10; i<4; ++i) (*rr++) += (*cs++);
  /* #55: {@8, @2, @9, @15} = vertsplit(@13) */
  w08 = w13[0];
  w02 = w13[1];
  w09 = w13[2];
  w15 = w13[3];
  /* #56: @5 = vertcat(@1, @3, @4) */
  rr=w05;
  *rr++ = w01;
  *rr++ = w03;
  *rr++ = w04;
  /* #57: @6 = (@0*@5) */
  for (i=0, rr=w06, cs=w05; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #58: @5 = @5' */
  /* #59: @5 = (@0*@5) */
  for (i=0, rr=w05, cs=w05; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #60: @5 = @5' */
  /* #61: @6 = (@6+@5) */
  for (i=0, rr=w06, cs=w05; i<3; ++i) (*rr++) += (*cs++);
  /* #62: {@1, @3, @4} = vertsplit(@6) */
  w01 = w06[0];
  w03 = w06[1];
  w04 = w06[2];
  /* #63: @6 = (-@6) */
  for (i=0, rr=w06, cs=w06; i<3; ++i) *rr++ = (- *cs++ );
  /* #64: {@17, @18, @19} = vertsplit(@6) */
  w17 = w06[0];
  w18 = w06[1];
  w19 = w06[2];
  /* #65: @20 = vertcat(@8, @2, @9, @15, @1, @3, @4, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16, @17, @18, @19, @16, @16, @16) */
  rr=w20;
  *rr++ = w08;
  *rr++ = w02;
  *rr++ = w09;
  *rr++ = w15;
  *rr++ = w01;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  /* #66: @24 = @20[:10] */
  for (rr=w24, cs=w20+0; cs!=w20+10; cs+=1) *rr++ = *cs;
  /* #67: (@22[0, 1, 2, 3, 16, 18, 20, 17, 19, 21] = @24) */
  for (cii=casadi_s4, rr=w22, cs=w24; cii!=casadi_s4+10; ++cii, ++cs) rr[*cii] = *cs;
  /* #68: (@22[0, 4, 8, 12, 16, 18, 20, 22, 24, 26] = @24) */
  for (cii=casadi_s5, rr=w22, cs=w24; cii!=casadi_s5+10; ++cii, ++cs) rr[*cii] = *cs;
  /* #69: @13 = ones(23x1,4nz) */
  casadi_fill(w13, 4, 1.);
  /* #70: {NULL, @8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @2, @9, @15, NULL, NULL, NULL} = vertsplit(@13) */
  w08 = w13[0];
  w02 = w13[1];
  w09 = w13[2];
  w15 = w13[3];
  /* #71: @1 = vertcat(@16, @8, @16, @16) */
  rr=(&w01);
  *rr++ = w08;
  /* #72: @1 = @1' */
  /* #73: @13 = mac(@1,@12,@7) */
  casadi_copy(w07, 4, w13);
  casadi_mtimes((&w01), casadi_s6, wr12, casadi_s2, w13, casadi_s1, w, 0);
  /* #74: @13 = @13' */
  /* #75: @10 = mac(@1,@14,@7) */
  casadi_copy(w07, 4, w10);
  casadi_mtimes((&w01), casadi_s6, w14, casadi_s2, w10, casadi_s1, w, 0);
  /* #76: @10 = @10' */
  /* #77: @13 = (@13+@10) */
  for (i=0, rr=w13, cs=w10; i<4; ++i) (*rr++) += (*cs++);
  /* #78: {@1, @8, @3, @4} = vertsplit(@13) */
  w01 = w13[0];
  w08 = w13[1];
  w03 = w13[2];
  w04 = w13[3];
  /* #79: @6 = vertcat(@2, @9, @15) */
  rr=w06;
  *rr++ = w02;
  *rr++ = w09;
  *rr++ = w15;
  /* #80: @5 = (-@6) */
  for (i=0, rr=w05, cs=w06; i<3; ++i) *rr++ = (- *cs++ );
  /* #81: @5 = @5' */
  /* #82: @5 = (@0*@5) */
  for (i=0, rr=w05, cs=w05; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #83: @5 = @5' */
  /* #84: @6 = (@0*@6) */
  for (i=0, rr=w06, cs=w06; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #85: @5 = (@5-@6) */
  for (i=0, rr=w05, cs=w06; i<3; ++i) (*rr++) -= (*cs++);
  /* #86: {@0, @2, @9} = vertsplit(@5) */
  w00 = w05[0];
  w02 = w05[1];
  w09 = w05[2];
  /* #87: @5 = (-@5) */
  for (i=0, rr=w05, cs=w05; i<3; ++i) *rr++ = (- *cs++ );
  /* #88: {@15, @17, @18} = vertsplit(@5) */
  w15 = w05[0];
  w17 = w05[1];
  w18 = w05[2];
  /* #89: @24 = vertcat(@1, @8, @3, @4, @0, @2, @9, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16, @15, @17, @18, @16, @16, @16) */
  rr=w24;
  *rr++ = w01;
  *rr++ = w08;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w00;
  *rr++ = w02;
  *rr++ = w09;
  *rr++ = w15;
  *rr++ = w17;
  *rr++ = w18;
  /* #90: @20 = @24[:10] */
  for (rr=w20, cs=w24+0; cs!=w24+10; cs+=1) *rr++ = *cs;
  /* #91: (@22[4, 5, 6, 7, 22, 24, 26, 23, 25, 27] = @20) */
  for (cii=casadi_s7, rr=w22, cs=w20; cii!=casadi_s7+10; ++cii, ++cs) rr[*cii] = *cs;
  /* #92: (@22[1, 5, 9, 13, 17, 19, 21, 23, 25, 27] = @20) */
  for (cii=casadi_s8, rr=w22, cs=w20; cii!=casadi_s8+10; ++cii, ++cs) rr[*cii] = *cs;
  /* #93: @1 = ones(23x1,1nz) */
  w01 = 1.;
  /* #94: {NULL, NULL, @8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@1) */
  w08 = w01;
  /* #95: @1 = vertcat(@16, @16, @8, @16) */
  rr=(&w01);
  *rr++ = w08;
  /* #96: @1 = @1' */
  /* #97: @13 = mac(@1,@12,@7) */
  casadi_copy(w07, 4, w13);
  casadi_mtimes((&w01), casadi_s9, wr12, casadi_s2, w13, casadi_s1, w, 0);
  /* #98: @13 = @13' */
  /* #99: @10 = mac(@1,@14,@7) */
  casadi_copy(w07, 4, w10);
  casadi_mtimes((&w01), casadi_s9, w14, casadi_s2, w10, casadi_s1, w, 0);
  /* #100: @10 = @10' */
  /* #101: @13 = (@13+@10) */
  for (i=0, rr=w13, cs=w10; i<4; ++i) (*rr++) += (*cs++);
  /* #102: {@1, @8, @3, @4} = vertsplit(@13) */
  w01 = w13[0];
  w08 = w13[1];
  w03 = w13[2];
  w04 = w13[3];
  /* #103: @13 = vertcat(@1, @8, @3, @4, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16) */
  rr=w13;
  *rr++ = w01;
  *rr++ = w08;
  *rr++ = w03;
  *rr++ = w04;
  /* #104: @10 = @13[:4] */
  for (rr=w10, cs=w13+0; cs!=w13+4; cs+=1) *rr++ = *cs;
  /* #105: (@22[8:12] = @10) */
  for (rr=w22+8, cs=w10; rr!=w22+12; rr+=1) *rr = *cs++;
  /* #106: (@22[2:18:4] = @10) */
  for (rr=w22+2, cs=w10; rr!=w22+18; rr+=4) *rr = *cs++;
  /* #107: @1 = ones(23x1,1nz) */
  w01 = 1.;
  /* #108: {NULL, NULL, NULL, @8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@1) */
  w08 = w01;
  /* #109: @1 = vertcat(@16, @16, @16, @8) */
  rr=(&w01);
  *rr++ = w08;
  /* #110: @1 = @1' */
  /* #111: @10 = mac(@1,@12,@7) */
  casadi_copy(w07, 4, w10);
  casadi_mtimes((&w01), casadi_s10, wr12, casadi_s2, w10, casadi_s1, w, 0);
  /* #112: @10 = @10' */
  /* #113: @7 = mac(@1,@14,@7) */
  casadi_mtimes((&w01), casadi_s10, w14, casadi_s2, w07, casadi_s1, w, 0);
  /* #114: @7 = @7' */
  /* #115: @10 = (@10+@7) */
  for (i=0, rr=w10, cs=w07; i<4; ++i) (*rr++) += (*cs++);
  /* #116: {@1, @8, @3, @4} = vertsplit(@10) */
  w01 = w10[0];
  w08 = w10[1];
  w03 = w10[2];
  w04 = w10[3];
  /* #117: @10 = vertcat(@1, @8, @3, @4, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16, @16) */
  rr=w10;
  *rr++ = w01;
  *rr++ = w08;
  *rr++ = w03;
  *rr++ = w04;
  /* #118: @7 = @10[:4] */
  for (rr=w07, cs=w10+0; cs!=w10+4; cs+=1) *rr++ = *cs;
  /* #119: (@22[12:16] = @7) */
  for (rr=w22+12, cs=w07; rr!=w22+16; rr+=1) *rr = *cs++;
  /* #120: (@22[3:19:4] = @7) */
  for (rr=w22+3, cs=w07; rr!=w22+19; rr+=4) *rr = *cs++;
  /* #121: @25 = @22' */
  casadi_trans(w22,casadi_s11, w25, casadi_s11, iw);
  /* #122: output[2][0] = @25 */
  casadi_copy(w25, 28, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_wargame_evader_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_wargame_evader_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_wargame_evader_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_wargame_evader_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_wargame_evader_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_wargame_evader_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_wargame_evader_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_wargame_evader_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_wargame_evader_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_wargame_evader_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_wargame_evader_cost_ext_cost_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_wargame_evader_cost_ext_cost_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_wargame_evader_cost_ext_cost_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_wargame_evader_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s12;
    case 1: return casadi_s13;
    case 2: return casadi_s14;
    case 3: return casadi_s14;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_wargame_evader_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s15;
    case 1: return casadi_s16;
    case 2: return casadi_s11;
    case 3: return casadi_s17;
    case 4: return casadi_s18;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_wargame_evader_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 27;
  if (sz_res) *sz_res = 28;
  if (sz_iw) *sz_iw = 24;
  if (sz_w) *sz_w = 182;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_wargame_evader_cost_ext_cost_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 27*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 28*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 24*sizeof(casadi_int);
  if (sz_w) *sz_w = 182*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
