/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {17, 1, 1};
static const casadi_int casadi_s3[18] = 
  {17, 1, 0, 14, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 13, 14,
  15, 16};

static const casadi_real casadi_c0[9] = 
  {3.0558700000000000e-03, 0., 0., 0., 1.5969500000000000e-03, 0., 0., 0.,
  1.5968700000000000e-03};
static const casadi_real casadi_c1[3] = {3.2723905139943781e+02, 6.2619368170575160e+02, 6.2622505275946071e+02};
static const casadi_real casadi_c2[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};

static const casadi_real casadi_zeros[13] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0.};

/* Drone_ode_complete_expl_vde_adj:(i0[13],i1[13],i2[4],i3[17])->(o0[17x1,14nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w01, w02, w03, *w05=w+22, *w06=w+26, w07, w08, w09, w10, w11, w12;
  casadi_real *w13=w+35, w14, w15, w16, *w17=w+47, w18, *w19=w+52, w20, w21, *w22=w+58, w23, *w24=w+68;
  casadi_real *w25=w+71, *w26=w+80, *w27=w+89, *w28=w+98, *w29=w+107, *w30=w+116, w31, *w32=w+121, *w33=w+124, w34, w35, w36;
  casadi_real *w37=w+130;
  const casadi_real *cr, *cs, *ct, *wr00, *wr04, *wr05, *wr06, *wr26, *wr28;
  /* #0: @0 = input[1][0] */
  wr00 = arg[1] ? arg[1] : casadi_zeros;
  /* #1: {@1, @2, @3, @4, @5, @6} = vertsplit(@0) */
  w01 = wr00[0];
  w02 = wr00[1];
  w03 = wr00[2];
  wr04 = wr00+3;
  wr05 = wr00+6;
  wr06 = wr00+10;
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #3: output[0][1] = @2 */
  if (res[0]) res[0][1] = w02;
  /* #4: output[0][2] = @3 */
  if (res[0]) res[0][2] = w03;
  /* #5: @3 = input[0][12] */
  w03 = arg[0] ? arg[0][12] : 0;
  /* #6: @2 = 0.5 */
  w02 = 5.0000000000000000e-01;
  /* #7: @5 = (@2*@5) */
  for (i=0, rr=w05, cs=wr05; i<4; ++i) (*rr++)  = (w02*(*cs++));
  /* #8: {@2, @1, @7, @8} = vertsplit(@5) */
  w02 = w05[0];
  w01 = w05[1];
  w07 = w05[2];
  w08 = w05[3];
  /* #9: @9 = (@3*@8) */
  w09  = (w03*w08);
  /* #10: @10 = input[0][11] */
  w10 = arg[0] ? arg[0][11] : 0;
  /* #11: @11 = (@10*@7) */
  w11  = (w10*w07);
  /* #12: @9 = (@9+@11) */
  w09 += w11;
  /* #13: @11 = input[0][10] */
  w11 = arg[0] ? arg[0][10] : 0;
  /* #14: @12 = (@11*@1) */
  w12  = (w11*w01);
  /* #15: @9 = (@9+@12) */
  w09 += w12;
  /* #16: @5 = zeros(4x1) */
  casadi_clear(w05, 4);
  /* #17: @13 = zeros(3x3) */
  casadi_clear(w13, 9);
  /* #18: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #19: @14 = input[0][7] */
  w14 = arg[0] ? arg[0][7] : 0;
  /* #20: @15 = input[0][8] */
  w15 = arg[0] ? arg[0][8] : 0;
  /* #21: @16 = input[0][9] */
  w16 = arg[0] ? arg[0][9] : 0;
  /* #22: @17 = vertcat(@12, @14, @15, @16) */
  rr=w17;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #23: @18 = ||@17||_F */
  w18 = casadi_norm_2(4, w17);
  /* #24: @19 = (@17/@18) */
  for (i=0, rr=w19, cr=w17; i<4; ++i) (*rr++)  = ((*cr++)/w18);
  /* #25: @20 = @19[3] */
  for (rr=(&w20), cs=w19+3; cs!=w19+4; cs+=1) *rr++ = *cs;
  /* #26: @21 = (-@20) */
  w21 = (- w20 );
  /* #27: @22 = @13; (@22[3] = @21) */
  casadi_copy(w13, 9, w22);
  for (rr=w22+3, cs=(&w21); rr!=w22+4; rr+=1) *rr = *cs++;
  /* #28: @21 = @19[2] */
  for (rr=(&w21), cs=w19+2; cs!=w19+3; cs+=1) *rr++ = *cs;
  /* #29: (@22[6] = @21) */
  for (rr=w22+6, cs=(&w21); rr!=w22+7; rr+=1) *rr = *cs++;
  /* #30: (@22[1] = @20) */
  for (rr=w22+1, cs=(&w20); rr!=w22+2; rr+=1) *rr = *cs++;
  /* #31: @20 = @19[1] */
  for (rr=(&w20), cs=w19+1; cs!=w19+2; cs+=1) *rr++ = *cs;
  /* #32: @23 = (-@20) */
  w23 = (- w20 );
  /* #33: (@22[7] = @23) */
  for (rr=w22+7, cs=(&w23); rr!=w22+8; rr+=1) *rr = *cs++;
  /* #34: @21 = (-@21) */
  w21 = (- w21 );
  /* #35: (@22[2] = @21) */
  for (rr=w22+2, cs=(&w21); rr!=w22+3; rr+=1) *rr = *cs++;
  /* #36: (@22[5] = @20) */
  for (rr=w22+5, cs=(&w20); rr!=w22+6; rr+=1) *rr = *cs++;
  /* #37: @20 = 0 */
  w20 = 0.;
  /* #38: @21 = input[2][0] */
  w21 = arg[2] ? arg[2][0] : 0;
  /* #39: @24 = vertcat(@20, @20, @21) */
  rr=w24;
  *rr++ = w20;
  *rr++ = w20;
  *rr++ = w21;
  /* #40: @24 = @24' */
  /* #41: @25 = mac(@4,@24,@13) */
  casadi_copy(w13, 9, w25);
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr04+j, ct=w24+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #42: @21 = dot(@22, @25) */
  w21 = casadi_dot(9, w22, w25);
  /* #43: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #44: (@5[0] += @21) */
  for (rr=w05+0, cs=(&w21); rr!=w05+1; rr+=1) *rr += *cs++;
  /* #45: @21 = @19[0] */
  for (rr=(&w21), cs=w19+0; cs!=w19+1; cs+=1) *rr++ = *cs;
  /* #46: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #47: @26 = (@21*@25) */
  for (i=0, rr=w26, cs=w25; i<9; ++i) (*rr++)  = (w21*(*cs++));
  /* #48: @27 = (2.*@22) */
  for (i=0, rr=w27, cs=w22; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #49: @28 = @27' */
  for (i=0, rr=w28, cs=w27; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #50: @29 = mac(@28,@25,@13) */
  casadi_copy(w13, 9, w29);
  for (i=0, rr=w29; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w28+j, ct=w25+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #51: @26 = (@26+@29) */
  for (i=0, rr=w26, cs=w29; i<9; ++i) (*rr++) += (*cs++);
  /* #52: @29 = @22' */
  for (i=0, rr=w29, cs=w22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #53: @28 = mac(@25,@29,@13) */
  casadi_copy(w13, 9, w28);
  for (i=0, rr=w28; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w25+j, ct=w29+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #54: @28 = (2.*@28) */
  for (i=0, rr=w28, cs=w28; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #55: @26 = (@26+@28) */
  for (i=0, rr=w26, cs=w28; i<9; ++i) (*rr++) += (*cs++);
  /* #56: @23 = @26[5] */
  for (rr=(&w23), cs=w26+5; cs!=w26+6; cs+=1) *rr++ = *cs;
  /* #57: (@5[1] += @23) */
  for (rr=w05+1, cs=(&w23); rr!=w05+2; rr+=1) *rr += *cs++;
  /* #58: (@26[5] = @20) */
  for (rr=w26+5, cs=(&w20); rr!=w26+6; rr+=1) *rr = *cs++;
  /* #59: @23 = @26[2] */
  for (rr=(&w23), cs=w26+2; cs!=w26+3; cs+=1) *rr++ = *cs;
  /* #60: @23 = (-@23) */
  w23 = (- w23 );
  /* #61: (@5[2] += @23) */
  for (rr=w05+2, cs=(&w23); rr!=w05+3; rr+=1) *rr += *cs++;
  /* #62: (@26[2] = @20) */
  for (rr=w26+2, cs=(&w20); rr!=w26+3; rr+=1) *rr = *cs++;
  /* #63: @23 = @26[7] */
  for (rr=(&w23), cs=w26+7; cs!=w26+8; cs+=1) *rr++ = *cs;
  /* #64: @23 = (-@23) */
  w23 = (- w23 );
  /* #65: (@5[1] += @23) */
  for (rr=w05+1, cs=(&w23); rr!=w05+2; rr+=1) *rr += *cs++;
  /* #66: (@26[7] = @20) */
  for (rr=w26+7, cs=(&w20); rr!=w26+8; rr+=1) *rr = *cs++;
  /* #67: @23 = @26[1] */
  for (rr=(&w23), cs=w26+1; cs!=w26+2; cs+=1) *rr++ = *cs;
  /* #68: (@5[3] += @23) */
  for (rr=w05+3, cs=(&w23); rr!=w05+4; rr+=1) *rr += *cs++;
  /* #69: (@26[1] = @20) */
  for (rr=w26+1, cs=(&w20); rr!=w26+2; rr+=1) *rr = *cs++;
  /* #70: @23 = @26[6] */
  for (rr=(&w23), cs=w26+6; cs!=w26+7; cs+=1) *rr++ = *cs;
  /* #71: (@5[2] += @23) */
  for (rr=w05+2, cs=(&w23); rr!=w05+3; rr+=1) *rr += *cs++;
  /* #72: (@26[6] = @20) */
  for (rr=w26+6, cs=(&w20); rr!=w26+7; rr+=1) *rr = *cs++;
  /* #73: @20 = @26[3] */
  for (rr=(&w20), cs=w26+3; cs!=w26+4; cs+=1) *rr++ = *cs;
  /* #74: @20 = (-@20) */
  w20 = (- w20 );
  /* #75: (@5[3] += @20) */
  for (rr=w05+3, cs=(&w20); rr!=w05+4; rr+=1) *rr += *cs++;
  /* #76: @30 = (@5/@18) */
  for (i=0, rr=w30, cr=w05; i<4; ++i) (*rr++)  = ((*cr++)/w18);
  /* #77: @19 = (@19/@18) */
  for (i=0, rr=w19; i<4; ++i) (*rr++) /= w18;
  /* #78: @19 = (-@19) */
  for (i=0, rr=w19, cs=w19; i<4; ++i) *rr++ = (- *cs++ );
  /* #79: @20 = dot(@19, @5) */
  w20 = casadi_dot(4, w19, w05);
  /* #80: @20 = (@20/@18) */
  w20 /= w18;
  /* #81: @17 = (@20*@17) */
  for (i=0, rr=w17, cs=w17; i<4; ++i) (*rr++)  = (w20*(*cs++));
  /* #82: @30 = (@30+@17) */
  for (i=0, rr=w30, cs=w17; i<4; ++i) (*rr++) += (*cs++);
  /* #83: {@20, @18, @23, @31} = vertsplit(@30) */
  w20 = w30[0];
  w18 = w30[1];
  w23 = w30[2];
  w31 = w30[3];
  /* #84: @9 = (@9+@20) */
  w09 += w20;
  /* #85: output[0][3] = @9 */
  if (res[0]) res[0][3] = w09;
  /* #86: @9 = (@10*@8) */
  w09  = (w10*w08);
  /* #87: @20 = (@3*@7) */
  w20  = (w03*w07);
  /* #88: @9 = (@9-@20) */
  w09 -= w20;
  /* #89: @20 = (@11*@2) */
  w20  = (w11*w02);
  /* #90: @9 = (@9-@20) */
  w09 -= w20;
  /* #91: @9 = (@9+@18) */
  w09 += w18;
  /* #92: output[0][4] = @9 */
  if (res[0]) res[0][4] = w09;
  /* #93: @9 = (@3*@1) */
  w09  = (w03*w01);
  /* #94: @18 = (@11*@8) */
  w18  = (w11*w08);
  /* #95: @9 = (@9-@18) */
  w09 -= w18;
  /* #96: @18 = (@10*@2) */
  w18  = (w10*w02);
  /* #97: @9 = (@9-@18) */
  w09 -= w18;
  /* #98: @9 = (@9+@23) */
  w09 += w23;
  /* #99: output[0][5] = @9 */
  if (res[0]) res[0][5] = w09;
  /* #100: @9 = (@11*@7) */
  w09  = (w11*w07);
  /* #101: @23 = (@10*@1) */
  w23  = (w10*w01);
  /* #102: @9 = (@9-@23) */
  w09 -= w23;
  /* #103: @23 = (@3*@2) */
  w23  = (w03*w02);
  /* #104: @9 = (@9-@23) */
  w09 -= w23;
  /* #105: @9 = (@9+@31) */
  w09 += w31;
  /* #106: output[0][6] = @9 */
  if (res[0]) res[0][6] = w09;
  /* #107: @24 = zeros(3x1) */
  casadi_clear(w24, 3);
  /* #108: @26 = 
  [[0.00305587, 0, 0], 
   [0, 0.00159695, 0], 
   [0, 0, 0.00159687]] */
  wr26 = casadi_c0;
  /* #109: @32 = vertcat(@11, @10, @3) */
  rr=w32;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w03;
  /* #110: @33 = mac(@26,@32,@24) */
  casadi_copy(w24, 3, w33);
  for (i=0, rr=w33; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr26+j, ct=w32+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #111: @9 = @33[1] */
  for (rr=(&w09), cs=w33+1; cs!=w33+2; cs+=1) *rr++ = *cs;
  /* #112: @32 = 
  [[327.239, 00, 00], 
   [00, 626.194, 00], 
   [00, 00, 626.225]] */
  casadi_copy(casadi_c1, 3, w32);
  /* #113: @32 = nonzeros(@32) */
  /* #114: @32 = (@32*@6) */
  for (i=0, rr=w32, cs=wr06; i<3; ++i) (*rr++) *= (*cs++);
  /* #115: @6 = (-@32) */
  for (i=0, rr=w06, cs=w32; i<3; ++i) *rr++ = (- *cs++ );
  /* #116: {@31, @23, @18} = vertsplit(@6) */
  w31 = w06[0];
  w23 = w06[1];
  w18 = w06[2];
  /* #117: @20 = (@9*@18) */
  w20  = (w09*w18);
  /* #118: @34 = @33[2] */
  for (rr=(&w34), cs=w33+2; cs!=w33+3; cs+=1) *rr++ = *cs;
  /* #119: @35 = (@34*@23) */
  w35  = (w34*w23);
  /* #120: @20 = (@20-@35) */
  w20 -= w35;
  /* #121: @28 = @26' */
  for (i=0, rr=w28, cs=wr26; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #122: @35 = (@3*@23) */
  w35  = (w03*w23);
  /* #123: @36 = (@10*@18) */
  w36  = (w10*w18);
  /* #124: @35 = (@35-@36) */
  w35 -= w36;
  /* #125: @6 = @24; (@6[0] += @35) */
  casadi_copy(w24, 3, w06);
  for (rr=w06+0, cs=(&w35); rr!=w06+1; rr+=1) *rr += *cs++;
  /* #126: @35 = (@11*@18) */
  w35  = (w11*w18);
  /* #127: @3 = (@3*@31) */
  w03 *= w31;
  /* #128: @35 = (@35-@3) */
  w35 -= w03;
  /* #129: (@6[1] += @35) */
  for (rr=w06+1, cs=(&w35); rr!=w06+2; rr+=1) *rr += *cs++;
  /* #130: @10 = (@10*@31) */
  w10 *= w31;
  /* #131: @11 = (@11*@23) */
  w11 *= w23;
  /* #132: @10 = (@10-@11) */
  w10 -= w11;
  /* #133: (@6[2] += @10) */
  for (rr=w06+2, cs=(&w10); rr!=w06+3; rr+=1) *rr += *cs++;
  /* #134: @37 = mac(@28,@6,@24) */
  casadi_copy(w24, 3, w37);
  for (i=0, rr=w37; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w28+j, ct=w06+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #135: {@10, @11, @35} = vertsplit(@37) */
  w10 = w37[0];
  w11 = w37[1];
  w35 = w37[2];
  /* #136: @20 = (@20+@10) */
  w20 += w10;
  /* #137: @10 = (@15*@8) */
  w10  = (w15*w08);
  /* #138: @20 = (@20-@10) */
  w20 -= w10;
  /* #139: @10 = (@16*@7) */
  w10  = (w16*w07);
  /* #140: @20 = (@20+@10) */
  w20 += w10;
  /* #141: @10 = (@12*@1) */
  w10  = (w12*w01);
  /* #142: @20 = (@20+@10) */
  w20 += w10;
  /* #143: @10 = (@14*@2) */
  w10  = (w14*w02);
  /* #144: @20 = (@20-@10) */
  w20 -= w10;
  /* #145: output[0][7] = @20 */
  if (res[0]) res[0][7] = w20;
  /* #146: @34 = (@34*@31) */
  w34 *= w31;
  /* #147: @20 = @33[0] */
  for (rr=(&w20), cs=w33+0; cs!=w33+1; cs+=1) *rr++ = *cs;
  /* #148: @18 = (@20*@18) */
  w18  = (w20*w18);
  /* #149: @34 = (@34-@18) */
  w34 -= w18;
  /* #150: @34 = (@34+@11) */
  w34 += w11;
  /* #151: @11 = (@14*@8) */
  w11  = (w14*w08);
  /* #152: @34 = (@34+@11) */
  w34 += w11;
  /* #153: @11 = (@12*@7) */
  w11  = (w12*w07);
  /* #154: @34 = (@34+@11) */
  w34 += w11;
  /* #155: @11 = (@16*@1) */
  w11  = (w16*w01);
  /* #156: @34 = (@34-@11) */
  w34 -= w11;
  /* #157: @11 = (@15*@2) */
  w11  = (w15*w02);
  /* #158: @34 = (@34-@11) */
  w34 -= w11;
  /* #159: output[0][8] = @34 */
  if (res[0]) res[0][8] = w34;
  /* #160: @20 = (@20*@23) */
  w20 *= w23;
  /* #161: @9 = (@9*@31) */
  w09 *= w31;
  /* #162: @20 = (@20-@9) */
  w20 -= w09;
  /* #163: @20 = (@20+@35) */
  w20 += w35;
  /* #164: @12 = (@12*@8) */
  w12 *= w08;
  /* #165: @20 = (@20+@12) */
  w20 += w12;
  /* #166: @14 = (@14*@7) */
  w14 *= w07;
  /* #167: @20 = (@20-@14) */
  w20 -= w14;
  /* #168: @15 = (@15*@1) */
  w15 *= w01;
  /* #169: @20 = (@20+@15) */
  w20 += w15;
  /* #170: @16 = (@16*@2) */
  w16 *= w02;
  /* #171: @20 = (@20-@16) */
  w20 -= w16;
  /* #172: output[0][9] = @20 */
  if (res[0]) res[0][9] = w20;
  /* #173: @28 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr28 = casadi_c2;
  /* #174: @13 = mac(@27,@22,@13) */
  for (i=0, rr=w13; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w27+j, ct=w22+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #175: @28 = (@28+@13) */
  for (i=0, rr=w28, cr=wr28, cs=w13; i<9; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #176: @22 = (@21*@22) */
  for (i=0, rr=w22, cs=w22; i<9; ++i) (*rr++)  = (w21*(*cs++));
  /* #177: @28 = (@28+@22) */
  for (i=0, rr=w28, cs=w22; i<9; ++i) (*rr++) += (*cs++);
  /* #178: @22 = @28' */
  for (i=0, rr=w22, cs=w28; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #179: @24 = mac(@22,@4,@24) */
  for (i=0, rr=w24; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=wr04+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #180: {NULL, NULL, @21} = vertsplit(@24) */
  w21 = w24[2];
  /* #181: output[0][10] = @21 */
  if (res[0]) res[0][10] = w21;
  /* #182: {@21, @20, @16} = vertsplit(@32) */
  w21 = w32[0];
  w20 = w32[1];
  w16 = w32[2];
  /* #183: output[0][11] = @21 */
  if (res[0]) res[0][11] = w21;
  /* #184: output[0][12] = @20 */
  if (res[0]) res[0][12] = w20;
  /* #185: output[0][13] = @16 */
  if (res[0]) res[0][13] = w16;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 133;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 133*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
