/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_gate_full_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[9] = 
  {1, 3, 0, 1, 2, 3, 0, 0,
  0};
static const casadi_int casadi_s1[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s3[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s4[13] = 
  {0, 1, 2, 9, 10, 11, 18, 19,
  20, 21, 34, 35, 36};
static const casadi_int casadi_s5[13] = 
  {0, 3, 6, 9, 12, 15, 18, 22,
  26, 30, 34, 37, 40};
static const casadi_int casadi_s6[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s7[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s8[13] = 
  {3, 4, 5, 12, 13, 14, 22, 23,
  24, 25, 37, 38, 39};
static const casadi_int casadi_s9[13] = 
  {1, 4, 7, 10, 13, 16, 19, 23,
  27, 31, 35, 38, 41};
static const casadi_int casadi_s10[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s11[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s12[13] = 
  {6, 7, 8, 15, 16, 17, 26, 27,
  28, 29, 40, 41, 42};
static const casadi_int casadi_s13[13] = 
  {2, 5, 8, 11, 14, 17, 20, 24,
  28, 32, 36, 39, 42};
static const casadi_int casadi_s14[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s15[59] = 
  {13, 13, 0, 3, 6, 9, 12, 15,
  18, 22, 26, 30, 34, 37, 40, 43,
  0, 1, 2, 0, 1, 2, 0, 1,
  2, 3, 4, 5, 3, 4, 5, 3,
  4, 5, 6, 7, 8, 9, 6, 7,
  8, 9, 6, 7, 8, 9, 6, 7,
  8, 9, 10, 11, 12, 10, 11, 12,
  10, 11, 12};
static const casadi_int casadi_s16[3] = {13, 1, 1};
static const casadi_int casadi_s17[3] = {0, 1, 1};
static const casadi_int casadi_s18[3] = {17, 1, 1};
static const casadi_int casadi_s19[3] = {1, 1, 1};
static const casadi_int casadi_s20[3] = {0, 0, 1};
static const casadi_int casadi_s21[3] = {0, 13, 1};

static const casadi_real casadi_c0[9] = 
  {50., 0., 0., 0., 50., 0., 0., 0.,
  60.};
static const casadi_real casadi_c1[9] = 
  {6., 0., 0., 0., 6., 0., 0., 0.,
  6.};
static const casadi_real casadi_c2[9] = 
  {15., 0., 0., 0., 15., 0., 0., 0.,
  15.};
static const casadi_real casadi_c3[9] = 
  {5.0000000000000000e-01, 0., 0., 0., 5.0000000000000000e-01, 0., 0., 0.,
  5.0000000000000000e-01};

/* Drone_gate_full_cost_ext_cost_e_fun_jac_hess:(i0[13],i1[0],i2[0],i3[17])->(o0,o1[13],o2[13x13,43nz],o3[],o4[0x13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+22, *w20=w+39, *w21=w+42, *w22=w+55;
  casadi_real *w24=w+67, *w25=w+70, *w27=w+82, *w28=w+85, *w29=w+89, *w30=w+93, *w31=w+97, *w32=w+101, *w33=w+104, *w34=w+107, *w36=w+119, *w37=w+122;
  casadi_real *w38=w+125, *w40=w+137, *w41=w+140, *w42=w+149, *w43=w+162, *w44=w+171, *w45=w+175, w46, w47, w48, w49, w50;
  casadi_real w51, *w52=w+185, *w53=w+194, w54, w55, w56, w57, w58, w59, *w60=w+209, *w61=w+252, *w63=w+256;
  casadi_real *w64=w+260, *w65=w+264, w66, w67, w68, *w69=w+270, w70, w71, w72, w73, w74, w75;
  casadi_real *w76=w+280, *w77=w+283;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct, *wr23, *wr26, *wr35, *wr39;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[3][0] */
  w02 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w03 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w04 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w05 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w06 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w07 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w08 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w09 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = input[3][16] */
  w18 = arg[3] ? arg[3][16] : 0;
  /* #19: @19 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #20: @20 = @19[:3] */
  for (rr=w20, cs=w19+0; cs!=w19+3; cs+=1) *rr++ = *cs;
  /* #21: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #22: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #23: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #24: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #25: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #26: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #27: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #28: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #29: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #30: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #31: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #32: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #33: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #34: @21 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w21;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #35: @22 = @21[:3] */
  for (rr=w22, cs=w21+0; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #36: @20 = (@20-@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #37: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #38: @23 = 
  [[50, 0, 0], 
   [0, 50, 0], 
   [0, 0, 60]] */
  wr23 = casadi_c0;
  /* #39: @24 = mac(@22,@23,@1) */
  casadi_copy(w01, 3, w24);
  for (i=0, rr=w24; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=wr23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #40: @2 = mac(@24,@20,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w24+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #41: @20 = @19[3:6] */
  for (rr=w20, cs=w19+3; cs!=w19+6; cs+=1) *rr++ = *cs;
  /* #42: @25 = @21[3:6] */
  for (rr=w25, cs=w21+3; cs!=w21+6; cs+=1) *rr++ = *cs;
  /* #43: @20 = (@20-@25) */
  for (i=0, rr=w20, cs=w25; i<3; ++i) (*rr++) -= (*cs++);
  /* #44: @25 = @20' */
  casadi_copy(w20, 3, w25);
  /* #45: @26 = 
  [[6, 0, 0], 
   [0, 6, 0], 
   [0, 0, 6]] */
  wr26 = casadi_c1;
  /* #46: @27 = mac(@25,@26,@1) */
  casadi_copy(w01, 3, w27);
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=wr26+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #47: @3 = mac(@27,@20,@0) */
  casadi_copy((&w00), 1, (&w03));
  for (i=0, rr=(&w03); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w27+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #48: @2 = (@2+@3) */
  w02 += w03;
  /* #49: @9 = (-@9) */
  w09 = (- w09 );
  /* #50: @10 = (-@10) */
  w10 = (- w10 );
  /* #51: @11 = (-@11) */
  w11 = (- w11 );
  /* #52: @28 = vertcat(@8, @9, @10, @11) */
  rr=w28;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  /* #53: @29 = @21[6:10] */
  for (rr=w29, cs=w21+6; cs!=w21+10; cs+=1) *rr++ = *cs;
  /* #54: @8 = ||@29||_F */
  w08 = casadi_norm_2(4, w29);
  /* #55: @28 = (@28/@8) */
  for (i=0, rr=w28; i<4; ++i) (*rr++) /= w08;
  /* #56: {@9, @10, @11, @3} = vertsplit(@28) */
  w09 = w28[0];
  w10 = w28[1];
  w11 = w28[2];
  w03 = w28[3];
  /* #57: @30 = @19[6:10] */
  for (rr=w30, cs=w19+6; cs!=w19+10; cs+=1) *rr++ = *cs;
  /* #58: {@4, @5, @6, @7} = vertsplit(@30) */
  w04 = w30[0];
  w05 = w30[1];
  w06 = w30[2];
  w07 = w30[3];
  /* #59: @12 = (@9*@4) */
  w12  = (w09*w04);
  /* #60: @13 = (@10*@5) */
  w13  = (w10*w05);
  /* #61: @12 = (@12-@13) */
  w12 -= w13;
  /* #62: @13 = (@11*@6) */
  w13  = (w11*w06);
  /* #63: @12 = (@12-@13) */
  w12 -= w13;
  /* #64: @13 = (@3*@7) */
  w13  = (w03*w07);
  /* #65: @12 = (@12-@13) */
  w12 -= w13;
  /* #66: @13 = (@12<@0) */
  w13  = (w12<w00);
  /* #67: @14 = (@9*@5) */
  w14  = (w09*w05);
  /* #68: @15 = (@10*@4) */
  w15  = (w10*w04);
  /* #69: @14 = (@14+@15) */
  w14 += w15;
  /* #70: @15 = (@11*@7) */
  w15  = (w11*w07);
  /* #71: @14 = (@14+@15) */
  w14 += w15;
  /* #72: @15 = (@3*@6) */
  w15  = (w03*w06);
  /* #73: @14 = (@14-@15) */
  w14 -= w15;
  /* #74: @15 = (@9*@6) */
  w15  = (w09*w06);
  /* #75: @16 = (@10*@7) */
  w16  = (w10*w07);
  /* #76: @15 = (@15-@16) */
  w15 -= w16;
  /* #77: @16 = (@11*@4) */
  w16  = (w11*w04);
  /* #78: @15 = (@15+@16) */
  w15 += w16;
  /* #79: @16 = (@3*@5) */
  w16  = (w03*w05);
  /* #80: @15 = (@15+@16) */
  w15 += w16;
  /* #81: @9 = (@9*@7) */
  w09 *= w07;
  /* #82: @10 = (@10*@6) */
  w10 *= w06;
  /* #83: @9 = (@9+@10) */
  w09 += w10;
  /* #84: @11 = (@11*@5) */
  w11 *= w05;
  /* #85: @9 = (@9-@11) */
  w09 -= w11;
  /* #86: @3 = (@3*@4) */
  w03 *= w04;
  /* #87: @9 = (@9+@3) */
  w09 += w03;
  /* #88: @30 = vertcat(@12, @14, @15, @9) */
  rr=w30;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w09;
  /* #89: @31 = (-@30) */
  for (i=0, rr=w31, cs=w30; i<4; ++i) *rr++ = (- *cs++ );
  /* #90: @31 = (@13?@31:0) */
  for (i=0, rr=w31, cs=w31; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #91: @12 = (!@13) */
  w12 = (! w13 );
  /* #92: @30 = (@12?@30:0) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #93: @31 = (@31+@30) */
  for (i=0, rr=w31, cs=w30; i<4; ++i) (*rr++) += (*cs++);
  /* #94: @20 = @31[1:4] */
  for (rr=w20, cs=w31+1; cs!=w31+4; cs+=1) *rr++ = *cs;
  /* #95: @32 = (2.*@20) */
  for (i=0, rr=w32, cs=w20; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #96: @14 = ||@20||_F */
  w14 = casadi_norm_2(3, w20);
  /* #97: @15 = @31[0] */
  for (rr=(&w15), cs=w31+0; cs!=w31+1; cs+=1) *rr++ = *cs;
  /* #98: @9 = atan2(@14,@15) */
  w09  = atan2(w14,w15);
  /* #99: @33 = (@32*@9) */
  for (i=0, rr=w33, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w09);
  /* #100: @3 = 1e-09 */
  w03 = 1.0000000000000001e-09;
  /* #101: @3 = (@3+@14) */
  w03 += w14;
  /* #102: @33 = (@33/@3) */
  for (i=0, rr=w33; i<3; ++i) (*rr++) /= w03;
  /* #103: @34 = @33' */
  casadi_copy(w33, 3, w34);
  /* #104: @35 = 
  [[15, 0, 0], 
   [0, 15, 0], 
   [0, 0, 15]] */
  wr35 = casadi_c2;
  /* #105: @36 = mac(@34,@35,@1) */
  casadi_copy(w01, 3, w36);
  for (i=0, rr=w36; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=wr35+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #106: @11 = mac(@36,@33,@0) */
  casadi_copy((&w00), 1, (&w11));
  for (i=0, rr=(&w11); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w36+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #107: @2 = (@2+@11) */
  w02 += w11;
  /* #108: @37 = @19[10:13] */
  for (rr=w37, cs=w19+10; cs!=w19+13; cs+=1) *rr++ = *cs;
  /* #109: @38 = @21[10:13] */
  for (rr=w38, cs=w21+10; cs!=w21+13; cs+=1) *rr++ = *cs;
  /* #110: @37 = (@37-@38) */
  for (i=0, rr=w37, cs=w38; i<3; ++i) (*rr++) -= (*cs++);
  /* #111: @38 = @37' */
  casadi_copy(w37, 3, w38);
  /* #112: @39 = 
  [[0.5, 0, 0], 
   [0, 0.5, 0], 
   [0, 0, 0.5]] */
  wr39 = casadi_c3;
  /* #113: @40 = mac(@38,@39,@1) */
  casadi_copy(w01, 3, w40);
  for (i=0, rr=w40; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=wr39+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #114: @0 = mac(@40,@37,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w40+j, ct=w37+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #115: @2 = (@2+@0) */
  w02 += w00;
  /* #116: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #117: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #118: @40 = @40' */
  /* #119: @41 = @39' */
  for (i=0, rr=w41, cs=wr39; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #120: @37 = mac(@38,@41,@1) */
  casadi_copy(w01, 3, w37);
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w41+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #121: @37 = @37' */
  /* #122: @40 = (@40+@37) */
  for (i=0, rr=w40, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #123: @40 = (-@40) */
  for (i=0, rr=w40, cs=w40; i<3; ++i) *rr++ = (- *cs++ );
  /* #124: @42 = @21; (@42[10:13] += @40) */
  casadi_copy(w21, 13, w42);
  for (rr=w42+10, cs=w40; rr!=w42+13; rr+=1) *rr += *cs++;
  /* #125: @28 = (@28/@8) */
  for (i=0, rr=w28; i<4; ++i) (*rr++) /= w08;
  /* #126: @31 = (-@28) */
  for (i=0, rr=w31, cs=w28; i<4; ++i) *rr++ = (- *cs++ );
  /* #127: @30 = zeros(4x1) */
  casadi_clear(w30, 4);
  /* #128: @2 = sq(@14) */
  w02 = casadi_sq( w14 );
  /* #129: @0 = sq(@15) */
  w00 = casadi_sq( w15 );
  /* #130: @2 = (@2+@0) */
  w02 += w00;
  /* #131: @0 = (@14/@2) */
  w00  = (w14/w02);
  /* #132: @36 = @36' */
  /* #133: @43 = @35' */
  for (i=0, rr=w43, cs=wr35; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #134: @40 = mac(@34,@43,@1) */
  casadi_copy(w01, 3, w40);
  for (i=0, rr=w40; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=w43+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #135: @40 = @40' */
  /* #136: @36 = (@36+@40) */
  for (i=0, rr=w36, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #137: @40 = (@36/@3) */
  for (i=0, rr=w40, cr=w36; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #138: @11 = dot(@32, @40) */
  w11 = casadi_dot(3, w32, w40);
  /* #139: @10 = (@0*@11) */
  w10  = (w00*w11);
  /* #140: @10 = (-@10) */
  w10 = (- w10 );
  /* #141: @44 = @30; (@44[0] += @10) */
  casadi_copy(w30, 4, w44);
  for (rr=w44+0, cs=(&w10); rr!=w44+1; rr+=1) *rr += *cs++;
  /* #142: @33 = (@33/@3) */
  for (i=0, rr=w33; i<3; ++i) (*rr++) /= w03;
  /* #143: @34 = (-@33) */
  for (i=0, rr=w34, cs=w33; i<3; ++i) *rr++ = (- *cs++ );
  /* #144: @10 = dot(@34, @36) */
  w10 = casadi_dot(3, w34, w36);
  /* #145: @16 = (@15/@2) */
  w16  = (w15/w02);
  /* #146: @17 = (@16*@11) */
  w17  = (w16*w11);
  /* #147: @10 = (@10+@17) */
  w10 += w17;
  /* #148: @10 = (@10/@14) */
  w10 /= w14;
  /* #149: @37 = (@10*@20) */
  for (i=0, rr=w37, cs=w20; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #150: @38 = (@9*@40) */
  for (i=0, rr=w38, cs=w40; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #151: @38 = (2.*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #152: @37 = (@37+@38) */
  for (i=0, rr=w37, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #153: (@44[1:4] += @37) */
  for (rr=w44+1, cs=w37; rr!=w44+4; rr+=1) *rr += *cs++;
  /* #154: @45 = (@12?@44:0) */
  for (i=0, rr=w45, cs=w44; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #155: @44 = (-@44) */
  for (i=0, rr=w44, cs=w44; i<4; ++i) *rr++ = (- *cs++ );
  /* #156: @44 = (@13?@44:0) */
  for (i=0, rr=w44, cs=w44; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #157: @45 = (@45+@44) */
  for (i=0, rr=w45, cs=w44; i<4; ++i) (*rr++) += (*cs++);
  /* #158: {@17, @18, @46, @47} = vertsplit(@45) */
  w17 = w45[0];
  w18 = w45[1];
  w46 = w45[2];
  w47 = w45[3];
  /* #159: @48 = (@7*@47) */
  w48  = (w07*w47);
  /* #160: @49 = (@6*@46) */
  w49  = (w06*w46);
  /* #161: @48 = (@48+@49) */
  w48 += w49;
  /* #162: @49 = (@5*@18) */
  w49  = (w05*w18);
  /* #163: @48 = (@48+@49) */
  w48 += w49;
  /* #164: @49 = (@4*@17) */
  w49  = (w04*w17);
  /* #165: @48 = (@48+@49) */
  w48 += w49;
  /* #166: @49 = (@6*@47) */
  w49  = (w06*w47);
  /* #167: @50 = (@7*@46) */
  w50  = (w07*w46);
  /* #168: @49 = (@49-@50) */
  w49 -= w50;
  /* #169: @50 = (@4*@18) */
  w50  = (w04*w18);
  /* #170: @49 = (@49+@50) */
  w49 += w50;
  /* #171: @50 = (@5*@17) */
  w50  = (w05*w17);
  /* #172: @49 = (@49-@50) */
  w49 -= w50;
  /* #173: @50 = (@4*@46) */
  w50  = (w04*w46);
  /* #174: @51 = (@5*@47) */
  w51  = (w05*w47);
  /* #175: @50 = (@50-@51) */
  w50 -= w51;
  /* #176: @51 = (@7*@18) */
  w51  = (w07*w18);
  /* #177: @50 = (@50+@51) */
  w50 += w51;
  /* #178: @51 = (@6*@17) */
  w51  = (w06*w17);
  /* #179: @50 = (@50-@51) */
  w50 -= w51;
  /* #180: @47 = (@4*@47) */
  w47  = (w04*w47);
  /* #181: @46 = (@5*@46) */
  w46  = (w05*w46);
  /* #182: @47 = (@47+@46) */
  w47 += w46;
  /* #183: @18 = (@6*@18) */
  w18  = (w06*w18);
  /* #184: @47 = (@47-@18) */
  w47 -= w18;
  /* #185: @17 = (@7*@17) */
  w17  = (w07*w17);
  /* #186: @47 = (@47-@17) */
  w47 -= w17;
  /* #187: @45 = vertcat(@48, @49, @50, @47) */
  rr=w45;
  *rr++ = w48;
  *rr++ = w49;
  *rr++ = w50;
  *rr++ = w47;
  /* #188: @48 = dot(@31, @45) */
  w48 = casadi_dot(4, w31, w45);
  /* #189: @48 = (@48/@8) */
  w48 /= w08;
  /* #190: @44 = (@48*@29) */
  for (i=0, rr=w44, cs=w29; i<4; ++i) (*rr++)  = (w48*(*cs++));
  /* #191: (@42[6:10] += @44) */
  for (rr=w42+6, cs=w44; rr!=w42+10; rr+=1) *rr += *cs++;
  /* #192: @27 = @27' */
  /* #193: @52 = @26' */
  for (i=0, rr=w52, cs=wr26; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #194: @37 = mac(@25,@52,@1) */
  casadi_copy(w01, 3, w37);
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=w52+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #195: @37 = @37' */
  /* #196: @27 = (@27+@37) */
  for (i=0, rr=w27, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #197: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) *rr++ = (- *cs++ );
  /* #198: (@42[3:6] += @27) */
  for (rr=w42+3, cs=w27; rr!=w42+6; rr+=1) *rr += *cs++;
  /* #199: @24 = @24' */
  /* #200: @53 = @23' */
  for (i=0, rr=w53, cs=wr23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #201: @27 = mac(@22,@53,@1) */
  casadi_copy(w01, 3, w27);
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w53+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #202: @27 = @27' */
  /* #203: @24 = (@24+@27) */
  for (i=0, rr=w24, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #204: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) *rr++ = (- *cs++ );
  /* #205: (@42[:3] += @24) */
  for (rr=w42+0, cs=w24; rr!=w42+3; rr+=1) *rr += *cs++;
  /* #206: {@49, @50, @47, @17, @18, @46, @51, @54, @55, @56, @57, @58, @59} = vertsplit(@42) */
  w49 = w42[0];
  w50 = w42[1];
  w47 = w42[2];
  w17 = w42[3];
  w18 = w42[4];
  w46 = w42[5];
  w51 = w42[6];
  w54 = w42[7];
  w55 = w42[8];
  w56 = w42[9];
  w57 = w42[10];
  w58 = w42[11];
  w59 = w42[12];
  /* #207: output[1][0] = @49 */
  if (res[1]) res[1][0] = w49;
  /* #208: output[1][1] = @50 */
  if (res[1]) res[1][1] = w50;
  /* #209: output[1][2] = @47 */
  if (res[1]) res[1][2] = w47;
  /* #210: output[1][3] = @17 */
  if (res[1]) res[1][3] = w17;
  /* #211: output[1][4] = @18 */
  if (res[1]) res[1][4] = w18;
  /* #212: output[1][5] = @46 */
  if (res[1]) res[1][5] = w46;
  /* #213: @44 = (@45/@8) */
  for (i=0, rr=w44, cr=w45; i<4; ++i) (*rr++)  = ((*cr++)/w08);
  /* #214: {@46, @18, @17, @47} = vertsplit(@44) */
  w46 = w44[0];
  w18 = w44[1];
  w17 = w44[2];
  w47 = w44[3];
  /* #215: @46 = (@46+@51) */
  w46 += w51;
  /* #216: output[1][6] = @46 */
  if (res[1]) res[1][6] = w46;
  /* #217: @54 = (@54-@18) */
  w54 -= w18;
  /* #218: output[1][7] = @54 */
  if (res[1]) res[1][7] = w54;
  /* #219: @55 = (@55-@17) */
  w55 -= w17;
  /* #220: output[1][8] = @55 */
  if (res[1]) res[1][8] = w55;
  /* #221: @56 = (@56-@47) */
  w56 -= w47;
  /* #222: output[1][9] = @56 */
  if (res[1]) res[1][9] = w56;
  /* #223: output[1][10] = @57 */
  if (res[1]) res[1][10] = w57;
  /* #224: output[1][11] = @58 */
  if (res[1]) res[1][11] = w58;
  /* #225: output[1][12] = @59 */
  if (res[1]) res[1][12] = w59;
  /* #226: @60 = zeros(13x13,43nz) */
  casadi_clear(w60, 43);
  /* #227: @61 = ones(13x1,4nz) */
  casadi_fill(w61, 4, 1.);
  /* #228: {@59, NULL, NULL, @58, NULL, NULL, @57, NULL, NULL, NULL, @56, NULL, NULL} = vertsplit(@61) */
  w59 = w61[0];
  w58 = w61[1];
  w57 = w61[2];
  w56 = w61[3];
  /* #229: @56 = sparsity_cast(@56) */
  /* #230: @56 = (-@56) */
  w56 = (- w56 );
  /* #231: @56 = @56' */
  /* #232: @24 = mac(@56,@39,@1) */
  casadi_copy(w01, 3, w24);
  casadi_mtimes((&w56), casadi_s2, wr39, casadi_s1, w24, casadi_s0, w, 0);
  /* #233: @24 = @24' */
  /* #234: @27 = mac(@56,@41,@1) */
  casadi_copy(w01, 3, w27);
  casadi_mtimes((&w56), casadi_s2, w41, casadi_s1, w27, casadi_s0, w, 0);
  /* #235: @27 = @27' */
  /* #236: @24 = (@24+@27) */
  for (i=0, rr=w24, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #237: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) *rr++ = (- *cs++ );
  /* #238: @42 = @21; (@42[10:13] += @24) */
  casadi_copy(w21, 13, w42);
  for (rr=w42+10, cs=w24; rr!=w42+13; rr+=1) *rr += *cs++;
  /* #239: @62 = 00 */
  /* #240: @56 = vertcat(@57, @62, @62, @62) */
  rr=(&w56);
  *rr++ = w57;
  /* #241: @56 = (@56/@8) */
  w56 /= w08;
  /* #242: @61 = dense(@56) */
  casadi_densify((&w56), casadi_s3, w61, 0);
  /* #243: @56 = project(@29) */
  casadi_sparsify(w29, (&w56), casadi_s3, 0);
  /* #244: @57 = sparsity_cast(@57) */
  /* #245: @47 = dot(@56, @57) */
  w47 = casadi_dot(1, (&w56), (&w57));
  /* #246: @47 = (@47/@8) */
  w47 /= w08;
  /* #247: @63 = (@28*@47) */
  for (i=0, rr=w63, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)*w47);
  /* #248: @61 = (@61-@63) */
  for (i=0, rr=w61, cs=w63; i<4; ++i) (*rr++) -= (*cs++);
  /* #249: {@56, @55, @17, @54} = vertsplit(@61) */
  w56 = w61[0];
  w55 = w61[1];
  w17 = w61[2];
  w54 = w61[3];
  /* #250: @18 = (@4*@56) */
  w18  = (w04*w56);
  /* #251: @46 = (@5*@55) */
  w46  = (w05*w55);
  /* #252: @18 = (@18-@46) */
  w18 -= w46;
  /* #253: @46 = (@6*@17) */
  w46  = (w06*w17);
  /* #254: @18 = (@18-@46) */
  w18 -= w46;
  /* #255: @46 = (@7*@54) */
  w46  = (w07*w54);
  /* #256: @18 = (@18-@46) */
  w18 -= w46;
  /* #257: @46 = (@5*@56) */
  w46  = (w05*w56);
  /* #258: @51 = (@4*@55) */
  w51  = (w04*w55);
  /* #259: @46 = (@46+@51) */
  w46 += w51;
  /* #260: @51 = (@7*@17) */
  w51  = (w07*w17);
  /* #261: @46 = (@46+@51) */
  w46 += w51;
  /* #262: @51 = (@6*@54) */
  w51  = (w06*w54);
  /* #263: @46 = (@46-@51) */
  w46 -= w51;
  /* #264: @51 = (@6*@56) */
  w51  = (w06*w56);
  /* #265: @50 = (@7*@55) */
  w50  = (w07*w55);
  /* #266: @51 = (@51-@50) */
  w51 -= w50;
  /* #267: @50 = (@4*@17) */
  w50  = (w04*w17);
  /* #268: @51 = (@51+@50) */
  w51 += w50;
  /* #269: @50 = (@5*@54) */
  w50  = (w05*w54);
  /* #270: @51 = (@51+@50) */
  w51 += w50;
  /* #271: @56 = (@7*@56) */
  w56  = (w07*w56);
  /* #272: @55 = (@6*@55) */
  w55  = (w06*w55);
  /* #273: @56 = (@56+@55) */
  w56 += w55;
  /* #274: @17 = (@5*@17) */
  w17  = (w05*w17);
  /* #275: @56 = (@56-@17) */
  w56 -= w17;
  /* #276: @54 = (@4*@54) */
  w54  = (w04*w54);
  /* #277: @56 = (@56+@54) */
  w56 += w54;
  /* #278: @63 = vertcat(@18, @46, @51, @56) */
  rr=w63;
  *rr++ = w18;
  *rr++ = w46;
  *rr++ = w51;
  *rr++ = w56;
  /* #279: @64 = (-@63) */
  for (i=0, rr=w64, cs=w63; i<4; ++i) *rr++ = (- *cs++ );
  /* #280: @64 = (@13?@64:0) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #281: @63 = (@12?@63:0) */
  for (i=0, rr=w63, cs=w63; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #282: @64 = (@64+@63) */
  for (i=0, rr=w64, cs=w63; i<4; ++i) (*rr++) += (*cs++);
  /* #283: @24 = @64[1:4] */
  for (rr=w24, cs=w64+1; cs!=w64+4; cs+=1) *rr++ = *cs;
  /* #284: @18 = dot(@20, @24) */
  w18 = casadi_dot(3, w20, w24);
  /* #285: @18 = (@18/@14) */
  w18 /= w14;
  /* #286: @46 = (@18/@2) */
  w46  = (w18/w02);
  /* #287: @51 = (@0/@2) */
  w51  = (w00/w02);
  /* #288: @56 = (2.*@14) */
  w56 = (2.* w14 );
  /* #289: @54 = (@56*@18) */
  w54  = (w56*w18);
  /* #290: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #291: @17 = @64[0] */
  for (rr=(&w17), cs=w64+0; cs!=w64+1; cs+=1) *rr++ = *cs;
  /* #292: @55 = (@15*@17) */
  w55  = (w15*w17);
  /* #293: @54 = (@54+@55) */
  w54 += w55;
  /* #294: @55 = (@51*@54) */
  w55  = (w51*w54);
  /* #295: @46 = (@46-@55) */
  w46 -= w55;
  /* #296: @46 = (@11*@46) */
  w46  = (w11*w46);
  /* #297: @27 = (2.*@24) */
  for (i=0, rr=w27, cs=w24; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #298: @22 = (@9*@27) */
  for (i=0, rr=w22, cs=w27; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #299: @55 = (@16*@18) */
  w55  = (w16*w18);
  /* #300: @50 = (@0*@17) */
  w50  = (w00*w17);
  /* #301: @55 = (@55-@50) */
  w55 -= w50;
  /* #302: @37 = (@32*@55) */
  for (i=0, rr=w37, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w55);
  /* #303: @22 = (@22+@37) */
  for (i=0, rr=w22, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #304: @22 = (@22/@3) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) /= w03;
  /* #305: @37 = (@33*@18) */
  for (i=0, rr=w37, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)*w18);
  /* #306: @22 = (@22-@37) */
  for (i=0, rr=w22, cs=w37; i<3; ++i) (*rr++) -= (*cs++);
  /* #307: @37 = @22' */
  casadi_copy(w22, 3, w37);
  /* #308: @25 = mac(@37,@35,@1) */
  casadi_copy(w01, 3, w25);
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w37+j, ct=wr35+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #309: @25 = @25' */
  /* #310: @38 = mac(@37,@43,@1) */
  casadi_copy(w01, 3, w38);
  for (i=0, rr=w38; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w37+j, ct=w43+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #311: @38 = @38' */
  /* #312: @25 = (@25+@38) */
  for (i=0, rr=w25, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #313: @38 = (@25/@3) */
  for (i=0, rr=w38, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #314: @37 = (@40/@3) */
  for (i=0, rr=w37, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #315: @65 = (@37*@18) */
  for (i=0, rr=w65, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w18);
  /* #316: @38 = (@38-@65) */
  for (i=0, rr=w38, cs=w65; i<3; ++i) (*rr++) -= (*cs++);
  /* #317: @50 = dot(@32, @38) */
  w50 = casadi_dot(3, w32, w38);
  /* #318: @49 = dot(@27, @40) */
  w49 = casadi_dot(3, w27, w40);
  /* #319: @50 = (@50+@49) */
  w50 += w49;
  /* #320: @49 = (@0*@50) */
  w49  = (w00*w50);
  /* #321: @46 = (@46+@49) */
  w46 += w49;
  /* #322: @46 = (-@46) */
  w46 = (- w46 );
  /* #323: @64 = @30; (@64[0] += @46) */
  casadi_copy(w30, 4, w64);
  for (rr=w64+0, cs=(&w46); rr!=w64+1; rr+=1) *rr += *cs++;
  /* #324: @46 = dot(@34, @25) */
  w46 = casadi_dot(3, w34, w25);
  /* #325: @22 = (@22/@3) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) /= w03;
  /* #326: @25 = (@33/@3) */
  for (i=0, rr=w25, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #327: @27 = (@25*@18) */
  for (i=0, rr=w27, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)*w18);
  /* #328: @22 = (@22-@27) */
  for (i=0, rr=w22, cs=w27; i<3; ++i) (*rr++) -= (*cs++);
  /* #329: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #330: @49 = dot(@22, @36) */
  w49 = casadi_dot(3, w22, w36);
  /* #331: @46 = (@46+@49) */
  w46 += w49;
  /* #332: @17 = (@17/@2) */
  w17 /= w02;
  /* #333: @49 = (@16/@2) */
  w49  = (w16/w02);
  /* #334: @54 = (@49*@54) */
  w54  = (w49*w54);
  /* #335: @17 = (@17-@54) */
  w17 -= w54;
  /* #336: @17 = (@11*@17) */
  w17  = (w11*w17);
  /* #337: @50 = (@16*@50) */
  w50  = (w16*w50);
  /* #338: @17 = (@17+@50) */
  w17 += w50;
  /* #339: @46 = (@46+@17) */
  w46 += w17;
  /* #340: @46 = (@46/@14) */
  w46 /= w14;
  /* #341: @17 = (@10/@14) */
  w17  = (w10/w14);
  /* #342: @18 = (@17*@18) */
  w18  = (w17*w18);
  /* #343: @46 = (@46-@18) */
  w46 -= w18;
  /* #344: @22 = (@20*@46) */
  for (i=0, rr=w22, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w46);
  /* #345: @24 = (@10*@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #346: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #347: @24 = (@40*@55) */
  for (i=0, rr=w24, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w55);
  /* #348: @38 = (@9*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #349: @24 = (@24+@38) */
  for (i=0, rr=w24, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #350: @24 = (2.*@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #351: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #352: (@64[1:4] += @22) */
  for (rr=w64+1, cs=w22; rr!=w64+4; rr+=1) *rr += *cs++;
  /* #353: @63 = (@12?@64:0) */
  for (i=0, rr=w63, cs=w64; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #354: @64 = (-@64) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) *rr++ = (- *cs++ );
  /* #355: @64 = (@13?@64:0) */
  for (i=0, rr=w64, cs=w64; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #356: @63 = (@63+@64) */
  for (i=0, rr=w63, cs=w64; i<4; ++i) (*rr++) += (*cs++);
  /* #357: {@55, @46, @18, @50} = vertsplit(@63) */
  w55 = w63[0];
  w46 = w63[1];
  w18 = w63[2];
  w50 = w63[3];
  /* #358: @54 = (@7*@50) */
  w54  = (w07*w50);
  /* #359: @66 = (@6*@18) */
  w66  = (w06*w18);
  /* #360: @54 = (@54+@66) */
  w54 += w66;
  /* #361: @66 = (@5*@46) */
  w66  = (w05*w46);
  /* #362: @54 = (@54+@66) */
  w54 += w66;
  /* #363: @66 = (@4*@55) */
  w66  = (w04*w55);
  /* #364: @54 = (@54+@66) */
  w54 += w66;
  /* #365: @66 = (@6*@50) */
  w66  = (w06*w50);
  /* #366: @67 = (@7*@18) */
  w67  = (w07*w18);
  /* #367: @66 = (@66-@67) */
  w66 -= w67;
  /* #368: @67 = (@4*@46) */
  w67  = (w04*w46);
  /* #369: @66 = (@66+@67) */
  w66 += w67;
  /* #370: @67 = (@5*@55) */
  w67  = (w05*w55);
  /* #371: @66 = (@66-@67) */
  w66 -= w67;
  /* #372: @67 = (@4*@18) */
  w67  = (w04*w18);
  /* #373: @68 = (@5*@50) */
  w68  = (w05*w50);
  /* #374: @67 = (@67-@68) */
  w67 -= w68;
  /* #375: @68 = (@7*@46) */
  w68  = (w07*w46);
  /* #376: @67 = (@67+@68) */
  w67 += w68;
  /* #377: @68 = (@6*@55) */
  w68  = (w06*w55);
  /* #378: @67 = (@67-@68) */
  w67 -= w68;
  /* #379: @50 = (@4*@50) */
  w50  = (w04*w50);
  /* #380: @18 = (@5*@18) */
  w18  = (w05*w18);
  /* #381: @50 = (@50+@18) */
  w50 += w18;
  /* #382: @46 = (@6*@46) */
  w46  = (w06*w46);
  /* #383: @50 = (@50-@46) */
  w50 -= w46;
  /* #384: @55 = (@7*@55) */
  w55  = (w07*w55);
  /* #385: @50 = (@50-@55) */
  w50 -= w55;
  /* #386: @63 = vertcat(@54, @66, @67, @50) */
  rr=w63;
  *rr++ = w54;
  *rr++ = w66;
  *rr++ = w67;
  *rr++ = w50;
  /* #387: @54 = dot(@31, @63) */
  w54 = casadi_dot(4, w31, w63);
  /* #388: @61 = (@61/@8) */
  for (i=0, rr=w61; i<4; ++i) (*rr++) /= w08;
  /* #389: @64 = (@28/@8) */
  for (i=0, rr=w64, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)/w08);
  /* #390: @69 = (@64*@47) */
  for (i=0, rr=w69, cr=w64; i<4; ++i) (*rr++)  = ((*cr++)*w47);
  /* #391: @61 = (@61-@69) */
  for (i=0, rr=w61, cs=w69; i<4; ++i) (*rr++) -= (*cs++);
  /* #392: @61 = (-@61) */
  for (i=0, rr=w61, cs=w61; i<4; ++i) *rr++ = (- *cs++ );
  /* #393: @66 = dot(@61, @45) */
  w66 = casadi_dot(4, w61, w45);
  /* #394: @54 = (@54+@66) */
  w54 += w66;
  /* #395: @54 = (@54/@8) */
  w54 /= w08;
  /* #396: @66 = (@48/@8) */
  w66  = (w48/w08);
  /* #397: @67 = (@66*@47) */
  w67  = (w66*w47);
  /* #398: @54 = (@54-@67) */
  w54 -= w67;
  /* #399: @61 = (@29*@54) */
  for (i=0, rr=w61, cr=w29; i<4; ++i) (*rr++)  = ((*cr++)*w54);
  /* #400: @57 = (@48*@57) */
  w57  = (w48*w57);
  /* #401: @69 = dense(@57) */
  casadi_densify((&w57), casadi_s3, w69, 0);
  /* #402: @61 = (@61+@69) */
  for (i=0, rr=w61, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #403: (@42[6:10] += @61) */
  for (rr=w42+6, cs=w61; rr!=w42+10; rr+=1) *rr += *cs++;
  /* #404: @58 = sparsity_cast(@58) */
  /* #405: @58 = (-@58) */
  w58 = (- w58 );
  /* #406: @58 = @58' */
  /* #407: @22 = mac(@58,@26,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w58), casadi_s2, wr26, casadi_s1, w22, casadi_s0, w, 0);
  /* #408: @22 = @22' */
  /* #409: @24 = mac(@58,@52,@1) */
  casadi_copy(w01, 3, w24);
  casadi_mtimes((&w58), casadi_s2, w52, casadi_s1, w24, casadi_s0, w, 0);
  /* #410: @24 = @24' */
  /* #411: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #412: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #413: (@42[3:6] += @22) */
  for (rr=w42+3, cs=w22; rr!=w42+6; rr+=1) *rr += *cs++;
  /* #414: @59 = sparsity_cast(@59) */
  /* #415: @59 = (-@59) */
  w59 = (- w59 );
  /* #416: @59 = @59' */
  /* #417: @22 = mac(@59,@23,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w59), casadi_s2, wr23, casadi_s1, w22, casadi_s0, w, 0);
  /* #418: @22 = @22' */
  /* #419: @24 = mac(@59,@53,@1) */
  casadi_copy(w01, 3, w24);
  casadi_mtimes((&w59), casadi_s2, w53, casadi_s1, w24, casadi_s0, w, 0);
  /* #420: @24 = @24' */
  /* #421: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #422: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #423: (@42[:3] += @22) */
  for (rr=w42+0, cs=w22; rr!=w42+3; rr+=1) *rr += *cs++;
  /* #424: {@59, @58, @57, @54, @67, @50, @55, @46, @18, @68, @70, @71, @72} = vertsplit(@42) */
  w59 = w42[0];
  w58 = w42[1];
  w57 = w42[2];
  w54 = w42[3];
  w67 = w42[4];
  w50 = w42[5];
  w55 = w42[6];
  w46 = w42[7];
  w18 = w42[8];
  w68 = w42[9];
  w70 = w42[10];
  w71 = w42[11];
  w72 = w42[12];
  /* #425: @63 = (@63/@8) */
  for (i=0, rr=w63; i<4; ++i) (*rr++) /= w08;
  /* #426: @44 = (@44/@8) */
  for (i=0, rr=w44; i<4; ++i) (*rr++) /= w08;
  /* #427: @61 = (@44*@47) */
  for (i=0, rr=w61, cr=w44; i<4; ++i) (*rr++)  = ((*cr++)*w47);
  /* #428: @63 = (@63-@61) */
  for (i=0, rr=w63, cs=w61; i<4; ++i) (*rr++) -= (*cs++);
  /* #429: {@47, @73, @74, @75} = vertsplit(@63) */
  w47 = w63[0];
  w73 = w63[1];
  w74 = w63[2];
  w75 = w63[3];
  /* #430: @47 = (@47+@55) */
  w47 += w55;
  /* #431: @46 = (@46-@73) */
  w46 -= w73;
  /* #432: @18 = (@18-@74) */
  w18 -= w74;
  /* #433: @68 = (@68-@75) */
  w68 -= w75;
  /* #434: @42 = vertcat(@59, @58, @57, @54, @67, @50, @47, @46, @18, @68, @70, @71, @72) */
  rr=w42;
  *rr++ = w59;
  *rr++ = w58;
  *rr++ = w57;
  *rr++ = w54;
  *rr++ = w67;
  *rr++ = w50;
  *rr++ = w47;
  *rr++ = w46;
  *rr++ = w18;
  *rr++ = w68;
  *rr++ = w70;
  *rr++ = w71;
  *rr++ = w72;
  /* #435: (@60[0, 1, 2, 9, 10, 11, 18, 19, 20, 21, 34, 35, 36] = @42) */
  for (cii=casadi_s4, rr=w60, cs=w42; cii!=casadi_s4+13; ++cii, ++cs) rr[*cii] = *cs;
  /* #436: (@60[0, 3, 6, 9, 12, 15, 18, 22, 26, 30, 34, 37, 40] = @42) */
  for (cii=casadi_s5, rr=w60, cs=w42; cii!=casadi_s5+13; ++cii, ++cs) rr[*cii] = *cs;
  /* #437: @63 = ones(13x1,4nz) */
  casadi_fill(w63, 4, 1.);
  /* #438: {NULL, @59, NULL, NULL, @58, NULL, NULL, @57, NULL, NULL, NULL, @54, NULL} = vertsplit(@63) */
  w59 = w63[0];
  w58 = w63[1];
  w57 = w63[2];
  w54 = w63[3];
  /* #439: @54 = sparsity_cast(@54) */
  /* #440: @54 = (-@54) */
  w54 = (- w54 );
  /* #441: @54 = @54' */
  /* #442: @22 = mac(@54,@39,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w54), casadi_s6, wr39, casadi_s1, w22, casadi_s0, w, 0);
  /* #443: @22 = @22' */
  /* #444: @24 = mac(@54,@41,@1) */
  casadi_copy(w01, 3, w24);
  casadi_mtimes((&w54), casadi_s6, w41, casadi_s1, w24, casadi_s0, w, 0);
  /* #445: @24 = @24' */
  /* #446: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #447: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #448: @42 = @21; (@42[10:13] += @22) */
  casadi_copy(w21, 13, w42);
  for (rr=w42+10, cs=w22; rr!=w42+13; rr+=1) *rr += *cs++;
  /* #449: @54 = (-@57) */
  w54 = (- w57 );
  /* #450: @67 = vertcat(@62, @54, @62, @62) */
  rr=(&w67);
  *rr++ = w54;
  /* #451: @67 = (@67/@8) */
  w67 /= w08;
  /* #452: @63 = dense(@67) */
  casadi_densify((&w67), casadi_s7, w63, 0);
  /* #453: @67 = project(@29) */
  casadi_sparsify(w29, (&w67), casadi_s7, 0);
  /* #454: @57 = sparsity_cast(@57) */
  /* #455: @54 = dot(@67, @57) */
  w54 = casadi_dot(1, (&w67), (&w57));
  /* #456: @54 = (@54/@8) */
  w54 /= w08;
  /* #457: @61 = (@28*@54) */
  for (i=0, rr=w61, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)*w54);
  /* #458: @63 = (@63-@61) */
  for (i=0, rr=w63, cs=w61; i<4; ++i) (*rr++) -= (*cs++);
  /* #459: {@67, @50, @47, @46} = vertsplit(@63) */
  w67 = w63[0];
  w50 = w63[1];
  w47 = w63[2];
  w46 = w63[3];
  /* #460: @18 = (@4*@67) */
  w18  = (w04*w67);
  /* #461: @68 = (@5*@50) */
  w68  = (w05*w50);
  /* #462: @18 = (@18-@68) */
  w18 -= w68;
  /* #463: @68 = (@6*@47) */
  w68  = (w06*w47);
  /* #464: @18 = (@18-@68) */
  w18 -= w68;
  /* #465: @68 = (@7*@46) */
  w68  = (w07*w46);
  /* #466: @18 = (@18-@68) */
  w18 -= w68;
  /* #467: @68 = (@5*@67) */
  w68  = (w05*w67);
  /* #468: @70 = (@4*@50) */
  w70  = (w04*w50);
  /* #469: @68 = (@68+@70) */
  w68 += w70;
  /* #470: @70 = (@7*@47) */
  w70  = (w07*w47);
  /* #471: @68 = (@68+@70) */
  w68 += w70;
  /* #472: @70 = (@6*@46) */
  w70  = (w06*w46);
  /* #473: @68 = (@68-@70) */
  w68 -= w70;
  /* #474: @70 = (@6*@67) */
  w70  = (w06*w67);
  /* #475: @71 = (@7*@50) */
  w71  = (w07*w50);
  /* #476: @70 = (@70-@71) */
  w70 -= w71;
  /* #477: @71 = (@4*@47) */
  w71  = (w04*w47);
  /* #478: @70 = (@70+@71) */
  w70 += w71;
  /* #479: @71 = (@5*@46) */
  w71  = (w05*w46);
  /* #480: @70 = (@70+@71) */
  w70 += w71;
  /* #481: @67 = (@7*@67) */
  w67  = (w07*w67);
  /* #482: @50 = (@6*@50) */
  w50  = (w06*w50);
  /* #483: @67 = (@67+@50) */
  w67 += w50;
  /* #484: @47 = (@5*@47) */
  w47  = (w05*w47);
  /* #485: @67 = (@67-@47) */
  w67 -= w47;
  /* #486: @46 = (@4*@46) */
  w46  = (w04*w46);
  /* #487: @67 = (@67+@46) */
  w67 += w46;
  /* #488: @61 = vertcat(@18, @68, @70, @67) */
  rr=w61;
  *rr++ = w18;
  *rr++ = w68;
  *rr++ = w70;
  *rr++ = w67;
  /* #489: @69 = (-@61) */
  for (i=0, rr=w69, cs=w61; i<4; ++i) *rr++ = (- *cs++ );
  /* #490: @69 = (@13?@69:0) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #491: @61 = (@12?@61:0) */
  for (i=0, rr=w61, cs=w61; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #492: @69 = (@69+@61) */
  for (i=0, rr=w69, cs=w61; i<4; ++i) (*rr++) += (*cs++);
  /* #493: @22 = @69[1:4] */
  for (rr=w22, cs=w69+1; cs!=w69+4; cs+=1) *rr++ = *cs;
  /* #494: @18 = dot(@20, @22) */
  w18 = casadi_dot(3, w20, w22);
  /* #495: @18 = (@18/@14) */
  w18 /= w14;
  /* #496: @68 = (@18/@2) */
  w68  = (w18/w02);
  /* #497: @70 = (@56*@18) */
  w70  = (w56*w18);
  /* #498: @67 = @69[0] */
  for (rr=(&w67), cs=w69+0; cs!=w69+1; cs+=1) *rr++ = *cs;
  /* #499: @46 = (@15*@67) */
  w46  = (w15*w67);
  /* #500: @70 = (@70+@46) */
  w70 += w46;
  /* #501: @46 = (@51*@70) */
  w46  = (w51*w70);
  /* #502: @68 = (@68-@46) */
  w68 -= w46;
  /* #503: @68 = (@11*@68) */
  w68  = (w11*w68);
  /* #504: @24 = (2.*@22) */
  for (i=0, rr=w24, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #505: @38 = (@9*@24) */
  for (i=0, rr=w38, cs=w24; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #506: @46 = (@16*@18) */
  w46  = (w16*w18);
  /* #507: @47 = (@0*@67) */
  w47  = (w00*w67);
  /* #508: @46 = (@46-@47) */
  w46 -= w47;
  /* #509: @27 = (@32*@46) */
  for (i=0, rr=w27, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w46);
  /* #510: @38 = (@38+@27) */
  for (i=0, rr=w38, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #511: @38 = (@38/@3) */
  for (i=0, rr=w38; i<3; ++i) (*rr++) /= w03;
  /* #512: @27 = (@33*@18) */
  for (i=0, rr=w27, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)*w18);
  /* #513: @38 = (@38-@27) */
  for (i=0, rr=w38, cs=w27; i<3; ++i) (*rr++) -= (*cs++);
  /* #514: @27 = @38' */
  casadi_copy(w38, 3, w27);
  /* #515: @65 = mac(@27,@35,@1) */
  casadi_copy(w01, 3, w65);
  for (i=0, rr=w65; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w27+j, ct=wr35+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #516: @65 = @65' */
  /* #517: @76 = mac(@27,@43,@1) */
  casadi_copy(w01, 3, w76);
  for (i=0, rr=w76; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w27+j, ct=w43+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #518: @76 = @76' */
  /* #519: @65 = (@65+@76) */
  for (i=0, rr=w65, cs=w76; i<3; ++i) (*rr++) += (*cs++);
  /* #520: @76 = (@65/@3) */
  for (i=0, rr=w76, cr=w65; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #521: @27 = (@37*@18) */
  for (i=0, rr=w27, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w18);
  /* #522: @76 = (@76-@27) */
  for (i=0, rr=w76, cs=w27; i<3; ++i) (*rr++) -= (*cs++);
  /* #523: @47 = dot(@32, @76) */
  w47 = casadi_dot(3, w32, w76);
  /* #524: @50 = dot(@24, @40) */
  w50 = casadi_dot(3, w24, w40);
  /* #525: @47 = (@47+@50) */
  w47 += w50;
  /* #526: @50 = (@0*@47) */
  w50  = (w00*w47);
  /* #527: @68 = (@68+@50) */
  w68 += w50;
  /* #528: @68 = (-@68) */
  w68 = (- w68 );
  /* #529: @69 = @30; (@69[0] += @68) */
  casadi_copy(w30, 4, w69);
  for (rr=w69+0, cs=(&w68); rr!=w69+1; rr+=1) *rr += *cs++;
  /* #530: @68 = dot(@34, @65) */
  w68 = casadi_dot(3, w34, w65);
  /* #531: @38 = (@38/@3) */
  for (i=0, rr=w38; i<3; ++i) (*rr++) /= w03;
  /* #532: @65 = (@25*@18) */
  for (i=0, rr=w65, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)*w18);
  /* #533: @38 = (@38-@65) */
  for (i=0, rr=w38, cs=w65; i<3; ++i) (*rr++) -= (*cs++);
  /* #534: @38 = (-@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (- *cs++ );
  /* #535: @50 = dot(@38, @36) */
  w50 = casadi_dot(3, w38, w36);
  /* #536: @68 = (@68+@50) */
  w68 += w50;
  /* #537: @67 = (@67/@2) */
  w67 /= w02;
  /* #538: @70 = (@49*@70) */
  w70  = (w49*w70);
  /* #539: @67 = (@67-@70) */
  w67 -= w70;
  /* #540: @67 = (@11*@67) */
  w67  = (w11*w67);
  /* #541: @47 = (@16*@47) */
  w47  = (w16*w47);
  /* #542: @67 = (@67+@47) */
  w67 += w47;
  /* #543: @68 = (@68+@67) */
  w68 += w67;
  /* #544: @68 = (@68/@14) */
  w68 /= w14;
  /* #545: @18 = (@17*@18) */
  w18  = (w17*w18);
  /* #546: @68 = (@68-@18) */
  w68 -= w18;
  /* #547: @38 = (@20*@68) */
  for (i=0, rr=w38, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w68);
  /* #548: @22 = (@10*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #549: @38 = (@38+@22) */
  for (i=0, rr=w38, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #550: @22 = (@40*@46) */
  for (i=0, rr=w22, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w46);
  /* #551: @76 = (@9*@76) */
  for (i=0, rr=w76, cs=w76; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #552: @22 = (@22+@76) */
  for (i=0, rr=w22, cs=w76; i<3; ++i) (*rr++) += (*cs++);
  /* #553: @22 = (2.*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #554: @38 = (@38+@22) */
  for (i=0, rr=w38, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #555: (@69[1:4] += @38) */
  for (rr=w69+1, cs=w38; rr!=w69+4; rr+=1) *rr += *cs++;
  /* #556: @61 = (@12?@69:0) */
  for (i=0, rr=w61, cs=w69; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #557: @69 = (-@69) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) *rr++ = (- *cs++ );
  /* #558: @69 = (@13?@69:0) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #559: @61 = (@61+@69) */
  for (i=0, rr=w61, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #560: {@46, @68, @18, @67} = vertsplit(@61) */
  w46 = w61[0];
  w68 = w61[1];
  w18 = w61[2];
  w67 = w61[3];
  /* #561: @47 = (@7*@67) */
  w47  = (w07*w67);
  /* #562: @70 = (@6*@18) */
  w70  = (w06*w18);
  /* #563: @47 = (@47+@70) */
  w47 += w70;
  /* #564: @70 = (@5*@68) */
  w70  = (w05*w68);
  /* #565: @47 = (@47+@70) */
  w47 += w70;
  /* #566: @70 = (@4*@46) */
  w70  = (w04*w46);
  /* #567: @47 = (@47+@70) */
  w47 += w70;
  /* #568: @70 = (@6*@67) */
  w70  = (w06*w67);
  /* #569: @50 = (@7*@18) */
  w50  = (w07*w18);
  /* #570: @70 = (@70-@50) */
  w70 -= w50;
  /* #571: @50 = (@4*@68) */
  w50  = (w04*w68);
  /* #572: @70 = (@70+@50) */
  w70 += w50;
  /* #573: @50 = (@5*@46) */
  w50  = (w05*w46);
  /* #574: @70 = (@70-@50) */
  w70 -= w50;
  /* #575: @50 = (@4*@18) */
  w50  = (w04*w18);
  /* #576: @71 = (@5*@67) */
  w71  = (w05*w67);
  /* #577: @50 = (@50-@71) */
  w50 -= w71;
  /* #578: @71 = (@7*@68) */
  w71  = (w07*w68);
  /* #579: @50 = (@50+@71) */
  w50 += w71;
  /* #580: @71 = (@6*@46) */
  w71  = (w06*w46);
  /* #581: @50 = (@50-@71) */
  w50 -= w71;
  /* #582: @67 = (@4*@67) */
  w67  = (w04*w67);
  /* #583: @18 = (@5*@18) */
  w18  = (w05*w18);
  /* #584: @67 = (@67+@18) */
  w67 += w18;
  /* #585: @68 = (@6*@68) */
  w68  = (w06*w68);
  /* #586: @67 = (@67-@68) */
  w67 -= w68;
  /* #587: @46 = (@7*@46) */
  w46  = (w07*w46);
  /* #588: @67 = (@67-@46) */
  w67 -= w46;
  /* #589: @61 = vertcat(@47, @70, @50, @67) */
  rr=w61;
  *rr++ = w47;
  *rr++ = w70;
  *rr++ = w50;
  *rr++ = w67;
  /* #590: @47 = dot(@31, @61) */
  w47 = casadi_dot(4, w31, w61);
  /* #591: @63 = (@63/@8) */
  for (i=0, rr=w63; i<4; ++i) (*rr++) /= w08;
  /* #592: @69 = (@64*@54) */
  for (i=0, rr=w69, cr=w64; i<4; ++i) (*rr++)  = ((*cr++)*w54);
  /* #593: @63 = (@63-@69) */
  for (i=0, rr=w63, cs=w69; i<4; ++i) (*rr++) -= (*cs++);
  /* #594: @63 = (-@63) */
  for (i=0, rr=w63, cs=w63; i<4; ++i) *rr++ = (- *cs++ );
  /* #595: @70 = dot(@63, @45) */
  w70 = casadi_dot(4, w63, w45);
  /* #596: @47 = (@47+@70) */
  w47 += w70;
  /* #597: @47 = (@47/@8) */
  w47 /= w08;
  /* #598: @70 = (@66*@54) */
  w70  = (w66*w54);
  /* #599: @47 = (@47-@70) */
  w47 -= w70;
  /* #600: @63 = (@29*@47) */
  for (i=0, rr=w63, cr=w29; i<4; ++i) (*rr++)  = ((*cr++)*w47);
  /* #601: @57 = (@48*@57) */
  w57  = (w48*w57);
  /* #602: @69 = dense(@57) */
  casadi_densify((&w57), casadi_s7, w69, 0);
  /* #603: @63 = (@63+@69) */
  for (i=0, rr=w63, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #604: (@42[6:10] += @63) */
  for (rr=w42+6, cs=w63; rr!=w42+10; rr+=1) *rr += *cs++;
  /* #605: @58 = sparsity_cast(@58) */
  /* #606: @58 = (-@58) */
  w58 = (- w58 );
  /* #607: @58 = @58' */
  /* #608: @38 = mac(@58,@26,@1) */
  casadi_copy(w01, 3, w38);
  casadi_mtimes((&w58), casadi_s6, wr26, casadi_s1, w38, casadi_s0, w, 0);
  /* #609: @38 = @38' */
  /* #610: @22 = mac(@58,@52,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w58), casadi_s6, w52, casadi_s1, w22, casadi_s0, w, 0);
  /* #611: @22 = @22' */
  /* #612: @38 = (@38+@22) */
  for (i=0, rr=w38, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #613: @38 = (-@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (- *cs++ );
  /* #614: (@42[3:6] += @38) */
  for (rr=w42+3, cs=w38; rr!=w42+6; rr+=1) *rr += *cs++;
  /* #615: @59 = sparsity_cast(@59) */
  /* #616: @59 = (-@59) */
  w59 = (- w59 );
  /* #617: @59 = @59' */
  /* #618: @38 = mac(@59,@23,@1) */
  casadi_copy(w01, 3, w38);
  casadi_mtimes((&w59), casadi_s6, wr23, casadi_s1, w38, casadi_s0, w, 0);
  /* #619: @38 = @38' */
  /* #620: @22 = mac(@59,@53,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w59), casadi_s6, w53, casadi_s1, w22, casadi_s0, w, 0);
  /* #621: @22 = @22' */
  /* #622: @38 = (@38+@22) */
  for (i=0, rr=w38, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #623: @38 = (-@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (- *cs++ );
  /* #624: (@42[:3] += @38) */
  for (rr=w42+0, cs=w38; rr!=w42+3; rr+=1) *rr += *cs++;
  /* #625: {@59, @58, @57, @47, @70, @50, @67, @46, @68, @18, @71, @72, @75} = vertsplit(@42) */
  w59 = w42[0];
  w58 = w42[1];
  w57 = w42[2];
  w47 = w42[3];
  w70 = w42[4];
  w50 = w42[5];
  w67 = w42[6];
  w46 = w42[7];
  w68 = w42[8];
  w18 = w42[9];
  w71 = w42[10];
  w72 = w42[11];
  w75 = w42[12];
  /* #626: @61 = (@61/@8) */
  for (i=0, rr=w61; i<4; ++i) (*rr++) /= w08;
  /* #627: @63 = (@44*@54) */
  for (i=0, rr=w63, cr=w44; i<4; ++i) (*rr++)  = ((*cr++)*w54);
  /* #628: @61 = (@61-@63) */
  for (i=0, rr=w61, cs=w63; i<4; ++i) (*rr++) -= (*cs++);
  /* #629: {@54, @74, @73, @55} = vertsplit(@61) */
  w54 = w61[0];
  w74 = w61[1];
  w73 = w61[2];
  w55 = w61[3];
  /* #630: @54 = (@54+@67) */
  w54 += w67;
  /* #631: @46 = (@46-@74) */
  w46 -= w74;
  /* #632: @68 = (@68-@73) */
  w68 -= w73;
  /* #633: @18 = (@18-@55) */
  w18 -= w55;
  /* #634: @42 = vertcat(@59, @58, @57, @47, @70, @50, @54, @46, @68, @18, @71, @72, @75) */
  rr=w42;
  *rr++ = w59;
  *rr++ = w58;
  *rr++ = w57;
  *rr++ = w47;
  *rr++ = w70;
  *rr++ = w50;
  *rr++ = w54;
  *rr++ = w46;
  *rr++ = w68;
  *rr++ = w18;
  *rr++ = w71;
  *rr++ = w72;
  *rr++ = w75;
  /* #635: (@60[3, 4, 5, 12, 13, 14, 22, 23, 24, 25, 37, 38, 39] = @42) */
  for (cii=casadi_s8, rr=w60, cs=w42; cii!=casadi_s8+13; ++cii, ++cs) rr[*cii] = *cs;
  /* #636: (@60[1, 4, 7, 10, 13, 16, 19, 23, 27, 31, 35, 38, 41] = @42) */
  for (cii=casadi_s9, rr=w60, cs=w42; cii!=casadi_s9+13; ++cii, ++cs) rr[*cii] = *cs;
  /* #637: @61 = ones(13x1,4nz) */
  casadi_fill(w61, 4, 1.);
  /* #638: {NULL, NULL, @59, NULL, NULL, @58, NULL, NULL, @57, NULL, NULL, NULL, @47} = vertsplit(@61) */
  w59 = w61[0];
  w58 = w61[1];
  w57 = w61[2];
  w47 = w61[3];
  /* #639: @47 = sparsity_cast(@47) */
  /* #640: @47 = (-@47) */
  w47 = (- w47 );
  /* #641: @47 = @47' */
  /* #642: @38 = mac(@47,@39,@1) */
  casadi_copy(w01, 3, w38);
  casadi_mtimes((&w47), casadi_s10, wr39, casadi_s1, w38, casadi_s0, w, 0);
  /* #643: @38 = @38' */
  /* #644: @22 = mac(@47,@41,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w47), casadi_s10, w41, casadi_s1, w22, casadi_s0, w, 0);
  /* #645: @22 = @22' */
  /* #646: @38 = (@38+@22) */
  for (i=0, rr=w38, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #647: @38 = (-@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (- *cs++ );
  /* #648: @42 = @21; (@42[10:13] += @38) */
  casadi_copy(w21, 13, w42);
  for (rr=w42+10, cs=w38; rr!=w42+13; rr+=1) *rr += *cs++;
  /* #649: @47 = (-@57) */
  w47 = (- w57 );
  /* #650: @70 = vertcat(@62, @62, @47, @62) */
  rr=(&w70);
  *rr++ = w47;
  /* #651: @70 = (@70/@8) */
  w70 /= w08;
  /* #652: @61 = dense(@70) */
  casadi_densify((&w70), casadi_s11, w61, 0);
  /* #653: @70 = project(@29) */
  casadi_sparsify(w29, (&w70), casadi_s11, 0);
  /* #654: @57 = sparsity_cast(@57) */
  /* #655: @47 = dot(@70, @57) */
  w47 = casadi_dot(1, (&w70), (&w57));
  /* #656: @47 = (@47/@8) */
  w47 /= w08;
  /* #657: @63 = (@28*@47) */
  for (i=0, rr=w63, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)*w47);
  /* #658: @61 = (@61-@63) */
  for (i=0, rr=w61, cs=w63; i<4; ++i) (*rr++) -= (*cs++);
  /* #659: {@70, @50, @54, @46} = vertsplit(@61) */
  w70 = w61[0];
  w50 = w61[1];
  w54 = w61[2];
  w46 = w61[3];
  /* #660: @68 = (@4*@70) */
  w68  = (w04*w70);
  /* #661: @18 = (@5*@50) */
  w18  = (w05*w50);
  /* #662: @68 = (@68-@18) */
  w68 -= w18;
  /* #663: @18 = (@6*@54) */
  w18  = (w06*w54);
  /* #664: @68 = (@68-@18) */
  w68 -= w18;
  /* #665: @18 = (@7*@46) */
  w18  = (w07*w46);
  /* #666: @68 = (@68-@18) */
  w68 -= w18;
  /* #667: @18 = (@5*@70) */
  w18  = (w05*w70);
  /* #668: @71 = (@4*@50) */
  w71  = (w04*w50);
  /* #669: @18 = (@18+@71) */
  w18 += w71;
  /* #670: @71 = (@7*@54) */
  w71  = (w07*w54);
  /* #671: @18 = (@18+@71) */
  w18 += w71;
  /* #672: @71 = (@6*@46) */
  w71  = (w06*w46);
  /* #673: @18 = (@18-@71) */
  w18 -= w71;
  /* #674: @71 = (@6*@70) */
  w71  = (w06*w70);
  /* #675: @72 = (@7*@50) */
  w72  = (w07*w50);
  /* #676: @71 = (@71-@72) */
  w71 -= w72;
  /* #677: @72 = (@4*@54) */
  w72  = (w04*w54);
  /* #678: @71 = (@71+@72) */
  w71 += w72;
  /* #679: @72 = (@5*@46) */
  w72  = (w05*w46);
  /* #680: @71 = (@71+@72) */
  w71 += w72;
  /* #681: @70 = (@7*@70) */
  w70  = (w07*w70);
  /* #682: @50 = (@6*@50) */
  w50  = (w06*w50);
  /* #683: @70 = (@70+@50) */
  w70 += w50;
  /* #684: @54 = (@5*@54) */
  w54  = (w05*w54);
  /* #685: @70 = (@70-@54) */
  w70 -= w54;
  /* #686: @46 = (@4*@46) */
  w46  = (w04*w46);
  /* #687: @70 = (@70+@46) */
  w70 += w46;
  /* #688: @63 = vertcat(@68, @18, @71, @70) */
  rr=w63;
  *rr++ = w68;
  *rr++ = w18;
  *rr++ = w71;
  *rr++ = w70;
  /* #689: @69 = (-@63) */
  for (i=0, rr=w69, cs=w63; i<4; ++i) *rr++ = (- *cs++ );
  /* #690: @69 = (@13?@69:0) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #691: @63 = (@12?@63:0) */
  for (i=0, rr=w63, cs=w63; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #692: @69 = (@69+@63) */
  for (i=0, rr=w69, cs=w63; i<4; ++i) (*rr++) += (*cs++);
  /* #693: @38 = @69[1:4] */
  for (rr=w38, cs=w69+1; cs!=w69+4; cs+=1) *rr++ = *cs;
  /* #694: @68 = dot(@20, @38) */
  w68 = casadi_dot(3, w20, w38);
  /* #695: @68 = (@68/@14) */
  w68 /= w14;
  /* #696: @18 = (@68/@2) */
  w18  = (w68/w02);
  /* #697: @71 = (@56*@68) */
  w71  = (w56*w68);
  /* #698: @70 = @69[0] */
  for (rr=(&w70), cs=w69+0; cs!=w69+1; cs+=1) *rr++ = *cs;
  /* #699: @46 = (@15*@70) */
  w46  = (w15*w70);
  /* #700: @71 = (@71+@46) */
  w71 += w46;
  /* #701: @46 = (@51*@71) */
  w46  = (w51*w71);
  /* #702: @18 = (@18-@46) */
  w18 -= w46;
  /* #703: @18 = (@11*@18) */
  w18  = (w11*w18);
  /* #704: @22 = (2.*@38) */
  for (i=0, rr=w22, cs=w38; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #705: @76 = (@9*@22) */
  for (i=0, rr=w76, cs=w22; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #706: @46 = (@16*@68) */
  w46  = (w16*w68);
  /* #707: @54 = (@0*@70) */
  w54  = (w00*w70);
  /* #708: @46 = (@46-@54) */
  w46 -= w54;
  /* #709: @65 = (@32*@46) */
  for (i=0, rr=w65, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w46);
  /* #710: @76 = (@76+@65) */
  for (i=0, rr=w76, cs=w65; i<3; ++i) (*rr++) += (*cs++);
  /* #711: @76 = (@76/@3) */
  for (i=0, rr=w76; i<3; ++i) (*rr++) /= w03;
  /* #712: @65 = (@33*@68) */
  for (i=0, rr=w65, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)*w68);
  /* #713: @76 = (@76-@65) */
  for (i=0, rr=w76, cs=w65; i<3; ++i) (*rr++) -= (*cs++);
  /* #714: @65 = @76' */
  casadi_copy(w76, 3, w65);
  /* #715: @24 = mac(@65,@35,@1) */
  casadi_copy(w01, 3, w24);
  for (i=0, rr=w24; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w65+j, ct=wr35+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #716: @24 = @24' */
  /* #717: @27 = mac(@65,@43,@1) */
  casadi_copy(w01, 3, w27);
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w65+j, ct=w43+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #718: @27 = @27' */
  /* #719: @24 = (@24+@27) */
  for (i=0, rr=w24, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #720: @27 = (@24/@3) */
  for (i=0, rr=w27, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #721: @65 = (@37*@68) */
  for (i=0, rr=w65, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w68);
  /* #722: @27 = (@27-@65) */
  for (i=0, rr=w27, cs=w65; i<3; ++i) (*rr++) -= (*cs++);
  /* #723: @54 = dot(@32, @27) */
  w54 = casadi_dot(3, w32, w27);
  /* #724: @50 = dot(@22, @40) */
  w50 = casadi_dot(3, w22, w40);
  /* #725: @54 = (@54+@50) */
  w54 += w50;
  /* #726: @50 = (@0*@54) */
  w50  = (w00*w54);
  /* #727: @18 = (@18+@50) */
  w18 += w50;
  /* #728: @18 = (-@18) */
  w18 = (- w18 );
  /* #729: @69 = @30; (@69[0] += @18) */
  casadi_copy(w30, 4, w69);
  for (rr=w69+0, cs=(&w18); rr!=w69+1; rr+=1) *rr += *cs++;
  /* #730: @18 = dot(@34, @24) */
  w18 = casadi_dot(3, w34, w24);
  /* #731: @76 = (@76/@3) */
  for (i=0, rr=w76; i<3; ++i) (*rr++) /= w03;
  /* #732: @24 = (@25*@68) */
  for (i=0, rr=w24, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)*w68);
  /* #733: @76 = (@76-@24) */
  for (i=0, rr=w76, cs=w24; i<3; ++i) (*rr++) -= (*cs++);
  /* #734: @76 = (-@76) */
  for (i=0, rr=w76, cs=w76; i<3; ++i) *rr++ = (- *cs++ );
  /* #735: @50 = dot(@76, @36) */
  w50 = casadi_dot(3, w76, w36);
  /* #736: @18 = (@18+@50) */
  w18 += w50;
  /* #737: @70 = (@70/@2) */
  w70 /= w02;
  /* #738: @71 = (@49*@71) */
  w71  = (w49*w71);
  /* #739: @70 = (@70-@71) */
  w70 -= w71;
  /* #740: @70 = (@11*@70) */
  w70  = (w11*w70);
  /* #741: @54 = (@16*@54) */
  w54  = (w16*w54);
  /* #742: @70 = (@70+@54) */
  w70 += w54;
  /* #743: @18 = (@18+@70) */
  w18 += w70;
  /* #744: @18 = (@18/@14) */
  w18 /= w14;
  /* #745: @68 = (@17*@68) */
  w68  = (w17*w68);
  /* #746: @18 = (@18-@68) */
  w18 -= w68;
  /* #747: @76 = (@20*@18) */
  for (i=0, rr=w76, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w18);
  /* #748: @38 = (@10*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #749: @76 = (@76+@38) */
  for (i=0, rr=w76, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #750: @38 = (@40*@46) */
  for (i=0, rr=w38, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w46);
  /* #751: @27 = (@9*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #752: @38 = (@38+@27) */
  for (i=0, rr=w38, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #753: @38 = (2.*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #754: @76 = (@76+@38) */
  for (i=0, rr=w76, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #755: (@69[1:4] += @76) */
  for (rr=w69+1, cs=w76; rr!=w69+4; rr+=1) *rr += *cs++;
  /* #756: @63 = (@12?@69:0) */
  for (i=0, rr=w63, cs=w69; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #757: @69 = (-@69) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) *rr++ = (- *cs++ );
  /* #758: @69 = (@13?@69:0) */
  for (i=0, rr=w69, cs=w69; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #759: @63 = (@63+@69) */
  for (i=0, rr=w63, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #760: {@46, @18, @68, @70} = vertsplit(@63) */
  w46 = w63[0];
  w18 = w63[1];
  w68 = w63[2];
  w70 = w63[3];
  /* #761: @54 = (@7*@70) */
  w54  = (w07*w70);
  /* #762: @71 = (@6*@68) */
  w71  = (w06*w68);
  /* #763: @54 = (@54+@71) */
  w54 += w71;
  /* #764: @71 = (@5*@18) */
  w71  = (w05*w18);
  /* #765: @54 = (@54+@71) */
  w54 += w71;
  /* #766: @71 = (@4*@46) */
  w71  = (w04*w46);
  /* #767: @54 = (@54+@71) */
  w54 += w71;
  /* #768: @71 = (@6*@70) */
  w71  = (w06*w70);
  /* #769: @50 = (@7*@68) */
  w50  = (w07*w68);
  /* #770: @71 = (@71-@50) */
  w71 -= w50;
  /* #771: @50 = (@4*@18) */
  w50  = (w04*w18);
  /* #772: @71 = (@71+@50) */
  w71 += w50;
  /* #773: @50 = (@5*@46) */
  w50  = (w05*w46);
  /* #774: @71 = (@71-@50) */
  w71 -= w50;
  /* #775: @50 = (@4*@68) */
  w50  = (w04*w68);
  /* #776: @72 = (@5*@70) */
  w72  = (w05*w70);
  /* #777: @50 = (@50-@72) */
  w50 -= w72;
  /* #778: @72 = (@7*@18) */
  w72  = (w07*w18);
  /* #779: @50 = (@50+@72) */
  w50 += w72;
  /* #780: @72 = (@6*@46) */
  w72  = (w06*w46);
  /* #781: @50 = (@50-@72) */
  w50 -= w72;
  /* #782: @70 = (@4*@70) */
  w70  = (w04*w70);
  /* #783: @68 = (@5*@68) */
  w68  = (w05*w68);
  /* #784: @70 = (@70+@68) */
  w70 += w68;
  /* #785: @18 = (@6*@18) */
  w18  = (w06*w18);
  /* #786: @70 = (@70-@18) */
  w70 -= w18;
  /* #787: @46 = (@7*@46) */
  w46  = (w07*w46);
  /* #788: @70 = (@70-@46) */
  w70 -= w46;
  /* #789: @63 = vertcat(@54, @71, @50, @70) */
  rr=w63;
  *rr++ = w54;
  *rr++ = w71;
  *rr++ = w50;
  *rr++ = w70;
  /* #790: @54 = dot(@31, @63) */
  w54 = casadi_dot(4, w31, w63);
  /* #791: @61 = (@61/@8) */
  for (i=0, rr=w61; i<4; ++i) (*rr++) /= w08;
  /* #792: @69 = (@64*@47) */
  for (i=0, rr=w69, cr=w64; i<4; ++i) (*rr++)  = ((*cr++)*w47);
  /* #793: @61 = (@61-@69) */
  for (i=0, rr=w61, cs=w69; i<4; ++i) (*rr++) -= (*cs++);
  /* #794: @61 = (-@61) */
  for (i=0, rr=w61, cs=w61; i<4; ++i) *rr++ = (- *cs++ );
  /* #795: @71 = dot(@61, @45) */
  w71 = casadi_dot(4, w61, w45);
  /* #796: @54 = (@54+@71) */
  w54 += w71;
  /* #797: @54 = (@54/@8) */
  w54 /= w08;
  /* #798: @71 = (@66*@47) */
  w71  = (w66*w47);
  /* #799: @54 = (@54-@71) */
  w54 -= w71;
  /* #800: @61 = (@29*@54) */
  for (i=0, rr=w61, cr=w29; i<4; ++i) (*rr++)  = ((*cr++)*w54);
  /* #801: @57 = (@48*@57) */
  w57  = (w48*w57);
  /* #802: @69 = dense(@57) */
  casadi_densify((&w57), casadi_s11, w69, 0);
  /* #803: @61 = (@61+@69) */
  for (i=0, rr=w61, cs=w69; i<4; ++i) (*rr++) += (*cs++);
  /* #804: (@42[6:10] += @61) */
  for (rr=w42+6, cs=w61; rr!=w42+10; rr+=1) *rr += *cs++;
  /* #805: @58 = sparsity_cast(@58) */
  /* #806: @58 = (-@58) */
  w58 = (- w58 );
  /* #807: @58 = @58' */
  /* #808: @76 = mac(@58,@26,@1) */
  casadi_copy(w01, 3, w76);
  casadi_mtimes((&w58), casadi_s10, wr26, casadi_s1, w76, casadi_s0, w, 0);
  /* #809: @76 = @76' */
  /* #810: @38 = mac(@58,@52,@1) */
  casadi_copy(w01, 3, w38);
  casadi_mtimes((&w58), casadi_s10, w52, casadi_s1, w38, casadi_s0, w, 0);
  /* #811: @38 = @38' */
  /* #812: @76 = (@76+@38) */
  for (i=0, rr=w76, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #813: @76 = (-@76) */
  for (i=0, rr=w76, cs=w76; i<3; ++i) *rr++ = (- *cs++ );
  /* #814: (@42[3:6] += @76) */
  for (rr=w42+3, cs=w76; rr!=w42+6; rr+=1) *rr += *cs++;
  /* #815: @59 = sparsity_cast(@59) */
  /* #816: @59 = (-@59) */
  w59 = (- w59 );
  /* #817: @59 = @59' */
  /* #818: @76 = mac(@59,@23,@1) */
  casadi_copy(w01, 3, w76);
  casadi_mtimes((&w59), casadi_s10, wr23, casadi_s1, w76, casadi_s0, w, 0);
  /* #819: @76 = @76' */
  /* #820: @38 = mac(@59,@53,@1) */
  casadi_copy(w01, 3, w38);
  casadi_mtimes((&w59), casadi_s10, w53, casadi_s1, w38, casadi_s0, w, 0);
  /* #821: @38 = @38' */
  /* #822: @76 = (@76+@38) */
  for (i=0, rr=w76, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #823: @76 = (-@76) */
  for (i=0, rr=w76, cs=w76; i<3; ++i) *rr++ = (- *cs++ );
  /* #824: (@42[:3] += @76) */
  for (rr=w42+0, cs=w76; rr!=w42+3; rr+=1) *rr += *cs++;
  /* #825: {@59, @58, @57, @54, @71, @50, @70, @46, @18, @68, @72, @75, @55} = vertsplit(@42) */
  w59 = w42[0];
  w58 = w42[1];
  w57 = w42[2];
  w54 = w42[3];
  w71 = w42[4];
  w50 = w42[5];
  w70 = w42[6];
  w46 = w42[7];
  w18 = w42[8];
  w68 = w42[9];
  w72 = w42[10];
  w75 = w42[11];
  w55 = w42[12];
  /* #826: @63 = (@63/@8) */
  for (i=0, rr=w63; i<4; ++i) (*rr++) /= w08;
  /* #827: @61 = (@44*@47) */
  for (i=0, rr=w61, cr=w44; i<4; ++i) (*rr++)  = ((*cr++)*w47);
  /* #828: @63 = (@63-@61) */
  for (i=0, rr=w63, cs=w61; i<4; ++i) (*rr++) -= (*cs++);
  /* #829: {@47, @73, @74, @67} = vertsplit(@63) */
  w47 = w63[0];
  w73 = w63[1];
  w74 = w63[2];
  w67 = w63[3];
  /* #830: @47 = (@47+@70) */
  w47 += w70;
  /* #831: @46 = (@46-@73) */
  w46 -= w73;
  /* #832: @18 = (@18-@74) */
  w18 -= w74;
  /* #833: @68 = (@68-@67) */
  w68 -= w67;
  /* #834: @42 = vertcat(@59, @58, @57, @54, @71, @50, @47, @46, @18, @68, @72, @75, @55) */
  rr=w42;
  *rr++ = w59;
  *rr++ = w58;
  *rr++ = w57;
  *rr++ = w54;
  *rr++ = w71;
  *rr++ = w50;
  *rr++ = w47;
  *rr++ = w46;
  *rr++ = w18;
  *rr++ = w68;
  *rr++ = w72;
  *rr++ = w75;
  *rr++ = w55;
  /* #835: (@60[6, 7, 8, 15, 16, 17, 26, 27, 28, 29, 40, 41, 42] = @42) */
  for (cii=casadi_s12, rr=w60, cs=w42; cii!=casadi_s12+13; ++cii, ++cs) rr[*cii] = *cs;
  /* #836: (@60[2, 5, 8, 11, 14, 17, 20, 24, 28, 32, 36, 39, 42] = @42) */
  for (cii=casadi_s13, rr=w60, cs=w42; cii!=casadi_s13+13; ++cii, ++cs) rr[*cii] = *cs;
  /* #837: @59 = ones(13x1,1nz) */
  w59 = 1.;
  /* #838: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @58, NULL, NULL, NULL} = vertsplit(@59) */
  w58 = w59;
  /* #839: @59 = (-@58) */
  w59 = (- w58 );
  /* #840: @57 = vertcat(@62, @62, @62, @59) */
  rr=(&w57);
  *rr++ = w59;
  /* #841: @57 = (@57/@8) */
  w57 /= w08;
  /* #842: @63 = dense(@57) */
  casadi_densify((&w57), casadi_s14, w63, 0);
  /* #843: @57 = project(@29) */
  casadi_sparsify(w29, (&w57), casadi_s14, 0);
  /* #844: @58 = sparsity_cast(@58) */
  /* #845: @59 = dot(@57, @58) */
  w59 = casadi_dot(1, (&w57), (&w58));
  /* #846: @59 = (@59/@8) */
  w59 /= w08;
  /* #847: @28 = (@28*@59) */
  for (i=0, rr=w28; i<4; ++i) (*rr++) *= w59;
  /* #848: @63 = (@63-@28) */
  for (i=0, rr=w63, cs=w28; i<4; ++i) (*rr++) -= (*cs++);
  /* #849: {@57, @54, @71, @50} = vertsplit(@63) */
  w57 = w63[0];
  w54 = w63[1];
  w71 = w63[2];
  w50 = w63[3];
  /* #850: @47 = (@4*@57) */
  w47  = (w04*w57);
  /* #851: @46 = (@5*@54) */
  w46  = (w05*w54);
  /* #852: @47 = (@47-@46) */
  w47 -= w46;
  /* #853: @46 = (@6*@71) */
  w46  = (w06*w71);
  /* #854: @47 = (@47-@46) */
  w47 -= w46;
  /* #855: @46 = (@7*@50) */
  w46  = (w07*w50);
  /* #856: @47 = (@47-@46) */
  w47 -= w46;
  /* #857: @46 = (@5*@57) */
  w46  = (w05*w57);
  /* #858: @18 = (@4*@54) */
  w18  = (w04*w54);
  /* #859: @46 = (@46+@18) */
  w46 += w18;
  /* #860: @18 = (@7*@71) */
  w18  = (w07*w71);
  /* #861: @46 = (@46+@18) */
  w46 += w18;
  /* #862: @18 = (@6*@50) */
  w18  = (w06*w50);
  /* #863: @46 = (@46-@18) */
  w46 -= w18;
  /* #864: @18 = (@6*@57) */
  w18  = (w06*w57);
  /* #865: @68 = (@7*@54) */
  w68  = (w07*w54);
  /* #866: @18 = (@18-@68) */
  w18 -= w68;
  /* #867: @68 = (@4*@71) */
  w68  = (w04*w71);
  /* #868: @18 = (@18+@68) */
  w18 += w68;
  /* #869: @68 = (@5*@50) */
  w68  = (w05*w50);
  /* #870: @18 = (@18+@68) */
  w18 += w68;
  /* #871: @57 = (@7*@57) */
  w57  = (w07*w57);
  /* #872: @54 = (@6*@54) */
  w54  = (w06*w54);
  /* #873: @57 = (@57+@54) */
  w57 += w54;
  /* #874: @71 = (@5*@71) */
  w71  = (w05*w71);
  /* #875: @57 = (@57-@71) */
  w57 -= w71;
  /* #876: @50 = (@4*@50) */
  w50  = (w04*w50);
  /* #877: @57 = (@57+@50) */
  w57 += w50;
  /* #878: @28 = vertcat(@47, @46, @18, @57) */
  rr=w28;
  *rr++ = w47;
  *rr++ = w46;
  *rr++ = w18;
  *rr++ = w57;
  /* #879: @61 = (-@28) */
  for (i=0, rr=w61, cs=w28; i<4; ++i) *rr++ = (- *cs++ );
  /* #880: @61 = (@13?@61:0) */
  for (i=0, rr=w61, cs=w61; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #881: @28 = (@12?@28:0) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #882: @61 = (@61+@28) */
  for (i=0, rr=w61, cs=w28; i<4; ++i) (*rr++) += (*cs++);
  /* #883: @76 = @61[1:4] */
  for (rr=w76, cs=w61+1; cs!=w61+4; cs+=1) *rr++ = *cs;
  /* #884: @47 = dot(@20, @76) */
  w47 = casadi_dot(3, w20, w76);
  /* #885: @47 = (@47/@14) */
  w47 /= w14;
  /* #886: @46 = (@47/@2) */
  w46  = (w47/w02);
  /* #887: @56 = (@56*@47) */
  w56 *= w47;
  /* #888: @18 = @61[0] */
  for (rr=(&w18), cs=w61+0; cs!=w61+1; cs+=1) *rr++ = *cs;
  /* #889: @15 = (@15*@18) */
  w15 *= w18;
  /* #890: @56 = (@56+@15) */
  w56 += w15;
  /* #891: @51 = (@51*@56) */
  w51 *= w56;
  /* #892: @46 = (@46-@51) */
  w46 -= w51;
  /* #893: @46 = (@11*@46) */
  w46  = (w11*w46);
  /* #894: @38 = (2.*@76) */
  for (i=0, rr=w38, cs=w76; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #895: @27 = (@9*@38) */
  for (i=0, rr=w27, cs=w38; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #896: @51 = (@16*@47) */
  w51  = (w16*w47);
  /* #897: @15 = (@0*@18) */
  w15  = (w00*w18);
  /* #898: @51 = (@51-@15) */
  w51 -= w15;
  /* #899: @24 = (@32*@51) */
  for (i=0, rr=w24, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w51);
  /* #900: @27 = (@27+@24) */
  for (i=0, rr=w27, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #901: @27 = (@27/@3) */
  for (i=0, rr=w27; i<3; ++i) (*rr++) /= w03;
  /* #902: @33 = (@33*@47) */
  for (i=0, rr=w33; i<3; ++i) (*rr++) *= w47;
  /* #903: @27 = (@27-@33) */
  for (i=0, rr=w27, cs=w33; i<3; ++i) (*rr++) -= (*cs++);
  /* #904: @33 = @27' */
  casadi_copy(w27, 3, w33);
  /* #905: @24 = mac(@33,@35,@1) */
  casadi_copy(w01, 3, w24);
  for (i=0, rr=w24; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w33+j, ct=wr35+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #906: @24 = @24' */
  /* #907: @1 = mac(@33,@43,@1) */
  for (i=0, rr=w01; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w33+j, ct=w43+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #908: @1 = @1' */
  /* #909: @24 = (@24+@1) */
  for (i=0, rr=w24, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #910: @1 = (@24/@3) */
  for (i=0, rr=w01, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #911: @37 = (@37*@47) */
  for (i=0, rr=w37; i<3; ++i) (*rr++) *= w47;
  /* #912: @1 = (@1-@37) */
  for (i=0, rr=w01, cs=w37; i<3; ++i) (*rr++) -= (*cs++);
  /* #913: @15 = dot(@32, @1) */
  w15 = casadi_dot(3, w32, w01);
  /* #914: @57 = dot(@38, @40) */
  w57 = casadi_dot(3, w38, w40);
  /* #915: @15 = (@15+@57) */
  w15 += w57;
  /* #916: @0 = (@0*@15) */
  w00 *= w15;
  /* #917: @46 = (@46+@0) */
  w46 += w00;
  /* #918: @46 = (-@46) */
  w46 = (- w46 );
  /* #919: (@30[0] += @46) */
  for (rr=w30+0, cs=(&w46); rr!=w30+1; rr+=1) *rr += *cs++;
  /* #920: @46 = dot(@34, @24) */
  w46 = casadi_dot(3, w34, w24);
  /* #921: @27 = (@27/@3) */
  for (i=0, rr=w27; i<3; ++i) (*rr++) /= w03;
  /* #922: @25 = (@25*@47) */
  for (i=0, rr=w25; i<3; ++i) (*rr++) *= w47;
  /* #923: @27 = (@27-@25) */
  for (i=0, rr=w27, cs=w25; i<3; ++i) (*rr++) -= (*cs++);
  /* #924: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) *rr++ = (- *cs++ );
  /* #925: @3 = dot(@27, @36) */
  w03 = casadi_dot(3, w27, w36);
  /* #926: @46 = (@46+@3) */
  w46 += w03;
  /* #927: @18 = (@18/@2) */
  w18 /= w02;
  /* #928: @49 = (@49*@56) */
  w49 *= w56;
  /* #929: @18 = (@18-@49) */
  w18 -= w49;
  /* #930: @11 = (@11*@18) */
  w11 *= w18;
  /* #931: @16 = (@16*@15) */
  w16 *= w15;
  /* #932: @11 = (@11+@16) */
  w11 += w16;
  /* #933: @46 = (@46+@11) */
  w46 += w11;
  /* #934: @46 = (@46/@14) */
  w46 /= w14;
  /* #935: @17 = (@17*@47) */
  w17 *= w47;
  /* #936: @46 = (@46-@17) */
  w46 -= w17;
  /* #937: @20 = (@20*@46) */
  for (i=0, rr=w20; i<3; ++i) (*rr++) *= w46;
  /* #938: @76 = (@10*@76) */
  for (i=0, rr=w76, cs=w76; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #939: @20 = (@20+@76) */
  for (i=0, rr=w20, cs=w76; i<3; ++i) (*rr++) += (*cs++);
  /* #940: @40 = (@40*@51) */
  for (i=0, rr=w40; i<3; ++i) (*rr++) *= w51;
  /* #941: @1 = (@9*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #942: @40 = (@40+@1) */
  for (i=0, rr=w40, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #943: @40 = (2.*@40) */
  for (i=0, rr=w40, cs=w40; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #944: @20 = (@20+@40) */
  for (i=0, rr=w20, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #945: (@30[1:4] += @20) */
  for (rr=w30+1, cs=w20; rr!=w30+4; rr+=1) *rr += *cs++;
  /* #946: @61 = (@12?@30:0) */
  for (i=0, rr=w61, cs=w30; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #947: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) *rr++ = (- *cs++ );
  /* #948: @30 = (@13?@30:0) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #949: @61 = (@61+@30) */
  for (i=0, rr=w61, cs=w30; i<4; ++i) (*rr++) += (*cs++);
  /* #950: {@13, @12, @9, @51} = vertsplit(@61) */
  w13 = w61[0];
  w12 = w61[1];
  w09 = w61[2];
  w51 = w61[3];
  /* #951: @10 = (@7*@51) */
  w10  = (w07*w51);
  /* #952: @46 = (@6*@9) */
  w46  = (w06*w09);
  /* #953: @10 = (@10+@46) */
  w10 += w46;
  /* #954: @46 = (@5*@12) */
  w46  = (w05*w12);
  /* #955: @10 = (@10+@46) */
  w10 += w46;
  /* #956: @46 = (@4*@13) */
  w46  = (w04*w13);
  /* #957: @10 = (@10+@46) */
  w10 += w46;
  /* #958: @46 = (@6*@51) */
  w46  = (w06*w51);
  /* #959: @17 = (@7*@9) */
  w17  = (w07*w09);
  /* #960: @46 = (@46-@17) */
  w46 -= w17;
  /* #961: @17 = (@4*@12) */
  w17  = (w04*w12);
  /* #962: @46 = (@46+@17) */
  w46 += w17;
  /* #963: @17 = (@5*@13) */
  w17  = (w05*w13);
  /* #964: @46 = (@46-@17) */
  w46 -= w17;
  /* #965: @17 = (@4*@9) */
  w17  = (w04*w09);
  /* #966: @47 = (@5*@51) */
  w47  = (w05*w51);
  /* #967: @17 = (@17-@47) */
  w17 -= w47;
  /* #968: @47 = (@7*@12) */
  w47  = (w07*w12);
  /* #969: @17 = (@17+@47) */
  w17 += w47;
  /* #970: @47 = (@6*@13) */
  w47  = (w06*w13);
  /* #971: @17 = (@17-@47) */
  w17 -= w47;
  /* #972: @4 = (@4*@51) */
  w04 *= w51;
  /* #973: @5 = (@5*@9) */
  w05 *= w09;
  /* #974: @4 = (@4+@5) */
  w04 += w05;
  /* #975: @6 = (@6*@12) */
  w06 *= w12;
  /* #976: @4 = (@4-@6) */
  w04 -= w06;
  /* #977: @7 = (@7*@13) */
  w07 *= w13;
  /* #978: @4 = (@4-@7) */
  w04 -= w07;
  /* #979: @61 = vertcat(@10, @46, @17, @4) */
  rr=w61;
  *rr++ = w10;
  *rr++ = w46;
  *rr++ = w17;
  *rr++ = w04;
  /* #980: @10 = dot(@31, @61) */
  w10 = casadi_dot(4, w31, w61);
  /* #981: @63 = (@63/@8) */
  for (i=0, rr=w63; i<4; ++i) (*rr++) /= w08;
  /* #982: @64 = (@64*@59) */
  for (i=0, rr=w64; i<4; ++i) (*rr++) *= w59;
  /* #983: @63 = (@63-@64) */
  for (i=0, rr=w63, cs=w64; i<4; ++i) (*rr++) -= (*cs++);
  /* #984: @63 = (-@63) */
  for (i=0, rr=w63, cs=w63; i<4; ++i) *rr++ = (- *cs++ );
  /* #985: @46 = dot(@63, @45) */
  w46 = casadi_dot(4, w63, w45);
  /* #986: @10 = (@10+@46) */
  w10 += w46;
  /* #987: @10 = (@10/@8) */
  w10 /= w08;
  /* #988: @66 = (@66*@59) */
  w66 *= w59;
  /* #989: @10 = (@10-@66) */
  w10 -= w66;
  /* #990: @29 = (@29*@10) */
  for (i=0, rr=w29; i<4; ++i) (*rr++) *= w10;
  /* #991: @48 = (@48*@58) */
  w48 *= w58;
  /* #992: @63 = dense(@48) */
  casadi_densify((&w48), casadi_s14, w63, 0);
  /* #993: @29 = (@29+@63) */
  for (i=0, rr=w29, cs=w63; i<4; ++i) (*rr++) += (*cs++);
  /* #994: (@21[6:10] += @29) */
  for (rr=w21+6, cs=w29; rr!=w21+10; rr+=1) *rr += *cs++;
  /* #995: {@48, @58, @10, @66, @46, @17, @4, @7, @13, @6, @12, @5, @9} = vertsplit(@21) */
  w48 = w21[0];
  w58 = w21[1];
  w10 = w21[2];
  w66 = w21[3];
  w46 = w21[4];
  w17 = w21[5];
  w04 = w21[6];
  w07 = w21[7];
  w13 = w21[8];
  w06 = w21[9];
  w12 = w21[10];
  w05 = w21[11];
  w09 = w21[12];
  /* #996: @61 = (@61/@8) */
  for (i=0, rr=w61; i<4; ++i) (*rr++) /= w08;
  /* #997: @44 = (@44*@59) */
  for (i=0, rr=w44; i<4; ++i) (*rr++) *= w59;
  /* #998: @61 = (@61-@44) */
  for (i=0, rr=w61, cs=w44; i<4; ++i) (*rr++) -= (*cs++);
  /* #999: {@59, @8, @51, @47} = vertsplit(@61) */
  w59 = w61[0];
  w08 = w61[1];
  w51 = w61[2];
  w47 = w61[3];
  /* #1000: @59 = (@59+@4) */
  w59 += w04;
  /* #1001: @7 = (@7-@8) */
  w07 -= w08;
  /* #1002: @13 = (@13-@51) */
  w13 -= w51;
  /* #1003: @6 = (@6-@47) */
  w06 -= w47;
  /* #1004: @21 = vertcat(@48, @58, @10, @66, @46, @17, @59, @7, @13, @6, @12, @5, @9) */
  rr=w21;
  *rr++ = w48;
  *rr++ = w58;
  *rr++ = w10;
  *rr++ = w66;
  *rr++ = w46;
  *rr++ = w17;
  *rr++ = w59;
  *rr++ = w07;
  *rr++ = w13;
  *rr++ = w06;
  *rr++ = w12;
  *rr++ = w05;
  *rr++ = w09;
  /* #1005: @61 = @21[6:10] */
  for (rr=w61, cs=w21+6; cs!=w21+10; cs+=1) *rr++ = *cs;
  /* #1006: (@60[30:34] = @61) */
  for (rr=w60+30, cs=w61; rr!=w60+34; rr+=1) *rr = *cs++;
  /* #1007: (@60[21:37:4] = @61) */
  for (rr=w60+21, cs=w61; rr!=w60+37; rr+=4) *rr = *cs++;
  /* #1008: @77 = @60' */
  casadi_trans(w60,casadi_s15, w77, casadi_s15, iw);
  /* #1009: output[2][0] = @77 */
  casadi_copy(w77, 43, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_gate_full_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_gate_full_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_gate_full_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_gate_full_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_gate_full_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_gate_full_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_gate_full_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_gate_full_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_gate_full_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_gate_full_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_gate_full_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_gate_full_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_gate_full_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_gate_full_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s16;
    case 1: return casadi_s17;
    case 2: return casadi_s17;
    case 3: return casadi_s18;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_gate_full_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s19;
    case 1: return casadi_s16;
    case 2: return casadi_s15;
    case 3: return casadi_s20;
    case 4: return casadi_s21;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_gate_full_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 18;
  if (sz_iw) *sz_iw = 14;
  if (sz_w) *sz_w = 326;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_gate_full_cost_ext_cost_e_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 18*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 14*sizeof(casadi_int);
  if (sz_w) *sz_w = 326*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
