/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_gate_att_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s1[9] = 
  {1, 3, 0, 1, 2, 3, 0, 0,
  0};
static const casadi_int casadi_s2[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s3[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s4[10] = 
  {0, 1, 2, 9, 10, 11, 18, 19,
  20, 21};
static const casadi_int casadi_s5[10] = 
  {0, 3, 6, 9, 12, 15, 18, 22,
  26, 30};
static const casadi_int casadi_s6[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s7[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s8[10] = 
  {3, 4, 5, 12, 13, 14, 22, 23,
  24, 25};
static const casadi_int casadi_s9[10] = 
  {1, 4, 7, 10, 13, 16, 19, 23,
  27, 31};
static const casadi_int casadi_s10[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s11[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s12[10] = 
  {6, 7, 8, 15, 16, 17, 26, 27,
  28, 29};
static const casadi_int casadi_s13[10] = 
  {2, 5, 8, 11, 14, 17, 20, 24,
  28, 32};
static const casadi_int casadi_s14[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s15[50] = 
  {13, 13, 0, 3, 6, 9, 12, 15,
  18, 22, 26, 30, 34, 34, 34, 34,
  0, 1, 2, 0, 1, 2, 0, 1,
  2, 3, 4, 5, 3, 4, 5, 3,
  4, 5, 6, 7, 8, 9, 6, 7,
  8, 9, 6, 7, 8, 9, 6, 7,
  8, 9};
static const casadi_int casadi_s16[3] = {13, 1, 1};
static const casadi_int casadi_s17[3] = {0, 1, 1};
static const casadi_int casadi_s18[3] = {17, 1, 1};
static const casadi_int casadi_s19[3] = {1, 1, 1};
static const casadi_int casadi_s20[3] = {0, 0, 1};
static const casadi_int casadi_s21[3] = {0, 13, 1};

static const casadi_real casadi_c0[9] = 
  {50., 0., 0., 0., 50., 0., 0., 0.,
  60.};
static const casadi_real casadi_c1[9] = 
  {6., 0., 0., 0., 6., 0., 0., 0.,
  6.};
static const casadi_real casadi_c2[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};

/* Drone_gate_att_cost_ext_cost_e_fun_jac_hess:(i0[13],i1[0],i2[0],i3[17])->(o0,o1[13],o2[13x13,34nz],o3[],o4[0x13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+22, *w20=w+39, *w21=w+42, *w22=w+55;
  casadi_real *w24=w+67, *w25=w+70, *w27=w+82, *w28=w+85, *w29=w+89, *w30=w+93, *w31=w+97, *w32=w+101, *w33=w+104, *w34=w+107, *w36=w+119, *w37=w+122;
  casadi_real *w38=w+131, *w39=w+134, *w40=w+138, *w41=w+141, *w42=w+144, w43, w44, w45, w46, w47, w48, *w49=w+154;
  casadi_real *w50=w+167, *w51=w+176, w52, w53, w54, w55, w56, w57, *w58=w+191, *w59=w+225, *w61=w+231, *w62=w+235;
  casadi_real *w63=w+239, *w64=w+243, w65, w66, w67, *w68=w+249, w69, w70, w71, w72, w73, w74;
  casadi_real *w75=w+259, *w76=w+269, *w77=w+272;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct, *wr23, *wr26, *wr35;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[3][0] */
  w02 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w03 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w04 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w05 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w06 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w07 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w08 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w09 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = input[3][16] */
  w18 = arg[3] ? arg[3][16] : 0;
  /* #19: @19 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #20: @20 = @19[:3] */
  for (rr=w20, cs=w19+0; cs!=w19+3; cs+=1) *rr++ = *cs;
  /* #21: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #22: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #23: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #24: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #25: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #26: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #27: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #28: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #29: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #30: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #31: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #32: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #33: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #34: @21 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w21;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #35: @22 = @21[:3] */
  for (rr=w22, cs=w21+0; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #36: @20 = (@20-@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #37: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #38: @23 = 
  [[50, 0, 0], 
   [0, 50, 0], 
   [0, 0, 60]] */
  wr23 = casadi_c0;
  /* #39: @24 = mac(@22,@23,@1) */
  casadi_copy(w01, 3, w24);
  for (i=0, rr=w24; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=wr23+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #40: @2 = mac(@24,@20,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w24+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #41: @20 = @19[3:6] */
  for (rr=w20, cs=w19+3; cs!=w19+6; cs+=1) *rr++ = *cs;
  /* #42: @25 = @21[3:6] */
  for (rr=w25, cs=w21+3; cs!=w21+6; cs+=1) *rr++ = *cs;
  /* #43: @20 = (@20-@25) */
  for (i=0, rr=w20, cs=w25; i<3; ++i) (*rr++) -= (*cs++);
  /* #44: @25 = @20' */
  casadi_copy(w20, 3, w25);
  /* #45: @26 = 
  [[6, 0, 0], 
   [0, 6, 0], 
   [0, 0, 6]] */
  wr26 = casadi_c1;
  /* #46: @27 = mac(@25,@26,@1) */
  casadi_copy(w01, 3, w27);
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=wr26+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #47: @3 = mac(@27,@20,@0) */
  casadi_copy((&w00), 1, (&w03));
  for (i=0, rr=(&w03); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w27+j, ct=w20+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #48: @2 = (@2+@3) */
  w02 += w03;
  /* #49: @9 = (-@9) */
  w09 = (- w09 );
  /* #50: @10 = (-@10) */
  w10 = (- w10 );
  /* #51: @11 = (-@11) */
  w11 = (- w11 );
  /* #52: @28 = vertcat(@8, @9, @10, @11) */
  rr=w28;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  /* #53: @29 = @21[6:10] */
  for (rr=w29, cs=w21+6; cs!=w21+10; cs+=1) *rr++ = *cs;
  /* #54: @8 = ||@29||_F */
  w08 = casadi_norm_2(4, w29);
  /* #55: @28 = (@28/@8) */
  for (i=0, rr=w28; i<4; ++i) (*rr++) /= w08;
  /* #56: {@9, @10, @11, @3} = vertsplit(@28) */
  w09 = w28[0];
  w10 = w28[1];
  w11 = w28[2];
  w03 = w28[3];
  /* #57: @30 = @19[6:10] */
  for (rr=w30, cs=w19+6; cs!=w19+10; cs+=1) *rr++ = *cs;
  /* #58: {@4, @5, @6, @7} = vertsplit(@30) */
  w04 = w30[0];
  w05 = w30[1];
  w06 = w30[2];
  w07 = w30[3];
  /* #59: @12 = (@9*@4) */
  w12  = (w09*w04);
  /* #60: @13 = (@10*@5) */
  w13  = (w10*w05);
  /* #61: @12 = (@12-@13) */
  w12 -= w13;
  /* #62: @13 = (@11*@6) */
  w13  = (w11*w06);
  /* #63: @12 = (@12-@13) */
  w12 -= w13;
  /* #64: @13 = (@3*@7) */
  w13  = (w03*w07);
  /* #65: @12 = (@12-@13) */
  w12 -= w13;
  /* #66: @13 = (@12<@0) */
  w13  = (w12<w00);
  /* #67: @14 = (@9*@5) */
  w14  = (w09*w05);
  /* #68: @15 = (@10*@4) */
  w15  = (w10*w04);
  /* #69: @14 = (@14+@15) */
  w14 += w15;
  /* #70: @15 = (@11*@7) */
  w15  = (w11*w07);
  /* #71: @14 = (@14+@15) */
  w14 += w15;
  /* #72: @15 = (@3*@6) */
  w15  = (w03*w06);
  /* #73: @14 = (@14-@15) */
  w14 -= w15;
  /* #74: @15 = (@9*@6) */
  w15  = (w09*w06);
  /* #75: @16 = (@10*@7) */
  w16  = (w10*w07);
  /* #76: @15 = (@15-@16) */
  w15 -= w16;
  /* #77: @16 = (@11*@4) */
  w16  = (w11*w04);
  /* #78: @15 = (@15+@16) */
  w15 += w16;
  /* #79: @16 = (@3*@5) */
  w16  = (w03*w05);
  /* #80: @15 = (@15+@16) */
  w15 += w16;
  /* #81: @9 = (@9*@7) */
  w09 *= w07;
  /* #82: @10 = (@10*@6) */
  w10 *= w06;
  /* #83: @9 = (@9+@10) */
  w09 += w10;
  /* #84: @11 = (@11*@5) */
  w11 *= w05;
  /* #85: @9 = (@9-@11) */
  w09 -= w11;
  /* #86: @3 = (@3*@4) */
  w03 *= w04;
  /* #87: @9 = (@9+@3) */
  w09 += w03;
  /* #88: @30 = vertcat(@12, @14, @15, @9) */
  rr=w30;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w09;
  /* #89: @31 = (-@30) */
  for (i=0, rr=w31, cs=w30; i<4; ++i) *rr++ = (- *cs++ );
  /* #90: @31 = (@13?@31:0) */
  for (i=0, rr=w31, cs=w31; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #91: @12 = (!@13) */
  w12 = (! w13 );
  /* #92: @30 = (@12?@30:0) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #93: @31 = (@31+@30) */
  for (i=0, rr=w31, cs=w30; i<4; ++i) (*rr++) += (*cs++);
  /* #94: @20 = @31[1:4] */
  for (rr=w20, cs=w31+1; cs!=w31+4; cs+=1) *rr++ = *cs;
  /* #95: @32 = (2.*@20) */
  for (i=0, rr=w32, cs=w20; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #96: @14 = ||@20||_F */
  w14 = casadi_norm_2(3, w20);
  /* #97: @15 = @31[0] */
  for (rr=(&w15), cs=w31+0; cs!=w31+1; cs+=1) *rr++ = *cs;
  /* #98: @9 = atan2(@14,@15) */
  w09  = atan2(w14,w15);
  /* #99: @33 = (@32*@9) */
  for (i=0, rr=w33, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w09);
  /* #100: @3 = 1e-09 */
  w03 = 1.0000000000000001e-09;
  /* #101: @3 = (@3+@14) */
  w03 += w14;
  /* #102: @33 = (@33/@3) */
  for (i=0, rr=w33; i<3; ++i) (*rr++) /= w03;
  /* #103: @34 = @33' */
  casadi_copy(w33, 3, w34);
  /* #104: @35 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr35 = casadi_c2;
  /* #105: @36 = mac(@34,@35,@1) */
  casadi_copy(w01, 3, w36);
  for (i=0, rr=w36; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=wr35+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #106: @0 = mac(@36,@33,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w36+j, ct=w33+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #107: @2 = (@2+@0) */
  w02 += w00;
  /* #108: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #109: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #110: @28 = (@28/@8) */
  for (i=0, rr=w28; i<4; ++i) (*rr++) /= w08;
  /* #111: @31 = (-@28) */
  for (i=0, rr=w31, cs=w28; i<4; ++i) *rr++ = (- *cs++ );
  /* #112: @30 = zeros(4x1) */
  casadi_clear(w30, 4);
  /* #113: @2 = sq(@14) */
  w02 = casadi_sq( w14 );
  /* #114: @0 = sq(@15) */
  w00 = casadi_sq( w15 );
  /* #115: @2 = (@2+@0) */
  w02 += w00;
  /* #116: @0 = (@14/@2) */
  w00  = (w14/w02);
  /* #117: @36 = @36' */
  /* #118: @37 = @35' */
  for (i=0, rr=w37, cs=wr35; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #119: @38 = mac(@34,@37,@1) */
  casadi_copy(w01, 3, w38);
  for (i=0, rr=w38; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=w37+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #120: @38 = @38' */
  /* #121: @36 = (@36+@38) */
  for (i=0, rr=w36, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #122: @38 = (@36/@3) */
  for (i=0, rr=w38, cr=w36; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #123: @11 = dot(@32, @38) */
  w11 = casadi_dot(3, w32, w38);
  /* #124: @10 = (@0*@11) */
  w10  = (w00*w11);
  /* #125: @10 = (-@10) */
  w10 = (- w10 );
  /* #126: @39 = @30; (@39[0] += @10) */
  casadi_copy(w30, 4, w39);
  for (rr=w39+0, cs=(&w10); rr!=w39+1; rr+=1) *rr += *cs++;
  /* #127: @33 = (@33/@3) */
  for (i=0, rr=w33; i<3; ++i) (*rr++) /= w03;
  /* #128: @34 = (-@33) */
  for (i=0, rr=w34, cs=w33; i<3; ++i) *rr++ = (- *cs++ );
  /* #129: @10 = dot(@34, @36) */
  w10 = casadi_dot(3, w34, w36);
  /* #130: @16 = (@15/@2) */
  w16  = (w15/w02);
  /* #131: @17 = (@16*@11) */
  w17  = (w16*w11);
  /* #132: @10 = (@10+@17) */
  w10 += w17;
  /* #133: @10 = (@10/@14) */
  w10 /= w14;
  /* #134: @40 = (@10*@20) */
  for (i=0, rr=w40, cs=w20; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #135: @41 = (@9*@38) */
  for (i=0, rr=w41, cs=w38; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #136: @41 = (2.*@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #137: @40 = (@40+@41) */
  for (i=0, rr=w40, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #138: (@39[1:4] += @40) */
  for (rr=w39+1, cs=w40; rr!=w39+4; rr+=1) *rr += *cs++;
  /* #139: @42 = (@12?@39:0) */
  for (i=0, rr=w42, cs=w39; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #140: @39 = (-@39) */
  for (i=0, rr=w39, cs=w39; i<4; ++i) *rr++ = (- *cs++ );
  /* #141: @39 = (@13?@39:0) */
  for (i=0, rr=w39, cs=w39; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #142: @42 = (@42+@39) */
  for (i=0, rr=w42, cs=w39; i<4; ++i) (*rr++) += (*cs++);
  /* #143: {@17, @18, @43, @44} = vertsplit(@42) */
  w17 = w42[0];
  w18 = w42[1];
  w43 = w42[2];
  w44 = w42[3];
  /* #144: @45 = (@7*@44) */
  w45  = (w07*w44);
  /* #145: @46 = (@6*@43) */
  w46  = (w06*w43);
  /* #146: @45 = (@45+@46) */
  w45 += w46;
  /* #147: @46 = (@5*@18) */
  w46  = (w05*w18);
  /* #148: @45 = (@45+@46) */
  w45 += w46;
  /* #149: @46 = (@4*@17) */
  w46  = (w04*w17);
  /* #150: @45 = (@45+@46) */
  w45 += w46;
  /* #151: @46 = (@6*@44) */
  w46  = (w06*w44);
  /* #152: @47 = (@7*@43) */
  w47  = (w07*w43);
  /* #153: @46 = (@46-@47) */
  w46 -= w47;
  /* #154: @47 = (@4*@18) */
  w47  = (w04*w18);
  /* #155: @46 = (@46+@47) */
  w46 += w47;
  /* #156: @47 = (@5*@17) */
  w47  = (w05*w17);
  /* #157: @46 = (@46-@47) */
  w46 -= w47;
  /* #158: @47 = (@4*@43) */
  w47  = (w04*w43);
  /* #159: @48 = (@5*@44) */
  w48  = (w05*w44);
  /* #160: @47 = (@47-@48) */
  w47 -= w48;
  /* #161: @48 = (@7*@18) */
  w48  = (w07*w18);
  /* #162: @47 = (@47+@48) */
  w47 += w48;
  /* #163: @48 = (@6*@17) */
  w48  = (w06*w17);
  /* #164: @47 = (@47-@48) */
  w47 -= w48;
  /* #165: @44 = (@4*@44) */
  w44  = (w04*w44);
  /* #166: @43 = (@5*@43) */
  w43  = (w05*w43);
  /* #167: @44 = (@44+@43) */
  w44 += w43;
  /* #168: @18 = (@6*@18) */
  w18  = (w06*w18);
  /* #169: @44 = (@44-@18) */
  w44 -= w18;
  /* #170: @17 = (@7*@17) */
  w17  = (w07*w17);
  /* #171: @44 = (@44-@17) */
  w44 -= w17;
  /* #172: @42 = vertcat(@45, @46, @47, @44) */
  rr=w42;
  *rr++ = w45;
  *rr++ = w46;
  *rr++ = w47;
  *rr++ = w44;
  /* #173: @45 = dot(@31, @42) */
  w45 = casadi_dot(4, w31, w42);
  /* #174: @45 = (@45/@8) */
  w45 /= w08;
  /* #175: @39 = (@45*@29) */
  for (i=0, rr=w39, cs=w29; i<4; ++i) (*rr++)  = (w45*(*cs++));
  /* #176: @49 = @21; (@49[6:10] += @39) */
  casadi_copy(w21, 13, w49);
  for (rr=w49+6, cs=w39; rr!=w49+10; rr+=1) *rr += *cs++;
  /* #177: @27 = @27' */
  /* #178: @50 = @26' */
  for (i=0, rr=w50, cs=wr26; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #179: @40 = mac(@25,@50,@1) */
  casadi_copy(w01, 3, w40);
  for (i=0, rr=w40; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=w50+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #180: @40 = @40' */
  /* #181: @27 = (@27+@40) */
  for (i=0, rr=w27, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #182: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) *rr++ = (- *cs++ );
  /* #183: (@49[3:6] += @27) */
  for (rr=w49+3, cs=w27; rr!=w49+6; rr+=1) *rr += *cs++;
  /* #184: @24 = @24' */
  /* #185: @51 = @23' */
  for (i=0, rr=w51, cs=wr23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #186: @27 = mac(@22,@51,@1) */
  casadi_copy(w01, 3, w27);
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w51+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #187: @27 = @27' */
  /* #188: @24 = (@24+@27) */
  for (i=0, rr=w24, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #189: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) *rr++ = (- *cs++ );
  /* #190: (@49[:3] += @24) */
  for (rr=w49+0, cs=w24; rr!=w49+3; rr+=1) *rr += *cs++;
  /* #191: {@46, @47, @44, @17, @18, @43, @48, @52, @53, @54, @55, @56, @57} = vertsplit(@49) */
  w46 = w49[0];
  w47 = w49[1];
  w44 = w49[2];
  w17 = w49[3];
  w18 = w49[4];
  w43 = w49[5];
  w48 = w49[6];
  w52 = w49[7];
  w53 = w49[8];
  w54 = w49[9];
  w55 = w49[10];
  w56 = w49[11];
  w57 = w49[12];
  /* #192: output[1][0] = @46 */
  if (res[1]) res[1][0] = w46;
  /* #193: output[1][1] = @47 */
  if (res[1]) res[1][1] = w47;
  /* #194: output[1][2] = @44 */
  if (res[1]) res[1][2] = w44;
  /* #195: output[1][3] = @17 */
  if (res[1]) res[1][3] = w17;
  /* #196: output[1][4] = @18 */
  if (res[1]) res[1][4] = w18;
  /* #197: output[1][5] = @43 */
  if (res[1]) res[1][5] = w43;
  /* #198: @39 = (@42/@8) */
  for (i=0, rr=w39, cr=w42; i<4; ++i) (*rr++)  = ((*cr++)/w08);
  /* #199: {@43, @18, @17, @44} = vertsplit(@39) */
  w43 = w39[0];
  w18 = w39[1];
  w17 = w39[2];
  w44 = w39[3];
  /* #200: @43 = (@43+@48) */
  w43 += w48;
  /* #201: output[1][6] = @43 */
  if (res[1]) res[1][6] = w43;
  /* #202: @52 = (@52-@18) */
  w52 -= w18;
  /* #203: output[1][7] = @52 */
  if (res[1]) res[1][7] = w52;
  /* #204: @53 = (@53-@17) */
  w53 -= w17;
  /* #205: output[1][8] = @53 */
  if (res[1]) res[1][8] = w53;
  /* #206: @54 = (@54-@44) */
  w54 -= w44;
  /* #207: output[1][9] = @54 */
  if (res[1]) res[1][9] = w54;
  /* #208: output[1][10] = @55 */
  if (res[1]) res[1][10] = w55;
  /* #209: output[1][11] = @56 */
  if (res[1]) res[1][11] = w56;
  /* #210: output[1][12] = @57 */
  if (res[1]) res[1][12] = w57;
  /* #211: @58 = zeros(13x13,34nz) */
  casadi_clear(w58, 34);
  /* #212: @59 = ones(13x1,6nz) */
  casadi_fill(w59, 6, 1.);
  /* #213: {@57, NULL, NULL, @56, NULL, NULL, @55, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@59) */
  w57 = w59[0];
  w56 = w59[1];
  w55 = w59[2];
  /* #214: @60 = 00 */
  /* #215: @54 = vertcat(@55, @60, @60, @60) */
  rr=(&w54);
  *rr++ = w55;
  /* #216: @54 = (@54/@8) */
  w54 /= w08;
  /* #217: @61 = dense(@54) */
  casadi_densify((&w54), casadi_s0, w61, 0);
  /* #218: @54 = project(@29) */
  casadi_sparsify(w29, (&w54), casadi_s0, 0);
  /* #219: @55 = sparsity_cast(@55) */
  /* #220: @44 = dot(@54, @55) */
  w44 = casadi_dot(1, (&w54), (&w55));
  /* #221: @44 = (@44/@8) */
  w44 /= w08;
  /* #222: @62 = (@28*@44) */
  for (i=0, rr=w62, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)*w44);
  /* #223: @61 = (@61-@62) */
  for (i=0, rr=w61, cs=w62; i<4; ++i) (*rr++) -= (*cs++);
  /* #224: {@54, @53, @17, @52} = vertsplit(@61) */
  w54 = w61[0];
  w53 = w61[1];
  w17 = w61[2];
  w52 = w61[3];
  /* #225: @18 = (@4*@54) */
  w18  = (w04*w54);
  /* #226: @43 = (@5*@53) */
  w43  = (w05*w53);
  /* #227: @18 = (@18-@43) */
  w18 -= w43;
  /* #228: @43 = (@6*@17) */
  w43  = (w06*w17);
  /* #229: @18 = (@18-@43) */
  w18 -= w43;
  /* #230: @43 = (@7*@52) */
  w43  = (w07*w52);
  /* #231: @18 = (@18-@43) */
  w18 -= w43;
  /* #232: @43 = (@5*@54) */
  w43  = (w05*w54);
  /* #233: @48 = (@4*@53) */
  w48  = (w04*w53);
  /* #234: @43 = (@43+@48) */
  w43 += w48;
  /* #235: @48 = (@7*@17) */
  w48  = (w07*w17);
  /* #236: @43 = (@43+@48) */
  w43 += w48;
  /* #237: @48 = (@6*@52) */
  w48  = (w06*w52);
  /* #238: @43 = (@43-@48) */
  w43 -= w48;
  /* #239: @48 = (@6*@54) */
  w48  = (w06*w54);
  /* #240: @47 = (@7*@53) */
  w47  = (w07*w53);
  /* #241: @48 = (@48-@47) */
  w48 -= w47;
  /* #242: @47 = (@4*@17) */
  w47  = (w04*w17);
  /* #243: @48 = (@48+@47) */
  w48 += w47;
  /* #244: @47 = (@5*@52) */
  w47  = (w05*w52);
  /* #245: @48 = (@48+@47) */
  w48 += w47;
  /* #246: @54 = (@7*@54) */
  w54  = (w07*w54);
  /* #247: @53 = (@6*@53) */
  w53  = (w06*w53);
  /* #248: @54 = (@54+@53) */
  w54 += w53;
  /* #249: @17 = (@5*@17) */
  w17  = (w05*w17);
  /* #250: @54 = (@54-@17) */
  w54 -= w17;
  /* #251: @52 = (@4*@52) */
  w52  = (w04*w52);
  /* #252: @54 = (@54+@52) */
  w54 += w52;
  /* #253: @62 = vertcat(@18, @43, @48, @54) */
  rr=w62;
  *rr++ = w18;
  *rr++ = w43;
  *rr++ = w48;
  *rr++ = w54;
  /* #254: @63 = (-@62) */
  for (i=0, rr=w63, cs=w62; i<4; ++i) *rr++ = (- *cs++ );
  /* #255: @63 = (@13?@63:0) */
  for (i=0, rr=w63, cs=w63; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #256: @62 = (@12?@62:0) */
  for (i=0, rr=w62, cs=w62; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #257: @63 = (@63+@62) */
  for (i=0, rr=w63, cs=w62; i<4; ++i) (*rr++) += (*cs++);
  /* #258: @24 = @63[1:4] */
  for (rr=w24, cs=w63+1; cs!=w63+4; cs+=1) *rr++ = *cs;
  /* #259: @18 = dot(@20, @24) */
  w18 = casadi_dot(3, w20, w24);
  /* #260: @18 = (@18/@14) */
  w18 /= w14;
  /* #261: @43 = (@18/@2) */
  w43  = (w18/w02);
  /* #262: @48 = (@0/@2) */
  w48  = (w00/w02);
  /* #263: @54 = (2.*@14) */
  w54 = (2.* w14 );
  /* #264: @52 = (@54*@18) */
  w52  = (w54*w18);
  /* #265: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #266: @17 = @63[0] */
  for (rr=(&w17), cs=w63+0; cs!=w63+1; cs+=1) *rr++ = *cs;
  /* #267: @53 = (@15*@17) */
  w53  = (w15*w17);
  /* #268: @52 = (@52+@53) */
  w52 += w53;
  /* #269: @53 = (@48*@52) */
  w53  = (w48*w52);
  /* #270: @43 = (@43-@53) */
  w43 -= w53;
  /* #271: @43 = (@11*@43) */
  w43  = (w11*w43);
  /* #272: @27 = (2.*@24) */
  for (i=0, rr=w27, cs=w24; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #273: @22 = (@9*@27) */
  for (i=0, rr=w22, cs=w27; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #274: @53 = (@16*@18) */
  w53  = (w16*w18);
  /* #275: @47 = (@0*@17) */
  w47  = (w00*w17);
  /* #276: @53 = (@53-@47) */
  w53 -= w47;
  /* #277: @40 = (@32*@53) */
  for (i=0, rr=w40, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w53);
  /* #278: @22 = (@22+@40) */
  for (i=0, rr=w22, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #279: @22 = (@22/@3) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) /= w03;
  /* #280: @40 = (@33*@18) */
  for (i=0, rr=w40, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)*w18);
  /* #281: @22 = (@22-@40) */
  for (i=0, rr=w22, cs=w40; i<3; ++i) (*rr++) -= (*cs++);
  /* #282: @40 = @22' */
  casadi_copy(w22, 3, w40);
  /* #283: @25 = mac(@40,@35,@1) */
  casadi_copy(w01, 3, w25);
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w40+j, ct=wr35+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #284: @25 = @25' */
  /* #285: @41 = mac(@40,@37,@1) */
  casadi_copy(w01, 3, w41);
  for (i=0, rr=w41; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w40+j, ct=w37+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #286: @41 = @41' */
  /* #287: @25 = (@25+@41) */
  for (i=0, rr=w25, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #288: @41 = (@25/@3) */
  for (i=0, rr=w41, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #289: @40 = (@38/@3) */
  for (i=0, rr=w40, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #290: @64 = (@40*@18) */
  for (i=0, rr=w64, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w18);
  /* #291: @41 = (@41-@64) */
  for (i=0, rr=w41, cs=w64; i<3; ++i) (*rr++) -= (*cs++);
  /* #292: @47 = dot(@32, @41) */
  w47 = casadi_dot(3, w32, w41);
  /* #293: @46 = dot(@27, @38) */
  w46 = casadi_dot(3, w27, w38);
  /* #294: @47 = (@47+@46) */
  w47 += w46;
  /* #295: @46 = (@0*@47) */
  w46  = (w00*w47);
  /* #296: @43 = (@43+@46) */
  w43 += w46;
  /* #297: @43 = (-@43) */
  w43 = (- w43 );
  /* #298: @63 = @30; (@63[0] += @43) */
  casadi_copy(w30, 4, w63);
  for (rr=w63+0, cs=(&w43); rr!=w63+1; rr+=1) *rr += *cs++;
  /* #299: @43 = dot(@34, @25) */
  w43 = casadi_dot(3, w34, w25);
  /* #300: @22 = (@22/@3) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) /= w03;
  /* #301: @25 = (@33/@3) */
  for (i=0, rr=w25, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #302: @27 = (@25*@18) */
  for (i=0, rr=w27, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)*w18);
  /* #303: @22 = (@22-@27) */
  for (i=0, rr=w22, cs=w27; i<3; ++i) (*rr++) -= (*cs++);
  /* #304: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #305: @46 = dot(@22, @36) */
  w46 = casadi_dot(3, w22, w36);
  /* #306: @43 = (@43+@46) */
  w43 += w46;
  /* #307: @17 = (@17/@2) */
  w17 /= w02;
  /* #308: @46 = (@16/@2) */
  w46  = (w16/w02);
  /* #309: @52 = (@46*@52) */
  w52  = (w46*w52);
  /* #310: @17 = (@17-@52) */
  w17 -= w52;
  /* #311: @17 = (@11*@17) */
  w17  = (w11*w17);
  /* #312: @47 = (@16*@47) */
  w47  = (w16*w47);
  /* #313: @17 = (@17+@47) */
  w17 += w47;
  /* #314: @43 = (@43+@17) */
  w43 += w17;
  /* #315: @43 = (@43/@14) */
  w43 /= w14;
  /* #316: @17 = (@10/@14) */
  w17  = (w10/w14);
  /* #317: @18 = (@17*@18) */
  w18  = (w17*w18);
  /* #318: @43 = (@43-@18) */
  w43 -= w18;
  /* #319: @22 = (@20*@43) */
  for (i=0, rr=w22, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w43);
  /* #320: @24 = (@10*@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #321: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #322: @24 = (@38*@53) */
  for (i=0, rr=w24, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w53);
  /* #323: @41 = (@9*@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #324: @24 = (@24+@41) */
  for (i=0, rr=w24, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #325: @24 = (2.*@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #326: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #327: (@63[1:4] += @22) */
  for (rr=w63+1, cs=w22; rr!=w63+4; rr+=1) *rr += *cs++;
  /* #328: @62 = (@12?@63:0) */
  for (i=0, rr=w62, cs=w63; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #329: @63 = (-@63) */
  for (i=0, rr=w63, cs=w63; i<4; ++i) *rr++ = (- *cs++ );
  /* #330: @63 = (@13?@63:0) */
  for (i=0, rr=w63, cs=w63; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #331: @62 = (@62+@63) */
  for (i=0, rr=w62, cs=w63; i<4; ++i) (*rr++) += (*cs++);
  /* #332: {@53, @43, @18, @47} = vertsplit(@62) */
  w53 = w62[0];
  w43 = w62[1];
  w18 = w62[2];
  w47 = w62[3];
  /* #333: @52 = (@7*@47) */
  w52  = (w07*w47);
  /* #334: @65 = (@6*@18) */
  w65  = (w06*w18);
  /* #335: @52 = (@52+@65) */
  w52 += w65;
  /* #336: @65 = (@5*@43) */
  w65  = (w05*w43);
  /* #337: @52 = (@52+@65) */
  w52 += w65;
  /* #338: @65 = (@4*@53) */
  w65  = (w04*w53);
  /* #339: @52 = (@52+@65) */
  w52 += w65;
  /* #340: @65 = (@6*@47) */
  w65  = (w06*w47);
  /* #341: @66 = (@7*@18) */
  w66  = (w07*w18);
  /* #342: @65 = (@65-@66) */
  w65 -= w66;
  /* #343: @66 = (@4*@43) */
  w66  = (w04*w43);
  /* #344: @65 = (@65+@66) */
  w65 += w66;
  /* #345: @66 = (@5*@53) */
  w66  = (w05*w53);
  /* #346: @65 = (@65-@66) */
  w65 -= w66;
  /* #347: @66 = (@4*@18) */
  w66  = (w04*w18);
  /* #348: @67 = (@5*@47) */
  w67  = (w05*w47);
  /* #349: @66 = (@66-@67) */
  w66 -= w67;
  /* #350: @67 = (@7*@43) */
  w67  = (w07*w43);
  /* #351: @66 = (@66+@67) */
  w66 += w67;
  /* #352: @67 = (@6*@53) */
  w67  = (w06*w53);
  /* #353: @66 = (@66-@67) */
  w66 -= w67;
  /* #354: @47 = (@4*@47) */
  w47  = (w04*w47);
  /* #355: @18 = (@5*@18) */
  w18  = (w05*w18);
  /* #356: @47 = (@47+@18) */
  w47 += w18;
  /* #357: @43 = (@6*@43) */
  w43  = (w06*w43);
  /* #358: @47 = (@47-@43) */
  w47 -= w43;
  /* #359: @53 = (@7*@53) */
  w53  = (w07*w53);
  /* #360: @47 = (@47-@53) */
  w47 -= w53;
  /* #361: @62 = vertcat(@52, @65, @66, @47) */
  rr=w62;
  *rr++ = w52;
  *rr++ = w65;
  *rr++ = w66;
  *rr++ = w47;
  /* #362: @52 = dot(@31, @62) */
  w52 = casadi_dot(4, w31, w62);
  /* #363: @61 = (@61/@8) */
  for (i=0, rr=w61; i<4; ++i) (*rr++) /= w08;
  /* #364: @63 = (@28/@8) */
  for (i=0, rr=w63, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)/w08);
  /* #365: @68 = (@63*@44) */
  for (i=0, rr=w68, cr=w63; i<4; ++i) (*rr++)  = ((*cr++)*w44);
  /* #366: @61 = (@61-@68) */
  for (i=0, rr=w61, cs=w68; i<4; ++i) (*rr++) -= (*cs++);
  /* #367: @61 = (-@61) */
  for (i=0, rr=w61, cs=w61; i<4; ++i) *rr++ = (- *cs++ );
  /* #368: @65 = dot(@61, @42) */
  w65 = casadi_dot(4, w61, w42);
  /* #369: @52 = (@52+@65) */
  w52 += w65;
  /* #370: @52 = (@52/@8) */
  w52 /= w08;
  /* #371: @65 = (@45/@8) */
  w65  = (w45/w08);
  /* #372: @66 = (@65*@44) */
  w66  = (w65*w44);
  /* #373: @52 = (@52-@66) */
  w52 -= w66;
  /* #374: @61 = (@29*@52) */
  for (i=0, rr=w61, cr=w29; i<4; ++i) (*rr++)  = ((*cr++)*w52);
  /* #375: @55 = (@45*@55) */
  w55  = (w45*w55);
  /* #376: @68 = dense(@55) */
  casadi_densify((&w55), casadi_s0, w68, 0);
  /* #377: @61 = (@61+@68) */
  for (i=0, rr=w61, cs=w68; i<4; ++i) (*rr++) += (*cs++);
  /* #378: @49 = @21; (@49[6:10] += @61) */
  casadi_copy(w21, 13, w49);
  for (rr=w49+6, cs=w61; rr!=w49+10; rr+=1) *rr += *cs++;
  /* #379: @56 = sparsity_cast(@56) */
  /* #380: @56 = (-@56) */
  w56 = (- w56 );
  /* #381: @56 = @56' */
  /* #382: @22 = mac(@56,@26,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w56), casadi_s3, wr26, casadi_s2, w22, casadi_s1, w, 0);
  /* #383: @22 = @22' */
  /* #384: @24 = mac(@56,@50,@1) */
  casadi_copy(w01, 3, w24);
  casadi_mtimes((&w56), casadi_s3, w50, casadi_s2, w24, casadi_s1, w, 0);
  /* #385: @24 = @24' */
  /* #386: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #387: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #388: (@49[3:6] += @22) */
  for (rr=w49+3, cs=w22; rr!=w49+6; rr+=1) *rr += *cs++;
  /* #389: @57 = sparsity_cast(@57) */
  /* #390: @57 = (-@57) */
  w57 = (- w57 );
  /* #391: @57 = @57' */
  /* #392: @22 = mac(@57,@23,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w57), casadi_s3, wr23, casadi_s2, w22, casadi_s1, w, 0);
  /* #393: @22 = @22' */
  /* #394: @24 = mac(@57,@51,@1) */
  casadi_copy(w01, 3, w24);
  casadi_mtimes((&w57), casadi_s3, w51, casadi_s2, w24, casadi_s1, w, 0);
  /* #395: @24 = @24' */
  /* #396: @22 = (@22+@24) */
  for (i=0, rr=w22, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #397: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #398: (@49[:3] += @22) */
  for (rr=w49+0, cs=w22; rr!=w49+3; rr+=1) *rr += *cs++;
  /* #399: {@57, @56, @55, @52, @66, @47, @53, @43, @18, @67, @69, @70, @71} = vertsplit(@49) */
  w57 = w49[0];
  w56 = w49[1];
  w55 = w49[2];
  w52 = w49[3];
  w66 = w49[4];
  w47 = w49[5];
  w53 = w49[6];
  w43 = w49[7];
  w18 = w49[8];
  w67 = w49[9];
  w69 = w49[10];
  w70 = w49[11];
  w71 = w49[12];
  /* #400: @62 = (@62/@8) */
  for (i=0, rr=w62; i<4; ++i) (*rr++) /= w08;
  /* #401: @39 = (@39/@8) */
  for (i=0, rr=w39; i<4; ++i) (*rr++) /= w08;
  /* #402: @61 = (@39*@44) */
  for (i=0, rr=w61, cr=w39; i<4; ++i) (*rr++)  = ((*cr++)*w44);
  /* #403: @62 = (@62-@61) */
  for (i=0, rr=w62, cs=w61; i<4; ++i) (*rr++) -= (*cs++);
  /* #404: {@44, @72, @73, @74} = vertsplit(@62) */
  w44 = w62[0];
  w72 = w62[1];
  w73 = w62[2];
  w74 = w62[3];
  /* #405: @44 = (@44+@53) */
  w44 += w53;
  /* #406: @43 = (@43-@72) */
  w43 -= w72;
  /* #407: @18 = (@18-@73) */
  w18 -= w73;
  /* #408: @67 = (@67-@74) */
  w67 -= w74;
  /* #409: @49 = vertcat(@57, @56, @55, @52, @66, @47, @44, @43, @18, @67, @69, @70, @71) */
  rr=w49;
  *rr++ = w57;
  *rr++ = w56;
  *rr++ = w55;
  *rr++ = w52;
  *rr++ = w66;
  *rr++ = w47;
  *rr++ = w44;
  *rr++ = w43;
  *rr++ = w18;
  *rr++ = w67;
  *rr++ = w69;
  *rr++ = w70;
  *rr++ = w71;
  /* #410: @75 = @49[:10] */
  for (rr=w75, cs=w49+0; cs!=w49+10; cs+=1) *rr++ = *cs;
  /* #411: (@58[0, 1, 2, 9, 10, 11, 18, 19, 20, 21] = @75) */
  for (cii=casadi_s4, rr=w58, cs=w75; cii!=casadi_s4+10; ++cii, ++cs) rr[*cii] = *cs;
  /* #412: (@58[0, 3, 6, 9, 12, 15, 18, 22, 26, 30] = @75) */
  for (cii=casadi_s5, rr=w58, cs=w75; cii!=casadi_s5+10; ++cii, ++cs) rr[*cii] = *cs;
  /* #413: @22 = ones(13x1,3nz) */
  casadi_fill(w22, 3, 1.);
  /* #414: {NULL, @57, NULL, NULL, @56, NULL, NULL, @55, NULL, NULL, NULL, NULL, NULL} = vertsplit(@22) */
  w57 = w22[0];
  w56 = w22[1];
  w55 = w22[2];
  /* #415: @52 = (-@55) */
  w52 = (- w55 );
  /* #416: @66 = vertcat(@60, @52, @60, @60) */
  rr=(&w66);
  *rr++ = w52;
  /* #417: @66 = (@66/@8) */
  w66 /= w08;
  /* #418: @62 = dense(@66) */
  casadi_densify((&w66), casadi_s6, w62, 0);
  /* #419: @66 = project(@29) */
  casadi_sparsify(w29, (&w66), casadi_s6, 0);
  /* #420: @55 = sparsity_cast(@55) */
  /* #421: @52 = dot(@66, @55) */
  w52 = casadi_dot(1, (&w66), (&w55));
  /* #422: @52 = (@52/@8) */
  w52 /= w08;
  /* #423: @61 = (@28*@52) */
  for (i=0, rr=w61, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)*w52);
  /* #424: @62 = (@62-@61) */
  for (i=0, rr=w62, cs=w61; i<4; ++i) (*rr++) -= (*cs++);
  /* #425: {@66, @47, @44, @43} = vertsplit(@62) */
  w66 = w62[0];
  w47 = w62[1];
  w44 = w62[2];
  w43 = w62[3];
  /* #426: @18 = (@4*@66) */
  w18  = (w04*w66);
  /* #427: @67 = (@5*@47) */
  w67  = (w05*w47);
  /* #428: @18 = (@18-@67) */
  w18 -= w67;
  /* #429: @67 = (@6*@44) */
  w67  = (w06*w44);
  /* #430: @18 = (@18-@67) */
  w18 -= w67;
  /* #431: @67 = (@7*@43) */
  w67  = (w07*w43);
  /* #432: @18 = (@18-@67) */
  w18 -= w67;
  /* #433: @67 = (@5*@66) */
  w67  = (w05*w66);
  /* #434: @69 = (@4*@47) */
  w69  = (w04*w47);
  /* #435: @67 = (@67+@69) */
  w67 += w69;
  /* #436: @69 = (@7*@44) */
  w69  = (w07*w44);
  /* #437: @67 = (@67+@69) */
  w67 += w69;
  /* #438: @69 = (@6*@43) */
  w69  = (w06*w43);
  /* #439: @67 = (@67-@69) */
  w67 -= w69;
  /* #440: @69 = (@6*@66) */
  w69  = (w06*w66);
  /* #441: @70 = (@7*@47) */
  w70  = (w07*w47);
  /* #442: @69 = (@69-@70) */
  w69 -= w70;
  /* #443: @70 = (@4*@44) */
  w70  = (w04*w44);
  /* #444: @69 = (@69+@70) */
  w69 += w70;
  /* #445: @70 = (@5*@43) */
  w70  = (w05*w43);
  /* #446: @69 = (@69+@70) */
  w69 += w70;
  /* #447: @66 = (@7*@66) */
  w66  = (w07*w66);
  /* #448: @47 = (@6*@47) */
  w47  = (w06*w47);
  /* #449: @66 = (@66+@47) */
  w66 += w47;
  /* #450: @44 = (@5*@44) */
  w44  = (w05*w44);
  /* #451: @66 = (@66-@44) */
  w66 -= w44;
  /* #452: @43 = (@4*@43) */
  w43  = (w04*w43);
  /* #453: @66 = (@66+@43) */
  w66 += w43;
  /* #454: @61 = vertcat(@18, @67, @69, @66) */
  rr=w61;
  *rr++ = w18;
  *rr++ = w67;
  *rr++ = w69;
  *rr++ = w66;
  /* #455: @68 = (-@61) */
  for (i=0, rr=w68, cs=w61; i<4; ++i) *rr++ = (- *cs++ );
  /* #456: @68 = (@13?@68:0) */
  for (i=0, rr=w68, cs=w68; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #457: @61 = (@12?@61:0) */
  for (i=0, rr=w61, cs=w61; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #458: @68 = (@68+@61) */
  for (i=0, rr=w68, cs=w61; i<4; ++i) (*rr++) += (*cs++);
  /* #459: @22 = @68[1:4] */
  for (rr=w22, cs=w68+1; cs!=w68+4; cs+=1) *rr++ = *cs;
  /* #460: @18 = dot(@20, @22) */
  w18 = casadi_dot(3, w20, w22);
  /* #461: @18 = (@18/@14) */
  w18 /= w14;
  /* #462: @67 = (@18/@2) */
  w67  = (w18/w02);
  /* #463: @69 = (@54*@18) */
  w69  = (w54*w18);
  /* #464: @66 = @68[0] */
  for (rr=(&w66), cs=w68+0; cs!=w68+1; cs+=1) *rr++ = *cs;
  /* #465: @43 = (@15*@66) */
  w43  = (w15*w66);
  /* #466: @69 = (@69+@43) */
  w69 += w43;
  /* #467: @43 = (@48*@69) */
  w43  = (w48*w69);
  /* #468: @67 = (@67-@43) */
  w67 -= w43;
  /* #469: @67 = (@11*@67) */
  w67  = (w11*w67);
  /* #470: @24 = (2.*@22) */
  for (i=0, rr=w24, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #471: @41 = (@9*@24) */
  for (i=0, rr=w41, cs=w24; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #472: @43 = (@16*@18) */
  w43  = (w16*w18);
  /* #473: @44 = (@0*@66) */
  w44  = (w00*w66);
  /* #474: @43 = (@43-@44) */
  w43 -= w44;
  /* #475: @27 = (@32*@43) */
  for (i=0, rr=w27, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w43);
  /* #476: @41 = (@41+@27) */
  for (i=0, rr=w41, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #477: @41 = (@41/@3) */
  for (i=0, rr=w41; i<3; ++i) (*rr++) /= w03;
  /* #478: @27 = (@33*@18) */
  for (i=0, rr=w27, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)*w18);
  /* #479: @41 = (@41-@27) */
  for (i=0, rr=w41, cs=w27; i<3; ++i) (*rr++) -= (*cs++);
  /* #480: @27 = @41' */
  casadi_copy(w41, 3, w27);
  /* #481: @64 = mac(@27,@35,@1) */
  casadi_copy(w01, 3, w64);
  for (i=0, rr=w64; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w27+j, ct=wr35+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #482: @64 = @64' */
  /* #483: @76 = mac(@27,@37,@1) */
  casadi_copy(w01, 3, w76);
  for (i=0, rr=w76; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w27+j, ct=w37+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #484: @76 = @76' */
  /* #485: @64 = (@64+@76) */
  for (i=0, rr=w64, cs=w76; i<3; ++i) (*rr++) += (*cs++);
  /* #486: @76 = (@64/@3) */
  for (i=0, rr=w76, cr=w64; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #487: @27 = (@40*@18) */
  for (i=0, rr=w27, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w18);
  /* #488: @76 = (@76-@27) */
  for (i=0, rr=w76, cs=w27; i<3; ++i) (*rr++) -= (*cs++);
  /* #489: @44 = dot(@32, @76) */
  w44 = casadi_dot(3, w32, w76);
  /* #490: @47 = dot(@24, @38) */
  w47 = casadi_dot(3, w24, w38);
  /* #491: @44 = (@44+@47) */
  w44 += w47;
  /* #492: @47 = (@0*@44) */
  w47  = (w00*w44);
  /* #493: @67 = (@67+@47) */
  w67 += w47;
  /* #494: @67 = (-@67) */
  w67 = (- w67 );
  /* #495: @68 = @30; (@68[0] += @67) */
  casadi_copy(w30, 4, w68);
  for (rr=w68+0, cs=(&w67); rr!=w68+1; rr+=1) *rr += *cs++;
  /* #496: @67 = dot(@34, @64) */
  w67 = casadi_dot(3, w34, w64);
  /* #497: @41 = (@41/@3) */
  for (i=0, rr=w41; i<3; ++i) (*rr++) /= w03;
  /* #498: @64 = (@25*@18) */
  for (i=0, rr=w64, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)*w18);
  /* #499: @41 = (@41-@64) */
  for (i=0, rr=w41, cs=w64; i<3; ++i) (*rr++) -= (*cs++);
  /* #500: @41 = (-@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) *rr++ = (- *cs++ );
  /* #501: @47 = dot(@41, @36) */
  w47 = casadi_dot(3, w41, w36);
  /* #502: @67 = (@67+@47) */
  w67 += w47;
  /* #503: @66 = (@66/@2) */
  w66 /= w02;
  /* #504: @69 = (@46*@69) */
  w69  = (w46*w69);
  /* #505: @66 = (@66-@69) */
  w66 -= w69;
  /* #506: @66 = (@11*@66) */
  w66  = (w11*w66);
  /* #507: @44 = (@16*@44) */
  w44  = (w16*w44);
  /* #508: @66 = (@66+@44) */
  w66 += w44;
  /* #509: @67 = (@67+@66) */
  w67 += w66;
  /* #510: @67 = (@67/@14) */
  w67 /= w14;
  /* #511: @18 = (@17*@18) */
  w18  = (w17*w18);
  /* #512: @67 = (@67-@18) */
  w67 -= w18;
  /* #513: @41 = (@20*@67) */
  for (i=0, rr=w41, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w67);
  /* #514: @22 = (@10*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #515: @41 = (@41+@22) */
  for (i=0, rr=w41, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #516: @22 = (@38*@43) */
  for (i=0, rr=w22, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w43);
  /* #517: @76 = (@9*@76) */
  for (i=0, rr=w76, cs=w76; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #518: @22 = (@22+@76) */
  for (i=0, rr=w22, cs=w76; i<3; ++i) (*rr++) += (*cs++);
  /* #519: @22 = (2.*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #520: @41 = (@41+@22) */
  for (i=0, rr=w41, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #521: (@68[1:4] += @41) */
  for (rr=w68+1, cs=w41; rr!=w68+4; rr+=1) *rr += *cs++;
  /* #522: @61 = (@12?@68:0) */
  for (i=0, rr=w61, cs=w68; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #523: @68 = (-@68) */
  for (i=0, rr=w68, cs=w68; i<4; ++i) *rr++ = (- *cs++ );
  /* #524: @68 = (@13?@68:0) */
  for (i=0, rr=w68, cs=w68; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #525: @61 = (@61+@68) */
  for (i=0, rr=w61, cs=w68; i<4; ++i) (*rr++) += (*cs++);
  /* #526: {@43, @67, @18, @66} = vertsplit(@61) */
  w43 = w61[0];
  w67 = w61[1];
  w18 = w61[2];
  w66 = w61[3];
  /* #527: @44 = (@7*@66) */
  w44  = (w07*w66);
  /* #528: @69 = (@6*@18) */
  w69  = (w06*w18);
  /* #529: @44 = (@44+@69) */
  w44 += w69;
  /* #530: @69 = (@5*@67) */
  w69  = (w05*w67);
  /* #531: @44 = (@44+@69) */
  w44 += w69;
  /* #532: @69 = (@4*@43) */
  w69  = (w04*w43);
  /* #533: @44 = (@44+@69) */
  w44 += w69;
  /* #534: @69 = (@6*@66) */
  w69  = (w06*w66);
  /* #535: @47 = (@7*@18) */
  w47  = (w07*w18);
  /* #536: @69 = (@69-@47) */
  w69 -= w47;
  /* #537: @47 = (@4*@67) */
  w47  = (w04*w67);
  /* #538: @69 = (@69+@47) */
  w69 += w47;
  /* #539: @47 = (@5*@43) */
  w47  = (w05*w43);
  /* #540: @69 = (@69-@47) */
  w69 -= w47;
  /* #541: @47 = (@4*@18) */
  w47  = (w04*w18);
  /* #542: @70 = (@5*@66) */
  w70  = (w05*w66);
  /* #543: @47 = (@47-@70) */
  w47 -= w70;
  /* #544: @70 = (@7*@67) */
  w70  = (w07*w67);
  /* #545: @47 = (@47+@70) */
  w47 += w70;
  /* #546: @70 = (@6*@43) */
  w70  = (w06*w43);
  /* #547: @47 = (@47-@70) */
  w47 -= w70;
  /* #548: @66 = (@4*@66) */
  w66  = (w04*w66);
  /* #549: @18 = (@5*@18) */
  w18  = (w05*w18);
  /* #550: @66 = (@66+@18) */
  w66 += w18;
  /* #551: @67 = (@6*@67) */
  w67  = (w06*w67);
  /* #552: @66 = (@66-@67) */
  w66 -= w67;
  /* #553: @43 = (@7*@43) */
  w43  = (w07*w43);
  /* #554: @66 = (@66-@43) */
  w66 -= w43;
  /* #555: @61 = vertcat(@44, @69, @47, @66) */
  rr=w61;
  *rr++ = w44;
  *rr++ = w69;
  *rr++ = w47;
  *rr++ = w66;
  /* #556: @44 = dot(@31, @61) */
  w44 = casadi_dot(4, w31, w61);
  /* #557: @62 = (@62/@8) */
  for (i=0, rr=w62; i<4; ++i) (*rr++) /= w08;
  /* #558: @68 = (@63*@52) */
  for (i=0, rr=w68, cr=w63; i<4; ++i) (*rr++)  = ((*cr++)*w52);
  /* #559: @62 = (@62-@68) */
  for (i=0, rr=w62, cs=w68; i<4; ++i) (*rr++) -= (*cs++);
  /* #560: @62 = (-@62) */
  for (i=0, rr=w62, cs=w62; i<4; ++i) *rr++ = (- *cs++ );
  /* #561: @69 = dot(@62, @42) */
  w69 = casadi_dot(4, w62, w42);
  /* #562: @44 = (@44+@69) */
  w44 += w69;
  /* #563: @44 = (@44/@8) */
  w44 /= w08;
  /* #564: @69 = (@65*@52) */
  w69  = (w65*w52);
  /* #565: @44 = (@44-@69) */
  w44 -= w69;
  /* #566: @62 = (@29*@44) */
  for (i=0, rr=w62, cr=w29; i<4; ++i) (*rr++)  = ((*cr++)*w44);
  /* #567: @55 = (@45*@55) */
  w55  = (w45*w55);
  /* #568: @68 = dense(@55) */
  casadi_densify((&w55), casadi_s6, w68, 0);
  /* #569: @62 = (@62+@68) */
  for (i=0, rr=w62, cs=w68; i<4; ++i) (*rr++) += (*cs++);
  /* #570: @49 = @21; (@49[6:10] += @62) */
  casadi_copy(w21, 13, w49);
  for (rr=w49+6, cs=w62; rr!=w49+10; rr+=1) *rr += *cs++;
  /* #571: @56 = sparsity_cast(@56) */
  /* #572: @56 = (-@56) */
  w56 = (- w56 );
  /* #573: @56 = @56' */
  /* #574: @41 = mac(@56,@26,@1) */
  casadi_copy(w01, 3, w41);
  casadi_mtimes((&w56), casadi_s7, wr26, casadi_s2, w41, casadi_s1, w, 0);
  /* #575: @41 = @41' */
  /* #576: @22 = mac(@56,@50,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w56), casadi_s7, w50, casadi_s2, w22, casadi_s1, w, 0);
  /* #577: @22 = @22' */
  /* #578: @41 = (@41+@22) */
  for (i=0, rr=w41, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #579: @41 = (-@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) *rr++ = (- *cs++ );
  /* #580: (@49[3:6] += @41) */
  for (rr=w49+3, cs=w41; rr!=w49+6; rr+=1) *rr += *cs++;
  /* #581: @57 = sparsity_cast(@57) */
  /* #582: @57 = (-@57) */
  w57 = (- w57 );
  /* #583: @57 = @57' */
  /* #584: @41 = mac(@57,@23,@1) */
  casadi_copy(w01, 3, w41);
  casadi_mtimes((&w57), casadi_s7, wr23, casadi_s2, w41, casadi_s1, w, 0);
  /* #585: @41 = @41' */
  /* #586: @22 = mac(@57,@51,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w57), casadi_s7, w51, casadi_s2, w22, casadi_s1, w, 0);
  /* #587: @22 = @22' */
  /* #588: @41 = (@41+@22) */
  for (i=0, rr=w41, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #589: @41 = (-@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) *rr++ = (- *cs++ );
  /* #590: (@49[:3] += @41) */
  for (rr=w49+0, cs=w41; rr!=w49+3; rr+=1) *rr += *cs++;
  /* #591: {@57, @56, @55, @44, @69, @47, @66, @43, @67, @18, @70, @71, @74} = vertsplit(@49) */
  w57 = w49[0];
  w56 = w49[1];
  w55 = w49[2];
  w44 = w49[3];
  w69 = w49[4];
  w47 = w49[5];
  w66 = w49[6];
  w43 = w49[7];
  w67 = w49[8];
  w18 = w49[9];
  w70 = w49[10];
  w71 = w49[11];
  w74 = w49[12];
  /* #592: @61 = (@61/@8) */
  for (i=0, rr=w61; i<4; ++i) (*rr++) /= w08;
  /* #593: @62 = (@39*@52) */
  for (i=0, rr=w62, cr=w39; i<4; ++i) (*rr++)  = ((*cr++)*w52);
  /* #594: @61 = (@61-@62) */
  for (i=0, rr=w61, cs=w62; i<4; ++i) (*rr++) -= (*cs++);
  /* #595: {@52, @73, @72, @53} = vertsplit(@61) */
  w52 = w61[0];
  w73 = w61[1];
  w72 = w61[2];
  w53 = w61[3];
  /* #596: @52 = (@52+@66) */
  w52 += w66;
  /* #597: @43 = (@43-@73) */
  w43 -= w73;
  /* #598: @67 = (@67-@72) */
  w67 -= w72;
  /* #599: @18 = (@18-@53) */
  w18 -= w53;
  /* #600: @49 = vertcat(@57, @56, @55, @44, @69, @47, @52, @43, @67, @18, @70, @71, @74) */
  rr=w49;
  *rr++ = w57;
  *rr++ = w56;
  *rr++ = w55;
  *rr++ = w44;
  *rr++ = w69;
  *rr++ = w47;
  *rr++ = w52;
  *rr++ = w43;
  *rr++ = w67;
  *rr++ = w18;
  *rr++ = w70;
  *rr++ = w71;
  *rr++ = w74;
  /* #601: @75 = @49[:10] */
  for (rr=w75, cs=w49+0; cs!=w49+10; cs+=1) *rr++ = *cs;
  /* #602: (@58[3, 4, 5, 12, 13, 14, 22, 23, 24, 25] = @75) */
  for (cii=casadi_s8, rr=w58, cs=w75; cii!=casadi_s8+10; ++cii, ++cs) rr[*cii] = *cs;
  /* #603: (@58[1, 4, 7, 10, 13, 16, 19, 23, 27, 31] = @75) */
  for (cii=casadi_s9, rr=w58, cs=w75; cii!=casadi_s9+10; ++cii, ++cs) rr[*cii] = *cs;
  /* #604: @41 = ones(13x1,3nz) */
  casadi_fill(w41, 3, 1.);
  /* #605: {NULL, NULL, @57, NULL, NULL, @56, NULL, NULL, @55, NULL, NULL, NULL, NULL} = vertsplit(@41) */
  w57 = w41[0];
  w56 = w41[1];
  w55 = w41[2];
  /* #606: @44 = (-@55) */
  w44 = (- w55 );
  /* #607: @69 = vertcat(@60, @60, @44, @60) */
  rr=(&w69);
  *rr++ = w44;
  /* #608: @69 = (@69/@8) */
  w69 /= w08;
  /* #609: @61 = dense(@69) */
  casadi_densify((&w69), casadi_s10, w61, 0);
  /* #610: @69 = project(@29) */
  casadi_sparsify(w29, (&w69), casadi_s10, 0);
  /* #611: @55 = sparsity_cast(@55) */
  /* #612: @44 = dot(@69, @55) */
  w44 = casadi_dot(1, (&w69), (&w55));
  /* #613: @44 = (@44/@8) */
  w44 /= w08;
  /* #614: @62 = (@28*@44) */
  for (i=0, rr=w62, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)*w44);
  /* #615: @61 = (@61-@62) */
  for (i=0, rr=w61, cs=w62; i<4; ++i) (*rr++) -= (*cs++);
  /* #616: {@69, @47, @52, @43} = vertsplit(@61) */
  w69 = w61[0];
  w47 = w61[1];
  w52 = w61[2];
  w43 = w61[3];
  /* #617: @67 = (@4*@69) */
  w67  = (w04*w69);
  /* #618: @18 = (@5*@47) */
  w18  = (w05*w47);
  /* #619: @67 = (@67-@18) */
  w67 -= w18;
  /* #620: @18 = (@6*@52) */
  w18  = (w06*w52);
  /* #621: @67 = (@67-@18) */
  w67 -= w18;
  /* #622: @18 = (@7*@43) */
  w18  = (w07*w43);
  /* #623: @67 = (@67-@18) */
  w67 -= w18;
  /* #624: @18 = (@5*@69) */
  w18  = (w05*w69);
  /* #625: @70 = (@4*@47) */
  w70  = (w04*w47);
  /* #626: @18 = (@18+@70) */
  w18 += w70;
  /* #627: @70 = (@7*@52) */
  w70  = (w07*w52);
  /* #628: @18 = (@18+@70) */
  w18 += w70;
  /* #629: @70 = (@6*@43) */
  w70  = (w06*w43);
  /* #630: @18 = (@18-@70) */
  w18 -= w70;
  /* #631: @70 = (@6*@69) */
  w70  = (w06*w69);
  /* #632: @71 = (@7*@47) */
  w71  = (w07*w47);
  /* #633: @70 = (@70-@71) */
  w70 -= w71;
  /* #634: @71 = (@4*@52) */
  w71  = (w04*w52);
  /* #635: @70 = (@70+@71) */
  w70 += w71;
  /* #636: @71 = (@5*@43) */
  w71  = (w05*w43);
  /* #637: @70 = (@70+@71) */
  w70 += w71;
  /* #638: @69 = (@7*@69) */
  w69  = (w07*w69);
  /* #639: @47 = (@6*@47) */
  w47  = (w06*w47);
  /* #640: @69 = (@69+@47) */
  w69 += w47;
  /* #641: @52 = (@5*@52) */
  w52  = (w05*w52);
  /* #642: @69 = (@69-@52) */
  w69 -= w52;
  /* #643: @43 = (@4*@43) */
  w43  = (w04*w43);
  /* #644: @69 = (@69+@43) */
  w69 += w43;
  /* #645: @62 = vertcat(@67, @18, @70, @69) */
  rr=w62;
  *rr++ = w67;
  *rr++ = w18;
  *rr++ = w70;
  *rr++ = w69;
  /* #646: @68 = (-@62) */
  for (i=0, rr=w68, cs=w62; i<4; ++i) *rr++ = (- *cs++ );
  /* #647: @68 = (@13?@68:0) */
  for (i=0, rr=w68, cs=w68; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #648: @62 = (@12?@62:0) */
  for (i=0, rr=w62, cs=w62; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #649: @68 = (@68+@62) */
  for (i=0, rr=w68, cs=w62; i<4; ++i) (*rr++) += (*cs++);
  /* #650: @41 = @68[1:4] */
  for (rr=w41, cs=w68+1; cs!=w68+4; cs+=1) *rr++ = *cs;
  /* #651: @67 = dot(@20, @41) */
  w67 = casadi_dot(3, w20, w41);
  /* #652: @67 = (@67/@14) */
  w67 /= w14;
  /* #653: @18 = (@67/@2) */
  w18  = (w67/w02);
  /* #654: @70 = (@54*@67) */
  w70  = (w54*w67);
  /* #655: @69 = @68[0] */
  for (rr=(&w69), cs=w68+0; cs!=w68+1; cs+=1) *rr++ = *cs;
  /* #656: @43 = (@15*@69) */
  w43  = (w15*w69);
  /* #657: @70 = (@70+@43) */
  w70 += w43;
  /* #658: @43 = (@48*@70) */
  w43  = (w48*w70);
  /* #659: @18 = (@18-@43) */
  w18 -= w43;
  /* #660: @18 = (@11*@18) */
  w18  = (w11*w18);
  /* #661: @22 = (2.*@41) */
  for (i=0, rr=w22, cs=w41; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #662: @76 = (@9*@22) */
  for (i=0, rr=w76, cs=w22; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #663: @43 = (@16*@67) */
  w43  = (w16*w67);
  /* #664: @52 = (@0*@69) */
  w52  = (w00*w69);
  /* #665: @43 = (@43-@52) */
  w43 -= w52;
  /* #666: @64 = (@32*@43) */
  for (i=0, rr=w64, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w43);
  /* #667: @76 = (@76+@64) */
  for (i=0, rr=w76, cs=w64; i<3; ++i) (*rr++) += (*cs++);
  /* #668: @76 = (@76/@3) */
  for (i=0, rr=w76; i<3; ++i) (*rr++) /= w03;
  /* #669: @64 = (@33*@67) */
  for (i=0, rr=w64, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)*w67);
  /* #670: @76 = (@76-@64) */
  for (i=0, rr=w76, cs=w64; i<3; ++i) (*rr++) -= (*cs++);
  /* #671: @64 = @76' */
  casadi_copy(w76, 3, w64);
  /* #672: @24 = mac(@64,@35,@1) */
  casadi_copy(w01, 3, w24);
  for (i=0, rr=w24; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w64+j, ct=wr35+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #673: @24 = @24' */
  /* #674: @27 = mac(@64,@37,@1) */
  casadi_copy(w01, 3, w27);
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w64+j, ct=w37+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #675: @27 = @27' */
  /* #676: @24 = (@24+@27) */
  for (i=0, rr=w24, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #677: @27 = (@24/@3) */
  for (i=0, rr=w27, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #678: @64 = (@40*@67) */
  for (i=0, rr=w64, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w67);
  /* #679: @27 = (@27-@64) */
  for (i=0, rr=w27, cs=w64; i<3; ++i) (*rr++) -= (*cs++);
  /* #680: @52 = dot(@32, @27) */
  w52 = casadi_dot(3, w32, w27);
  /* #681: @47 = dot(@22, @38) */
  w47 = casadi_dot(3, w22, w38);
  /* #682: @52 = (@52+@47) */
  w52 += w47;
  /* #683: @47 = (@0*@52) */
  w47  = (w00*w52);
  /* #684: @18 = (@18+@47) */
  w18 += w47;
  /* #685: @18 = (-@18) */
  w18 = (- w18 );
  /* #686: @68 = @30; (@68[0] += @18) */
  casadi_copy(w30, 4, w68);
  for (rr=w68+0, cs=(&w18); rr!=w68+1; rr+=1) *rr += *cs++;
  /* #687: @18 = dot(@34, @24) */
  w18 = casadi_dot(3, w34, w24);
  /* #688: @76 = (@76/@3) */
  for (i=0, rr=w76; i<3; ++i) (*rr++) /= w03;
  /* #689: @24 = (@25*@67) */
  for (i=0, rr=w24, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)*w67);
  /* #690: @76 = (@76-@24) */
  for (i=0, rr=w76, cs=w24; i<3; ++i) (*rr++) -= (*cs++);
  /* #691: @76 = (-@76) */
  for (i=0, rr=w76, cs=w76; i<3; ++i) *rr++ = (- *cs++ );
  /* #692: @47 = dot(@76, @36) */
  w47 = casadi_dot(3, w76, w36);
  /* #693: @18 = (@18+@47) */
  w18 += w47;
  /* #694: @69 = (@69/@2) */
  w69 /= w02;
  /* #695: @70 = (@46*@70) */
  w70  = (w46*w70);
  /* #696: @69 = (@69-@70) */
  w69 -= w70;
  /* #697: @69 = (@11*@69) */
  w69  = (w11*w69);
  /* #698: @52 = (@16*@52) */
  w52  = (w16*w52);
  /* #699: @69 = (@69+@52) */
  w69 += w52;
  /* #700: @18 = (@18+@69) */
  w18 += w69;
  /* #701: @18 = (@18/@14) */
  w18 /= w14;
  /* #702: @67 = (@17*@67) */
  w67  = (w17*w67);
  /* #703: @18 = (@18-@67) */
  w18 -= w67;
  /* #704: @76 = (@20*@18) */
  for (i=0, rr=w76, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w18);
  /* #705: @41 = (@10*@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #706: @76 = (@76+@41) */
  for (i=0, rr=w76, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #707: @41 = (@38*@43) */
  for (i=0, rr=w41, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)*w43);
  /* #708: @27 = (@9*@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #709: @41 = (@41+@27) */
  for (i=0, rr=w41, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #710: @41 = (2.*@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #711: @76 = (@76+@41) */
  for (i=0, rr=w76, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #712: (@68[1:4] += @76) */
  for (rr=w68+1, cs=w76; rr!=w68+4; rr+=1) *rr += *cs++;
  /* #713: @62 = (@12?@68:0) */
  for (i=0, rr=w62, cs=w68; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #714: @68 = (-@68) */
  for (i=0, rr=w68, cs=w68; i<4; ++i) *rr++ = (- *cs++ );
  /* #715: @68 = (@13?@68:0) */
  for (i=0, rr=w68, cs=w68; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #716: @62 = (@62+@68) */
  for (i=0, rr=w62, cs=w68; i<4; ++i) (*rr++) += (*cs++);
  /* #717: {@43, @18, @67, @69} = vertsplit(@62) */
  w43 = w62[0];
  w18 = w62[1];
  w67 = w62[2];
  w69 = w62[3];
  /* #718: @52 = (@7*@69) */
  w52  = (w07*w69);
  /* #719: @70 = (@6*@67) */
  w70  = (w06*w67);
  /* #720: @52 = (@52+@70) */
  w52 += w70;
  /* #721: @70 = (@5*@18) */
  w70  = (w05*w18);
  /* #722: @52 = (@52+@70) */
  w52 += w70;
  /* #723: @70 = (@4*@43) */
  w70  = (w04*w43);
  /* #724: @52 = (@52+@70) */
  w52 += w70;
  /* #725: @70 = (@6*@69) */
  w70  = (w06*w69);
  /* #726: @47 = (@7*@67) */
  w47  = (w07*w67);
  /* #727: @70 = (@70-@47) */
  w70 -= w47;
  /* #728: @47 = (@4*@18) */
  w47  = (w04*w18);
  /* #729: @70 = (@70+@47) */
  w70 += w47;
  /* #730: @47 = (@5*@43) */
  w47  = (w05*w43);
  /* #731: @70 = (@70-@47) */
  w70 -= w47;
  /* #732: @47 = (@4*@67) */
  w47  = (w04*w67);
  /* #733: @71 = (@5*@69) */
  w71  = (w05*w69);
  /* #734: @47 = (@47-@71) */
  w47 -= w71;
  /* #735: @71 = (@7*@18) */
  w71  = (w07*w18);
  /* #736: @47 = (@47+@71) */
  w47 += w71;
  /* #737: @71 = (@6*@43) */
  w71  = (w06*w43);
  /* #738: @47 = (@47-@71) */
  w47 -= w71;
  /* #739: @69 = (@4*@69) */
  w69  = (w04*w69);
  /* #740: @67 = (@5*@67) */
  w67  = (w05*w67);
  /* #741: @69 = (@69+@67) */
  w69 += w67;
  /* #742: @18 = (@6*@18) */
  w18  = (w06*w18);
  /* #743: @69 = (@69-@18) */
  w69 -= w18;
  /* #744: @43 = (@7*@43) */
  w43  = (w07*w43);
  /* #745: @69 = (@69-@43) */
  w69 -= w43;
  /* #746: @62 = vertcat(@52, @70, @47, @69) */
  rr=w62;
  *rr++ = w52;
  *rr++ = w70;
  *rr++ = w47;
  *rr++ = w69;
  /* #747: @52 = dot(@31, @62) */
  w52 = casadi_dot(4, w31, w62);
  /* #748: @61 = (@61/@8) */
  for (i=0, rr=w61; i<4; ++i) (*rr++) /= w08;
  /* #749: @68 = (@63*@44) */
  for (i=0, rr=w68, cr=w63; i<4; ++i) (*rr++)  = ((*cr++)*w44);
  /* #750: @61 = (@61-@68) */
  for (i=0, rr=w61, cs=w68; i<4; ++i) (*rr++) -= (*cs++);
  /* #751: @61 = (-@61) */
  for (i=0, rr=w61, cs=w61; i<4; ++i) *rr++ = (- *cs++ );
  /* #752: @70 = dot(@61, @42) */
  w70 = casadi_dot(4, w61, w42);
  /* #753: @52 = (@52+@70) */
  w52 += w70;
  /* #754: @52 = (@52/@8) */
  w52 /= w08;
  /* #755: @70 = (@65*@44) */
  w70  = (w65*w44);
  /* #756: @52 = (@52-@70) */
  w52 -= w70;
  /* #757: @61 = (@29*@52) */
  for (i=0, rr=w61, cr=w29; i<4; ++i) (*rr++)  = ((*cr++)*w52);
  /* #758: @55 = (@45*@55) */
  w55  = (w45*w55);
  /* #759: @68 = dense(@55) */
  casadi_densify((&w55), casadi_s10, w68, 0);
  /* #760: @61 = (@61+@68) */
  for (i=0, rr=w61, cs=w68; i<4; ++i) (*rr++) += (*cs++);
  /* #761: @49 = @21; (@49[6:10] += @61) */
  casadi_copy(w21, 13, w49);
  for (rr=w49+6, cs=w61; rr!=w49+10; rr+=1) *rr += *cs++;
  /* #762: @56 = sparsity_cast(@56) */
  /* #763: @56 = (-@56) */
  w56 = (- w56 );
  /* #764: @56 = @56' */
  /* #765: @76 = mac(@56,@26,@1) */
  casadi_copy(w01, 3, w76);
  casadi_mtimes((&w56), casadi_s11, wr26, casadi_s2, w76, casadi_s1, w, 0);
  /* #766: @76 = @76' */
  /* #767: @41 = mac(@56,@50,@1) */
  casadi_copy(w01, 3, w41);
  casadi_mtimes((&w56), casadi_s11, w50, casadi_s2, w41, casadi_s1, w, 0);
  /* #768: @41 = @41' */
  /* #769: @76 = (@76+@41) */
  for (i=0, rr=w76, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #770: @76 = (-@76) */
  for (i=0, rr=w76, cs=w76; i<3; ++i) *rr++ = (- *cs++ );
  /* #771: (@49[3:6] += @76) */
  for (rr=w49+3, cs=w76; rr!=w49+6; rr+=1) *rr += *cs++;
  /* #772: @57 = sparsity_cast(@57) */
  /* #773: @57 = (-@57) */
  w57 = (- w57 );
  /* #774: @57 = @57' */
  /* #775: @76 = mac(@57,@23,@1) */
  casadi_copy(w01, 3, w76);
  casadi_mtimes((&w57), casadi_s11, wr23, casadi_s2, w76, casadi_s1, w, 0);
  /* #776: @76 = @76' */
  /* #777: @41 = mac(@57,@51,@1) */
  casadi_copy(w01, 3, w41);
  casadi_mtimes((&w57), casadi_s11, w51, casadi_s2, w41, casadi_s1, w, 0);
  /* #778: @41 = @41' */
  /* #779: @76 = (@76+@41) */
  for (i=0, rr=w76, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #780: @76 = (-@76) */
  for (i=0, rr=w76, cs=w76; i<3; ++i) *rr++ = (- *cs++ );
  /* #781: (@49[:3] += @76) */
  for (rr=w49+0, cs=w76; rr!=w49+3; rr+=1) *rr += *cs++;
  /* #782: {@57, @56, @55, @52, @70, @47, @69, @43, @18, @67, @71, @74, @53} = vertsplit(@49) */
  w57 = w49[0];
  w56 = w49[1];
  w55 = w49[2];
  w52 = w49[3];
  w70 = w49[4];
  w47 = w49[5];
  w69 = w49[6];
  w43 = w49[7];
  w18 = w49[8];
  w67 = w49[9];
  w71 = w49[10];
  w74 = w49[11];
  w53 = w49[12];
  /* #783: @62 = (@62/@8) */
  for (i=0, rr=w62; i<4; ++i) (*rr++) /= w08;
  /* #784: @61 = (@39*@44) */
  for (i=0, rr=w61, cr=w39; i<4; ++i) (*rr++)  = ((*cr++)*w44);
  /* #785: @62 = (@62-@61) */
  for (i=0, rr=w62, cs=w61; i<4; ++i) (*rr++) -= (*cs++);
  /* #786: {@44, @72, @73, @66} = vertsplit(@62) */
  w44 = w62[0];
  w72 = w62[1];
  w73 = w62[2];
  w66 = w62[3];
  /* #787: @44 = (@44+@69) */
  w44 += w69;
  /* #788: @43 = (@43-@72) */
  w43 -= w72;
  /* #789: @18 = (@18-@73) */
  w18 -= w73;
  /* #790: @67 = (@67-@66) */
  w67 -= w66;
  /* #791: @49 = vertcat(@57, @56, @55, @52, @70, @47, @44, @43, @18, @67, @71, @74, @53) */
  rr=w49;
  *rr++ = w57;
  *rr++ = w56;
  *rr++ = w55;
  *rr++ = w52;
  *rr++ = w70;
  *rr++ = w47;
  *rr++ = w44;
  *rr++ = w43;
  *rr++ = w18;
  *rr++ = w67;
  *rr++ = w71;
  *rr++ = w74;
  *rr++ = w53;
  /* #792: @75 = @49[:10] */
  for (rr=w75, cs=w49+0; cs!=w49+10; cs+=1) *rr++ = *cs;
  /* #793: (@58[6, 7, 8, 15, 16, 17, 26, 27, 28, 29] = @75) */
  for (cii=casadi_s12, rr=w58, cs=w75; cii!=casadi_s12+10; ++cii, ++cs) rr[*cii] = *cs;
  /* #794: (@58[2, 5, 8, 11, 14, 17, 20, 24, 28, 32] = @75) */
  for (cii=casadi_s13, rr=w58, cs=w75; cii!=casadi_s13+10; ++cii, ++cs) rr[*cii] = *cs;
  /* #795: @57 = ones(13x1,1nz) */
  w57 = 1.;
  /* #796: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @56, NULL, NULL, NULL} = vertsplit(@57) */
  w56 = w57;
  /* #797: @57 = (-@56) */
  w57 = (- w56 );
  /* #798: @55 = vertcat(@60, @60, @60, @57) */
  rr=(&w55);
  *rr++ = w57;
  /* #799: @55 = (@55/@8) */
  w55 /= w08;
  /* #800: @62 = dense(@55) */
  casadi_densify((&w55), casadi_s14, w62, 0);
  /* #801: @55 = project(@29) */
  casadi_sparsify(w29, (&w55), casadi_s14, 0);
  /* #802: @56 = sparsity_cast(@56) */
  /* #803: @57 = dot(@55, @56) */
  w57 = casadi_dot(1, (&w55), (&w56));
  /* #804: @57 = (@57/@8) */
  w57 /= w08;
  /* #805: @28 = (@28*@57) */
  for (i=0, rr=w28; i<4; ++i) (*rr++) *= w57;
  /* #806: @62 = (@62-@28) */
  for (i=0, rr=w62, cs=w28; i<4; ++i) (*rr++) -= (*cs++);
  /* #807: {@55, @52, @70, @47} = vertsplit(@62) */
  w55 = w62[0];
  w52 = w62[1];
  w70 = w62[2];
  w47 = w62[3];
  /* #808: @44 = (@4*@55) */
  w44  = (w04*w55);
  /* #809: @43 = (@5*@52) */
  w43  = (w05*w52);
  /* #810: @44 = (@44-@43) */
  w44 -= w43;
  /* #811: @43 = (@6*@70) */
  w43  = (w06*w70);
  /* #812: @44 = (@44-@43) */
  w44 -= w43;
  /* #813: @43 = (@7*@47) */
  w43  = (w07*w47);
  /* #814: @44 = (@44-@43) */
  w44 -= w43;
  /* #815: @43 = (@5*@55) */
  w43  = (w05*w55);
  /* #816: @18 = (@4*@52) */
  w18  = (w04*w52);
  /* #817: @43 = (@43+@18) */
  w43 += w18;
  /* #818: @18 = (@7*@70) */
  w18  = (w07*w70);
  /* #819: @43 = (@43+@18) */
  w43 += w18;
  /* #820: @18 = (@6*@47) */
  w18  = (w06*w47);
  /* #821: @43 = (@43-@18) */
  w43 -= w18;
  /* #822: @18 = (@6*@55) */
  w18  = (w06*w55);
  /* #823: @67 = (@7*@52) */
  w67  = (w07*w52);
  /* #824: @18 = (@18-@67) */
  w18 -= w67;
  /* #825: @67 = (@4*@70) */
  w67  = (w04*w70);
  /* #826: @18 = (@18+@67) */
  w18 += w67;
  /* #827: @67 = (@5*@47) */
  w67  = (w05*w47);
  /* #828: @18 = (@18+@67) */
  w18 += w67;
  /* #829: @55 = (@7*@55) */
  w55  = (w07*w55);
  /* #830: @52 = (@6*@52) */
  w52  = (w06*w52);
  /* #831: @55 = (@55+@52) */
  w55 += w52;
  /* #832: @70 = (@5*@70) */
  w70  = (w05*w70);
  /* #833: @55 = (@55-@70) */
  w55 -= w70;
  /* #834: @47 = (@4*@47) */
  w47  = (w04*w47);
  /* #835: @55 = (@55+@47) */
  w55 += w47;
  /* #836: @28 = vertcat(@44, @43, @18, @55) */
  rr=w28;
  *rr++ = w44;
  *rr++ = w43;
  *rr++ = w18;
  *rr++ = w55;
  /* #837: @61 = (-@28) */
  for (i=0, rr=w61, cs=w28; i<4; ++i) *rr++ = (- *cs++ );
  /* #838: @61 = (@13?@61:0) */
  for (i=0, rr=w61, cs=w61; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #839: @28 = (@12?@28:0) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #840: @61 = (@61+@28) */
  for (i=0, rr=w61, cs=w28; i<4; ++i) (*rr++) += (*cs++);
  /* #841: @76 = @61[1:4] */
  for (rr=w76, cs=w61+1; cs!=w61+4; cs+=1) *rr++ = *cs;
  /* #842: @44 = dot(@20, @76) */
  w44 = casadi_dot(3, w20, w76);
  /* #843: @44 = (@44/@14) */
  w44 /= w14;
  /* #844: @43 = (@44/@2) */
  w43  = (w44/w02);
  /* #845: @54 = (@54*@44) */
  w54 *= w44;
  /* #846: @18 = @61[0] */
  for (rr=(&w18), cs=w61+0; cs!=w61+1; cs+=1) *rr++ = *cs;
  /* #847: @15 = (@15*@18) */
  w15 *= w18;
  /* #848: @54 = (@54+@15) */
  w54 += w15;
  /* #849: @48 = (@48*@54) */
  w48 *= w54;
  /* #850: @43 = (@43-@48) */
  w43 -= w48;
  /* #851: @43 = (@11*@43) */
  w43  = (w11*w43);
  /* #852: @41 = (2.*@76) */
  for (i=0, rr=w41, cs=w76; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #853: @27 = (@9*@41) */
  for (i=0, rr=w27, cs=w41; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #854: @48 = (@16*@44) */
  w48  = (w16*w44);
  /* #855: @15 = (@0*@18) */
  w15  = (w00*w18);
  /* #856: @48 = (@48-@15) */
  w48 -= w15;
  /* #857: @24 = (@32*@48) */
  for (i=0, rr=w24, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w48);
  /* #858: @27 = (@27+@24) */
  for (i=0, rr=w27, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #859: @27 = (@27/@3) */
  for (i=0, rr=w27; i<3; ++i) (*rr++) /= w03;
  /* #860: @33 = (@33*@44) */
  for (i=0, rr=w33; i<3; ++i) (*rr++) *= w44;
  /* #861: @27 = (@27-@33) */
  for (i=0, rr=w27, cs=w33; i<3; ++i) (*rr++) -= (*cs++);
  /* #862: @33 = @27' */
  casadi_copy(w27, 3, w33);
  /* #863: @24 = mac(@33,@35,@1) */
  casadi_copy(w01, 3, w24);
  for (i=0, rr=w24; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w33+j, ct=wr35+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #864: @24 = @24' */
  /* #865: @1 = mac(@33,@37,@1) */
  for (i=0, rr=w01; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w33+j, ct=w37+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #866: @1 = @1' */
  /* #867: @24 = (@24+@1) */
  for (i=0, rr=w24, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #868: @1 = (@24/@3) */
  for (i=0, rr=w01, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)/w03);
  /* #869: @40 = (@40*@44) */
  for (i=0, rr=w40; i<3; ++i) (*rr++) *= w44;
  /* #870: @1 = (@1-@40) */
  for (i=0, rr=w01, cs=w40; i<3; ++i) (*rr++) -= (*cs++);
  /* #871: @15 = dot(@32, @1) */
  w15 = casadi_dot(3, w32, w01);
  /* #872: @55 = dot(@41, @38) */
  w55 = casadi_dot(3, w41, w38);
  /* #873: @15 = (@15+@55) */
  w15 += w55;
  /* #874: @0 = (@0*@15) */
  w00 *= w15;
  /* #875: @43 = (@43+@0) */
  w43 += w00;
  /* #876: @43 = (-@43) */
  w43 = (- w43 );
  /* #877: (@30[0] += @43) */
  for (rr=w30+0, cs=(&w43); rr!=w30+1; rr+=1) *rr += *cs++;
  /* #878: @43 = dot(@34, @24) */
  w43 = casadi_dot(3, w34, w24);
  /* #879: @27 = (@27/@3) */
  for (i=0, rr=w27; i<3; ++i) (*rr++) /= w03;
  /* #880: @25 = (@25*@44) */
  for (i=0, rr=w25; i<3; ++i) (*rr++) *= w44;
  /* #881: @27 = (@27-@25) */
  for (i=0, rr=w27, cs=w25; i<3; ++i) (*rr++) -= (*cs++);
  /* #882: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) *rr++ = (- *cs++ );
  /* #883: @3 = dot(@27, @36) */
  w03 = casadi_dot(3, w27, w36);
  /* #884: @43 = (@43+@3) */
  w43 += w03;
  /* #885: @18 = (@18/@2) */
  w18 /= w02;
  /* #886: @46 = (@46*@54) */
  w46 *= w54;
  /* #887: @18 = (@18-@46) */
  w18 -= w46;
  /* #888: @11 = (@11*@18) */
  w11 *= w18;
  /* #889: @16 = (@16*@15) */
  w16 *= w15;
  /* #890: @11 = (@11+@16) */
  w11 += w16;
  /* #891: @43 = (@43+@11) */
  w43 += w11;
  /* #892: @43 = (@43/@14) */
  w43 /= w14;
  /* #893: @17 = (@17*@44) */
  w17 *= w44;
  /* #894: @43 = (@43-@17) */
  w43 -= w17;
  /* #895: @20 = (@20*@43) */
  for (i=0, rr=w20; i<3; ++i) (*rr++) *= w43;
  /* #896: @76 = (@10*@76) */
  for (i=0, rr=w76, cs=w76; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #897: @20 = (@20+@76) */
  for (i=0, rr=w20, cs=w76; i<3; ++i) (*rr++) += (*cs++);
  /* #898: @38 = (@38*@48) */
  for (i=0, rr=w38; i<3; ++i) (*rr++) *= w48;
  /* #899: @1 = (@9*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) (*rr++)  = (w09*(*cs++));
  /* #900: @38 = (@38+@1) */
  for (i=0, rr=w38, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #901: @38 = (2.*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #902: @20 = (@20+@38) */
  for (i=0, rr=w20, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #903: (@30[1:4] += @20) */
  for (rr=w30+1, cs=w20; rr!=w30+4; rr+=1) *rr += *cs++;
  /* #904: @61 = (@12?@30:0) */
  for (i=0, rr=w61, cs=w30; i<4; ++i) (*rr++)  = (w12?cs[i]:0);
  /* #905: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) *rr++ = (- *cs++ );
  /* #906: @30 = (@13?@30:0) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #907: @61 = (@61+@30) */
  for (i=0, rr=w61, cs=w30; i<4; ++i) (*rr++) += (*cs++);
  /* #908: {@13, @12, @9, @48} = vertsplit(@61) */
  w13 = w61[0];
  w12 = w61[1];
  w09 = w61[2];
  w48 = w61[3];
  /* #909: @10 = (@7*@48) */
  w10  = (w07*w48);
  /* #910: @43 = (@6*@9) */
  w43  = (w06*w09);
  /* #911: @10 = (@10+@43) */
  w10 += w43;
  /* #912: @43 = (@5*@12) */
  w43  = (w05*w12);
  /* #913: @10 = (@10+@43) */
  w10 += w43;
  /* #914: @43 = (@4*@13) */
  w43  = (w04*w13);
  /* #915: @10 = (@10+@43) */
  w10 += w43;
  /* #916: @43 = (@6*@48) */
  w43  = (w06*w48);
  /* #917: @17 = (@7*@9) */
  w17  = (w07*w09);
  /* #918: @43 = (@43-@17) */
  w43 -= w17;
  /* #919: @17 = (@4*@12) */
  w17  = (w04*w12);
  /* #920: @43 = (@43+@17) */
  w43 += w17;
  /* #921: @17 = (@5*@13) */
  w17  = (w05*w13);
  /* #922: @43 = (@43-@17) */
  w43 -= w17;
  /* #923: @17 = (@4*@9) */
  w17  = (w04*w09);
  /* #924: @44 = (@5*@48) */
  w44  = (w05*w48);
  /* #925: @17 = (@17-@44) */
  w17 -= w44;
  /* #926: @44 = (@7*@12) */
  w44  = (w07*w12);
  /* #927: @17 = (@17+@44) */
  w17 += w44;
  /* #928: @44 = (@6*@13) */
  w44  = (w06*w13);
  /* #929: @17 = (@17-@44) */
  w17 -= w44;
  /* #930: @4 = (@4*@48) */
  w04 *= w48;
  /* #931: @5 = (@5*@9) */
  w05 *= w09;
  /* #932: @4 = (@4+@5) */
  w04 += w05;
  /* #933: @6 = (@6*@12) */
  w06 *= w12;
  /* #934: @4 = (@4-@6) */
  w04 -= w06;
  /* #935: @7 = (@7*@13) */
  w07 *= w13;
  /* #936: @4 = (@4-@7) */
  w04 -= w07;
  /* #937: @61 = vertcat(@10, @43, @17, @4) */
  rr=w61;
  *rr++ = w10;
  *rr++ = w43;
  *rr++ = w17;
  *rr++ = w04;
  /* #938: @10 = dot(@31, @61) */
  w10 = casadi_dot(4, w31, w61);
  /* #939: @62 = (@62/@8) */
  for (i=0, rr=w62; i<4; ++i) (*rr++) /= w08;
  /* #940: @63 = (@63*@57) */
  for (i=0, rr=w63; i<4; ++i) (*rr++) *= w57;
  /* #941: @62 = (@62-@63) */
  for (i=0, rr=w62, cs=w63; i<4; ++i) (*rr++) -= (*cs++);
  /* #942: @62 = (-@62) */
  for (i=0, rr=w62, cs=w62; i<4; ++i) *rr++ = (- *cs++ );
  /* #943: @43 = dot(@62, @42) */
  w43 = casadi_dot(4, w62, w42);
  /* #944: @10 = (@10+@43) */
  w10 += w43;
  /* #945: @10 = (@10/@8) */
  w10 /= w08;
  /* #946: @65 = (@65*@57) */
  w65 *= w57;
  /* #947: @10 = (@10-@65) */
  w10 -= w65;
  /* #948: @29 = (@29*@10) */
  for (i=0, rr=w29; i<4; ++i) (*rr++) *= w10;
  /* #949: @45 = (@45*@56) */
  w45 *= w56;
  /* #950: @62 = dense(@45) */
  casadi_densify((&w45), casadi_s14, w62, 0);
  /* #951: @29 = (@29+@62) */
  for (i=0, rr=w29, cs=w62; i<4; ++i) (*rr++) += (*cs++);
  /* #952: (@21[6:10] += @29) */
  for (rr=w21+6, cs=w29; rr!=w21+10; rr+=1) *rr += *cs++;
  /* #953: {@45, @56, @10, @65, @43, @17, @4, @7, @13, @6, @12, @5, @9} = vertsplit(@21) */
  w45 = w21[0];
  w56 = w21[1];
  w10 = w21[2];
  w65 = w21[3];
  w43 = w21[4];
  w17 = w21[5];
  w04 = w21[6];
  w07 = w21[7];
  w13 = w21[8];
  w06 = w21[9];
  w12 = w21[10];
  w05 = w21[11];
  w09 = w21[12];
  /* #954: @61 = (@61/@8) */
  for (i=0, rr=w61; i<4; ++i) (*rr++) /= w08;
  /* #955: @39 = (@39*@57) */
  for (i=0, rr=w39; i<4; ++i) (*rr++) *= w57;
  /* #956: @61 = (@61-@39) */
  for (i=0, rr=w61, cs=w39; i<4; ++i) (*rr++) -= (*cs++);
  /* #957: {@57, @8, @48, @44} = vertsplit(@61) */
  w57 = w61[0];
  w08 = w61[1];
  w48 = w61[2];
  w44 = w61[3];
  /* #958: @57 = (@57+@4) */
  w57 += w04;
  /* #959: @7 = (@7-@8) */
  w07 -= w08;
  /* #960: @13 = (@13-@48) */
  w13 -= w48;
  /* #961: @6 = (@6-@44) */
  w06 -= w44;
  /* #962: @21 = vertcat(@45, @56, @10, @65, @43, @17, @57, @7, @13, @6, @12, @5, @9) */
  rr=w21;
  *rr++ = w45;
  *rr++ = w56;
  *rr++ = w10;
  *rr++ = w65;
  *rr++ = w43;
  *rr++ = w17;
  *rr++ = w57;
  *rr++ = w07;
  *rr++ = w13;
  *rr++ = w06;
  *rr++ = w12;
  *rr++ = w05;
  *rr++ = w09;
  /* #963: @61 = @21[6:10] */
  for (rr=w61, cs=w21+6; cs!=w21+10; cs+=1) *rr++ = *cs;
  /* #964: (@58[30:34] = @61) */
  for (rr=w58+30, cs=w61; rr!=w58+34; rr+=1) *rr = *cs++;
  /* #965: (@58[21:37:4] = @61) */
  for (rr=w58+21, cs=w61; rr!=w58+37; rr+=4) *rr = *cs++;
  /* #966: @77 = @58' */
  casadi_trans(w58,casadi_s15, w77, casadi_s15, iw);
  /* #967: output[2][0] = @77 */
  casadi_copy(w77, 34, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_gate_att_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_gate_att_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_gate_att_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_gate_att_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_gate_att_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_gate_att_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_gate_att_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_gate_att_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_gate_att_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_gate_att_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_gate_att_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_gate_att_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_gate_att_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_gate_att_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s16;
    case 1: return casadi_s17;
    case 2: return casadi_s17;
    case 3: return casadi_s18;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_gate_att_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s19;
    case 1: return casadi_s16;
    case 2: return casadi_s15;
    case 3: return casadi_s20;
    case 4: return casadi_s21;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_gate_att_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 18;
  if (sz_iw) *sz_iw = 14;
  if (sz_w) *sz_w = 306;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_gate_att_cost_ext_cost_e_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 18*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 14*sizeof(casadi_int);
  if (sz_w) *sz_w = 306*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
